import { buildEventDeskMatches, findEventCourtOverlaps, normalizeEventCourt } from './tournament-event-desk'
import { buildTournamentPreview, type TiqTournamentRecord } from './tiq-tournament-registry'
import type { EventArrival } from './tournament-event-arrivals'
import { formatTournamentEventDate, formatTournamentEventTime } from './tournament-event-presentation'

export function buildEventRunSheet(event: TiqTournamentRecord, divisions: TiqTournamentRecord[], arrivals: EventArrival[], preparedAt: string, windowMinutes = 60) {
  const own = divisions.filter(division => division.eventId === event.id && !division.isEvent)
  const matches = buildEventDeskMatches(own)
  const overlaps = new Set(findEventCourtOverlaps(matches, windowMinutes).flatMap(pair => [pair.first.key, pair.second.key]))
  const results = new Map<string, import('./tiq-tournament-registry').TiqTournamentMatchResult | undefined>(own.flatMap(division => buildTournamentPreview(division).map(match => [`${division.id}:${match.id}`, match.result] as const)))
  const checkedIn = (divisionId: string, name: string) => arrivals.some(row => row.tournament_id === divisionId && row.entrant_name === name && row.checked_in)
  const rows = matches.map(match => {
    const division = own.find(item => item.id === match.divisionId)!
    const known = division.entrants.includes(match.sideA) && division.entrants.includes(match.sideB)
    const arrivalCount = Number(checkedIn(match.divisionId, match.sideA)) + Number(checkedIn(match.divisionId, match.sideB))
    return { ...match, courtLabel: /^court\b/i.test(match.court) ? match.court : `Court ${match.court}`, overlap: overlaps.has(match.key),
      arrivalLabel: known ? `${arrivalCount}/2 checked in` : 'Awaiting players',
      status: match.completed ? 'Complete' : match.ready === false || !known ? 'Awaiting players' : match.assigned ? 'Scheduled' : 'Awaiting slot',
      winner: results.get(match.key)?.winner || '', score: results.get(match.key)?.score || '' }
  })
  const courts = Array.from(new Set(rows.filter(row => row.assigned).map(row => normalizeEventCourt(row.court))))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true })).map(key => ({ name: rows.find(row => row.assigned && normalizeEventCourt(row.court) === key)!.courtLabel,
      matches: rows.filter(row => row.assigned && normalizeEventCourt(row.court) === key) }))
  const roster = own.map(division => ({ id: division.id, name: division.name, entrants: division.entrants.map(name => ({ name, checkedIn: checkedIn(division.id, name) })) }))
  return { event, preparedAt, windowMinutes, courts, pending: rows.filter(row => !row.assigned), roster, total: rows.length,
    assigned: rows.filter(row => row.assigned).length, checkedIn: roster.reduce((sum, division) => sum + division.entrants.filter(row => row.checkedIn).length, 0),
    confirmed: roster.reduce((sum, division) => sum + division.entrants.length, 0), overlaps: overlaps.size }
}
export type EventRunSheet = ReturnType<typeof buildEventRunSheet>
function escape(value: string | undefined) { return (value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!)) }
export function buildEventRunSheetHtml(sheet: EventRunSheet) {
  const { event } = sheet
  const zone = event.eventDetails?.timeZoneLabel || event.eventDetails?.timeZone || 'Event local time'
  const rows = (matches: EventRunSheet['pending']) => matches.map(match => `<tr><td>${escape(match.assigned ? `${formatTournamentEventDate(match.date, true)} · ${formatTournamentEventTime(match.time)}` : 'Unassigned')}<br><small>${escape(match.label)}</small></td><td><small>${escape(match.divisionName)}</small><br><strong>${escape(match.sideA)}</strong><br>vs ${escape(match.sideB)}</td><td>${escape(match.arrivalLabel)}<br>${escape(match.completed ? `${match.winner} won${match.score ? ` · ${match.score}` : ''}` : match.status)}${match.overlap ? '<br><strong>COURT OVERLAP — REVIEW</strong>' : ''}</td><td class="notes">________________<br>________________</td></tr>`).join('')
  const table = (matches: EventRunSheet['pending']) => `<table><thead><tr><th>Start / round</th><th>Division / matchup</th><th>Check-in / result</th><th>Staff notes</th></tr></thead><tbody>${rows(matches)}</tbody></table>`
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(event.name)} · Event-day run sheet</title><style>
*{box-sizing:border-box}body{margin:0;background:#e9eef5;color:#06172f;font:14px/1.5 Arial,sans-serif}main{max-width:1050px;margin:24px auto;padding:32px;background:white;border-top:6px solid #06172f}h1{font-size:32px;line-height:1.1;margin:12px 0}h2{font-size:19px;margin:28px 0 10px}p{margin:8px 0}.eyebrow{font-size:11px;letter-spacing:2px;text-transform:uppercase;font-weight:bold}.meta{color:#334155;font-size:12px}.notice{padding:12px;border:1px solid #64748b}.instructions{padding:12px;background:#06172f;color:white}.summary{display:flex;gap:20px;flex-wrap:wrap;margin:20px 0;font-weight:bold}table{width:100%;border-collapse:collapse;table-layout:fixed;margin:12px 0}th,td{padding:11px 8px;text-align:left;border-bottom:1px solid #cbd5e1;vertical-align:top;overflow-wrap:anywhere}th{font-size:10px;text-transform:uppercase;letter-spacing:.5px;border-top:1px solid #06172f}th:nth-child(1){width:23%}th:nth-child(2){width:34%}th:nth-child(3){width:27%}th:nth-child(4){width:16%}small{font-size:11px;color:#334155}.roster th:first-child{width:65%}.notes{font-size:10px;color:#64748b}footer{font-size:11px;margin-top:28px;border-top:1px solid #cbd5e1;padding-top:12px}@page{size:letter landscape;margin:12mm}@media print{body{background:white;font-size:11px}main{max-width:none;margin:0;padding:0;border-top:3px solid #06172f}.instructions{display:none}thead{display:table-header-group}tr{break-inside:avoid}h2{break-after:avoid}td,th{padding:8px 6px}.summary{margin:14px 0}h1{font-size:27px}}
</style></head><body><main><p class="instructions">Print or save as PDF using your browser’s Print command. This is a snapshot; prepare a new sheet after schedule or check-in changes.</p><header><p class="eyebrow">TenAceIQ · Event-day run sheet</p><h1>${escape(event.name)}</h1><p>${escape(formatTournamentEventDate(event.startsOn))} · ${escape(zone)}</p><p class="meta">${escape(event.eventDetails?.venueName || event.locationLabel)}${event.eventDetails?.venueAddress ? ` · ${escape(event.eventDetails.venueAddress)}` : ''}</p>${event.eventDetails?.directorName ? `<p class="meta">Director: ${escape(event.eventDetails.directorName)}</p>` : ''}<p class="meta">Prepared: ${escape(sheet.preparedAt)}</p></header><div class="summary"><span>${sheet.assigned}/${sheet.total} matches assigned</span><span>${sheet.checkedIn}/${sheet.confirmed} confirmed entrants checked in</span><span>${sheet.pending.length} awaiting a slot</span></div>${sheet.overlaps ? `<p class="notice">${sheet.overlaps} matches have a court overlap in the ${sheet.windowMinutes}-minute planning window. Review before sending players to court.</p>` : ''}${sheet.courts.map(court => `<section><h2>${escape(court.name)}</h2>${table(court.matches)}</section>`).join('')}${sheet.pending.length ? `<section><h2>Awaiting court or start time</h2>${table(sheet.pending)}</section>` : ''}${!sheet.total ? '<p class="notice">No matches yet. Confirm at least two entrants in a division to prepare its court plan.</p>' : ''}<section><h2>Confirmed entrants · Check-in snapshot</h2>${sheet.roster.map(division => `<h3>${escape(division.name)}</h3>${division.entrants.length ? `<table class="roster"><thead><tr><th>Team / player</th><th>Arrival</th></tr></thead><tbody>${division.entrants.map(row => `<tr><td>${escape(row.name)}</td><td>${row.checkedIn ? 'Checked in' : '[ ] Check in at event desk'}</td></tr>`).join('')}</tbody></table>` : '<p>No confirmed entrants.</p>'}`).join('')}</section><footer>Check the event desk for changes. Playoff names resolve after qualifying results are posted. Times use ${escape(zone)}. Staff notes are for this printed copy.</footer></main></body></html>`
}
