import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pageSource = readFileSync(join(process.cwd(), 'app/admin/growth/page.tsx'), 'utf8')
const routeSource = readFileSync(join(process.cwd(), 'app/api/admin/growth-funnel/route.ts'), 'utf8')
const signupSource = readFileSync(join(process.cwd(), 'app/api/auth/signup/route.ts'), 'utf8')
const pageStyles = readFileSync(join(process.cwd(), 'app/admin/growth/growth.module.css'), 'utf8')
const claimSource = readFileSync(join(process.cwd(), 'app/api/captain-pilot/claim/route.ts'), 'utf8')
const sourceMigration = readFileSync(join(process.cwd(), 'supabase/migrations/20260910000100_add_captain_pilot_acquisition_source.sql'), 'utf8')
const cardFreeMigration = readFileSync(join(process.cwd(), 'supabase/migrations/20260910000200_add_card_free_captain_pilot.sql'), 'utf8')
const pilotStatusSource = readFileSync(join(process.cwd(), 'app/api/captain-pilot/status/route.ts'), 'utf8')

describe('admin growth funnel', () => {
  it('keeps visitor traffic separate from signed-in product and billing conversion signals', () => {
    expect(pageSource).toContain('Visitor and page-view traffic belongs in Vercel Web Analytics.')
    expect(pageSource).toContain('Signup requests')
    expect(pageSource).toContain('Checkout clicks')
    expect(pageSource).toContain('Stripe opens')
    expect(pageSource).toContain('Paid activations')
    expect(pageSource).toContain('Offer to active Captain')
    expect(pageSource).toContain('Billing added')
    expect(pageSource).toContain('Largest opportunity')
    expect(routeSource).toContain("uniqueUsers(events, 'signup_confirmation_sent')")
    expect(routeSource).toContain("uniqueUsers(events, 'upgrade_checkout_clicked')")
    expect(routeSource).toContain("uniqueUsers(events, 'upgrade_checkout_started')")
    expect(routeSource).toContain("uniqueUsers(events, 'upgrade_checkout_failed')")
    expect(routeSource).toContain("event.resulting_status === 'active' || event.resulting_status === 'trial'")
    expect(routeSource).toContain('buildCaptainPilotFunnel')
    expect(routeSource).toContain('buildCaptainPilotFollowUps')
    expect(routeSource).toContain(".from('captain_pilot_redemptions')")
    expect(pageSource).toContain('Who may need help')
    expect(pageSource).toContain('Copy reminder')
    expect(routeSource).toContain('captainPilotFollowUpCount')
    expect(routeSource).toContain('buildCaptainPilotActivation')
    expect(routeSource).toContain('buildCaptainPilotActivationFollowUps')
    expect(pageSource).toContain('What happens after activation')
    expect(pageSource).toContain('First week started')
    expect(pageSource).toContain('What brings captains in')
    expect(pageSource).toContain('Copy {source.label.toLowerCase()} link')
    expect(routeSource).toContain('buildCaptainPilotSourceBreakdown')
    expect(signupSource).toContain('acquisitionSource')
    expect(claimSource).toContain('acquisition_source: acquisitionSource')
    expect(sourceMigration).toContain("'text', 'flyer', 'email', 'referral', 'direct'")
    expect(claimSource).toContain(".rpc('activate_captain_pilot_card_free'")
    expect(claimSource).not.toContain('PAID_CHECKOUT_ENABLED')
    expect(cardFreeMigration).toContain('security definer')
    expect(cardFreeMigration).toContain('grant execute on function public.activate_captain_pilot_card_free')
    expect(cardFreeMigration).toContain('to service_role')
    expect(pilotStatusSource).toContain("billingRequired: data.billing_status !== 'collected'")
    expect(pageStyles).toContain('@media (max-width: 560px)')
    expect(pageStyles).toContain('grid-template-columns: 1fr')
  })

  it('records a successful signup email as the funnel entry step without blocking signup delivery', () => {
    expect(signupSource).toContain("event_name: 'signup_confirmation_sent'")
    expect(signupSource).toContain("console.warn('Signup funnel event was not recorded.'")
    expect(signupSource.indexOf("if (!response.ok)")).toBeLessThan(signupSource.indexOf("event_name: 'signup_confirmation_sent'"))
  })
})
