import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const sharedSource = readFileSync(join(process.cwd(), 'app/admin/_components/admin-review-ui.tsx'), 'utf8')
const adminDashboardSource = readFileSync(join(process.cwd(), 'app/admin/page.tsx'), 'utf8')
const dataAssistSource = readFileSync(join(process.cwd(), 'app/admin/data-assist/page.tsx'), 'utf8')
const matchReportsSource = readFileSync(join(process.cwd(), 'app/admin/match-reports/page.tsx'), 'utf8')
const productEventsSource = readFileSync(join(process.cwd(), 'app/admin/product-events/page.tsx'), 'utf8')
const missingScorecardsSource = readFileSync(join(process.cwd(), 'app/admin/missing-scorecards/page.tsx'), 'utf8')
const importQueueSource = readFileSync(join(process.cwd(), 'app/admin/import-queue/page.tsx'), 'utf8')
const upgradeRequestsSource = readFileSync(join(process.cwd(), 'app/admin/upgrade-requests/page.tsx'), 'utf8')
const accessSource = readFileSync(join(process.cwd(), 'app/admin/access/page.tsx'), 'utf8')
const manageMatchesSource = readFileSync(join(process.cwd(), 'app/admin/manage-matches/page.tsx'), 'utf8')
const managePlayersSource = readFileSync(join(process.cwd(), 'app/admin/manage-players/page.tsx'), 'utf8')
const adminImportSource = readFileSync(join(process.cwd(), 'app/admin/import/page.tsx'), 'utf8')
const addMatchSource = readFileSync(join(process.cwd(), 'app/admin/add-match/page.tsx'), 'utf8')
const deduplicateSource = readFileSync(join(process.cwd(), 'app/admin/deduplicate/page.tsx'), 'utf8')
const anomaliesSource = readFileSync(join(process.cwd(), 'app/admin/anomalies/page.tsx'), 'utf8')
const lineupAvailabilitySource = readFileSync(join(process.cwd(), 'app/admin/lineup-availability/page.tsx'), 'utf8')
const tiqTeamMatchesSource = readFileSync(join(process.cwd(), 'app/admin/tiq-team-matches/page.tsx'), 'utf8')

describe('admin review UI system', () => {
  it('centralizes common review queue surfaces', () => {
    expect(sharedSource).toContain('export function AdminReviewFrame')
    expect(sharedSource).toContain('export function AdminReviewHero')
    expect(sharedSource).toContain('export function AdminReviewGrid')
    expect(sharedSource).toContain('export function AdminReviewPanel')
    expect(sharedSource).toContain('export function AdminStatusPanel')
    expect(sharedSource).toContain('export function AdminEmptyState')
    expect(sharedSource).toContain('export function AdminFact')
  })

  it('keeps the Admin dashboard on the shared admin review shell', () => {
    expect(adminDashboardSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(adminDashboardSource).toContain('<AdminReviewFrame>')
    expect(adminDashboardSource).toContain('<AdminReviewHero')
    expect(adminDashboardSource).toContain('<AdminReviewPanel')
    expect(adminDashboardSource).toContain('className="metric-grid"')
    expect(adminDashboardSource).toContain('className="card-grid three"')
    expect(adminDashboardSource).toContain('League Office entitlement flags')
    expect(adminDashboardSource).toContain('League Office permissions')
    expect(adminDashboardSource).toContain("flexWrap: 'wrap'")
    expect(adminDashboardSource).not.toContain("gridTemplateColumns: '1.3fr 1fr'")
    expect(adminDashboardSource).not.toContain('minWidth: 46')
    expect(adminDashboardSource).not.toContain("minWidth: 'min(100%, 880px)'")
    expect(adminDashboardSource).not.toContain('style={{ minWidth: 880 }}')
    expect(adminDashboardSource).not.toContain('TIQ league entitlement flags')
    expect(adminDashboardSource).not.toContain('TIQ league permissions')
    expect(adminDashboardSource).not.toContain('<HeroSection')
    expect(adminDashboardSource).not.toContain('className="hero-panel"')
    expect(adminDashboardSource).not.toContain('radial-gradient')
  })

  it('keeps Data Assist and Match Reports on the shared admin review shell', () => {
    expect(dataAssistSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(matchReportsSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(dataAssistSource).toContain('<AdminReviewHero')
    expect(matchReportsSource).toContain('<AdminReviewHero')
    expect(dataAssistSource).toContain('<AdminReviewGrid>')
    expect(matchReportsSource).toContain('<AdminReviewGrid>')
  })

  it('keeps Product Events on the shared admin review shell', () => {
    expect(productEventsSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(productEventsSource).toContain('<AdminReviewFrame>')
    expect(productEventsSource).toContain('<AdminReviewHero')
    expect(productEventsSource).toContain('<AdminReviewPanel>')
    expect(productEventsSource).toContain('<AdminEmptyState')
    expect(productEventsSource).toContain("style={{ width: '100%', tableLayout: 'auto' }}")
    expect(productEventsSource).toContain("tableLayout: 'auto'")
    expect(productEventsSource).not.toContain("minWidth: 'min(100%, 1120px)'")
    expect(productEventsSource).not.toContain('style={{ minWidth: 1120 }}')
  })

  it('keeps Missing Scorecards on the shared admin review shell', () => {
    expect(missingScorecardsSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(missingScorecardsSource).toContain('<AdminReviewFrame>')
    expect(missingScorecardsSource).toContain('<AdminReviewHero')
    expect(missingScorecardsSource).toContain('<AdminReviewPanel')
    expect(missingScorecardsSource).toContain('<AdminEmptyState')
    expect(missingScorecardsSource).toContain('className="metric-card"')
  })

  it('keeps Import Queue on the shared admin review shell', () => {
    expect(importQueueSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(importQueueSource).toContain('<AdminReviewFrame>')
    expect(importQueueSource).toContain('<AdminReviewHero')
    expect(importQueueSource).toContain('<AdminReviewPanel')
    expect(importQueueSource).toContain('<AdminStatusPanel')
    expect(importQueueSource).toContain('<AdminEmptyState')
    expect(importQueueSource).toContain('adminSubPanelStyle')
  })

  it('keeps Upgrade Requests on the shared admin review shell', () => {
    expect(upgradeRequestsSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(upgradeRequestsSource).toContain('<AdminReviewFrame>')
    expect(upgradeRequestsSource).toContain('<AdminReviewHero')
    expect(upgradeRequestsSource).toContain('<AdminReviewPanel')
    expect(upgradeRequestsSource).toContain('<AdminStatusPanel')
    expect(upgradeRequestsSource).toContain('<AdminEmptyState')
    expect(upgradeRequestsSource).toContain('className="metric-card"')
  })

  it('keeps Access Control on the shared admin review shell', () => {
    expect(accessSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(accessSource).toContain('<AdminReviewFrame>')
    expect(accessSource).toContain('<AdminReviewHero')
    expect(accessSource).toContain('<AdminReviewPanel')
    expect(accessSource).toContain('<AdminStatusPanel')
    expect(accessSource).toContain('<AdminEmptyState')
    expect(accessSource).toContain('Player, Coach, Captain, and League Office entitlements')
    expect(accessSource).toContain('Team League Office')
    expect(accessSource).toContain('Individual League Office')
    expect(accessSource).toContain('Draft League Office')
    expect(accessSource).toContain('League Office flags are enabled.')
    expect(accessSource).toContain('Review: League Office checkout currently has Player access.')
    expect(accessSource).not.toContain('Player, Coach, Captain, and Coordinator entitlements')
    expect(accessSource).not.toContain('Draft Coordinator')
    expect(accessSource).not.toContain('Coordinator flags are enabled.')
    expect(accessSource).toContain('className="metric-card"')
    expect(accessSource).toContain("style={{ width: '100%', tableLayout: 'auto' }}")
    expect(accessSource).toContain('maxWidth: 140')
    expect(accessSource).toContain('maxWidth: 150')
    expect(accessSource).toContain('maxWidth: 180')
    expect(accessSource).toContain('maxWidth: 220')
    expect(accessSource).toContain('maxWidth: 260')
    expect(accessSource).not.toContain("minWidth: 'min(100%,")
    expect(accessSource).not.toContain('minWidth: 1920')
    expect(accessSource).not.toContain('minWidth: 140')
    expect(accessSource).not.toContain('minWidth: 150')
    expect(accessSource).not.toContain('minWidth: 180')
    expect(accessSource).not.toContain('minWidth: 220')
    expect(accessSource).not.toContain('minWidth: 260')
    expect(accessSource).not.toContain("color: '#f8fbff'")
    expect(accessSource).not.toContain("color: '#e2e8f0'")
  })

  it('keeps Manage Matches on the shared admin review shell', () => {
    expect(manageMatchesSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(manageMatchesSource).toContain('<AdminReviewFrame>')
    expect(manageMatchesSource).toContain('<AdminReviewHero')
    expect(manageMatchesSource).toContain('<AdminReviewPanel')
    expect(manageMatchesSource).toContain('<AdminStatusPanel')
    expect(manageMatchesSource).toContain('<AdminEmptyState')
    expect(manageMatchesSource).toContain('className="metric-card"')
    expect(manageMatchesSource).toContain("style={{ width: '100%', tableLayout: 'auto' }}")
    expect(manageMatchesSource).toContain('maxWidth: 180')
    expect(manageMatchesSource).not.toContain("minWidth: 'min(100%,")
    expect(manageMatchesSource).toContain("overflowWrap: 'anywhere'")
    expect(manageMatchesSource).not.toContain('minWidth: 1300')
    expect(manageMatchesSource).not.toContain('minWidth: 320')
    expect(manageMatchesSource).not.toContain('radial-gradient')
    expect(manageMatchesSource).not.toContain("'—'")
  })
  it('keeps Manage Players on the shared admin review shell', () => {
    expect(managePlayersSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(managePlayersSource).toContain('<AdminReviewFrame>')
    expect(managePlayersSource).toContain('<AdminReviewHero')
    expect(managePlayersSource).toContain('<AdminReviewPanel')
    expect(managePlayersSource).toContain('<AdminStatusPanel')
    expect(managePlayersSource).toContain('<AdminEmptyState')
    expect(managePlayersSource).toContain('className="metric-card"')
    expect(managePlayersSource).toContain("style={{ width: '100%', tableLayout: 'auto' }}")
    expect(managePlayersSource).toContain("width: 'min(100%, 110px)'")
    expect(managePlayersSource).toContain('maxWidth: 180')
    expect(managePlayersSource).toContain('maxWidth: 150')
    expect(managePlayersSource).not.toContain('width: 110')
    expect(managePlayersSource).not.toContain("minWidth: 'min(100%,")
    expect(managePlayersSource).not.toContain('minWidth: 1250')
    expect(managePlayersSource).not.toContain('minWidth: 180')
    expect(managePlayersSource).not.toContain('minWidth: 150')
    expect(managePlayersSource).not.toContain("minWidth: '320px'")
    expect(managePlayersSource).not.toContain('radial-gradient')
    expect(managePlayersSource).not.toContain("'â€”'")
    expect(managePlayersSource).not.toContain("color: '#666'")
  })
  it('keeps Admin Import on the shared admin review shell', () => {
    expect(adminImportSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(adminImportSource).toContain('<AdminReviewFrame>')
    expect(adminImportSource).toContain('<AdminReviewHero')
    expect(adminImportSource).toContain('title="Admin Import Center"')
    expect(adminImportSource).not.toContain('pageWrapStyle')
  })

  it('keeps Add Match on the shared admin review shell', () => {
    expect(addMatchSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(addMatchSource).toContain('<AdminReviewFrame>')
    expect(addMatchSource).toContain('<AdminReviewHero')
    expect(addMatchSource).toContain('<AdminReviewPanel')
    expect(addMatchSource).toContain('<AdminStatusPanel')
    expect(addMatchSource).not.toContain('radial-gradient')
    expect(addMatchSource).not.toContain('className="hero-panel"')
  })

  it('keeps Deduplicate on the shared admin review shell', () => {
    expect(deduplicateSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(deduplicateSource).toContain('<AdminReviewFrame>')
    expect(deduplicateSource).toContain('<AdminReviewHero')
    expect(deduplicateSource).toContain('<AdminReviewPanel')
    expect(deduplicateSource).toContain('<AdminStatusPanel')
    expect(deduplicateSource).toContain('<AdminEmptyState')
    expect(deduplicateSource).not.toContain('const shell')
    expect(deduplicateSource).not.toContain('successBanner')
    expect(deduplicateSource).not.toContain('errorBanner')
  })

  it('keeps Anomalies on the shared admin review shell', () => {
    expect(anomaliesSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(anomaliesSource).toContain('<AdminReviewFrame>')
    expect(anomaliesSource).toContain('<AdminReviewHero')
    expect(anomaliesSource).toContain('<AdminReviewPanel')
    expect(anomaliesSource).toContain('<AdminStatusPanel')
    expect(anomaliesSource).toContain('<AdminEmptyState')
    expect(anomaliesSource).toContain('minWidth: 0')
    expect(anomaliesSource).not.toContain("minWidth: 'min(100%, 860px)'")
    expect(anomaliesSource).toContain("tableLayout: 'auto'")
    expect(anomaliesSource).toContain("overscrollBehaviorX: 'contain'")
    expect(anomaliesSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(anomaliesSource).toContain("scrollbarWidth: 'thin'")
    expect(anomaliesSource).toContain("maxWidth: '100%'")
    expect(anomaliesSource).not.toContain('minWidth: 860')
    expect(anomaliesSource).not.toContain('const shell')
    expect(anomaliesSource).not.toContain('errorBanner')
    expect(anomaliesSource).not.toContain("'â€”'")
  })
  it('keeps Lineup Availability on the shared admin review shell', () => {
    expect(lineupAvailabilitySource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(lineupAvailabilitySource).toContain("import { useAuth } from '@/app/components/auth-provider'")
    expect(lineupAvailabilitySource).toContain('<AdminReviewFrame>')
    expect(lineupAvailabilitySource).toContain('<AdminReviewHero')
    expect(lineupAvailabilitySource).toContain('<AdminReviewPanel')
    expect(lineupAvailabilitySource).toContain('<AdminStatusPanel')
    expect(lineupAvailabilitySource).toContain('<AdminEmptyState')
    expect(lineupAvailabilitySource).toContain('const { role, authResolved } = useAuth()')
    expect(lineupAvailabilitySource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 132px), 1fr))'")
    expect(lineupAvailabilitySource).toContain("whiteSpace: 'normal'")
    expect(lineupAvailabilitySource).not.toContain('getClientAuthState')
    expect(lineupAvailabilitySource).not.toContain('const [role, setRole]')
    expect(lineupAvailabilitySource).not.toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(lineupAvailabilitySource).not.toContain('className="page-shell"')
    expect(lineupAvailabilitySource).not.toContain("background: '#f8fafc'")
    expect(lineupAvailabilitySource).not.toContain('Â·')
  })
  it('keeps TIQ Team Matches on the shared admin review shell', () => {
    expect(tiqTeamMatchesSource).toContain("from '@/app/admin/_components/admin-review-ui'")
    expect(tiqTeamMatchesSource).toContain('<AdminReviewFrame>')
    expect(tiqTeamMatchesSource).toContain('<AdminReviewHero')
    expect(tiqTeamMatchesSource).toContain('<AdminReviewPanel')
    expect(tiqTeamMatchesSource).toContain('<AdminStatusPanel')
    expect(tiqTeamMatchesSource).toContain('<AdminEmptyState')
    expect(tiqTeamMatchesSource).not.toContain('const pageWrap')
    expect(tiqTeamMatchesSource).not.toContain('const heading')
    expect(tiqTeamMatchesSource).not.toContain("color: '#94a3b8'")
  })
})
