import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const component = readFileSync('app/components/captain-lineup-intelligence.tsx', 'utf8')
const page = readFileSync('app/captain/lineup-builder/page.tsx', 'utf8')
const route = readFileSync('app/api/captain/lineup-builder/route.ts', 'utf8')

describe('captain lineup intelligence UI', () => {
  it('keeps roster recovery, manual editing, and auto-builder strategies in one mobile flow', () => {
    expect(page).toContain('<CaptainLineupIntelligence')
    expect(component).toContain('Opponent roster missing')
    expect(component).toContain('Upload Team Summary')
    expect(component).toContain('Enter names instead')
    expect(component).toContain('Build my best lineup')
    expect(component).toContain('Best odds')
    expect(component).toContain('Safer floor')
    expect(component).toContain('More upside')
    expect(component).toContain('Compare or edit court')
    expect(component).toContain('Why this lineup?')
    expect(component).toContain('Court locked')
    expect(component).toContain('confidenceDetail')
    expect(component).toContain('playerEvidence.length > 1')
    expect(component).toContain('role="tablist"')
    expect(page).toContain('strategyPreviews={lineupStrategyPreviews}')
    expect(page).toContain('onToggleCourtLock={toggleLockedSlot}')
    expect(page).toContain('onTogglePlayerLock={toggleOptimizerPlayerLock}')
    expect(page).toContain('onAutoBuild={(strategy) => applyOptimizedPlan(strategy, false)}')
  })

  it('puts the phone win-path directly after match week navigation', () => {
    const matchWeek = page.lastIndexOf('<CaptainMatchWeekRail')
    const winPath = page.indexOf('<CaptainLineupIntelligence', matchWeek)
    const controls = page.indexOf('aria-label="Lineup controls"', matchWeek)
    expect(matchWeek).toBeGreaterThanOrEqual(0)
    expect(winPath).toBeGreaterThan(matchWeek)
    expect(winPath).toBeLessThan(controls)
  })

  it('loads real court result evidence for sample-backed tendencies', () => {
    expect(route).toContain('line_number,match_type,winner_side,score')
    expect(component).toContain('Based on ${selectedInsight.startCount} start')
    expect(component).toContain('Based on ${selectedInsight.scoredWinCount} scored win')
  })

  it('simulates an eligible one-player swap before changing the lineup', () => {
    expect(component).toContain('Quick matchup simulator')
    expect(component).toContain('Try a swap')
    expect(component).toContain('Swap out')
    expect(component).toContain('Try instead')
    expect(component).toContain('Apply this swap')
    expect(component).toContain('Explore freely. Unlock to apply.')
    expect(component).toContain('Why the odds moved')
    expect(component).toContain("factor.modeled ? 'Modeled' : 'Supporting'")
    expect(component).toContain('Rating drives today&apos;s projection')
    expect(component).toContain('Court <strong>{percent(currentCourtProbability)} → {percent(candidate.courtProbability)}</strong>')
    expect(component).toContain('Match <strong>{percent(currentOverallProbability)} → {percent(candidate.overallProbability)}</strong>')
    expect(page).toContain('const lineupSimulations = useMemo<CaptainLineupSimulationCourt[]>')
    expect(page).toContain('.filter((player) => isPlayerEligibleForSlot(player, slot, competitionRules))')
    expect(page).toContain('simulations={lineupSimulations}')
    expect(page).toContain('onApplySimulation={applyLineupSimulationSwap}')
    expect(page).toContain('Directly drives today’s court and match percentages.')
    expect(page).toContain('supporting evidence only today.')
    expect(page).toContain('Controls who is offered by the simulator, not the displayed percentage.')
  })

  it('stress-tests the lineup against three opponent approaches', () => {
    expect(component).toContain('Does your lineup hold up?')
    expect(component).toContain('Opponent scenarios')
    expect(page).toContain("scenario.id === 'aggressive' ? 'Aggressive' : 'Conservative'")
    expect(component).toContain('Pressure point')
    expect(component).toContain('Court odds below and Auto Builder now use this opponent scenario.')
    expect(page).toContain('const opponentScenarioLineups = useMemo')
    expect(page).toContain("arrangeOpponentScenarioSlots(optimizerTeamSlots, strongestRoster, builderPlayers, 'aggressive')")
    expect(page).toContain('activeProjectedOpponentSlots')
    expect(page).toContain('opponentScenarios={lineupOpponentScenarios}')
    expect(page).toContain('onOpponentScenarioChange={setActiveOpponentScenarioId}')
    expect(component).toContain('Best all-scenario floor')
    expect(component).toContain('Build for all 3')
    expect(component).toContain('Your current courts already match the resilient build.')
    expect(page).toContain('const resilientPlan = useMemo')
    expect(page).toContain('worstCaseProbability * 0.7 + averageProbability * 0.3')
    expect(page).toContain('resilientPreview={lineupResilientPreview}')
    expect(page).toContain('onBuildResilient={applyResilientPlan}')
    expect(component).toContain('See their projected courts')
    expect(component).toContain('No legal court moves from Likely in this format.')
    expect(component).toContain('Same legal courts')
    expect(component).toContain("confidence === 'Medium' ? 0.06 : 0.1")
    expect(component).toContain('Resilient lineup active')
    expect(page).toContain('movedFromLikely: slotPlayerSignature(slot.players)')
  })

  it('ranks safe roster pairs and places one without disrupting other courts', () => {
    expect(component).toContain('Pair matrix')
    expect(component).toContain('Compare every available pair')
    expect(component).toContain('Projected odds rank the list.')
    expect(component).toContain('Shared history gives you context and is not weighted yet.')
    expect(component).toContain('Current pair')
    expect(component).toContain('onApplyPair(activePairMatrixCourt.id, pair.playerIds)')
    expect(component).toContain("pair.blockingLock?.kind === 'player'")
    expect(component).toContain('onTogglePlayerLock(pair.blockingLock.id)')
    expect(page).toContain('const lineupPairMatrix = useMemo<CaptainPairMatrixCourt[]>')
    expect(page).toContain("!assignedPlayerIds.has(player.id) || currentPlayerIdSet.has(player.id)")
    expect(page).toContain("availabilityLabel(player.availabilityStatus) !== 'Out'")
    expect(page).toContain('function applyPairMatrixRecommendation')
    expect(page).toContain('pairMatrix={lineupPairMatrix}')
    expect(page).toContain('onApplyPair={applyPairMatrixRecommendation}')
  })
})
