import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Captain mobile command center', () => {
  const page = readFileSync(join(process.cwd(), 'app/captain/page.tsx'), 'utf8')
  const styles = readFileSync(join(process.cwd(), 'app/captain/captain-mobile-command.module.css'), 'utf8')
  const connectionBanner = readFileSync(join(process.cwd(), 'app/components/team-connection-invite.tsx'), 'utf8')

  it('puts the timely captain jobs on one compact mobile surface', () => {
    const chatActionStart = page.indexOf("id: 'chat'")
    const chatAction = page.slice(chatActionStart, page.indexOf("id: 'scorecard'", chatActionStart))

    expect(page).toContain('aria-label="Captain mobile command center"')
    expect(page).toContain('shouldShowCaptainMobileTeamSelect(')
    expect(page).toContain('{showCaptainMobileTeamSelect ? (')
    expect(page).toContain('aria-label="Captain team"')
    expect(page).toContain('href="/team-connections">Manage teams')
    expect(page).toContain('buildConsumedCaptainHandoffHref(')
    expect(page).toContain("incomingLevelUpTeamChallenge && canConsumeLevelUpHandoff ? ['levelUpChallenge', 'card'] : []")
    expect(page).toContain('onClick={() => setCaptainImportHandoff(null)}')
    expect(styles).toContain('.noticeDismiss')
    expect(page).toContain('aria-label="Captain now"')
    expect(page).toContain('orderCaptainMobileNowItems(')
    expect(page).toContain("some((item) => item.id !== 'availability-complete')")
    expect(page).toContain('const captainMobileNowPrimary = captainMobileNowItems[0]')
    expect(page).toContain('const captainMobileNowSecondary = captainMobileNowItems.slice(1)')
    expect(page).toContain('View {captainMobileNowSecondary.length} more')
    expect(page).toContain("captainShowLockedLineup ? 'lineup-locked' : 'lineup-confirmed'")
    expect(page).toContain('Court confirmed')
    expect(page).toContain('Lineup locked')
    expect(page).toContain('Send final lineup')
    expect(page).toContain("action: captainShowLockedLineup ? 'send_final_lineup' : 'send'")
    expect(page).toContain('captainLockedLineupWasSent')
    expect(page).toContain('Captains and co-captains now share this sent status.')
    expect(page).toContain('final-lineup-sent:')
    expect(page).toContain('buildCaptainLockedLineupAnnouncement({')
    expect(page).toContain('buildCaptainLockedLineupId({')
    expect(page).toContain('isCaptainLineupLocked({')
    expect(page).toContain('Share confirmed court')
    expect(page).toContain('rememberCaptainLineupConfirmationSeen(')
    expect(page).toContain('buildCaptainLineupConfirmationNextStep({')
    expect(page).toContain('{captainLineupConfirmationNextStep.cta}')
    expect(page).toContain('handleCaptainLineupConfirmationNext')
    expect(page).toContain('captainVisibleCourtReadinessCard')
    expect(page).toContain("captainHomeShortcutItems.find((item) => item.tone !== 'good')")
    expect(page).toContain('{captainMobileNow}')
    expect(page).toContain('`${captainAvailabilityPendingCount} waiting`')
    expect(page).toContain('aria-label="Captain one tap actions"')
    expect(page).toContain('getCaptainMobileActionLayout({')
    expect(page).toContain('captainMobileVisibleActions.map')
    expect(page).toContain('captainMobileMoreMatchActions.map')
    expect(page).toContain('onClick={() => handleCaptainMobileCommandAction(item)}')
    expect(page).toContain("label: 'Who can play'")
    expect(page).toContain("captainLateArrival ? 'Handle late arrival' : captainArrivalFollowUp ? 'Follow up arrivals' : 'Team chat'")
    expect(page).toContain('teamRoomSummary.unreadCount')
    expect(chatAction).toContain('`${captainArrivalFollowUp.count} still waiting`')
    expect(chatAction).toContain('captainLateArrivalMessageHref || captainArrivalFollowUpHref || teamRoomHref')
    expect(chatAction).toContain('Boolean(captainLateArrival || captainArrivalFollowUp) || teamRoomSummary.unreadCount > 0')
    expect(chatAction).toContain('`${teamRoomSummary.unreadCount} unread`')
    expect(chatAction).toContain("'Open team chat'")
    expect(chatAction).not.toContain('unresolvedCount')
    expect(chatAction).not.toContain('pendingCount')
    expect(chatAction).not.toContain('maybeCount')
    expect(chatAction).not.toContain('unseenLineupCount')
    expect(chatAction).not.toContain('responseCount')
    expect(page).toContain("summary=1")
    expect(page).toContain('Courts needing captain attention')
    expect(page).toContain('captainUnresolvedCourts.map')
    expect(page).toContain("court.status === 'needs_captain'")
    expect(page).toContain("messageId: captainCourtReadiness?.messageId || ''")
    expect(page).toContain('court: courtLabel')
    expect(page).toContain('handleCaptainTeamRoomNav(courtHref)')
    expect(page).toContain('selectPrimaryTeamRoomCourtReadiness(captainUnresolvedCourts)')
    expect(page).toContain('const captainHomePrimaryStatus = captainLateArrivalAction')
    expect(page).toContain('const captainHomePrimaryAction = captainLateArrivalAction || captainArrivalFollowUpAction ||')
    expect(page).toContain("state: 'Running late'")
    expect(page).toContain('captainHomeLateArrivalActions')
    expect(page).toContain('captainLateArrivalMessageHref')
    expect(page).toContain('captainLateArrivalCourtHref')
    expect(page).toContain('captainLateArrivalBackupHref')
    expect(page).toContain("state: 'Needs follow-up'")
    expect(page).toContain("cta: 'Open Team Room'")
    expect(page).toContain('onClick={() => handleCaptainTeamRoomNav(captainPrimaryCourtHref)}')
    expect(page).toContain("'court' : 'courts'} open")
    expect(page).toContain('const loadTeamRoomSummary = useCallback(async () =>')
    expect(page).toContain('requestId !== teamRoomSummaryRequestRef.current')
    expect(page).toContain("document.addEventListener('visibilitychange', refreshVisibleTeamRoomSummary)")
    expect(page).toContain("window.addEventListener('pageshow', refreshRestoredTeamRoomSummary)")
    expect(page).toContain('window.setInterval(refreshVisibleTeamRoomSummary, TEAM_ROOM_SUMMARY_REFRESH_MS)')
    expect(page).not.toContain('window.location.reload()')
    expect(page).toContain("label: 'Add scorecard'")
    expect(page).toContain('<span>More</span>')
    expect(page).toContain('Pairings, setup, and extras')
    expect(page).not.toContain('More captain tools')
    expect(styles).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));')
    expect(styles).toContain('min-height: 66px;')
    expect(styles).toContain('.action:last-child:nth-child(odd)')
    expect(styles).toContain('.readinessGrid')
    expect(styles).toContain('minmax(min(100%, 118px), 1fr)')
    expect(styles).toContain('.attentionBadgeButton')
    expect(styles).toContain('.nowMoreSummary')
    expect(styles).toContain('.nowMoreBody')
  })

  it('hides the catalog-style Captain surfaces and overlapping action bar on phones', () => {
    expect(page).toContain('{!isMobile ? (')
    expect(page).toContain("display: 'none',")
    expect(page).toContain('{captainMobileCommandCenter}')
  })

  it('turns the already-open Captain connection action into Team Chat', () => {
    expect(connectionBanner).toContain("import { buildTeamRoomHref } from '@/lib/team-room'")
    expect(connectionBanner).toContain("isCaptainConnection ? 'Open Team Chat' : 'Continue with team'")
    expect(connectionBanner).toContain("alreadyAtDestination ? teamRoomHref")
    expect(connectionBanner).toContain('.team-connection-invite-banner.is-accepted .team-connection-invite-body')
  })
})
