import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/captain/page.tsx'), 'utf8')
const shellSmokeSource = readFileSync(join(process.cwd(), 'scripts/site-shell-layout-smoke.mjs'), 'utf8')

function styleBlock(styleName: string) {
  const start = source.indexOf(`const ${styleName}: CSSProperties = {`)
  expect(start, `Missing ${styleName}`).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

describe('Captain onboarding surface', () => {
  it('keeps the first Captain screen progressive and Data Assist aware', () => {
    expect(source).toContain('CAPTAIN_EMPTY_STATE_ACTIONS')
    expect(source).toContain('CaptainLockedSurface')
    expect(source).toContain('Team Hub preview')
    expect(source).toContain('Run match week with less chaos.')
    expect(source).toContain('Preparing Team Hub')
    expect(source).toContain('<h1 style={loadingStateTitleStyle}>Preparing Team Hub</h1>')
    expect(source).toContain('League Office')
    expect(source).not.toContain('League Coordinator')
    expect(source).toContain('Compare plans')
    expect(source).toContain("if (!authResolved || role === 'public' || isMember(role))")
    expect(source).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(source).toContain('const CAPTAIN_LEVEL_UP_HREF = `/level-up/${CAPTAIN_PLAYER_IDENTITY.slug}#level-up-flow`')
    expect(source).toContain('const CAPTAIN_PLAYER_DEVELOPMENT_HREF = `/player-development/${CAPTAIN_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('Set your Player ID so Team Hub can find your profile team.')
    expect(source).toContain('Team Hub Player ID starter')
    expect(source).toContain('Captain Player ID starter')
    expect(source).toContain('Captain Player ID starter read')
    expect(source).toContain('captainPlayerIdStarterRead.map((item)')
    expect(source).toContain('Upload a reviewed team summary or schedule through Data Assist')
    expect(source).toContain('Refresh Captain after the upload review connects teams, schedules, and scorecards.')
    expect(source).toContain('Need a team to manage here?')
    expect(source).toContain('Connect a profile team or upload reviewed roster and schedule data')
    expect(source).toContain("const dataAssistCaptainHref = '/data-assist?intent=upload-source&context=Team%20Hub'")
    expect(source).toContain('href={dataAssistCaptainHref}')
    expect(source).toContain('Set profile')
    expect(source).toContain('Start Level Up')
    expect(source).toContain('Read Player ID')
    expect(source).toContain('Refresh with Data Assist')
    expect(source).toContain('Start with who can play, build the lineup, check the pairings, and send the match-week plan.')
    expect(source).toContain('Start with who can play, choose the lineup, check the pairings, and send the team plan without leaving the match-week lane.')
    expect(source).toContain('Open the weekly brief for lineup, notes, opponent context, and final captain actions.')
    expect(source).not.toContain('send the team plan from one place')
    expect(source).not.toContain('final captain actions in one place')
    expect(source).toContain('Plan practice')
    expect(source).toContain('Schedule practice, invite the roster, and collect In, Out, or Maybe responses in Messages.')
    expect(source).toContain('Save status')
    expect(source).toContain('Know what carries forward.')
    expect(source).toContain('Local honesty')
    expect(source).toContain('CAPTAIN_LOCAL_SYNC_PROOF_CHECKS')
    expect(source).toContain('Saved data check')
    expect(source).toContain('Separate browser proof from linked team history.')
    expect(source).toContain('CAPTAIN_DECISION_HANDOFF_PROOF_STEPS')
    expect(source).toContain('Decision path check')
    expect(source).toContain('Move from availability to lineup to team send.')
    expect(source).toContain('Start with who is in, out, maybe, or still needs a follow-up.')
    expect(source).toContain('Save at least one playable court plan before messaging the team.')
    expect(source).toContain('Compare one projection or alternative when the lineup call is not obvious.')
    expect(source).toContain('Open the weekly brief, team brief, or message prep after the decision is ready.')
    expect(source).toContain('Captain decision path')
    expect(source).toContain('Answer match week from your phone.')
    expect(source).toContain('Who is available?')
    expect(source).toContain('What lineup gives us the best chance?')
    expect(source).toContain('Who should play together?')
    expect(source).toContain('What should I communicate?')
    expect(source).toContain('What needs to be cleaned up?')
    expect(source).toContain('Check Availability')
    expect(source).toContain('Build Lineup')
    expect(source).toContain('Check Pairings')
    expect(source).toContain('Message Team')
    expect(source).toContain('Track Scorecard')
    expect(source).toContain("href: dataAssistCaptainHref")
    expect(source).toContain("targetHref = needsScope ? '#captain-team-scope' : item.href")
    expect(source).toContain('Browser-saved: selected team week, lineups, event notes, response status, and week status.')
    expect(source).toContain('Linked context: roster, schedule, and team history from profile links or reviewed Data Assist imports.')
    expect(source).toContain('Not account sync yet: browser-saved week work should not be treated as cross-device proof.')
    expect(source).toContain('Lineups, event notes, response status, and week status are saved in this browser.')
    expect(source).not.toContain('browser-saved proof')
    expect(source).not.toContain('Browser proof')
    expect(source).toContain('This browser remembers the selected team week so the hub can resume the same captain lane.')
    expect(source).not.toContain("label: 'Read brief'")
    expect(source).not.toContain('Link your player identity in My Lab')
    expect(source).not.toContain('Link in My Lab')
    expect(source).not.toContain("if (role === 'public') return null")
  })

  it('keeps Captain onboarding compact on small mobile screens', () => {
    expect(styleBlock('pageWrap')).toContain("width: 'min(1280px, calc(100% - clamp(24px, 5vw, 48px)))'")
    expect(styleBlock('pageWrap')).toContain('overflowX: \'clip\'')
    expect(styleBlock('loadingWrap')).toContain("width: 'min(1280px, calc(100% - clamp(24px, 5vw, 48px)))'")
    expect(styleBlock('loadingWrap')).toContain('minWidth: 0')
    expect(styleBlock('heroCard')).toContain('minmax(0, 1.2fr)')
    expect(styleBlock('heroCard')).toContain('minmax(min(100%, 320px), 0.8fr)')
    expect(styleBlock('captainDataAssistCueStyle')).toContain('flexWrap: \'wrap\'')
    expect(styleBlock('captainPlayerIdStarterCopyStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainPlayerIdStarterStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainPlayerIdStarterGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 158px), 1fr))'")
    expect(styleBlock('captainPlayerIdStarterCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainSaveStatusGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))'")
    expect(styleBlock('captainSaveStatusCard')).toContain('minWidth: 0')
    expect(styleBlock('captainLocalSyncProofStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainLocalSyncProofGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 240px), 1fr))'")
    expect(styleBlock('captainLocalSyncProofItemStyle')).toContain("gridTemplateColumns: 'minmax(0, 12px) minmax(0, 1fr)'")
    expect(styleBlock('captainLocalSyncProofItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainDecisionHandoffProofGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(styleBlock('captainDecisionHandoffProofItemStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainDecisionHandoffProofItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainDecisionHandoffProofTopStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainPreviewGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 210px), 1fr))'")
    expect(styleBlock('captainPreviewStepStyle')).toContain("gridTemplateColumns: 'minmax(0, 34px) minmax(0, 1fr)'")
    expect(styleBlock('captainPreviewStepStyle')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain('const lockedPreviewPanelStyle')
    expect(source).toContain('const lockedPreviewGrid: CSSProperties')
    expect(source).toContain("'repeat(2, minmax(0, 1fr))'")
    expect(source).toContain('const lockedPreviewStep: CSSProperties')
    expect(source).toContain("'minmax(0, 24px) minmax(0, 1fr)'")
    expect(source).toContain('const lockedPreviewStepCopy: CSSProperties')
    expect(source).toContain('fontSize: isMobile ? 11')
    expect(source).toContain('{!isMobile ? (')
    expect(source).toContain('{!isMobile ? <span>{body}</span> : null}')
    expect(source).toContain("background: 'transparent'")
    expect(source).toContain("boxShadow: 'none'")
    expect(source).toContain('aria-label="Captain mobile unlock actions"')
    expect(source).toContain("const captainUnlockHref = getPlanUnlockHref('captain')")
    expect(source).toContain('summaryOnly={isMobile}')
    expect(source).toContain("router.replace('/login?plan=captain&next=%2Fcaptain')")
    expect(source).not.toContain("router.replace('/login?next=/captain')")
    expect(styleBlock('captainPreviewMobileActionRowStyle')).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock('captainPreviewMobilePrimaryActionStyle')).toContain('minHeight: 38')
    expect(styleBlock('captainPreviewMobilePrimaryActionStyle')).toContain("overflowWrap: 'anywhere'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-unlock-actions-missing'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-unlock-action-not-prominent'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-summary-repeated-guidance'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-summary-card-not-in-first-view'")
    expect(shellSmokeSource).toContain('/upgrade?plan=captain&next=%2Fcaptain')
    expect(styleBlock('captainDecisionPathShellStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainDecisionPathGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(source).toContain('const dynamicCaptainDecisionPathShell: CSSProperties')
    expect(source).toContain('const dynamicCaptainDecisionPathGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isMobile ? 'repeat(2, minmax(0, 1fr))' : captainDecisionPathGridStyle.gridTemplateColumns")
    expect(source).toContain('const dynamicCaptainDecisionPathCard: CSSProperties')
    expect(source).toContain('minHeight: isMobile ? 0 : captainDecisionPathCardStyle.minHeight')
    expect(source).toContain("{isMobile ? 'Answer match week.' : 'Answer match week from your phone.'}")
    expect(source).toContain("!isMobile ? (")
    expect(source).toContain("{needsScope ? (isMobile ? 'Team' : 'Choose Team') : isMobile ? item.label : item.cta}")
    expect(source).toContain('const dynamicCaptainSaveStatusShell: CSSProperties')
    expect(source).toContain('const dynamicCommandCenterShell: CSSProperties')
    expect(source).toContain('const dynamicCommandCenterCard: CSSProperties')
    expect(source).toContain('<section style={dynamicCommandCenterShell} aria-label="Captain week command center">')
    expect(source).toContain('Captain week command center')
    expect(source).toContain("Make this week's call.")
    expect(source).toContain("Make this week's call from one lane.")
    expect(source).toContain('Captain week snapshot')
    expect(source).toContain('Captain week readiness')
    expect(source).toContain('Ready for match day')
    expect(source).toContain('captainCommandSnapshots')
    expect(source).toContain('captainReadinessScore}% ready')
    expect(source.indexOf('<section style={dynamicCommandCenterShell} aria-label="Captain week command center">')).toBeLessThan(
      source.indexOf('<section style={dynamicCaptainDecisionPathShell} aria-label="Captain decision path">'),
    )
    expect(source.indexOf('<section style={dynamicCommandCenterShell} aria-label="Captain week command center">')).toBeLessThan(
      source.indexOf('<details style={dynamicCaptainSaveStatusShell} aria-label="Captain save status">'),
    )
    expect(styleBlock('commandCenterSnapshotGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('commandCenterSnapshotCard')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterSnapshotCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('commandCenterReadinessShell')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterReadinessTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('commandCenterGrid')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterCard')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterCard')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain("{isMobile ? 'What saves here?' : 'Know what carries forward.'}")
    expect(source).toContain("gridTemplateColumns: isMobile ? 'repeat(2, minmax(0, 1fr))' : statusStrip.gridTemplateColumns")
    expect(styleBlock('captainDecisionPathCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainDecisionPathCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainDecisionPathTopStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainDecisionPathAnswerStyle')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(source).not.toContain("calc(100% - 48px)")
    expect(source).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(source).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(source).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(source).not.toContain("gridTemplateColumns: 'auto minmax(0, 1fr)'")
  })

  it('keeps Captain empty states actionable for missing teams and rosters', () => {
    expect(source).toContain('Choose or connect a team scope.')
    expect(source).toContain('No roster players are available yet.')
    expect(source).toContain('Set profile')
    expect(source).toContain('Upload team data')
    expect(source).toContain('Open Data Assist')
    expect(source).toContain('Refresh Captain')
    expect(source).toContain('captainEmptyActionRowStyle')
    expect(source).toContain('inlineEmptyLinkStyle')
    expect(source).toContain('inlineEmptyButtonStyle')
  })
})
