import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/captain/page.tsx'), 'utf8')
const shellSmokeSource = readFileSync(join(process.cwd(), 'scripts/site-shell-layout-smoke.mjs'), 'utf8')

function styleBlock(styleName: string) {
  const start = source.indexOf(`const ${styleName}: CSSProperties = {`)
  expect(start, `Missing ${styleName}`).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

describe('Captain onboarding surface', () => {
  it('keeps the first Captain screen progressive and Data Assist aware', () => {
    expect(source).toContain('CAPTAIN_EMPTY_STATE_ACTIONS')
    expect(source).toContain('CaptainLockedSurface')
    expect(source).toContain('Team Hub preview')
    expect(source).toContain('Run match week with less chaos.')
    expect(source).toContain('Preparing Team Hub')
    expect(source).toContain('<h1 style={loadingStateTitleStyle}>Preparing Team Hub</h1>')
    expect(source).toContain('League Office')
    expect(source).not.toContain('League Coordinator')
    expect(source).toContain('Compare plans')
    expect(source).toContain("if (!authResolved || role === 'public' || isMember(role))")
    expect(source).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(source).toContain('const CAPTAIN_LEVEL_UP_HREF = `/level-up/${CAPTAIN_PLAYER_IDENTITY.slug}#level-up-flow`')
    expect(source).toContain('const CAPTAIN_PLAYER_DEVELOPMENT_HREF = `/player-development/${CAPTAIN_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('Set your Player ID so Team Hub can find your profile team.')
    expect(source).toContain('Team Hub Player ID starter')
    expect(source).toContain('Captain Player ID starter')
    expect(source).toContain('Captain Player ID starter read')
    expect(source).toContain('captainPlayerIdStarterRead.map((item)')
    expect(source).toContain('Upload a reviewed team summary or schedule through Data Assist')
    expect(source).toContain('Refresh Captain after the upload review connects teams, schedules, and scorecards.')
    expect(source).toContain('Need a team to manage here?')
    expect(source).toContain('Connect a profile team or upload reviewed roster and schedule data')
    expect(source).toContain("const dataAssistCaptainHref = '/data-assist?intent=upload-source&context=Team%20Hub'")
    expect(source).toContain('href={dataAssistCaptainHref}')
    expect(source).toContain('Set profile')
    expect(source).toContain('Start Level Up')
    expect(source).toContain('Read Player ID')
    expect(source).toContain('Refresh with Data Assist')
    expect(source).toContain('Start with who can play, build the lineup, check the pairings, and send the match-week plan.')
    expect(source).toContain('Start with who can play, choose the lineup, check the pairings, and send the team plan without leaving the match-week lane.')
    expect(source).toContain('Open the weekly brief for lineup, notes, opponent context, and final captain actions.')
    expect(source).not.toContain('send the team plan from one place')
    expect(source).not.toContain('final captain actions in one place')
    expect(source).toContain('Plan practice')
    expect(source).toContain('Schedule practice, invite the roster, and collect In, Out, or Maybe responses in Messages.')
    expect(source).toContain('Save status')
    expect(source).toContain('Know what carries forward.')
    expect(source).toContain('Local honesty')
    expect(source).toContain('CAPTAIN_LOCAL_SYNC_PROOF_CHECKS')
    expect(source).toContain('Saved data check')
    expect(source).toContain('Separate browser proof from linked team history.')
    expect(source).toContain('CAPTAIN_DECISION_HANDOFF_PROOF_STEPS')
    expect(source).toContain('Decision path check')
    expect(source).toContain('Move from availability to lineup to team send.')
    expect(source).toContain('Start with who is in, out, maybe, or still needs a follow-up.')
    expect(source).toContain('Save at least one playable court plan before messaging the team.')
    expect(source).toContain('Compare one projection or alternative when the lineup call is not obvious.')
    expect(source).toContain('Open the weekly brief, team brief, or message prep after the decision is ready.')
    expect(source).toContain('Captain decision path')
    expect(source).toContain('Answer match week from your phone.')
    expect(source).toContain('Who is available?')
    expect(source).toContain('What lineup gives us the best chance?')
    expect(source).toContain('Who should play together?')
    expect(source).toContain('What should I communicate?')
    expect(source).toContain('What needs to be cleaned up?')
    expect(source).toContain('Check Availability')
    expect(source).toContain('Build Lineup')
    expect(source).toContain('Check Pairings')
    expect(source).toContain('Message Team')
    expect(source).toContain('Track Scorecard')
    expect(source).toContain("href: dataAssistCaptainHref")
    expect(source).toContain("targetHref = needsScope ? '#captain-team-scope' : item.href")
    expect(source).toContain('Browser-saved: selected team week, lineups, event notes, response status, and week status.')
    expect(source).toContain('Linked context: roster, schedule, and team history from profile links or reviewed Data Assist imports.')
    expect(source).toContain('Not account sync yet: browser-saved week work should not be treated as cross-device proof.')
    expect(source).toContain('Lineups, event notes, response status, and week status are saved in this browser.')
    expect(source).not.toContain('browser-saved proof')
    expect(source).not.toContain('Browser proof')
    expect(source).toContain('This browser remembers the selected team week so the hub can resume the same captain lane.')
    expect(source).not.toContain("label: 'Read brief'")
    expect(source).not.toContain('Link your player identity in My Lab')
    expect(source).not.toContain('Link in My Lab')
    expect(source).not.toContain("if (role === 'public') return null")
  })

  it('keeps Captain onboarding compact on small mobile screens', () => {
    expect(styleBlock('pageWrap')).toContain("width: 'min(1280px, calc(100% - clamp(24px, 5vw, 48px)))'")
    expect(styleBlock('pageWrap')).toContain('overflowX: \'clip\'')
    expect(styleBlock('loadingWrap')).toContain("width: 'min(1280px, calc(100% - clamp(24px, 5vw, 48px)))'")
    expect(styleBlock('loadingWrap')).toContain('minWidth: 0')
    expect(styleBlock('heroCard')).toContain('minmax(0, 1.2fr)')
    expect(styleBlock('heroCard')).toContain('minmax(min(100%, 320px), 0.8fr)')
    expect(styleBlock('captainDataAssistCueStyle')).toContain('flexWrap: \'wrap\'')
    expect(styleBlock('captainPlayerIdStarterCopyStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainPlayerIdStarterStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainPlayerIdStarterGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 158px), 1fr))'")
    expect(styleBlock('captainPlayerIdStarterCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainSaveStatusGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))'")
    expect(styleBlock('captainSaveStatusCard')).toContain('minWidth: 0')
    expect(styleBlock('captainLocalSyncProofStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainLocalSyncProofGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 240px), 1fr))'")
    expect(styleBlock('captainLocalSyncProofItemStyle')).toContain("gridTemplateColumns: 'minmax(0, 12px) minmax(0, 1fr)'")
    expect(styleBlock('captainLocalSyncProofItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainDecisionHandoffProofGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(styleBlock('captainDecisionHandoffProofItemStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainDecisionHandoffProofItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainDecisionHandoffProofTopStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainPreviewGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 210px), 1fr))'")
    expect(styleBlock('captainPreviewStepStyle')).toContain("gridTemplateColumns: 'minmax(0, 34px) minmax(0, 1fr)'")
    expect(styleBlock('captainPreviewStepStyle')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain('const lockedPreviewPanelStyle')
    expect(source).toContain('const lockedPreviewGrid: CSSProperties')
    expect(source).toContain("'repeat(2, minmax(0, 1fr))'")
    expect(source).toContain('const lockedPreviewStep: CSSProperties')
    expect(source).toContain("'minmax(0, 24px) minmax(0, 1fr)'")
    expect(source).toContain('const lockedPreviewStepCopy: CSSProperties')
    expect(source).toContain('fontSize: isMobile ? 11')
    expect(source).toContain('{!isMobile ? (')
    expect(source).toContain('{!isMobile ? <span>{body}</span> : null}')
    expect(source).toContain("background: 'transparent'")
    expect(source).toContain("boxShadow: 'none'")
    expect(source).toContain('aria-label="Captain mobile unlock actions"')
    expect(source).toContain("const captainUnlockHref = getPlanUnlockHref('captain')")
    expect(source).toContain('summaryOnly={isMobile}')
    expect(source).toContain("router.replace('/login?plan=captain&next=%2Fcaptain')")
    expect(source).not.toContain("router.replace('/login?next=/captain')")
    expect(styleBlock('captainPreviewMobileActionRowStyle')).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock('captainPreviewMobilePrimaryActionStyle')).toContain('minHeight: 38')
    expect(styleBlock('captainPreviewMobilePrimaryActionStyle')).toContain("overflowWrap: 'anywhere'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-unlock-actions-missing'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-unlock-action-not-prominent'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-summary-repeated-guidance'")
    expect(shellSmokeSource).toContain("type: 'captain-mobile-summary-card-not-in-first-view'")
    expect(shellSmokeSource).toContain('/upgrade?plan=captain&next=%2Fcaptain')
    expect(styleBlock('captainDecisionPathShellStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainDecisionPathGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(source).toContain('const dynamicCaptainDecisionPathShell: CSSProperties')
    expect(source).toContain('const dynamicCaptainDecisionPathGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isMobile ? 'repeat(2, minmax(0, 1fr))' : captainDecisionPathGridStyle.gridTemplateColumns")
    expect(source).toContain('const dynamicCaptainDecisionPathCard: CSSProperties')
    expect(source).toContain('minHeight: isMobile ? 0 : captainDecisionPathCardStyle.minHeight')
    expect(source).toContain("{isMobile ? 'Answer match week.' : 'Answer match week from your phone.'}")
    expect(source).toContain("!isMobile ? (")
    expect(source).toContain("{needsScope ? (isMobile ? 'Team' : 'Choose Team') : isMobile ? item.label : item.cta}")
    expect(source).toContain('const dynamicCaptainSaveStatusShell: CSSProperties')
    expect(source).toContain('const dynamicCommandCenterShell: CSSProperties')
    expect(source).toContain('const dynamicCommandCenterCard: CSSProperties')
    expect(source).toContain('<section style={dynamicCommandCenterShell} aria-label="Captain week command center">')
    expect(source).toContain('Captain week command center')
    expect(source).toContain("Make this week's call.")
    expect(source).toContain("Make this week's call from one lane.")
    expect(source).toContain('Captain week snapshot')
    expect(source).toContain('Captain week readiness')
    expect(source).toContain('Ready for match day')
    expect(source).toContain('captainCommandSnapshots')
    expect(source).toContain('captainReadinessScore}% ready')
    expect(source).toContain('Captain season launch checklist')
    expect(source).toContain('Season launch checklist')
    expect(source).toContain('Start the season clean.')
    expect(source).toContain('Start the season with the team ready.')
    expect(source).toContain('Season launch snapshot')
    expect(source).toContain('Refresh team data')
    expect(source).toContain('Season tools')
    expect(source).toContain('captainSeasonLaunchItems')
    expect(source).toContain('captainSeasonLaunchReadyCount')
    expect(source).toContain('Captain opponent scout pocket')
    expect(source).toContain('Opponent scout pocket')
    expect(source).toContain('Know the other side.')
    expect(source).toContain('Know the other side before you set courts.')
    expect(source).toContain('Scout checks')
    expect(source).toContain('Open scout brief')
    expect(source).toContain('Review patterns')
    expect(source).toContain('opponentScoutChecks')
    expect(source).toContain('opponentScoutReadyCount')
    expect(source).toContain('Captain player readiness pulse')
    expect(source).toContain('Player readiness pulse')
    expect(source).toContain('Know who is ready.')
    expect(source).toContain('Know who is ready before you lock courts.')
    expect(source).toContain('Team pulse')
    expect(source).toContain('Readiness checks')
    expect(source).toContain('Check availability')
    expect(source).toContain('Build lineup')
    expect(source).toContain('Send nudge')
    expect(source).toContain('playerReadinessPulseChecks')
    expect(source).toContain('playerReadinessReadyCount')
    expect(source).toContain('playerReadinessRiskCount')
    expect(source).toContain('Captain nudge composer')
    expect(source).toContain('Nudge composer')
    expect(source).toContain('Send the right nudge.')
    expect(source).toContain('Send the right nudge before replies drift.')
    expect(source).toContain('Best next send')
    expect(source).toContain('Ready-to-send drafts')
    expect(source).toContain('Confirm availability')
    expect(source).toContain('Running late')
    expect(source).toContain('Need sub')
    expect(source).toContain('Final lineup posted')
    expect(source).toContain('Copy draft')
    expect(source).toContain('captainNudgeDrafts')
    expect(source).toContain('captainNudgePrimaryDraft')
    expect(source).toContain('handleCopyCaptainNudge')
    expect(source).toContain('Captain week timeline')
    expect(source).toContain('Week timeline')
    expect(source).toContain('Keep the week moving.')
    expect(source).toContain('Keep the week moving from first nudge to closeout.')
    expect(source).toContain('Today')
    expect(source).toContain('Tomorrow')
    expect(source).toContain('Match day')
    expect(source).toContain('After play')
    expect(source).toContain('Tighten replies')
    expect(source).toContain('Close the loop')
    expect(source).toContain('captainWeekTimelineItems')
    expect(source).toContain('captainWeekTimelineNextItem')
    expect(source).toContain('captainWeekTimelineReadyCount')
    expect(source).toContain('Captain court confidence meter')
    expect(source).toContain('Court confidence meter')
    expect(source).toContain('Trust the courts.')
    expect(source).toContain('Trust the courts before you send the lineup.')
    expect(source).toContain('Spot solid courts, backup needs, and rating-watch calls before the final team note goes out.')
    expect(source).toContain('Captain court confidence')
    expect(source).toContain('Solid')
    expect(source).toContain('Watch')
    expect(source).toContain('Backup')
    expect(source).toContain('captainCourtConfidenceItems')
    expect(source).toContain('captainCourtConfidencePercent')
    expect(source).toContain('captainCourtBackupCount')
    expect(source).toContain('captainCourtWatchCount')
    expect(source).toContain('Captain match day sheet')
    expect(source).toContain('Match day sheet')
    expect(source).toContain('Carry the court plan.')
    expect(source).toContain('Carry the court plan into match day.')
    expect(source).toContain("See today&apos;s courts, confirmation gaps, arrival details, and the scorecard handoff before players arrive.")
    expect(source).toContain('Today&apos;s lineup')
    expect(source).toContain('At-court checks')
    expect(source).toContain('Captain sub board')
    expect(source).toContain('Sub board')
    expect(source).toContain('Cover late changes.')
    expect(source).toContain('Cover late changes before warm-up.')
    expect(source).toContain('Court watch')
    expect(source).toContain('Backup reads')
    expect(source).toContain('Find backup')
    expect(source).toContain('Move in lineup')
    expect(source).toContain('Send sub update')
    expect(source).toContain('matchDaySubBoardFlags')
    expect(source).toContain('matchDaySubCandidates')
    expect(source).toContain('Send final note')
    expect(source).toContain('Follow up gaps')
    expect(source).toContain('Upload scorecard')
    expect(source).toContain('Captain post-match closeout')
    expect(source).toContain('Post-match closeout')
    expect(source).toContain('Close the match.')
    expect(source).toContain('Close the match while it is fresh.')
    expect(source).toContain('Scorecard trail')
    expect(source).toContain('Closeout checks')
    expect(source).toContain('Court results to capture')
    expect(source).toContain('Send recap')
    expect(source).toContain('Review team brief')
    expect(source).toContain('Mark closed')
    expect(source).toContain('postMatchCloseoutChecks')
    expect(source).toContain('postMatchCloseoutRows')
    expect(source).toContain('matchDayChecklist')
    expect(source).toContain('matchDayLineupPreview')
    expect(source.indexOf('{captainCommandCenter}')).toBeLessThan(
      source.indexOf('{captainSeasonLaunchChecklist}'),
    )
    expect(source.indexOf('{captainSeasonLaunchChecklist}')).toBeLessThan(
      source.indexOf('{captainOpponentScoutPocket}'),
    )
    expect(source.indexOf('{captainOpponentScoutPocket}')).toBeLessThan(
      source.indexOf('{captainPlayerReadinessPulse}'),
    )
    expect(source.indexOf('{captainPlayerReadinessPulse}')).toBeLessThan(
      source.indexOf('{captainNudgeComposer}'),
    )
    expect(source.indexOf('{captainNudgeComposer}')).toBeLessThan(
      source.indexOf('{captainWeekTimeline}'),
    )
    expect(source.indexOf('{captainWeekTimeline}')).toBeLessThan(
      source.indexOf('{captainCourtConfidenceMeter}'),
    )
    expect(source.indexOf('{captainCourtConfidenceMeter}')).toBeLessThan(
      source.indexOf('{captainMatchDaySheet}'),
    )
    expect(source.indexOf('<section style={dynamicMatchDaySheetShell} aria-label="Captain match day sheet">')).toBeLessThan(
      source.indexOf('<section style={dynamicPostMatchCloseoutShell} aria-label="Captain post-match closeout">'),
    )
    expect(source.indexOf('<section style={dynamicPostMatchCloseoutShell} aria-label="Captain post-match closeout">')).toBeLessThan(
      source.indexOf('<section style={dynamicCaptainDecisionPathShell} aria-label="Captain decision path">'),
    )
    expect(source.indexOf('<section style={dynamicCommandCenterShell} aria-label="Captain week command center">')).toBeLessThan(
      source.indexOf('<details style={dynamicCaptainSaveStatusShell} aria-label="Captain save status">'),
    )
    expect(styleBlock('commandCenterSnapshotGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('commandCenterSnapshotCard')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterSnapshotCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('commandCenterReadinessShell')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterReadinessTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('commandCenterGrid')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterCard')).toContain('minWidth: 0')
    expect(styleBlock('commandCenterCard')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain('const dynamicSeasonLaunchShell: CSSProperties')
    expect(source).toContain('const dynamicSeasonLaunchGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : seasonLaunchGrid.gridTemplateColumns")
    expect(styleBlock('seasonLaunchShell')).toContain('minWidth: 0')
    expect(styleBlock('seasonLaunchSnapshotGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 170px), 1fr))'")
    expect(styleBlock('seasonLaunchSnapshotCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('seasonLaunchGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 210px), 1fr))'")
    expect(styleBlock('seasonLaunchCard')).toContain('minWidth: 0')
    expect(styleBlock('seasonLaunchCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('seasonLaunchCardTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('seasonLaunchCardDetail')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('seasonLaunchActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicOpponentScoutShell: CSSProperties')
    expect(source).toContain('const dynamicOpponentScoutGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)' : opponentScoutGrid.gridTemplateColumns")
    expect(styleBlock('opponentScoutShell')).toContain('minWidth: 0')
    expect(styleBlock('opponentScoutGrid')).toContain('minmax(min(100%, 310px), 0.88fr)')
    expect(styleBlock('opponentScoutMain')).toContain('minWidth: 0')
    expect(styleBlock('opponentScoutHeroTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('opponentScoutTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('opponentScoutMetaGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('opponentScoutMetaCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('opponentScoutNoteCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('opponentScoutChecklist')).toContain('minWidth: 0')
    expect(styleBlock('opponentScoutItem')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('opponentScoutItemTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('opponentScoutActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicPlayerReadinessPulseShell: CSSProperties')
    expect(source).toContain('const dynamicPlayerReadinessPulseGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)' : playerReadinessPulseGrid.gridTemplateColumns")
    expect(styleBlock('playerReadinessPulseShell')).toContain('minWidth: 0')
    expect(styleBlock('playerReadinessPulseGrid')).toContain('minmax(min(100%, 300px), 0.86fr)')
    expect(styleBlock('playerReadinessMain')).toContain('minWidth: 0')
    expect(styleBlock('playerReadinessScoreTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('playerReadinessScoreValue')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerReadinessMetricGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 140px), 1fr))'")
    expect(styleBlock('playerReadinessMetricCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerReadinessChecklist')).toContain('minWidth: 0')
    expect(styleBlock('playerReadinessItem')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerReadinessItemTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('playerReadinessActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicCaptainNudgeComposerShell: CSSProperties')
    expect(source).toContain('const dynamicCaptainNudgeComposerGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)' : captainNudgeComposerGrid.gridTemplateColumns")
    expect(styleBlock('captainNudgeComposerShell')).toContain('minWidth: 0')
    expect(styleBlock('captainNudgeComposerGrid')).toContain('minmax(min(100%, 340px), 1fr)')
    expect(styleBlock('captainNudgeFeaturedDraft')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainNudgeFeaturedTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainNudgeFeaturedTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainNudgeDraftBody')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainNudgeDraftList')).toContain('minWidth: 0')
    expect(styleBlock('captainNudgeDraftGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))'")
    expect(styleBlock('captainNudgeDraftCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainNudgeDraftTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainNudgeActionRow')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainNudgeMiniActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicCaptainWeekTimelineShell: CSSProperties')
    expect(source).toContain('const dynamicCaptainWeekTimelineGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : captainWeekTimelineGrid.gridTemplateColumns")
    expect(styleBlock('captainWeekTimelineShell')).toContain('minWidth: 0')
    expect(styleBlock('captainWeekTimelineGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 210px), 1fr))'")
    expect(styleBlock('captainWeekTimelineCard')).toContain('minWidth: 0')
    expect(styleBlock('captainWeekTimelineCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainWeekTimelineTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainWeekTimelineMarker')).toContain('minWidth: 0')
    expect(styleBlock('captainWeekTimelineDot')).toContain("flex: '0 0 28px'")
    expect(styleBlock('captainWeekTimelineBody')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainWeekTimelineTitle')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain('const dynamicCaptainCourtConfidenceShell: CSSProperties')
    expect(source).toContain('const dynamicCaptainCourtConfidenceGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : captainCourtConfidenceGrid.gridTemplateColumns")
    expect(styleBlock('captainCourtConfidenceShell')).toContain('minWidth: 0')
    expect(styleBlock('captainCourtConfidenceSummary')).toContain('minWidth: 0')
    expect(styleBlock('captainCourtConfidenceTrack')).toContain("overflow: 'hidden'")
    expect(styleBlock('captainCourtConfidenceStats')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
    expect(styleBlock('captainCourtConfidenceStatCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainCourtConfidenceGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))'")
    expect(styleBlock('captainCourtConfidenceCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainCourtConfidenceTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainCourtConfidenceBody')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainCourtConfidencePlayers')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainCourtConfidenceActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicMatchDaySheetShell: CSSProperties')
    expect(source).toContain('const dynamicMatchDaySheetGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)' : matchDaySheetGrid.gridTemplateColumns")
    expect(styleBlock('matchDaySheetShell')).toContain('minWidth: 0')
    expect(styleBlock('matchDayLogisticsGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 180px), 1fr))'")
    expect(styleBlock('matchDayLogisticsCard')).toContain('minWidth: 0')
    expect(styleBlock('matchDaySheetGrid')).toContain('minmax(min(100%, 300px), 0.82fr)')
    expect(styleBlock('matchDaySheetMain')).toContain('minWidth: 0')
    expect(styleBlock('matchDaySheetTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('matchDayLineupStack')).toContain('minWidth: 0')
    expect(styleBlock('matchDayCourtCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('matchDayCourtTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('matchDayChecklistPanel')).toContain('minWidth: 0')
    expect(styleBlock('matchDayChecklistItem')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('matchDayActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicMatchDaySubBoardGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)' : matchDaySubBoardGrid.gridTemplateColumns")
    expect(styleBlock('matchDaySubBoardShell')).toContain('minWidth: 0')
    expect(styleBlock('matchDaySubBoardHeader')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('matchDaySubBoardGrid')).toContain('minmax(min(100%, 300px), 1.1fr)')
    expect(styleBlock('matchDaySubPanel')).toContain('minWidth: 0')
    expect(styleBlock('matchDaySubList')).toContain('minWidth: 0')
    expect(styleBlock('matchDaySubCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('matchDaySubCandidateTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('matchDaySubActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain('const dynamicPostMatchCloseoutShell: CSSProperties')
    expect(source).toContain('const dynamicPostMatchCloseoutGrid: CSSProperties')
    expect(source).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)' : postMatchCloseoutGrid.gridTemplateColumns")
    expect(styleBlock('postMatchCloseoutShell')).toContain('minWidth: 0')
    expect(styleBlock('postMatchCloseoutGrid')).toContain('minmax(min(100%, 300px), 0.86fr)')
    expect(styleBlock('postMatchCloseoutMain')).toContain('minWidth: 0')
    expect(styleBlock('postMatchCourtList')).toContain('minWidth: 0')
    expect(styleBlock('postMatchCourtCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('postMatchCloseoutChecklist')).toContain('minWidth: 0')
    expect(styleBlock('postMatchCloseoutItem')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('postMatchCloseoutTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('postMatchActionRow')).toContain("flexWrap: 'wrap'")
    expect(source).toContain("{isMobile ? 'What saves here?' : 'Know what carries forward.'}")
    expect(source).toContain("gridTemplateColumns: isMobile ? 'repeat(2, minmax(0, 1fr))' : statusStrip.gridTemplateColumns")
    expect(styleBlock('captainDecisionPathCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('captainDecisionPathCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('captainDecisionPathTopStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('captainDecisionPathAnswerStyle')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(source).not.toContain("calc(100% - 48px)")
    expect(source).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(source).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(source).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(source).not.toContain("gridTemplateColumns: 'auto minmax(0, 1fr)'")
  })

  it('keeps Captain empty states actionable for missing teams and rosters', () => {
    expect(source).toContain('Choose or connect a team scope.')
    expect(source).toContain('No roster players are available yet.')
    expect(source).toContain('Set profile')
    expect(source).toContain('Upload team data')
    expect(source).toContain('Open Data Assist')
    expect(source).toContain('Refresh Captain')
    expect(source).toContain('captainEmptyActionRowStyle')
    expect(source).toContain('inlineEmptyLinkStyle')
    expect(source).toContain('inlineEmptyButtonStyle')
  })
})
