import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Captain practice scheduler', () => {
  it('surfaces practice coordination as a Captain workspace page', () => {
    const source = readFileSync(join(process.cwd(), 'app/captain/practice/page.tsx'), 'utf8')

    expect(source).toContain('Plan practice without a separate thread.')
    expect(source).toContain('Practice scheduler setup')
    expect(source).toContain('ScheduleMessageComposer')
    expect(source).toContain('mode="captain-practice"')
    expect(source).toContain('triggerLabel="Review & send invite"')
    expect(source).toContain('defaultNotes={practiceNotes}')
    expect(source).toContain('defaultEndTime={practiceEndTime}')
    expect(source.indexOf('aria-label="Practice scheduler setup"')).toBeLessThan(
      source.indexOf('Plan practice without a separate thread.'),
    )
    expect(source).toContain('router.replace(`/login?plan=captain&next=${encodeURIComponent(returnTo)}`)')
    expect(source).toContain('Unlock practice coordination with Captain')
  })

  it('loads Captain scope and a one-time Level Up challenge into the practice form', () => {
    const source = readFileSync(join(process.cwd(), 'app/captain/practice/page.tsx'), 'utf8')

    expect(source).toContain("searchParams.get('team')")
    expect(source).toContain("searchParams.get('league')")
    expect(source).toContain("searchParams.get('flight')")
    expect(source).toContain('buildCaptainLevelUpChallenge')
    expect(source).toContain('incomingLevelUpChallenge ? `${incomingLevelUpChallenge.title}: ${incomingLevelUpChallenge.focus}`')
    expect(source).toContain("['levelUpChallenge', 'card']")
    expect(source).toContain('Challenge loaded')
    expect(source).toContain('Practice focus is filled in.')
  })

  it('opens as a practice hub before asking the captain to create another practice', () => {
    const source = readFileSync(join(process.cwd(), 'app/captain/practice/page.tsx'), 'utf8')
    const scheduling = readFileSync(join(process.cwd(), 'lib/internal-scheduling.ts'), 'utf8')

    expect(source).toContain('listCaptainPracticeManagementOverview')
    expect(source).toContain('Manage practice.')
    expect(source).toContain('Create another practice')
    expect(source).toContain('Manage roster')
    expect(source).toContain('Open signup')
    expect(source).toContain('Delete practice')
    expect(source).toContain('players will no longer be able to RSVP')
    expect(source).toContain('notifyParticipants: false')
    expect(source).toContain('current.filter(({ event }) => event.id !== practice.event.id)')
    expect(source).toContain('signed up')
    expect(source).toContain('confirmed')
    expect(source).toContain('waiting')
    expect(source).toContain('event.metadata.practiceEndTime')
    expect(source).toContain('`/messages?thread=${encodeURIComponent(event.conversationId)}`')
    expect(scheduling).toContain('export async function listCaptainPracticeManagementOverview')
    expect(scheduling).toContain(".eq('event_type', 'captain_practice')")
    expect(scheduling).toContain(".eq('created_by_user_id', identity.userId)")
    expect(scheduling).toContain('input.notifyParticipants !== false')
  })

  it('uses the existing practice scheduling foundation instead of a separate workflow', () => {
    const composer = readFileSync(join(process.cwd(), 'app/components/schedule-message-composer.tsx'), 'utf8')
    const scheduling = readFileSync(join(process.cwd(), 'lib/internal-scheduling.ts'), 'utf8')
    const teams = readFileSync(join(process.cwd(), 'app/compete/teams/page.tsx'), 'utf8')
    const teamCard = readFileSync(join(process.cwd(), 'app/compete/teams/team-home-card.tsx'), 'utf8')
    const room = readFileSync(join(process.cwd(), 'app/team-room/page.tsx'), 'utf8')

    expect(composer).toContain('defaultNotes')
    expect(composer).toContain('scheduledEndTime')
    expect(composer).toContain('End time must be later than start time.')
    expect(composer).toContain('createCaptainPracticeThread')
    expect(composer).toContain("action: 'send'")
    expect(composer).toContain('postedToTeamChat')
    expect(composer).toContain('Text group')
    expect(composer).toContain('View RSVPs')
    expect(composer).toContain('practiceRsvpPath(result.publicToken)')
    expect(composer).toContain('No account needed.')
    expect(composer).toContain('PracticeVenueFinder')
    expect(composer).toContain('Recognize this location for players')
    expect(composer).toContain('Find in Google Maps')
    expect(scheduling).toContain("eventType: 'captain_practice'")
    expect(scheduling).toContain("from('captain_practice_invites')")
    expect(scheduling).toContain('Please mark In, Out, or Maybe')
    expect(scheduling).toContain('profileName')
    expect(teams).toContain("buildCaptainScopedHref('/captain/practice'")
    expect(teamCard).toContain('Plan practice')
    expect(room).toContain('<Link className={styles.quickButton} href={practiceHref}>Plan practice</Link>')
  })

  it('shows the captain who is coming without mixing replies from another scheduled event', () => {
    const messages = readFileSync(join(process.cwd(), 'app/messages/page.tsx'), 'utf8')
    const scheduling = readFileSync(join(process.cwd(), 'lib/internal-scheduling.ts'), 'utf8')
    const migration = readFileSync(join(process.cwd(), 'supabase/migrations/20260914000100_add_practice_captain_confirmations.sql'), 'utf8')

    expect(messages).toContain('const selectedScheduleResponses = useMemo(')
    expect(messages).toContain('response.eventId === selectedScheduleEvent.id')
    expect(messages).toContain('Practice roster')
    expect(messages).toContain('See every reply')
    expect(messages).toContain('practiceSignedUpPlayers')
    expect(messages).toContain('practiceConfirmedPlayers')
    expect(messages).toContain("practiceRosterGroups.get('waitlist')")
    expect(messages).toContain('Remind ${practiceRosterGroups.get(\'unanswered\')!.length} waiting')
    expect(messages).toContain('Confirm spot')
    expect(messages).toContain('Undo confirm')
    expect(messages).toContain('Text group')
    expect(messages).toContain('setCaptainPracticeInviteeConfirmed')
    expect(scheduling).toContain('captain_confirmed_at')
    expect(migration).toContain('captain_confirmed_by_user_id')
  })

  it('gives guests a premium account-free RSVP and calendar path', () => {
    const page = readFileSync(join(process.cwd(), 'app/pr/[code]/practice-rsvp-client.tsx'), 'utf8')
    const route = readFileSync(join(process.cwd(), 'app/api/practice/[token]/route.ts'), 'utf8')
    const reminder = readFileSync(join(process.cwd(), 'app/api/captain/practices/[eventId]/remind/route.ts'), 'utf8')

    expect(page).toContain('No account needed to RSVP.')
    expect(page).toContain('Add to iPhone')
    expect(page).toContain('Google Calendar')
    expect(page).toContain('Who’s coming')
    expect(page).toContain('Captain confirmed')
    expect(page).toContain('Signed up')
    expect(page).toContain('Guest player')
    expect(page).toContain('You do not need a TenAceIQ account.')
    expect(page).toContain('Create a free account')
    expect(page).toContain('player.isTeamRoster')
    expect(page).toContain('window.setInterval(() => void loadPractice(), 15000)')
    expect(route).toContain("response_status: status")
    expect(route).toContain("from('captain_practice_invitees')")
    expect(route).toContain('cleanPracticeDisplayName')
    expect(route).toContain('isTeamRoster: Boolean(row.player_id)')
    expect(route).toContain("from('internal_schedule_event_responses').upsert")
    expect(reminder).toContain(".eq('response_status', 'unanswered')")
    expect(reminder).toContain('smsHref')
  })
})
