import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const coachSource = readFileSync(join(process.cwd(), 'app/coach/page.tsx'), 'utf8')
const myLabSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const messagesSource = readFileSync(join(process.cwd(), 'app/messages/page.tsx'), 'utf8')

describe('coach assignment message context', () => {
  it('passes assignment context from Coach and Player assignment cards into Messages', () => {
    for (const source of [coachSource, myLabSource]) {
      expect(source).toContain('assignmentId: assignment.id')
      expect(source).toContain('assignmentTitle: assignment.title')
      expect(source).toContain('assignmentFocus: assignment.focus')
      expect(source).toContain('assignmentCardId:')
      expect(source).toContain("params.set('assignmentId'")
      expect(source).toContain("params.set('assignmentTitle'")
      expect(source).toContain("params.set('assignmentFocus'")
      expect(source).toContain("params.set('assignmentCardId'")
    }
  })

  it('stores and displays assignment metadata on direct coach-player threads', () => {
    expect(messagesSource).toContain('PLAYER_TIER_NAME = MEMBERSHIP_TIERS.player_plus.name')
    expect(messagesSource).toContain('`${PLAYER_TIER_NAME} coach thread`')
    expect(messagesSource).toContain('`${PLAYER_TIER_NAME} coach check-in`')
    expect(messagesSource).toContain('quick {PLAYER_TIER_NAME} check-ins')
    expect(messagesSource).not.toContain('Player+ coach thread')
    expect(messagesSource).not.toContain('Player+ coach check-in')
    expect(messagesSource).not.toContain('quick Player+ check-ins')
    expect(messagesSource).toContain('assignmentId: searchParams.get')
    expect(messagesSource).toContain('assignmentTitle: searchParams.get')
    expect(messagesSource).toContain('assignmentFocus: searchParams.get')
    expect(messagesSource).toContain('assignmentCardId: searchParams.get')
    expect(messagesSource).toContain('metadata: {')
    expect(messagesSource).toContain('Assignment follow-up:')
  })

  it('links message context back to the exact assignment card when possible', () => {
    expect(coachSource).toContain('id={`coach-assignment-${assignment.id}`}')
    expect(myLabSource).toContain('id={`coach-assignment-${assignment.id}`}')
    expect(messagesSource).toContain('conversation.metadata.assignmentId')
    expect(messagesSource).toContain('#coach-assignment-')
    expect(messagesSource).toContain('return `/coach${assignmentAnchor}`')
    expect(messagesSource).toContain('return assignmentAnchor ? `/mylab${assignmentAnchor}` :')
  })

  it('opens assignment message context straight into player court mode', () => {
    expect(coachSource).toContain('assignmentCardId: getCoachAssignmentCourtCardId(assignment)')
    expect(myLabSource).toContain('assignmentCardId: getAssignmentLevelUpCardId(assignment)')
    expect(messagesSource).toContain('buildConversationCourtHref')
    expect(messagesSource).toContain('conversation.metadata.assignmentCardId')
    expect(messagesSource).toContain('getMessageAssignmentCardId')
    expect(messagesSource).toContain('getMessageAssignmentShortcutCardId')
    expect(messagesSource).toContain('inferMessageAssignmentCardId')
    expect(messagesSource).toContain('LEVEL_UP_CARDS')
    expect(messagesSource).toContain('.filter((card) => card.assignable)')
    expect(messagesSource).toContain("contact.relationship === 'student'")
    expect(messagesSource).toContain('selectedCourtHref')
    expect(messagesSource).toContain('Open on court')
    expect(messagesSource).toContain("params.set('assignmentTitle'")
    expect(messagesSource).toContain("params.set('assignmentFocus'")
    expect(messagesSource).toContain('buildConversationAssignmentHandoff')
    expect(messagesSource).toContain('selectedAssignmentHandoff')
    expect(messagesSource).toContain('assignmentHandoffStyle')
    expect(messagesSource).toContain('Assignment handoff')
    expect(messagesSource).toContain('Open court mode, score proof, then send the recap.')
    expect(messagesSource).toContain('Review proof, choose the next coach move, then send the note.')
    expect(messagesSource).toContain('getMessageAssignmentCard(conversation)')
    expect(messagesSource).toContain('buildMessageAssignmentStandard')
    expect(messagesSource).toContain('selectedAssignmentHandoff.standard')
    expect(messagesSource).toContain('Assignment proof standard for')
    expect(messagesSource).toContain('Count only')
    expect(messagesSource).toContain('Common leak')
    expect(messagesSource).toContain('Next clean rep')
    expect(messagesSource).toContain('card.qualityChecks?.[0] ?? card.proof')
    expect(messagesSource).toContain('card.commonMiss?.fix ?? card.regression ?? card.cue')
    expect(messagesSource).toContain('Read proof')
    expect(messagesSource).toContain('Repeat or add pressure')
    expect(messagesSource).toContain('Coach note')
    expect(messagesSource).toContain('0-5 proof')
    expect(messagesSource).toContain('Reply with recap')
    expect(messagesSource).toContain("'assignment'")
    expect(messagesSource).toContain("if (filter === 'assignment') return isCoachAssignmentConversation(conversation)")
    expect(messagesSource).toContain("if (filter === 'assignment') return 'Assignment'")
    expect(messagesSource).toContain('assignmentPillStyle')
    expect(messagesSource).toContain('assignmentThreadCount')
    expect(messagesSource).toContain('No assignment threads')
    expect(messagesSource).toContain('/mylab#coach-assignments')
    expect(messagesSource).toContain('Assignment threads appear after a coach or player messages about assigned work.')
  })

  it('adds court-ready quick replies for assignment message threads', () => {
    expect(messagesSource).toContain('isCoachAssignmentConversation')
    expect(messagesSource).toContain('getCoachAssignmentConversationRelationship')
    expect(messagesSource).toContain("relationship === 'student'")
    expect(messagesSource).toContain('Reviewing proof')
    expect(messagesSource).toContain('Repeat cleaner')
    expect(messagesSource).toContain('Add pressure')
    expect(messagesSource).toContain('Starting court')
    expect(messagesSource).toContain('Starting the court work')
    expect(messagesSource).toContain('Proof update')
    expect(messagesSource).toContain('score __/5')
    expect(messagesSource).toContain('Next focus')
    expect(messagesSource).toContain('repeat this cleaner, make it easier, or add pressure')
  })

  it('keeps coach assignment texts pointed at the phone court flow', () => {
    expect(coachSource).toContain('buildCoachAssignmentCourtHref')
    expect(coachSource).toContain('lastAssignmentShareHref')
    expect(coachSource).toContain('assignmentShareHref')
    expect(coachSource).toContain('Open court mode:')
    expect(coachSource).toContain('copyCoachAssignmentCourtLink')
    expect(coachSource).toContain('Copy court link')
    expect(coachSource).toContain('Text court link')
  })

  it('shows coach-facing Level Up standards before assigning a card', () => {
    expect(coachSource).toContain('buildCoachLevelUpAssignmentStandard')
    expect(coachSource).toContain('selectedLevelUpAssignmentStandard')
    expect(coachSource).toContain('Coach assignment standard')
    expect(coachSource).toContain('Player sees')
    expect(coachSource).toContain('Coach watches')
    expect(coachSource).toContain('Common leak')
    expect(coachSource).toContain('Next rep')
    expect(coachSource).toContain('Score proof, note whether')
    expect(coachSource).toContain('Coach watch:')
    expect(coachSource).toContain('tracker: [card.proof, coachWatches, nextRep, scoreRead]')
  })
})
