import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/compete/leagues/page.tsx'), 'utf8')

function styleBlock(styleName: string) {
  const pattern = new RegExp(`const ${styleName}(?:: CSSProperties)? = ([\\s\\S]*?)(?=\\nconst |\\nfunction |\\nexport |$)`)
  const match = source.match(pattern)
  if (!match) throw new Error(`Missing style block: ${styleName}`)
  return match[0]
}

describe('compete leagues readiness', () => {
  it('gives Leagues visitors a clear first-action path', () => {
    expect(source).toContain("import { DATA_ASSIST_STORY, LEAGUE_COORDINATOR_STORY, MY_LAB_STORY } from '@/lib/product-story'")
    expect(source).toContain('const leaguePathActions')
    expect(source).toContain('function LeaguePathPanel')
    expect(source).toContain('League path')
    expect(source).toContain('id="compete-league-path-title"')
    expect(source).toContain('Open the league room you need.')
    expect(source).toContain('Choose what to do with a league.')
    expect(source).toContain('Start with the league need, then open the shortest path to the next action.')
    expect(source).not.toContain('Start with the league job')
    expect(source).toContain('How do I run the season?')
    expect(source).toContain('Open League Office')
    expect(source).toContain('Which league am I looking for?')
    expect(source).toContain('Browse leagues')
    expect(source).toContain('How do I refresh schedules or scorecards?')
    expect(source).toContain('Upload league data')
    expect(source).toContain('What does this mean for my team?')
    expect(source).toContain('Open Team week')
    expect(source).toContain('data-compete-league-path-job={action.job}')
    expect(source).toContain('Help me choose')
    expect(source).toContain('Open the path that matches the tennis need.')
    expect(source).toContain('function LeagueToolsDisclosure')
    expect(source).toContain('More league tools')
    expect(source).toContain('meta="Run"')
    expect(source).not.toContain('Open the workspace that matches the job.')
    expect(source).not.toContain('meta="Workspace"')
  })

  it('keeps League path cards tappable on mobile', () => {
    expect(styleBlock('leaguePathStyle')).toContain('minWidth: 0')
    expect(styleBlock('leaguePathStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('leaguePathHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('leaguePathGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('leaguePathCardStyle')).toContain('minHeight: 92')
    expect(styleBlock('leaguePathCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('leaguePathHelpGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('leaguePathHelpItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(source).toContain("import { useViewportBreakpoints } from '@/lib/use-viewport-breakpoints'")
    expect(source).toContain('const { isMobile } = useViewportBreakpoints()')
    expect(source).toContain("display: isMobile ? 'none' : undefined")
    expect(source).toContain("minHeight: isMobile ? 76 : leaguePathCardStyle.minHeight")
    expect(source).toContain("padding: isMobile ? '10px' : leaguePathCardStyle.padding")
  })

  it('puts saved league rooms before guidance and secondary tools', () => {
    expect(source).toContain('Captain-owned league rooms for results, schedules, team context, and weekly decisions.')
    expect(source).toContain('Player-vs-player league rooms for standings, results, prompts, and next-match prep.')
    expect(source.indexOf('title="Team Leagues"')).toBeLessThan(source.indexOf('<LeaguePathPanel />'))
    expect(source.indexOf('title="Individual Leagues"')).toBeLessThan(source.indexOf('<LeaguePathPanel />'))
    expect(source.indexOf('<LeaguePathPanel />')).toBeGreaterThan(source.indexOf('title="Individual Leagues"'))
    expect(source.indexOf('<LeagueToolsDisclosure>')).toBeGreaterThan(source.indexOf('<LeaguePathPanel />'))
    expect(source.indexOf('<LeagueSupportDisclosure>')).toBeGreaterThan(source.indexOf('</LeagueToolsDisclosure>'))
    expect(source.indexOf('<LeagueUpgradeDisclosure>')).toBeGreaterThan(source.indexOf('</LeagueSupportDisclosure>'))
  })

  it('shows league readiness and keeps rows focused on one primary action', () => {
    expect(source).toContain('leagueReadinessItems')
    expect(source).toContain("label: 'Teams'")
    expect(source).toContain("label: 'Schedule'")
    expect(source).toContain("label: 'Season'")
    expect(source).toContain("label: 'Players'")
    expect(source).toContain("label: 'Results'")
    expect(source).toContain("label: 'Prompts'")
    expect(source).toContain('leagueReadinessGridStyle')
    expect(source).toContain('leaguePrimaryActionStyle')
    expect(source).toContain('Record results')
    expect(source).toContain('Log result')
    expect(source).toContain('Open league')
    expect(source).not.toContain("const secondaryActionLabel")
    expect(source).not.toContain("const secondaryActionHref")
  })

  it('connects individual league context back into Player ID and Level Up prep', () => {
    expect(source).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(source).toContain("const LEAGUE_PLAYER_IDENTITY = getPlayerDevelopmentIdentity('relentless-competitor-4-0')")
    expect(source).toContain('const LEAGUE_PLAYER_IDENTITY_READ = getPlayerDevelopmentIdentityActionRead(LEAGUE_PLAYER_IDENTITY)')
    expect(source).toContain('const LEAGUE_LEVEL_UP_HREF = `/level-up/${LEAGUE_PLAYER_IDENTITY.slug}#level-up-flow`')
    expect(source).toContain('const LEAGUE_PLAYER_DEVELOPMENT_HREF = `/player-development/${LEAGUE_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('function LeagueSupportDisclosure')
    expect(source).toContain('Use Player ID inside this league room')
    expect(source).toContain('aria-label="Leagues Player ID individual prep"')
    expect(source).toContain('aria-label="Leagues Player ID starter read"')
    expect(source).toContain('Individual league to Player ID')
    expect(source).toContain('When the league question becomes personal, pick one cue.')
    expect(source).toContain('Keep League Office as the season layer, then use Player ID to turn standings, results, and prompts into one prep action.')
    expect(source).toContain('Start Level Up')
    expect(source).toContain('Read Player ID')
    expect(source).toContain('Open results')
    expect(source.indexOf('<LeaguePlayerIdPrepPanel />')).toBeGreaterThan(source.indexOf('<LeaguePathPanel />'))
    expect(source.indexOf('<LeaguePlayerIdPrepPanel />')).toBeGreaterThan(source.indexOf('</CompeteGrid>'))
  })

  it('keeps the Leagues Player ID bridge compact on phones', () => {
    expect(styleBlock('leagueSupportDisclosureStyle')).toContain('minWidth: 0')
    expect(styleBlock('leagueSupportSummaryStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('leagueSupportBodyStyle')).toContain('minWidth: 0')
    expect(styleBlock('leaguePlayerIdPrepStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 240px), 1fr))'")
    expect(styleBlock('leaguePlayerIdPrepStyle')).toContain('minWidth: 0')
    expect(styleBlock('leaguePlayerIdPrepStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('leaguePlayerIdPrepGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('leaguePlayerIdPrepCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('leaguePlayerIdActionRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('leaguePlayerIdActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock('leaguePlayerIdActionStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock('leaguePlayerIdActionStyle')).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps empty league sections actionable without duplicating row actions', () => {
    expect(source).toContain('function EmptyLeagueSection')
    expect(source).toContain('Team seasons start in League Office.')
    expect(source).toContain('Individual play starts with a league room.')
    expect(source).toContain('Create league')
    expect(source).toContain('Browse leagues')
    expect(source).not.toContain('No leagues in this format yet. Create one from League Coordinator.')
    expect(source).toContain('emptyLeagueActionRowStyle')
    expect(source).toContain('emptyLeagueActionStyle')
  })
})
