import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/compete/schedule/page.tsx'), 'utf8')

function styleBlock(styleName: string) {
  const pattern = new RegExp(`const ${styleName}(?:: CSSProperties)? = ([\\s\\S]*?)(?=\\nconst |\\nfunction |\\nexport |$)`)
  const match = source.match(pattern)
  if (!match) throw new Error(`Missing style block: ${styleName}`)
  return match[0]
}

describe('compete schedule scheduler status', () => {
  it('connects the schedule page to the shared league scheduler flow', () => {
    expect(source).toContain('schedulerStatusItems')
    expect(source).toContain('title="Publish dates"')
    expect(source).toContain('title="Team book"')
    expect(source).toContain('title="Team week"')
    expect(source).toContain('Confirmed matches stay visible before they become team prep or scorebook work.')
    expect(source).toContain('League scheduler status')
    expect(source).toContain('Shared scheduler')
    expect(source).toContain('Confirmed dates become prep, messages, and result entry.')
    expect(source).toContain("label: 'Dates'")
    expect(source).toContain("label: 'Sites'")
    expect(source).toContain("label: 'Teams'")
    expect(source).toContain('schedulerStripStyle')
    expect(source).toContain('schedulerStatusGridStyle')
    expect(source).toContain('scheduleReadyCount')
    expect(source).toContain('calendarLayerItems')
    expect(source).toContain('Calendar layers')
    expect(source).toContain('Keep one personal tennis calendar, then layer shared league, team, coach, and message schedules on top.')
    expect(source).toContain("label: 'My calendar'")
    expect(source).toContain("label: 'Shared league'")
    expect(source).toContain("label: 'Team overlays'")
    expect(source).toContain("label: 'External sync'")
    expect(source).toContain('Google, Outlook, and iCal should subscribe to the same TIQ calendar feed.')
    expect(source).toContain('Scheduling inbox')
    expect(source).toContain('calendarLayerPanelStyle')
    expect(source).toContain('calendarLayerGridStyle')
    expect(source).toContain('Start the shared calendar.')
    expect(source).toContain("const dataAssistScheduleHref = '/data-assist?intent=upload-source&context=League%20Office%20schedule'")
    expect(source).not.toContain('context=Compete%20schedule')
    expect(source).toContain("href: dataAssistScheduleHref")
    expect(source).toContain(': dataAssistScheduleHref')
    expect(source).toContain('League setup')
    expect(source).toContain('Upload schedule')
    expect(source).toContain('Coordinate dates')
    expect(source).toContain('Team results')
    expect(source).toContain('function EmptyScheduleState')
    expect(source).toContain('emptySchedulerStyle')
    expect(source).toContain('rowReadinessItems')
    expect(source).toContain("label: 'Date'")
    expect(source).toContain("label: 'Site'")
    expect(source).toContain('Fill schedule')
    expect(source).toContain('Open prep')
    expect(source).toContain('rowReadinessGridStyle')
    expect(source).toContain('rowNextActionStyle')
    expect(source).not.toContain('title="Captain Week View"')
    expect(source).not.toContain('title="Scenario Builder"')
    expect(source).not.toContain('title="My Lab"')
    expect(source).not.toContain('Build Smarter Lineups')
  })

  it('keeps the empty scheduler action panel mobile-safe', () => {
    expect(source).toContain('emptyScheduleActions')
    expect(styleBlock('emptySchedulerStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('emptyActionGridStyle')).toContain('minWidth: 0')
    expect(styleBlock('emptyActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock('emptyActionStyle')).toContain("whiteSpace: 'normal'")
  })

  it('keeps the calendar layer panel mobile-safe', () => {
    expect(styleBlock('calendarLayerPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock('calendarLayerHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('calendarLayerHeaderStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('calendarLayerGridStyle')).toContain("repeat(auto-fit, minmax(min(100%, 190px), 1fr))")
    expect(styleBlock('calendarLayerCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('calendarLayerCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('calendarLayerActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock('calendarLayerActionStyle')).toContain("whiteSpace: 'normal'")
  })
})
