import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/compete/schedule/page.tsx'), 'utf8')

function styleBlock(styleName: string) {
  const pattern = new RegExp(`const ${styleName}(?:: CSSProperties)? = ([\\s\\S]*?)(?=\\nconst |\\nfunction |\\nexport |$)`)
  const match = source.match(pattern)
  if (!match) throw new Error(`Missing style block: ${styleName}`)
  return match[0]
}

describe('compete schedule scheduler status', () => {
  it('gives Schedule visitors a clear first-action path', () => {
    expect(source).toContain("import { PRODUCT_MOTTO } from '@/lib/product-story'")
    expect(source).toContain('const schedulePathActions')
    expect(source).toContain('function SchedulePathPanel')
    expect(source).toContain('Schedule path')
    expect(source).toContain('id="compete-schedule-path-title"')
    expect(source).toContain('Start with the calendar need, then open the smallest action that keeps match week moving.')
    expect(source).not.toContain('Start with the calendar job, then open the smallest action that keeps match week moving.')
    expect(source).toContain('How do I organize the season?')
    expect(source).toContain('Publish dates')
    expect(source).toContain('How do I avoid retyping dates?')
    expect(source).toContain('Upload a schedule')
    expect(source).toContain('What match needs prep?')
    expect(source).toContain('Open match week')
    expect(source).toContain('What happens after the match?')
    expect(source).toContain('Post results')
    expect(source).toContain('data-compete-schedule-path-job={action.job}')
    expect(source).toContain("href: '#up-next-schedule'")
    expect(source).toContain('id="up-next-schedule"')
  })

  it('keeps Schedule path cards tappable on mobile', () => {
    expect(styleBlock('schedulePathStyle')).toContain('minWidth: 0')
    expect(styleBlock('schedulePathStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('schedulePathHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('schedulePathGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(styleBlock('schedulePathCardStyle')).toContain('minHeight: 148')
    expect(styleBlock('schedulePathCardStyle')).toContain("overflowWrap: 'anywhere'")
  })

  it('connects the schedule page to the shared league scheduler flow', () => {
    expect(source).toContain('schedulerStatusItems')
    expect(source).toContain('title="Publish dates"')
    expect(source).toContain('title="Team book"')
    expect(source).toContain('title="Team week"')
    expect(source).toContain('Confirmed matches stay visible before they become team prep or scorebook work.')
    expect(source).toContain('League scheduler status')
    expect(source).toContain('Shared scheduler')
    expect(source).toContain('Confirmed dates become prep, messages, and result entry.')
    expect(source).toContain("label: 'Dates'")
    expect(source).toContain("label: 'Sites'")
    expect(source).toContain("label: 'Teams'")
    expect(source).toContain('schedulerStripStyle')
    expect(source).toContain('schedulerStatusGridStyle')
    expect(source).toContain('scheduleReadyCount')
    expect(source).toContain('calendarLayerItems')
    expect(source).toContain('Calendar layers')
    expect(source).toContain('Keep one personal tennis calendar, then layer shared league, team, coach, and message schedules on top.')
    expect(source).toContain("label: 'My calendar'")
    expect(source).toContain("label: 'Shared league'")
    expect(source).toContain("label: 'Team overlays'")
    expect(source).toContain("label: 'External sync'")
    expect(source).toContain('Google, Outlook, and iCal should subscribe to the same TIQ calendar feed.')
    expect(source).toContain('Scheduling inbox')
    expect(source).toContain('calendarLayerPanelStyle')
    expect(source).toContain('calendarLayerGridStyle')
    expect(source).toContain('Start the shared calendar.')
    expect(source).toContain("const dataAssistScheduleHref = '/data-assist?intent=upload-source&context=League%20Office%20schedule'")
    expect(source).not.toContain('context=Compete%20schedule')
    expect(source).toContain("href: dataAssistScheduleHref")
    expect(source).toContain(': dataAssistScheduleHref')
    expect(source).toContain('League setup')
    expect(source).toContain('Upload schedule')
    expect(source).toContain('Coordinate dates')
    expect(source).toContain('Team results')
    expect(source).toContain('function EmptyScheduleState')
    expect(source).toContain('emptySchedulerStyle')
    expect(source).toContain('rowReadinessItems')
    expect(source).toContain("label: 'Date'")
    expect(source).toContain("label: 'Site'")
    expect(source).toContain('Fill schedule')
    expect(source).toContain('Open prep')
    expect(source).toContain('rowReadinessGridStyle')
    expect(source).toContain('rowNextActionStyle')
    expect(source).not.toContain('title="Captain Week View"')
    expect(source).not.toContain('title="Scenario Builder"')
    expect(source).not.toContain('title="My Lab"')
    expect(source).not.toContain('Build Smarter Lineups')
  })

  it('connects schedule dates back into Player ID and Level Up prep', () => {
    expect(source).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(source).toContain("const SCHEDULE_PLAYER_IDENTITY = getPlayerDevelopmentIdentity('smart-attacker-4-0-to-4-5')")
    expect(source).toContain('const SCHEDULE_LEVEL_UP_HREF = `/level-up/${SCHEDULE_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('const SCHEDULE_PLAYER_DEVELOPMENT_HREF = `/player-development/${SCHEDULE_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('function SchedulePlayerIdPrepPanel')
    expect(source).toContain('aria-label="Schedule Player ID match prep"')
    expect(source).toContain('aria-label="Schedule Player ID starter read"')
    expect(source).toContain('Turn the date into one prep cue.')
    expect(source).toContain('Once the match is on the calendar, use the same Player ID read to pick the next rep.')
    expect(source).toContain('Start Level Up')
    expect(source).toContain('Read Player ID')
    expect(source.indexOf('<SchedulePlayerIdPrepPanel />')).toBeGreaterThan(source.indexOf('<SchedulePathPanel />'))
    expect(source.indexOf('<SchedulePlayerIdPrepPanel />')).toBeLessThan(source.indexOf('<CompeteGrid>'))
  })

  it('keeps the Schedule Player ID prep loop mobile-safe', () => {
    expect(styleBlock('schedulePlayerIdPrepStyle')).toContain('minWidth: 0')
    expect(styleBlock('schedulePlayerIdPrepStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 240px), 1fr))'")
    expect(styleBlock('schedulePlayerIdPrepGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock('schedulePlayerIdActionRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('schedulePlayerIdActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock('schedulePlayerIdActionStyle')).toContain("whiteSpace: 'normal'")
  })

  it('keeps the empty scheduler action panel mobile-safe', () => {
    expect(source).toContain('emptyScheduleActions')
    expect(styleBlock('emptySchedulerStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('emptyActionGridStyle')).toContain('minWidth: 0')
    expect(styleBlock('emptyActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock('emptyActionStyle')).toContain("whiteSpace: 'normal'")
  })

  it('keeps the calendar layer panel mobile-safe', () => {
    expect(styleBlock('calendarLayerPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock('calendarLayerHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('calendarLayerHeaderStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('calendarLayerGridStyle')).toContain("repeat(auto-fit, minmax(min(100%, 190px), 1fr))")
    expect(styleBlock('calendarLayerCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('calendarLayerCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('calendarLayerActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock('calendarLayerActionStyle')).toContain("whiteSpace: 'normal'")
  })
})
