import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/data-assist/page.tsx'), 'utf8')
const globalsSource = readFileSync(join(process.cwd(), 'app/globals.css'), 'utf8')

describe('Data Assist mobile layout guards', () => {
  it('keeps closed Data Assist drawers out of measured layout', () => {
    expect(source).toContain('className="dataAssistDetailsSection"')
    expect(source).toContain('className="dataAssistDetailsBody"')
    expect(globalsSource).toContain('.dataAssistDetailsSection:not([open]) > .dataAssistDetailsBody')
    expect(source).toContain('const isCompactViewport = isMobile || isTablet')
    expect(source).toContain('const dynamicPanelStyle = isCompactViewport ? compactPanelStyle : panelStyle')
    expect(source).toContain('const dynamicSectionHeaderStyle = isCompactViewport ? compactSectionHeaderStyle : sectionHeaderStyle')
    expect(source).toContain('const dynamicImportTypeSelectWrapStyle = isCompactViewport ? compactImportTypeSelectWrapStyle : importTypeSelectWrapStyle')
    expect(source).toContain('const dynamicImportTypeSelectStyle = isCompactViewport ? compactImportTypeSelectStyle : importTypeSelectStyle')
    expect(source).toContain('const dynamicStepDividerStyle = isCompactViewport ? compactStepDividerStyle : stepDividerStyle')
    expect(source).toContain('const { isMobile, isTablet } = useViewportBreakpoints()')
    expect(source).toContain("padding: isCompactViewport ? '7px 8px' : dataAssistDetailsSummaryStyle.padding")
    expect(source).toContain("fontSize: isCompactViewport ? 13 : dataAssistDetailsTitleStyle.fontSize")
    expect(source).toContain("{isCompactViewport ? 'Open' : cue}")
    expect(source).toContain('const compactPanelStyle: CSSProperties')
    expect(source).toContain('const compactSectionHeaderStyle: CSSProperties')
    expect(source).toContain('const compactImportTypeSelectWrapStyle: CSSProperties')
    expect(source).toContain('const compactImportTypeSelectStyle: CSSProperties')
    expect(source).toContain('const compactStepDividerStyle: CSSProperties')
    expect(source).toContain('const dropzoneStyle = (status: string, compact = false): CSSProperties')
    expect(source).toContain('minHeight: compact ? 82 : 150')
    expect(source).toContain("dropzoneStyle(scorecardUploadBlocked ? 'paused' : summary?.status || '', isMobile)")
    expect(source).toContain('getCompactUploadHint(importType)')
    expect(source).toContain('getCompactImportTypeHint(importType)')
    expect(source).toContain('const compactSourcePathPanelStyle: CSSProperties')
    expect(source).toContain('const compactSourcePathGridStyle: CSSProperties')
    expect(source).toContain('const compactSourcePathCardStyle: CSSProperties')
    expect(source).toContain("{!isCompactViewport ? <span>{job.body}</span> : null}")
    expect(source).toContain('Need upload help?')
    expect(source).toContain('{!isCompactViewport ? (')
    expect(source).toContain('Need help choosing the right source?')
    expect(source).toContain('What happens after an upload?')
    expect(source).toContain('Know what changes records.')
  })
})
