import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/data-assist/page.tsx'), 'utf8')
const globalsSource = readFileSync(join(process.cwd(), 'app/globals.css'), 'utf8')

describe('Data Assist mobile layout guards', () => {
  it('keeps closed Data Assist drawers out of measured layout', () => {
    expect(source).toContain('className="dataAssistDetailsSection"')
    expect(source).toContain('className="dataAssistDetailsBody"')
    expect(globalsSource).toContain('.dataAssistDetailsSection:not([open]) > .dataAssistDetailsBody')
    expect(source).toContain('const isCompactViewport = isMobile || isTablet')
    expect(source).toContain('const dynamicPanelStyle = isCompactViewport ? compactPanelStyle : panelStyle')
    expect(source).toContain('const dynamicSectionHeaderStyle = isCompactViewport ? compactSectionHeaderStyle : sectionHeaderStyle')
    expect(source).toContain('const dynamicImportTypeSelectWrapStyle = isCompactViewport ? compactImportTypeSelectWrapStyle : importTypeSelectWrapStyle')
    expect(source).toContain('const dynamicImportTypeSelectStyle = isCompactViewport ? compactImportTypeSelectStyle : importTypeSelectStyle')
    expect(source).toContain('const { isMobile, isTablet } = useViewportBreakpoints()')
    expect(source).toContain("padding: isCompactViewport ? '7px 8px' : dataAssistDetailsSummaryStyle.padding")
    expect(source).toContain("fontSize: isCompactViewport ? 13 : dataAssistDetailsTitleStyle.fontSize")
    expect(source).toContain("{isCompactViewport ? 'Open' : cue}")
    expect(source).toContain('const compactPanelStyle: CSSProperties')
    expect(source).toContain('const compactSectionHeaderStyle: CSSProperties')
    expect(source).toContain('const compactImportTypeSelectWrapStyle: CSSProperties')
    expect(source).toContain('const compactImportTypeSelectStyle: CSSProperties')
    expect(source).not.toContain('const dropzoneStyle =')
    expect(source).toContain('ref={fileInputRef}')
    expect(source).toContain('fileInputRef.current?.click()')
    expect(source).toContain('style={hiddenFileInputStyle}')
    expect(source).toContain('const hiddenFileInputStyle: CSSProperties')
    expect(source).toContain("display: 'none'")
    expect(source).toContain('style={replaceExportPickerStyle}')
    expect(source).toContain('style={replaceExportInputStyle}')
    expect(source).toContain('Choose the source, add its TennisLink export, then review what TiQ found.')
    expect(source).toContain('<UploadJourneyRail />')
    expect(source).toContain('selectedImportType={importType}')
    expect(source).toContain('aria-pressed={selected}')
    expect(source).toContain('<span>Having trouble?</span>')
    expect(source).toContain('<strong>Choose file type</strong>')
    expect(source).toContain('Only use this when TenAceIQ cannot identify the export.')
    expect(source).toContain('const typeOverrideDetailsStyle: CSSProperties')
    expect(source).toContain('const typeOverrideSummaryStyle: CSSProperties')
    expect(source).not.toContain('<span style={dropzoneKickerStyle}>Source type</span>')
    expect(source).toContain('const compactSourcePathPanelStyle: CSSProperties')
    expect(source).toContain('const compactSourcePathGridStyle: CSSProperties')
    expect(source).toContain('const compactSourcePathCardStyle: CSSProperties')
    expect(source).toContain("{!isCompactViewport ? <span style={sourcePathQuestionStyle}>{question}</span> : null}")
    expect(source).toContain("{!isCompactViewport ? <span>{body}</span> : null}")
    expect(source).toContain('Need upload help?')
    expect(source).toContain('{!isCompactViewport ? (')
    expect(source).toContain('What happens after an upload?')
    expect(source).toContain('Know what changes records.')
  })
})
