import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/data-assist/page.tsx'), 'utf8').replace(/\r\n/g, '\n')
const layoutSource = readFileSync(join(process.cwd(), 'app/data-assist/layout.tsx'), 'utf8')
const eventsSource = readFileSync(join(process.cwd(), 'lib/product-usage-events.ts'), 'utf8')

describe('Data Assist trust engine', () => {
  it('positions Data Assist as the public data-quality workflow', () => {
    expect(source).toContain('Fix Data / Data Assist')
    expect(source).toContain("import { buildSupportMessageHref } from '@/lib/message-links'")
    expect(source).toContain('Help keep TenAceIQ accurate.')
    expect(source).toContain('Upload scorecards, schedules, Team Summaries, and corrections.')
    expect(source).toContain('Reviewed data can improve player profiles')
    expect(source).toContain('team pages, and Team Hub')
    expect(source).not.toContain('Captain workspaces')
    expect(layoutSource).toContain('buildRouteMetadata')
    expect(layoutSource).toContain("path: '/data-assist'")
    expect(layoutSource).toContain('Fix tennis data with reviewed scorecard')
  })

  it('shows source, freshness, confidence, status, and review actions', () => {
    expect(source).toContain('USTA / TIQ / user upload / admin reviewed / public data')
    expect(source).toContain('Updated today / last refreshed / pending review')
    expect(source).toContain('High / medium / limited')
    expect(source).toContain('Verified / needs review / imported / disputed')
    expect(source).toContain('Upload source')
    expect(source).toContain('Report issue')
    expect(source).toContain('Request review')
    expect(source).toContain('League Office results')
    expect(source).toContain('Open League Office')
    expect(source).not.toContain('Coordinator results')
    expect(source).not.toContain('Open Coordinator')
    expect(source).toContain('id="history"')
  })

  it('shows how reviewed uploads become player ID signals', () => {
    expect(source).toContain('const dataAssistPlayerIdSignalPath')
    expect(source).toContain('Data Assist player ID signal path')
    expect(source).toContain("label: 'Player ID'")
    expect(source).toContain('Match the source to the right tennis identity.')
    expect(source).toContain('Scorecards and team exports should strengthen the correct player profile, not create mystery records.')
    expect(source).toContain("label: 'Reviewed signal'")
    expect(source).toContain('Keep unreviewed uploads out of ratings.')
    expect(source).toContain('profiles, rankings, Matchup, My Lab, and Coach Hub wait for a clean review path.')
    expect(source).toContain("label: 'Next use'")
    expect(source).toContain('profile confidence, Level Up context, matchup prep, and team decisions.')
  })

  it('turns reviewed data context into a Player ID starter path', () => {
    expect(source).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(source).toContain('const DATA_ASSIST_LEVEL_UP_HREF = `/level-up/${DATA_ASSIST_PLAYER_IDENTITY.slug}#level-up-flow`')
    expect(source).toContain('const DATA_ASSIST_PLAYER_DEVELOPMENT_HREF = `/player-development/${DATA_ASSIST_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('Data Assist Player ID starter')
    expect(source).toContain('Data Assist Player ID starter read')
    expect(source).toContain('dataAssistPlayerIdStarterRead.map((item)')
    expect(source).toContain('Start Level Up')
    expect(source).toContain('Read Player ID')
    expect(source).toContain("location: 'data_assist_player_id_starter'")
    expect(source).toContain("action: 'start_level_up'")
    expect(source).toContain("action: 'read_player_id'")
  })

  it('keeps review-first details available after the upload tool', () => {
    expect(source).toContain('const dataAssistReviewFlow')
    expect(source).toContain('const dataAssistUploadStateProof')
    expect(source).toContain('DataAssistReviewFlowPanel')
    expect(source).toContain('Review-first handoff')
    expect(source).toContain('What happens after an upload?')
    expect(source).toContain('Data Assist is intentionally review-first.')
    expect(source).toContain('Upload source')
    expect(source).toContain('Read the signals')
    expect(source).toContain('Confirm or flag')
    expect(source).toContain('Feed tennis context')
    expect(source).toContain('refresh tennis context across player, team, and rating views')
    expect(source).toContain('Reviewed data can improve players, teams, leagues, rankings, Matchup, My Lab, and Coach Hub.')
    expect(source).toContain('aria-label="Upload review status"')
    expect(source).toContain('Upload review status')
    expect(source).not.toContain('Data Assist upload state proof cue')
    expect(source).not.toContain('Upload state proof cue')
    expect(source).toContain('Know what changed and what did not.')
    expect(source).toContain('Saved upload')
    expect(source).toContain('Review state')
    expect(source).toContain('Trust boundary')
    expect(source).toContain('Unreviewed uploads do not change players, teams, leagues, rankings, Matchup, My Lab, or Coach Hub.')
    expect(source).toContain('no public records change until the import check finishes')
    expect(source).not.toContain('refresh analytics across the platform')
    expect(source).not.toContain('ready without admin review')
    expect(source.indexOf('ref={fileInputRef}')).toBeLessThan(source.indexOf('<DataAssistReviewFlowPanel />'))
    expect(source.indexOf('ref={fileInputRef}')).toBeLessThan(source.indexOf('<DataAssistTrustEnginePanel />'))
  })

  it('gives upload visitors a plain source refresh path before the file picker', () => {
    expect(source).toContain('const dataAssistSourcePathJobs')
    expect(source).toContain('DataAssistSourcePathPanel')
    expect(source).toContain('Source refresh path')
    expect(source).toContain('Choose your first source.')
    expect(source).toContain('For your own team, import Team Summary, Match Schedule, then Player Roster. TiQ reviews every source before records change.')
    expect(source).toContain('For your own team: Team Summary, schedule, then Player Roster.')
    expect(source).toContain('Team setup: Team Summary → schedule → Player Roster.')
    expect(source).toContain('After it imports, approve your team once to add it to My Teams.')
    expect(source).toContain("const teamSetupRequested = requestedImportType === 'team_summary' && intentContext.toLowerCase().includes('team')")
    expect(source).toContain('{intent && !teamSetupRequested ? <DataAssistIntentPanel')
    expect(source).toContain("<StepBadge step={1} label={teamSetupRequested ? 'Add a team' : 'Data Assist'} />")
    expect(source).toContain('Upload your Team Summary.')
    expect(source).toContain('TiQ will read your team, league, flight, and roster.')
    expect(source).toContain('const visibleJobs = contactImportRequested || teamSetupRequested')
    expect(source).toContain("? 'Choose Team Summary file'")
    expect(source).toContain('Start with your Team Summary.')
    expect(source).toContain('Your team path: Team Summary → schedule → approve your team link.')
    expect(source).toContain('A Team Summary does not automatically connect the team to you.')
    expect(source).toContain('What result should update first?')
    expect(source).toContain("title: 'Scorecard'")
    expect(source).toContain('What is the season schedule?')
    expect(source).toContain("title: 'Schedule'")
    expect(source).toContain('Who is on the roster?')
    expect(source).toContain("title: 'Team Summary'")
    expect(source).toContain('Something looks wrong? Report a data issue')
    expect(source).toContain('data-data-assist-source-path-job={job.id}')
    expect(source).not.toContain('data-data-assist-source-path-job="report_or_review"')
    expect(source).toContain('onClick={() => onSelectImportType(job.id)}')
    expect(source).toContain('function chooseImportType(nextType: DataAssistImportType)')
    expect(source).toContain('fileInputRef.current?.click()')
    expect(source).toContain('aria-label={`Upload ${title}: ${cta}`}')
    expect(source).toContain("location: 'data_assist_source_path'")
    expect(source.indexOf('<DataAssistSourcePathPanel')).toBeLessThan(source.indexOf('ref={fileInputRef}'))
    expect(source).not.toContain('<label style={dropzoneStyle')
  })

  it('gives captains a dedicated Player Roster contact import without replacing Team Summary', () => {
    expect(source).toContain("const contactImportRequested = searchParams.get('contactImport') === '1'")
    expect(source).toContain('Add team contacts.')
    expect(source).toContain('Captain contacts: use Player Roster.')
    expect(source).toContain('Player Roster contacts')
    expect(source).toContain('This adds contact details only. After import, approve the team connection so it appears in My Teams.')
    expect(source).toContain('Player Roster contact export')
    expect(source).toContain('Team contacts imported')
    expect(source).toContain('Make this your team')
    expect(source).toContain('function TeamSummaryReviewPanel({')
    expect(source).toContain('aria-label="Import this team summary"')
    expect(source).toContain("onImport={() => void reviewLatestScan('confirmed')}")
    expect(source).toContain('Save this roster now. Next, review and link the team to My Teams, Team Chat, and Captain.')
    expect(source).toContain("'Import Team Summary'")
    expect(source).toContain('Review & link this team')
    expect(source).toContain('Add this to My Teams')
    expect(source).toContain('Review & link this team')
    expect(source).toContain('Return to Team contacts')
    expect(source).toContain("if (path.startsWith('/teams/')) return path")
  })

  it('makes the latest import outcome and next action visible without opening history', () => {
    expect(source).toContain('function DataAssistOperationsPanel')
    expect(source).toContain('latestSubmission={submissions[0] ?? null}')
    expect(source).toContain('data-data-assist-operation="latest"')
    expect(source).toContain('function getDataAssistLatestActivity')
    expect(source).toContain("title: 'Start team setup'")
    expect(source).toContain('Upload a Team Summary for roster, ratings, flight, and standings.')
    expect(source).toContain('Open the review queue to confirm the visible team or match details.')
    expect(source).toContain('Open import history for the details.')
  })

  it('lets users cancel an upload and returns completed imports to the source buttons', () => {
    expect(source).toContain('function resetUploadFlow()')
    expect(source).toContain('setSaving(false)')
    expect(source).toContain('Cancel upload')
    expect(source).toContain("function completeUploadFlow(completionMessage = 'Upload complete.', nextOutcome: DataAssistOutcome | null = null)")
    expect(source).toContain("'Upload complete.',\n            buildImportedDataAssistOutcome(ocrResult.parsedDraft, result.batchId)")
    expect(source).toContain("'Already uploaded. No changes were needed.',\n            buildImportedDataAssistOutcome(ocrResult.parsedDraft, result.batchId, true)")
    expect(source).toContain('const showUploadStep = !hasPreparedScreenshots && !saving && !latestScan')
  })

  it('keeps source refresh cards tappable on mobile', () => {
    expect(source).toContain('const sourcePathPanelStyle: CSSProperties')
    expect(source).toContain('const sourcePathGridStyle: CSSProperties')
    expect(source).toContain('const sourcePathCardBaseStyle: CSSProperties')
    expect(source).toContain('const playerIdSignalPathStyle: CSSProperties')
    expect(source).toContain('const playerIdSignalCardStyle: CSSProperties')
    expect(source).toContain('const dataAssistPlayerIdStarterStyle: CSSProperties')
    expect(source).toContain('const dataAssistPlayerIdStarterGridStyle: CSSProperties')
    expect(source).toContain('const dataAssistPlayerIdStarterActionRowStyle: CSSProperties')
    expect(source).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(source).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 168px), 1fr))'")
    expect(source).toContain('minHeight: 152')
    expect(source).toContain('minHeight: 132')
    expect(source).toContain("flexWrap: 'wrap'")
    expect(source).toContain("overflowWrap: 'anywhere'")
  })

  it('acknowledges review/report URL intents from public trust links', () => {
    expect(source).toContain("import { useRouter, useSearchParams } from 'next/navigation'")
    expect(source).toContain("type DataAssistIntent = 'upload-source' | 'report-issue' | 'request-review'")
    expect(source).toContain('function getDataAssistIntent')
    expect(source).toContain('function getDataAssistContext')
    expect(source).toContain('function getDataAssistQuery')
    expect(source).toContain('function buildDataAssistIssueHref')
    expect(source).toContain("subject: context ? `Data issue: ${context}` : 'Data issue'")
    expect(source).toContain('Source context: ${context}')
    expect(source).toContain('Search phrase: ${query}')
    expect(source).toContain("const intent = getDataAssistIntent(searchParams.get('intent'))")
    expect(source).toContain("const intentContext = getDataAssistContext(searchParams.get('context'))")
    expect(source).toContain("const intentQuery = getDataAssistQuery(searchParams.get('q'))")
    expect(source).toContain('DataAssistIntentPanel')
    expect(source).toContain('Add the source behind this tennis read.')
    expect(source).toContain('Tell TenAceIQ what looks wrong.')
    expect(source).toContain('Send a source for review.')
    expect(source).toContain('metadata: intent || requestedImportType || intentContext || intentQuery')
    expect(source).toContain('{ intent, importType: requestedImportType, context: intentContext, query: intentQuery }')
    expect(source).toContain('From: {context}')
    expect(source).toContain('Search: {query}')
    expect(source).toContain("location: 'data_assist_intent_panel'")
  })

  it('keeps intent panel layout mobile-safe', () => {
    expect(source).toContain('const intentPanelStyle: CSSProperties')
    expect(source).toContain('const intentContextStyle: CSSProperties')
    expect(source).toContain('const intentActionRowStyle: CSSProperties')
    expect(source).toContain("flexWrap: 'wrap'")
    expect(source).toContain("overflowWrap: 'anywhere'")
  })

  it('tracks Data Assist discovery, upload choices, upload starts, and reports', () => {
    expect(eventsSource).toContain("'data_assist_opened'")
    expect(eventsSource).toContain("'upload_type_selected'")
    expect(eventsSource).toContain("'scorecard_upload_started'")
    expect(eventsSource).toContain("'schedule_upload_started'")
    expect(eventsSource).toContain("'team_summary_upload_started'")
    expect(eventsSource).toContain("'data_issue_reported'")
    expect(source).toContain("eventName: 'upload_type_selected'")
    expect(source).toContain("eventName: 'data_assist_opened'")
    expect(source).toContain("eventName: 'data_issue_reported'")
  })
})
