import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const exploreSource = readFileSync(join(process.cwd(), 'app/explore/page.tsx'), 'utf8')
const exploreSearchSource = readFileSync(join(process.cwd(), 'app/explore/search/page.tsx'), 'utf8')
const rankingsSource = readFileSync(join(process.cwd(), 'app/rankings/page.tsx'), 'utf8')
const playersSource = readFileSync(join(process.cwd(), 'app/players/page.tsx'), 'utf8')
const playerDetailSource = readFileSync(join(process.cwd(), 'app/players/[id]/page.tsx'), 'utf8')
const teamsSource = readFileSync(join(process.cwd(), 'app/teams/page.tsx'), 'utf8')
const teamDetailSource = readFileSync(join(process.cwd(), 'app/teams/[team]/page.tsx'), 'utf8')
const leaguesSource = readFileSync(join(process.cwd(), 'app/leagues/page.tsx'), 'utf8')
const leagueDetailSource = readFileSync(join(process.cwd(), 'app/leagues/[league]/page.tsx'), 'utf8')
const exploreLeaguesSource = readFileSync(join(process.cwd(), 'app/explore/leagues/page.tsx'), 'utf8')
const ustaExploreLeagueDetailSource = readFileSync(join(process.cwd(), 'app/explore/leagues/usta/[league]/page.tsx'), 'utf8')
const tiqLeagueDetailSource = readFileSync(join(process.cwd(), 'app/explore/leagues/tiq/[league]/page.tsx'), 'utf8')

function styleBlock(source: string, styleName: string) {
  const start = source.indexOf(`const ${styleName}:`)
  expect(start).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

function functionBlock(source: string, functionName: string) {
  const start = source.indexOf(`const ${functionName} =`)
  expect(start).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

describe('Explore responsive surfaces', () => {
  it('keeps Explore action cards protected from narrow mobile overflow', () => {
    expect(exploreSource).toContain('const actionBody: CSSProperties')
    expect(exploreSource).toContain('const actionFooterRow: CSSProperties')
    expect(exploreSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(exploreSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(exploreSource).toContain("overflowWrap: 'anywhere'")
    expect(exploreSource).toContain("flexWrap: 'wrap'")
    expect(exploreSource).toContain('minWidth: 0')
    expect(styleBlock(exploreSource, 'pillBase')).toContain('minWidth: 0')
    expect(styleBlock(exploreSource, 'pillBase')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(exploreSource, 'featurePanel')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'startStepStack')).toContain('minWidth: 0')
    expect(styleBlock(exploreSource, 'startStepLabel')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'discoveryPathLabel')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'actionCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'actionCardTop')).toContain('minWidth: 0')
    expect(styleBlock(exploreSource, 'actionEyebrow')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'actionFooterCtaBlue')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'actionFooterArrow')).toContain("flex: '0 0 auto'")
  })

  it('keeps Explore Search grids and filter controls mobile-safe', () => {
    expect(exploreSearchSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(exploreSearchSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(exploreSearchSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(exploreSearchSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(exploreSearchSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(exploreSearchSource).toContain('function FilterSelect')
    expect(exploreSearchSource).toContain("style={{ display: 'grid', gap: 6, minWidth: 0 }}")
    expect(styleBlock(exploreSearchSource, 'emptyStateStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'emptyTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'exampleSearchButtonStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'resultGroupStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'resultGroupHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(exploreSearchSource, 'resultGroupCopyStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'resultGroupActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock(exploreSearchSource, 'resultGroupActionStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(exploreSearchSource, 'resultGroupListStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'resultBadgeWrapStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'matchedFilterStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'matchedFilterLinkRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(exploreSearchSource, 'filterJumpStyle')).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps Explore start-step markers shell-aware across themes', () => {
    expect(exploreSource).toContain('const startStepNumber: CSSProperties')
    expect(exploreSource).toContain("background: 'color-mix(in srgb, var(--brand-green) 22%, var(--shell-chip-bg) 78%)'")
    expect(exploreSource).toContain("color: 'var(--foreground-strong)'")
    expect(exploreSource).not.toContain("color: 'var(--text-dark)',\n  background: 'linear-gradient(135deg, var(--brand-green) 0%, #4ade80 100%)'")
  })

  it('keeps rankings compact cards single-column friendly on mobile', () => {
    expect(rankingsSource).toContain('dynamicLeaderboardActionGrid')
    expect(rankingsSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(rankingsSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(rankingsSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(rankingsSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain('const compactRankingCardStyle: CSSProperties')
    expect(rankingsSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 112px), 1fr))'")
    expect(rankingsSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 132px), 1fr))'")
    expect(rankingsSource).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(rankingsSource, 'heroContent')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'controlsGrid')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'podiumGrid')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'summaryStatsGrid')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'summaryStatsGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock(rankingsSource, 'chipStatLabel')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(rankingsSource, 'chipStatValue')).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps rankings insight panels and table actions mobile-safe', () => {
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("overscrollBehaviorX: 'contain'")
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("scrollbarWidth: 'thin'")
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'dataTable')).toContain("minWidth: 'min(100%, 760px)'")
    expect(styleBlock(rankingsSource, 'rowActionStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'rowActionPrimaryStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(rankingsSource, 'insightSummary')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(rankingsSource, 'signalListItem')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(rankingsSource, 'distributionRow')).toContain("gridTemplateColumns: 'minmax(0, 72px) minmax(0, 1fr) minmax(0, 32px)'")
    expect(styleBlock(rankingsSource, 'distributionTrack')).toContain('minWidth: 0')
  })

  it('keeps public discovery empty states actionable and Data Assist aware', () => {
    expect(playersSource).toContain('Public discovery only shows reviewed player context')
    expect(playersSource).toContain('Reset filters')
    expect(playersSource).toContain('emptyStateActionRow')
    expect(playersSource).toContain('DATA_ASSIST_STORY.cta')

    expect(teamsSource).toContain('Public discovery only shows reviewed team context')
    expect(teamsSource).toContain('Reset team filters')
    expect(teamsSource).toContain('emptyActionRow')
    expect(teamsSource).toContain('DATA_ASSIST_STORY.cta')
  })

  it('keeps Players and Teams directory grids minmax-safe on mobile', () => {
    expect(playersSource).not.toContain("gridTemplateColumns: isTablet\n      ? '1fr'")
    expect(playersSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(playersSource).toMatch(/gridTemplateColumns: isTablet\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(playersSource).toContain("isSmallMobile ? 'minmax(0, 1fr)'")
    expect(styleBlock(playersSource, 'heroContent')).toContain('minWidth: 0')
    expect(styleBlock(playersSource, 'cardGrid')).toContain('minWidth: 0')

    expect(teamsSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(teamsSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(teamsSource).toContain('const filtersGrid = (isMobile: boolean): CSSProperties')
    expect(teamsSource).toContain('const cardsGrid = (isTablet: boolean, isMobile: boolean): CSSProperties')
    expect(teamsSource).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'heroCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamsSource, 'exploreNavRow')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'exploreNavLink')).toContain("whiteSpace: 'normal'")
    expect(functionBlock(teamsSource, 'heroStatsGrid')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'sectionHeader')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'sectionTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamsSource, 'resetButton')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(teamsSource, 'editorialGrid')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'filtersActionRow')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'surfaceCard')).toContain("background: 'var(--shell-panel-bg)'")
    expect(styleBlock(teamsSource, 'emptyActionRow')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'teamCardCopy')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'metaRow')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'metaPillGreen')).toContain('...metaPillBlue')
    expect(styleBlock(teamsSource, 'viewPill')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamsSource, 'teamRecordBar')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'teamRecordLegend')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(teamsSource, 'recentFormRow')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(teamsSource, 'metricsGrid')).toContain('minWidth: 0')
  })

  it('keeps Teams directory readable in light mode with shell tokens', () => {
    expect(teamsSource).toContain('var(--background)')
    expect(teamsSource).toContain("color: 'var(--foreground)'")
    expect(teamsSource).toContain("background: 'var(--shell-panel-bg)'")
    expect(teamsSource).toContain("color: 'var(--foreground-strong)'")
    expect(teamsSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(teamsSource).toContain("colorScheme: 'normal'")
    expect(teamsSource).not.toContain("colorScheme: 'dark'")
  })

  it('keeps Leagues directory Data Assist centered and light-mode readable', () => {
    expect(leaguesSource).toContain('Browse uploaded league seasons.')
    expect(leaguesSource).toContain('reviewed Data Assist league groupings')
    expect(leaguesSource).toContain('DATA_ASSIST_STORY.cta')
    expect(leaguesSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(leaguesSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(leaguesSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(leaguesSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(leaguesSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(leaguesSource).toMatch(/gridTemplateColumns: isSmallMobile\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(styleBlock(leaguesSource, 'heroContent')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'summaryGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'filterGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'cardGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'leagueDetailGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'heroHintRow')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'heroHintPill')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(leaguesSource, 'contentWrap')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'editorialPanel')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'editorialGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'panelHead')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'filterActionRow')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(leaguesSource, 'clearFilterButton')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(leaguesSource, 'diagnosticChipRow')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'emptyActionRow')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'leagueCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(leaguesSource, 'leagueTop')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(leaguesSource, 'leagueMetaPillBase')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(leaguesSource, 'primaryButton')).toContain("overflowWrap: 'anywhere'")
    expect(leaguesSource).toContain("background: 'var(--shell-chip-bg)'")
    expect(leaguesSource).toContain("color: 'var(--foreground-strong)'")
    expect(leaguesSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(leaguesSource).toContain("colorScheme: 'normal'")
    expect(leaguesSource).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps league detail pages Data Assist aware and light-mode readable', () => {
    expect(leagueDetailSource).toContain('reviewed match rows')
    expect(leagueDetailSource).toContain('DATA_ASSIST_STORY.cta')
    expect(leagueDetailSource).toContain('Use reviewed Data Assist uploads')
    expect(leagueDetailSource).toContain('const standingsTableScrollStyle: CSSProperties')
    expect(leagueDetailSource).toContain("overscrollBehaviorX: 'contain'")
    expect(leagueDetailSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(leagueDetailSource).toContain("minWidth: 'min(100%, 620px)'")
    expect(leagueDetailSource).toContain("tableLayout: 'auto'")
    expect(styleBlock(leagueDetailSource, 'standingsTableHeaderCellStyle')).toContain("whiteSpace: 'normal'")
    expect(leagueDetailSource).toContain("background: 'var(--shell-panel-bg)'")
    expect(leagueDetailSource).toContain("background: 'var(--shell-chip-bg)'")
    expect(leagueDetailSource).toContain("color: 'var(--foreground-strong)'")
    expect(leagueDetailSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(leagueDetailSource).toContain("colorScheme: 'normal'")
    expect(leagueDetailSource).toContain("overflowWrap: 'anywhere'")
    expect(leagueDetailSource).toContain('const topPerformerGridStyle: CSSProperties')
    expect(leagueDetailSource).toContain('const standingsViewToggleRowStyle: CSSProperties')
    expect(styleBlock(leagueDetailSource, 'topPerformerGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'standingsViewToggleRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(leagueDetailSource, 'seasonToolsCard')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'seasonToolsQuickActionGrid')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'seasonToolsQuickActionGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 148px), 1fr))'")
    expect(styleBlock(leagueDetailSource, 'seasonQuickActionButton')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(leagueDetailSource, 'ghostButton')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(leagueDetailSource, 'miniPillBase')).toContain("maxWidth: '100%'")
    expect(styleBlock(leagueDetailSource, 'metricGrid')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'signalCardStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'signalLabelStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(leagueDetailSource, 'leagueDiscoveryPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'leagueDiscoveryHeaderStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'leagueDiscoveryCardStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'stateActionRow')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'sectionHead')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'teamGrid')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'teamTop')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'teamCardActionRow')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'teamCardCopyStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(leagueDetailSource, 'teamRankRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(leagueDetailSource, 'teamLeaderPillStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(leagueDetailSource, 'teamWinBarStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'teamWinBarLegendStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(leagueDetailSource, 'topPerformerSectionLabelStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(leagueDetailSource, 'standingsTeamCellContentStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(leagueDetailSource, 'primaryButton')).toContain("maxWidth: '100%'")
    expect(styleBlock(leagueDetailSource, 'tableActionLink')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(leagueDetailSource, 'miniGrid')).toContain('minWidth: 0')
    expect(leagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : 'repeat(auto-fit, minmax(min(100%, 160px), 1fr))'")
    expect(styleBlock(leagueDetailSource, 'filterWrap')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'matchList')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'matchCard')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'winnerPill')).toContain("maxWidth: '100%'")
    expect(styleBlock(leagueDetailSource, 'matchQualityRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'matchQualityPillStyle')).toContain("flexWrap: 'wrap'")
    expect(leagueDetailSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(leagueDetailSource).toContain("? 'minmax(0, 1fr)'")
    expect(leagueDetailSource).toContain("subtitle={subtitleParts.join(' | ')}")
    expect(leagueDetailSource).toContain("row.score ?? '-'")
    expect(leagueDetailSource).not.toContain("<Link href={teamHref} style={{ color: '#93c5fd'")
    expect(leagueDetailSource).not.toContain("row.score ?? '—'")
    expect(ustaExploreLeagueDetailSource).toContain("export { default } from '@/app/leagues/[league]/page'")
  })

  it('keeps team detail pages Data Assist aware and light-mode readable', () => {
    expect(teamDetailSource).toContain('reviewed scorecards')
    expect(teamDetailSource).toContain('No reviewed scorecards yet')
    expect(teamDetailSource).toContain('reviewed Data Assist scorecards')
    expect(teamDetailSource).toContain('DATA_ASSIST_STORY.cta')
    expect(teamDetailSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(teamDetailSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(teamDetailSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(teamDetailSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(teamDetailSource).toMatch(/gridTemplateColumns: isSmallMobile\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(teamDetailSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(functionBlock(teamDetailSource, 'signalGridStyle')).toContain('minWidth: 0')
    expect(functionBlock(teamDetailSource, 'teamDiscoveryGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'pageContent')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'heroShell')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'eyebrow')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'eyebrow')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(teamDetailSource, 'eyebrow')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'heroTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'heroText')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'heroBadgeRow')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'heroActions')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'buttonPrimary')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'buttonPrimary')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'buttonSecondary')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'buttonSecondary')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'badgeBase')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'badgeBase')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(teamDetailSource, 'badgeBase')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'teamStatusPill')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'summaryCard')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'summaryMetricGrid')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'summaryMetricGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock(teamDetailSource, 'summaryMetricCard')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'surfaceCard')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'teamDiscoveryHeaderStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'teamDiscoveryCardTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'teamDiscoveryCardTextStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'teamDiscoveryCtaStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'sectionHeadingRow')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'sectionTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'panelCountPill')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'panelCountPill')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'listRow')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(teamDetailSource, 'listRow')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'rosterFilterButton')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'rosterFilterButton')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'rosterCompareTray')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'rosterCompareActions')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'rosterCompareLinkReady')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'rosterCompareLinkReady')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'helperCallout')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'helperCallout')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("overscrollBehaviorX: 'contain'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("scrollbarWidth: 'thin'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'dataTable')).toContain("minWidth: 'min(100%, 620px)'")
    expect(styleBlock(teamDetailSource, 'tableHeaderCell')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(teamDetailSource, 'tableHeaderCell')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'tableCell')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'scoreCellStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'scoreCellStackStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'playerLink')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'rosterActionRow')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'rosterActionLink')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'rosterActionLink')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'summarySplitRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'summarySplitItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'recentFormRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'listRowCopyStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'listRowCopyStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'ratingStackStyle')).toContain("flexDirection: 'column'")
    expect(styleBlock(teamDetailSource, 'ratingStackStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'opponentBreakdownHeaderStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'seasonFilterControlsStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'seasonFilterButtonStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(teamDetailSource, 'seasonFilterButtonStyle')).toContain("overflowWrap: 'anywhere'")
    expect(functionBlock(teamDetailSource, 'reportStatusBadgeStyle')).toContain("maxWidth: '100%'")
    expect(functionBlock(teamDetailSource, 'reportStatusBadgeStyle')).toContain("overflowWrap: 'anywhere'")
    expect(teamDetailSource).not.toContain('minWidth: 112')
    expect(teamDetailSource).toContain("minWidth: 'min(100%, 420px)'")
    expect(teamDetailSource).toContain("background: 'var(--shell-panel-bg)'")
    expect(teamDetailSource).toContain("background: 'var(--shell-chip-bg)'")
    expect(teamDetailSource).toContain("color: 'var(--foreground-strong)'")
    expect(teamDetailSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(teamDetailSource).toContain("boxShadow: 'var(--shadow-soft)'")
  })

  it('keeps player detail analytics and match lists mobile-safe', () => {
    expect(playerDetailSource).not.toContain("gridTemplateColumns: isTablet\n      ? '1fr'")
    expect(playerDetailSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(playerDetailSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(playerDetailSource).toMatch(/gridTemplateColumns: isTablet\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(playerDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(playerDetailSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(playerDetailSource).toContain('const comparisonMetricGridStyle: CSSProperties')
    expect(playerDetailSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 160px), 1fr))'")
    expect(playerDetailSource).toContain('const matchHistoryToolbarStyle: CSSProperties')
    expect(playerDetailSource).toContain("width: 'min(100%, 180px)'")
    expect(playerDetailSource).toContain('const rivalryRowStyle: CSSProperties')
    expect(playerDetailSource).toContain('const seasonTableWrapStyle: CSSProperties')
    expect(playerDetailSource).toContain('const ratingHistoryTableWrapStyle: CSSProperties')
    expect(playerDetailSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(playerDetailSource, 'tableWrap')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'dataTable')).toContain("minWidth: 'min(100%, 760px)'")
    expect(styleBlock(playerDetailSource, 'seasonTableStyle')).toContain("minWidth: 'min(100%, 560px)'")
    expect(styleBlock(playerDetailSource, 'scoreCellStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'heroWrap')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'meterHeader')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'focusCard')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'focusHead')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'focusLabel')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'focusSubtitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'segmentWrap')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'summaryStatsGrid')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'summaryStatsGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock(playerDetailSource, 'profileDiscoveryHeaderStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'profileDiscoveryLabelStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'advancedStatsDetailsStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'advancedStatsSummaryStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(playerDetailSource, 'advancedStatsSummaryStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'signalLabelStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'scorecardMetricGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'scorecardMetricLabelStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'scorecardActionRailStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'scorecardRailLabelStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'contentGrid')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'rosterReadyCard')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'rosterReadyCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'rosterReadyContent')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'rosterReadyTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'rosterReadyText')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'rosterReadyStats')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'rosterReadyStats')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock(playerDetailSource, 'sectionKicker')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'tableHead')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'resultPill')).toContain("maxWidth: '100%'")
    expect(styleBlock(playerDetailSource, 'resultPill')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(playerDetailSource, 'resultPill')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'sectionTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(playerDetailSource, 'breadcrumbLink')).toContain("maxWidth: '100%'")
    expect(styleBlock(playerDetailSource, 'breadcrumbLink')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(playerDetailSource, 'breadcrumbLink')).toContain("overflowWrap: 'anywhere'")
    expect(playerDetailSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))', gap: 12, marginTop: 16, minWidth: 0")
    expect(playerDetailSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 160px), 1fr))', gap: 12, marginTop: 16, minWidth: 0")
    expect(playerDetailSource).toContain("display: 'grid', gap: 12, marginTop: 20, minWidth: 0")
    expect(playerDetailSource).toContain("display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' as const, minWidth: 0")
    expect(playerDetailSource).toContain("display: 'flex', flexWrap: 'wrap' as const, gap: '14px', marginTop: '12px', padding: '0 4px', minWidth: 0")
    expect(playerDetailSource).toContain("minWidth: 'min(100%, 162px)'")
    expect(playerDetailSource).not.toContain('minWidth: 560')
    expect(playerDetailSource).not.toContain('minWidth: 162')
    expect(playerDetailSource).not.toContain('minWidth: 112')
    expect(functionBlock(playerDetailSource, 'profileDiscoveryGridStyle')).toContain('minWidth: 0')
    expect(functionBlock(playerDetailSource, 'signalGridStyle')).toContain('minWidth: 0')
    expect(playerDetailSource).toContain('const nearbyPlayerRowStyle: CSSProperties')
    expect(playerDetailSource).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps Explore Leagues empty lanes separated by source and workflow', () => {
    expect(exploreLeaguesSource).toContain("emptyKind=\"usta\"")
    expect(exploreLeaguesSource).toContain('USTA league lanes come from reviewed TennisLink exports')
    expect(exploreLeaguesSource).toContain('Search leagues')
    expect(exploreLeaguesSource).toContain("emptyKind=\"tiq-team\"")
    expect(exploreLeaguesSource).toContain('TIQ team leagues are coordinator-created seasons')
    expect(exploreLeaguesSource).toContain('Create team league')
    expect(exploreLeaguesSource).toContain("emptyKind=\"tiq-individual\"")
    expect(exploreLeaguesSource).toContain('TIQ individual leagues are coordinator-created player-vs-player seasons')
    expect(exploreLeaguesSource).toContain('Create individual league')
    expect(styleBlock(exploreLeaguesSource, 'heroGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'heroPillRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'exploreNavRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'exploreNavLinkStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(exploreLeaguesSource, 'heroPillBlueStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock(exploreLeaguesSource, 'heroPillBlueStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreLeaguesSource, 'heroPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'searchGroupStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'layerToggleGroupStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'toggleStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(exploreLeaguesSource, 'noticeStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreLeaguesSource, 'sectionStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'sectionHeaderStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'cardMetaRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'metaBlueStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(exploreLeaguesSource, 'miniStatsStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'individualSummaryStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreLeaguesSource, 'emptyActionRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'ghostButtonStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock(exploreLeaguesSource, 'upgradeGridStyle')).toContain('minWidth: 0')
  })

  it('keeps TIQ league standings and team results theme-aware on mobile', () => {
    expect(tiqLeagueDetailSource).toContain('const teamStandingsScrollStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain("overscrollBehaviorX: 'contain'")
    expect(tiqLeagueDetailSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(tiqLeagueDetailSource).toContain("minWidth: 'min(100%, 560px)'")
    expect(tiqLeagueDetailSource).toContain("tableLayout: 'auto'")
    expect(styleBlock(tiqLeagueDetailSource, 'teamStandingsHeaderCellStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(tiqLeagueDetailSource, 'teamStandingsTeamNameCellStyle')).toContain('minWidth: 0')
    expect(tiqLeagueDetailSource).toContain("color: 'var(--foreground-strong)'")
    expect(tiqLeagueDetailSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(tiqLeagueDetailSource).toContain("border: '1px solid var(--shell-panel-border)'")
    expect(tiqLeagueDetailSource).toContain("overflowWrap: 'anywhere'")
    expect(tiqLeagueDetailSource).toContain('const teamResultHeaderRowStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain('const teamLineGridStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain('const teamLineHeaderStyle: CSSProperties')
    expect(styleBlock(tiqLeagueDetailSource, 'teamLineGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'teamLineHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'hintPill')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(tiqLeagueDetailSource, 'sideCard')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'leaderTableStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'leaderNameCellStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'leaderRankAccentStyle')).toContain("color: '#f8fbff'")
    expect(styleBlock(tiqLeagueDetailSource, 'actionRow')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'ghostButton')).toContain("maxWidth: '100%'")
    expect(styleBlock(tiqLeagueDetailSource, 'leagueHubPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'leagueHubScoreStyle')).toContain("width: 'min(100%, 156px)'")
    expect(styleBlock(tiqLeagueDetailSource, 'hubNavStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'seasonPulseGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'seasonPulseCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'upcomingMatchRowStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'schedulePanelStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleViewToggleStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleViewToggleButtonStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleCalendarGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'participantStatusGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'requestPreviewGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'resultBookGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'resultFormGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 180px), 1fr))'")
    expect(styleBlock(tiqLeagueDetailSource, 'resultFormGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'resultCuePanelStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'resultCueActionRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'contentGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'panelCard')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'panelCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'formatCallout')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'listWrap')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'listCard')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'standingCard')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'standingHeader')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'standingNameRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'leagueStatusPillStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(tiqLeagueDetailSource, 'standingMetrics')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'opportunityGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'opportunityGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))'")
    expect(styleBlock(tiqLeagueDetailSource, 'opportunityCard')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'quickGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'quickGrid')).toContain("repeat(auto-fit, minmax(min(100%, 160px), 1fr))")
    expect(styleBlock(tiqLeagueDetailSource, 'quickButton')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'stateCard')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'stateTitle')).toContain("overflowWrap: 'anywhere'")
    expect(tiqLeagueDetailSource).toContain("join(' | ')")
    expect(tiqLeagueDetailSource).not.toContain("color: '#06121a'")
    expect(tiqLeagueDetailSource).not.toContain("color: '#94a3b8'")
    expect(tiqLeagueDetailSource).not.toContain("color: '#64748b'")
    expect(tiqLeagueDetailSource).not.toContain("color: '#cbd5e1'")
  })

  it('keeps TIQ league detail grids minmax-safe on mobile', () => {
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : '56px minmax(0, 1fr)'")
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : 'repeat(2, minmax(0, 1fr))'")
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : isMobile ? 'repeat(2, minmax(0, 1fr))' : 'repeat(4, minmax(0, 1fr))'")
    expect(tiqLeagueDetailSource).not.toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock(tiqLeagueDetailSource, 'pageWrap')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'heroGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'pillBase')).toContain("whiteSpace: 'normal'")
  })
})
