import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const exploreSource = source('app/explore/page.tsx')
const exploreSearchSource = source('app/explore/search/page.tsx')
const publicCommandCenterSource = source('app/components/public-command-center.tsx')
const rankingsSource = source('app/rankings/page.tsx')
const playersSource = source('app/players/page.tsx')
const playerDetailSource = source('app/players/[id]/page.tsx')
const teamsSource = source('app/teams/page.tsx')
const teamDetailSource = source('app/teams/[team]/page.tsx')
const leaguesSource = source('app/leagues/page.tsx')
const leagueDetailSource = source('app/leagues/[league]/page.tsx')
const exploreLeaguesSource = source('app/explore/leagues/page.tsx')
const tiqLeagueDetailSource = source('app/explore/leagues/tiq/[league]/page.tsx')
const pricingSource = source('app/pricing/page.tsx')
const myLabSource = source('app/mylab/page.tsx')
const captainSource = source('app/captain/page.tsx')
const leagueCoordinatorSource = source('app/components/league-coordinator-workspace.tsx')
const playerDevelopmentSource = source('app/player-development/_components/player-development-system.tsx')
const playerDevelopmentStyles = source('app/player-development/_components/player-development.module.css')
const matchupSource = source('app/matchup/page.tsx')
const appGlobalsSource = source('app/globals.css')

function source(path: string) {
  return readFileSync(join(process.cwd(), path), 'utf8')
}

function styleBlock(sourceText: string, styleName: string) {
  const start = sourceText.indexOf(`const ${styleName}:`)
  expect(start, `Missing ${styleName}`).toBeGreaterThanOrEqual(0)
  const nextStyle = sourceText.indexOf('\nconst ', start + 1)
  return sourceText.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

function functionBlock(sourceText: string, functionName: string) {
  const start = sourceText.indexOf(`const ${functionName} =`)
  expect(start, `Missing ${functionName}`).toBeGreaterThanOrEqual(0)
  const nextStyle = sourceText.indexOf('\nconst ', start + 1)
  return sourceText.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

describe('Explore responsive surfaces', () => {
  it('keeps the simplified Explore hub aligned with the persistent Find portal', () => {
    expect(exploreSource).toContain('FIND_COMMAND_STEPS')
    expect(exploreSource).toContain('EXPLORE_PRIMARY_COMMAND')
    expect(exploreSource).toContain('PUBLIC_DISCOVERY_PROOF_STEPS')
    expect(exploreSource).toContain('function FindCommandPanel')
    expect(exploreSource).toContain('TrackedProductLink')
    expect(exploreSource).toContain('Find players, teams, leagues.')
    expect(exploreSource).toContain('Search by name, team, league, city, rating, court, coach, or tournament.')
    expect(exploreSource).toContain('<UniversalSearch compact />')
    expect(exploreSource).toContain('getMembershipTier')
    expect(exploreSource).toContain('DATA_ASSIST_STORY.shortCue')
    expect(exploreSource).toContain('aria-label="Explore tennis search tools"')
    expect(exploreSource).toContain('className="explore-primary-command"')
    expect(exploreSource).toContain("label: 'Search first'")
    expect(exploreSource).toContain('Start with one tennis question.')
    expect(exploreSource).toContain('Open search')
    expect(exploreSource).toContain('aria-label="What you can check free"')
    expect(exploreSource).toContain('What you can check free')
    expect(exploreSource).not.toContain('Public discovery proof cue')
    expect(exploreSource).toContain('Useful before upgrade.')
    expect(exploreSource).toContain('Find first')
    expect(exploreSource).toContain('Public detail')
    expect(exploreSource).toContain('Open player, team, league, and ranking pages before you upgrade.')
    expect(exploreSource).toContain('Next tier')
    expect(exploreSource).toContain('See ratings, teams, and recent public tennis context.')
    expect(exploreSource).toContain('Review team, flight, league, and opponent context.')
    expect(exploreSource).toContain('Find schedules, results, and where the season stands.')
    expect(exploreSource).toContain('Compare rating, area, and player shape before you choose.')
    expect(exploreSource).toContain("location: 'explore_path'")
    expect(exploreSource).toContain("location: 'public_discovery_proof'")

    for (const label of ['Find a player', 'Browse teams', 'Check standings', 'Check rankings']) {
      expect(exploreSource).toContain(`label: '${label}'`)
    }

    expect(styleBlock(exploreSource, 'heroShell')).toContain("width: 'min(1280px, calc(100% - clamp(24px, 5vw, 40px)))'")
    expect(styleBlock(exploreSource, 'heroShell')).toContain('minWidth: 0')
    expect(styleBlock(exploreSource, 'heroTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'findCommandHeader')).toContain("'48px minmax(0, 1fr) minmax(0, auto)'")
    expect(styleBlock(exploreSource, 'findCommandWorkspace')).toContain("'minmax(min(100%, 360px), 0.9fr) minmax(0, 1.1fr)'")
    expect(styleBlock(exploreSource, 'findCommandGrid')).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock(exploreSource, 'findCommandPrimaryCard')).toContain('minHeight: 220')
    expect(styleBlock(exploreSource, 'findCommandPrimaryCard')).toContain("overflowWrap: 'anywhere'")
    expect(exploreSource).toContain("const primaryCardStyle = compact")
    expect(exploreSource).toContain('minHeight: mobile ? 62 : 152')
    expect(exploreSource).toContain("gridTemplateRows: mobile ? 'auto auto' : findCommandPrimaryCard.gridTemplateRows")
    expect(exploreSource).toContain("padding: mobile ? '8px' : '12px'")
    expect(exploreSource).toContain('compactFindCommandHeader')
    expect(exploreSource).toContain('compactFindCommandTitle')
    expect(exploreSource).toContain('compactFindCommandPill')
    expect(exploreSource).toContain('compactPublicDiscoveryProofSummaryStyle')
    expect(exploreSource).toContain('compactPublicDiscoveryProofTitleStyle')
    expect(exploreSource).toContain('compactPublicDiscoveryProofSummaryActionStyle')
    expect(styleBlock(exploreSource, 'compactFindCommandHeader')).toContain("'32px minmax(0, 1fr) minmax(0, auto)'")
    expect(styleBlock(exploreSource, 'compactFindCommandTitle')).toContain("fontSize: '1rem'")
    expect(styleBlock(exploreSource, 'compactFindCommandPill')).toContain('minHeight: 28')
    expect(styleBlock(exploreSource, 'compactPublicDiscoveryProofSummaryActionStyle')).toContain('minHeight: 26')
    expect(exploreSource).not.toContain('if (compact) {')
    expect(exploreSource).toContain('const shortcutGridStyle = compact')
    expect(exploreSource).toContain("gridTemplateColumns: mobile")
    expect(styleBlock(exploreSource, 'findCommandCard')).toContain("'32px minmax(0, 1fr)'")
    expect(styleBlock(exploreSource, 'findCommandCard')).toContain('minHeight: 64')
    expect(styleBlock(exploreSource, 'findCommandCardTitle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'findCommandPrimaryBodyStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSource, 'publicDiscoveryProofStyle')).toContain("display: 'block'")
    expect(styleBlock(exploreSource, 'publicDiscoveryProofSummaryStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(exploreSource, 'publicDiscoveryProofGridStyle')).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock(exploreSource, 'publicDiscoveryProofGridStyle')).toContain("marginTop: '10px'")
    expect(styleBlock(exploreSource, 'publicDiscoveryProofItemStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSource, 'publicDiscoveryProofItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(exploreSource).toContain('className="exploreDetailsSection"')
    expect(appGlobalsSource).toContain('.exploreDetailsSection:not([open]) > :not(summary)')
    expect(styleBlock(exploreSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(exploreSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(exploreSource, 'watermarkStyle')).not.toContain("right: '-86px'")
    expect(exploreSource).toContain("'repeat(auto-fit, minmax(min(100%, 190px), 1fr))'")
    expect(exploreSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 160px), 1fr))'")
    expect(exploreSource).not.toContain('const actionBody: CSSProperties')
    expect(exploreSource).not.toContain('const startStepNumber: CSSProperties')
    expect(exploreSource).not.toContain("'auto minmax(0, 1fr)'")
  })

  it('keeps the homepage tool-first with optional explanation boards', () => {
    expect(publicCommandCenterSource).toContain('export function CommandHero')
    expect(publicCommandCenterSource).toContain('Quick actions')
    expect(publicCommandCenterSource).toContain('export function HomeIntelligenceSnapshot')
    expect(publicCommandCenterSource).toContain('<details style={homeDisclosureStyle} aria-labelledby="home-intelligence-snapshot-title">')
    expect(publicCommandCenterSource).toContain('Open reads before you choose a tool.')
    expect(publicCommandCenterSource).toContain('Show reads')
    expect(publicCommandCenterSource).toContain('export function HomeModeRouter')
    expect(publicCommandCenterSource).toContain('<details style={homeDisclosureStyle} aria-labelledby="home-mode-router-title">')
    expect(publicCommandCenterSource).toContain('Open role paths.')
    expect(publicCommandCenterSource).toContain('Show paths')
    expect(styleBlock(publicCommandCenterSource, 'homeDisclosureStyle')).toContain('overflowWrap: \'anywhere\'')
    expect(styleBlock(publicCommandCenterSource, 'homeDisclosureSummaryStyle')).toContain('flexWrap: \'wrap\'')
    expect(styleBlock(publicCommandCenterSource, 'homeDisclosureCueStyle')).toContain('...ghostButtonStyle')
    expect(publicCommandCenterSource).not.toContain('title="See what TenAceIQ can tell you."')
    expect(publicCommandCenterSource).not.toContain('title="One clean path from here."')
  })

  it('keeps Explore Search grids and filter controls mobile-safe', () => {
    expect(exploreSearchSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(exploreSearchSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(exploreSearchSource).toContain("'minmax(min(100%, 172px), 196px) minmax(0, 1fr) minmax(0, auto)'")
    expect(exploreSearchSource).toContain('searchNextActions')
    expect(exploreSearchSource).toContain('aria-label="Search next actions"')
    expect(exploreSearchSource).toContain('What are you looking for?')
    expect(exploreSearchSource).toContain('Open the record, then act on it.')
    expect(exploreSearchSource).toContain('getSearchSelectStyle(isMobile)')
    expect(exploreSearchSource).toContain('getSearchInputWrapStyle(isMobile)')
    expect(exploreSearchSource).toContain('getSearchInputStyle(isMobile)')
    expect(exploreSearchSource).toContain('minHeight: compact ? 42 : 56')
    expect(exploreSearchSource).toContain('compactSearchNextActionsGridStyle')
    expect(exploreSearchSource).toContain('{!isMobile ? <span style={searchNextActionsTextStyle}>{action.body}</span> : null}')
    expect(styleBlock(exploreSearchSource, 'compactSearchNextActionsGridStyle')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
    expect(styleBlock(exploreSearchSource, 'compactSearchNextActionCardStyle')).toContain('minHeight: 94')
    expect(styleBlock(exploreSearchSource, 'compactSearchNextActionLinkStyle')).toContain('minHeight: 30')
    expect(exploreSearchSource).toContain('function FilterSelect')
    expect(exploreSearchSource).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'emptyStateStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'emptyTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'resultGroupStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'resultGroupHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(exploreSearchSource, 'resultGroupActionStyle')).toContain("maxWidth: '100%'")
    expect(styleBlock(exploreSearchSource, 'searchCommandGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 154px), 1fr))'")
    expect(styleBlock(exploreSearchSource, 'searchCommandCardStyle')).toContain("'32px minmax(0, 1fr)'")
    expect(styleBlock(exploreSearchSource, 'searchNextActionsStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'searchNextActionsHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(exploreSearchSource, 'searchNextActionsGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 210px), 1fr))'")
    expect(styleBlock(exploreSearchSource, 'searchNextActionCardStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'searchNextActionLinkStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(exploreSearchSource, 'filterJumpStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(exploreSearchSource, 'watermarkStyle')).not.toContain("right: '-86px'")
    expect(exploreSearchSource).not.toContain("'minmax(min(100%, 172px), 196px) minmax(0, 1fr) auto'")
    expect(exploreSearchSource).not.toContain('searchCommandNumberStyle')
  })

  it('keeps rankings cards, tables, and insight panels mobile-safe', () => {
    expect(rankingsSource).toContain('const dynamicControlsGrid: CSSProperties')
    expect(rankingsSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain('const [focusedDirectoryControl, setFocusedDirectoryControl]')
    expect(rankingsSource).toContain("onFocus={() => setFocusedDirectoryControl('search')}")
    expect(rankingsSource).toContain("onFocus={() => setFocusedDirectoryControl('location')}")
    expect(rankingsSource).toContain("onFocus={() => setFocusedDirectoryControl('overall')}")
    expect(rankingsSource).toContain('directoryControlFocusStyle')
    expect(rankingsSource).toContain("outline: '2px solid transparent'")
    expect(rankingsSource).not.toContain("outline: 'none'")
    expect(styleBlock(rankingsSource, 'controlsGrid')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'summaryStatsGrid')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(styleBlock(rankingsSource, 'compactRankingSummaryStrip')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(rankingsSource, 'rankingDecisionBoardStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 250px), 1fr))'")
    expect(styleBlock(rankingsSource, 'rankingDecisionBoardStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'rankingPlayerIdTrailStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'rankingPlayerIdSignalStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("overscrollBehaviorX: 'contain'")
    expect(rankingsSource).toContain('const useCompactLeaderboard = isMobile || isTablet')
    expect(rankingsSource).toContain('const rankingDefaultRowLimit = isMobile ? 2 : isTablet ? 3 : RANKINGS_DEFAULT_ROW_LIMIT')
    expect(rankingsSource).toContain('{useCompactLeaderboard ? (')
    expect(rankingsSource).not.toContain('Top 3 in field drawer')
    expect(rankingsSource).not.toContain('Top three are in the field drawer. Open the full board when you need every ranked player.')
    expect(rankingsSource).toContain('displayedTieredRows.length === 0')
    expect(rankingsSource).toContain('Open matchup, player, league, and data checks')
    expect(rankingsSource).toContain('<span style={insightSummaryMeta}>4 checks</span>')
    expect(rankingsSource).toContain('const compactBoardSummary =')
    expect(rankingsSource).toContain('style={dynamicCompactRankingSummaryStrip}')
    expect(rankingsSource).toContain('const rankingSignalCount =')
    expect(rankingsSource).toContain('{!loading && !error && rankingSignalCount > 0 ? (')
    expect(rankingsSource).not.toContain('Location filters appear after review')
    expect(rankingsSource).toContain('const compareHref = buildRankingCompareHref(player, topPlayer, topRival)')
    expect(rankingsSource).toContain('<article')
    expect(rankingsSource).toContain('style={podiumName}')
    expect(rankingsSource).toContain('style={podiumActionPrimaryStyle}')
    expect(rankingsSource).toContain('style={podiumActionSecondaryStyle}')
    expect(rankingsSource).toContain('<details className="rankingDetailsSection" style={mobileTopFieldDetailsStyle} aria-label="Top of the rankings field">')
    expect(rankingsSource).toContain('style={mobileTopFieldSummaryStyle}')
    expect(rankingsSource).toContain('Open top 3')
    expect(rankingsSource).toContain("justifySelf: 'start'")
    expect(rankingsSource).toContain('function CompactRankingDetails')
    expect(rankingsSource).toContain('title="Rating checks"')
    expect(rankingsSource).toContain('showDetails={!isMobile}')
    expect(rankingsSource).toContain('showDetails: boolean')
    expect(rankingsSource).toContain('{showDetails ? (')
    expect(rankingsSource).toContain("style={compactRankingDetailsStyle}")
    expect(rankingsSource.indexOf('<div style={compactActionRowStyle}>')).toBeLessThan(
      rankingsSource.indexOf('{showDetails ? ('),
    )
    expect(styleBlock(rankingsSource, 'dataTable')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'dataTable')).toContain("tableLayout: 'fixed'")
    expect(styleBlock(rankingsSource, 'tableHead')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(rankingsSource, 'rankingPlayerIdentityStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'rankingPlayerIdentityStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(rankingsSource, 'statusPill')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(rankingsSource, 'statusPill')).toContain("maxWidth: '100%'")
    expect(styleBlock(rankingsSource, 'rowActionPrimaryStyle')).toContain("width: '100%'")
    expect(styleBlock(rankingsSource, 'rowActionPrimaryStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'podiumCard')).toContain("display: 'grid'")
    expect(styleBlock(rankingsSource, 'podiumCard')).toContain("padding: '16px'")
    expect(styleBlock(rankingsSource, 'podiumName')).toContain("fontSize: '23px'")
    expect(styleBlock(rankingsSource, 'podiumActionRowStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 124px), 1fr))'")
    expect(styleBlock(rankingsSource, 'podiumActionPrimaryStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'mobileTopFieldSummaryStyle')).toContain("gridTemplateColumns: 'minmax(0, 1fr) minmax(0, auto)'")
    expect(styleBlock(rankingsSource, 'mobileTopFieldRowStyle')).toContain("gridTemplateColumns: 'minmax(0, 32px) minmax(0, 1fr)'")
    expect(styleBlock(rankingsSource, 'mobileTopFieldActionRowStyle')).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock(rankingsSource, 'mobileTopFieldActionStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'compactRankingCardStyle')).toContain("gap: '10px'")
    expect(styleBlock(rankingsSource, 'compactRankingDetailsStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'compactRankingSummaryStyle')).toContain("gridTemplateColumns: 'minmax(0, auto) minmax(0, 1fr)'")
    expect(styleBlock(rankingsSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(rankingsSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(rankingsSource, 'distributionRow')).toContain("'minmax(0, 72px) minmax(0, 1fr) minmax(0, 32px)'")
    expect(rankingsSource).not.toContain("'auto minmax(0, 1fr)'")
    expect(rankingsSource).not.toContain("'minmax(0, 1fr) auto'")
    expect(rankingsSource).not.toContain('minWidth: 1180')
    expect(rankingsSource).not.toContain('minWidth: 980')
    expect(styleBlock(rankingsSource, 'watermarkStyle')).not.toContain("right: '-86px'")
  })

  it('keeps public player and team discovery empty states actionable', () => {
    expect(playersSource).toContain('Public discovery only shows reviewed player context')
    expect(playersSource).toContain('Reset filters')
    expect(playersSource).toContain('DATA_ASSIST_STORY.cta')
    expect(playersSource).toContain('<label htmlFor="players-directory-search"')
    expect(playersSource).toContain('<label htmlFor="players-directory-sort"')
    expect(playersSource).toContain('<label htmlFor="players-directory-filter"')
    expect(playersSource).toContain('<label htmlFor="players-directory-flight"')
    expect(playersSource).toContain('const srOnlyStyle: CSSProperties')
    expect(playersSource).toContain('const [focusedDirectoryControl, setFocusedDirectoryControl]')
    expect(playersSource).toContain('directoryControlFocusStyle')
    expect(playersSource).toContain("onFocus={() => setFocusedDirectoryControl('sort')}")
    expect(playersSource).toContain("outline: '2px solid transparent'")
    expect(playersSource).not.toContain("outline: 'none'")
    expect(styleBlock(playersSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(playersSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(playersSource, 'watermarkStyle')).not.toContain("right: '-86px'")
    expect(teamsSource).toContain('Public discovery only shows reviewed team context')
    expect(teamsSource).toContain('Reset team filters')
    expect(teamsSource).toContain('DATA_ASSIST_STORY.cta')
    expect(teamsSource).toContain("location: 'teams_filters'")
    expect(teamsSource).toContain('Captain Tools')
    expect(teamsSource).not.toContain('Jump to search.')
    expect(teamsSource).not.toContain('Results signal.')
    expect(teamsSource).not.toContain('Full board.')
    expect(styleBlock(teamsSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(teamsSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(teamsSource, 'watermarkStyle')).not.toContain("right: '-86px'")
    expect(teamsSource).toContain('cue="Show team paths"')
    expect(teamsSource).not.toContain('Team tennis without the group-text chaos.')
    expect(teamsSource).not.toContain('teams_intro')
    expect(teamsSource.indexOf('<h1 style={sectionTitle}>Find a team.</h1>')).toBeLessThan(
      teamsSource.indexOf('eyebrow="Team paths"'),
    )
    expect(teamsSource.indexOf('<h1 style={sectionTitle}>Find a team.</h1>')).toBeLessThan(
      teamsSource.indexOf('eyebrow="Team Hub preview"'),
    )
  })

  it('keeps Players and Teams directory grids minmax-safe on mobile', () => {
    expect(playersSource).toContain('const dynamicCardGrid: CSSProperties')
    expect(playersSource).toContain('gridTemplateColumns: isSmallMobile')
    expect(playersSource).toContain("? 'minmax(0, 1fr)'")
    expect(styleBlock(playersSource, 'cardGrid')).toContain('minWidth: 0')
    expect(styleBlock(playersSource, 'cardAccentGlow')).toContain("right: 0")
    expect(styleBlock(playersSource, 'cardAccentGlow')).toContain("width: 'min(42%, 150px)'")

    expect(teamsSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(styleBlock(teamsSource, 'surfaceCard')).toContain("background: 'rgba(8,16,34,0.74)'")
    expect(styleBlock(teamsSource, 'teamCardCopy')).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'metricsGrid')).toContain('minWidth: 0')
  })

  it('keeps public detail pages dark-shell readable and Data Assist aware', () => {
    expect(leaguesSource).toContain('DATA_ASSIST_STORY')
    expect(leaguesSource).toContain('DATA_ASSIST_STORY.cta')
    expect(leagueDetailSource).toContain('reviewed match rows')
    expect(leagueDetailSource).toContain('DATA_ASSIST_STORY.cta')
    expect(teamDetailSource).toContain('reviewed Data Assist scorecards')
    expect(teamDetailSource).toContain('DATA_ASSIST_STORY.cta')
    expect(playerDetailSource).toContain('scorecardMetricGridStyle')
    expect(playerDetailSource).toContain('scorecardActionRailStyle')

    for (const sourceText of [leaguesSource, leagueDetailSource, teamDetailSource, playerDetailSource]) {
      expect(sourceText).toContain("color: 'var(--foreground-strong)'")
      expect(sourceText).toContain("color: 'var(--shell-copy-muted)'")
      expect(sourceText).toContain("overflowWrap: 'anywhere'")
    }
  })

  it('keeps player detail analytics and match lists mobile-safe', () => {
    expect(styleBlock(playerDetailSource, 'tableWrap')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(playerDetailSource, 'tableWrap')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'seasonTableStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'scoreCellStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'mobileMatchListStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'mobileMatchCardStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'mobileMatchMetaGridStyle')).toContain("minmax(min(100%, 110px), 1fr)")
    expect(functionBlock(playerDetailSource, 'signalGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'scorecardMetricGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'scorecardActionRailStyle')).toContain("overflowWrap: 'anywhere'")
    expect(functionBlock(playerDetailSource, 'reportStatusPillStyle')).toContain('minWidth: 0')
    expect(playerDetailSource).toContain('aria-label="Search latest match history"')
    expect(playerDetailSource).toContain('aria-label="Latest match history"')
    expect(playerDetailSource).toContain(') : isMobile ? (')
    expect(playerDetailSource).toContain('onFocus={() => setMatchSearchFocused(true)}')
    expect(playerDetailSource).toContain('const matchSearchInputFocusStyle: CSSProperties')
    expect(styleBlock(playerDetailSource, 'matchSearchInputStyle')).toContain("outline: '2px solid transparent'")
    expect(styleBlock(playerDetailSource, 'matchSearchInputStyle')).toContain('outlineOffset: 2')
    expect(styleBlock(playerDetailSource, 'matchSearchInputStyle')).not.toContain("outline: 'none'")
    expect(playerDetailSource).not.toContain("minWidth: 'auto'")
    expect(playerDetailSource).not.toContain('minWidth: 560')
  })

  it('keeps Explore Leagues empty lanes separated by source and workflow', () => {
    expect(exploreLeaguesSource).toContain("emptyKind=\"usta\"")
    expect(exploreLeaguesSource).toContain('USTA league views come from reviewed TennisLink exports')
    expect(exploreLeaguesSource).toContain("emptyKind=\"tiq-team\"")
    expect(exploreLeaguesSource).toContain('Create the first team league.')
    expect(exploreLeaguesSource).toContain('Team seasons become schedule, standings, result book, and Captain handoff spaces')
    expect(exploreLeaguesSource).toContain('start a TIQ League Office season')
    expect(exploreLeaguesSource).toContain('Create and run team leagues with schedules, standings, results, lineups, and captain handoffs.')
    expect(exploreLeaguesSource).toContain('Run ladders, round robins, challenge formats, standings, results, and awards for individual players.')
    expect(exploreLeaguesSource).toContain("emptyKind=\"tiq-individual\"")
    expect(exploreLeaguesSource).toContain('Start a player-vs-player season.')
    expect(exploreLeaguesSource).toContain('Results start with the first logged match.')
    expect(exploreLeaguesSource).toContain('const LEAGUE_SECTION_DEFAULT_LIMIT = 1')
    expect(exploreLeaguesSource).toContain('const { isMobile } = useViewportBreakpoints()')
    expect(exploreLeaguesSource).toContain('const activeSecondaryFilterCount = [yearFilter, seasonFilter, genderFilter, ratingFilter]')
    expect(exploreLeaguesSource).toContain('<details style={dynamicMoreFiltersDetailsStyle} open={!isMobile}>')
    expect(exploreLeaguesSource).toContain('More filters')
    expect(exploreLeaguesSource).toContain('Year, season, rating')
    expect(exploreLeaguesSource).toContain('const dynamicHeroStyle = isMobile ? compactHeroStyle : heroStyle')
    expect(exploreLeaguesSource).toContain('const dynamicPanelHeaderStyle = isMobile ? compactPanelHeaderStyle : panelHeaderStyle')
    expect(exploreLeaguesSource).toContain('const dynamicHeroPillRowStyle = isMobile ? compactHeroPillRowStyle : heroPillRowStyle')
    expect(exploreLeaguesSource).toContain('const dynamicFilterBarStyle = isMobile ? compactFilterBarStyle : filterBarStyle')
    expect(styleBlock(exploreLeaguesSource, 'compactHeroStyle')).toContain("padding: '9px'")
    expect(styleBlock(exploreLeaguesSource, 'compactHeroPillBlueStyle')).toContain("minHeight: '26px'")
    expect(styleBlock(exploreLeaguesSource, 'compactFilterBarStyle')).toContain("marginTop: '9px'")
    expect(styleBlock(exploreLeaguesSource, 'compactStateStyle')).toContain("padding: '10px'")
    expect(exploreLeaguesSource).toContain('const [showAllLeagues, setShowAllLeagues] = useState(false)')
    expect(exploreLeaguesSource).toContain('const visibleLeagues = showAllLeagues ? leagues : leagues.slice(0, LEAGUE_SECTION_DEFAULT_LIMIT)')
    expect(exploreLeaguesSource).toContain('Showing the first league. Search, filter, or show more when you need another league.')
    expect(exploreLeaguesSource).toContain('League, flight, section, or district')
    expect(exploreLeaguesSource).toContain('Show more leagues')
    expect(exploreLeaguesSource).toContain('Show fewer leagues')
    expect(exploreLeaguesSource).not.toContain('Show full lane')
    expect(exploreLeaguesSource).not.toContain('Show starter lane')
    expect(exploreLeaguesSource).toContain('function LeagueCardDetails')
    expect(exploreLeaguesSource).toContain('eyebrow="Data check"')
    expect(exploreLeaguesSource).toContain('Show checks')
    expect(exploreLeaguesSource).toContain("layerFilter !== 'tiq'")
    expect(exploreLeaguesSource).toContain("layerFilter !== 'usta'")
    expect(exploreLeaguesSource).toContain('defaultOpen={layerFilter === \'tiq\'}')
    expect(exploreLeaguesSource).toContain('<details style={dynamicSectionStyle} open={defaultOpen && !isMobile}>')
    expect(styleBlock(exploreLeaguesSource, 'heroPillRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'filterBarStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 180px), 1fr))'")
    expect(styleBlock(exploreLeaguesSource, 'moreFiltersDetailsStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'moreFiltersSummaryStyle')).toContain('flexWrap: \'wrap\'')
    expect(styleBlock(exploreLeaguesSource, 'moreFiltersGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 180px), 1fr))'")
    expect(styleBlock(exploreLeaguesSource, 'sectionStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'sectionStyle')).toContain("padding: '16px'")
    expect(styleBlock(exploreLeaguesSource, 'sectionSummaryStyle')).toContain('cursor: \'pointer\'')
    expect(styleBlock(exploreLeaguesSource, 'sectionSummaryStyle')).toContain("gridTemplateColumns: 'minmax(0, 1fr) minmax(0, auto)'")
    expect(styleBlock(exploreLeaguesSource, 'sectionSummaryMetaStyle')).toContain('overflowWrap: \'anywhere\'')
    expect(styleBlock(exploreLeaguesSource, 'gridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 300px), 1fr))'")
    expect(styleBlock(exploreLeaguesSource, 'cardStyle')).toContain('minHeight: 0')
    expect(styleBlock(exploreLeaguesSource, 'leagueCardDetailsStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'leagueLaneLimitStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'emptyActionRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreLeaguesSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(exploreLeaguesSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(exploreLeaguesSource, 'watermarkStyle')).not.toContain("right: '-86px'")
    expect(exploreLeaguesSource).not.toContain('minmax(min(320px, 100%)')
    expect(exploreLeaguesSource).not.toContain('No TIQ team leagues are visible yet.')
    expect(exploreLeaguesSource).not.toContain('start a TIQ league workspace')
    expect(exploreLeaguesSource).not.toContain('create a TIQ League Office workspace')
    expect(exploreLeaguesSource).not.toContain('No TIQ individual leagues are visible yet.')
    expect(exploreLeaguesSource).not.toContain('No TIQ results logged yet')
  })

  it('keeps Pricing mobile-first and upgrade actions ahead of explanations', () => {
    expect(pricingSource).toContain('const { isMobile } = useViewportBreakpoints()')
    expect(pricingSource).toContain('const planCta = (')
    expect(pricingSource).toContain('{isMobile ? planCta : null}')
    expect(pricingSource).toContain('{!isMobile ? planCta : null}')
    expect(pricingSource.indexOf('{isMobile ? planCta : null}')).toBeLessThan(
      pricingSource.indexOf('<details className="pricingPlanDetails" style={planDetailsStyle}>'),
    )
    expect(pricingSource).toContain('{!isMobile ? (')
    expect(pricingSource).toContain('<details className="pricingPlanDetails" style={planDetailsStyle}>')
    expect(pricingSource).toContain('<section id="start" style={finalCtaStyle}>')
    expect(pricingSource).toContain("size={isMobile ? 'md' : 'lg'}")
    expect(pricingSource).toContain('compactPlanCardStyle')
    expect(pricingSource).toContain('compactPlanTopStyle')
    expect(pricingSource).toContain('compactPriceStyle')
    expect(pricingSource).toContain('PLAN_MOBILE_NAMES')
    expect(pricingSource).toContain('Start free. Unlock the tools for your role when you are ready.')
    expect(pricingSource).toContain("body={isMobile ? 'Choose the role, then start.'")
    expect(pricingSource).toContain('{isMobile ? PLAN_MOBILE_NAMES[plan.id] : PLAN_PUBLIC_NAMES[plan.id]}')
    expect(pricingSource).toContain("{isMobile ? 'Need help choosing?' : 'Not sure which plan fits?'}")
    expect(pricingSource).toContain("{isMobile ? 'See what opens.' : 'Know what opens before you upgrade.'}")
    expect(pricingSource).toContain("{isMobile ? 'Compare plans.' : 'Compare by tennis need.'}")
    expect(pricingSource).toContain("{isMobile ? 'Billing basics.' : 'Monthly plans renew until canceled. League is a season fee.'}")
    expect(pricingSource).toContain('{!isMobile ? <p style={cardTextStyle}>{plan.outcome}</p> : null}')
    expect(styleBlock(pricingSource, 'compactHeroStyle')).toContain('padding: 14')
    expect(styleBlock(pricingSource, 'compactHeroTextStyle')).toContain('fontSize: 14')
    expect(styleBlock(pricingSource, 'compactPlanGridStyle')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
    expect(styleBlock(pricingSource, 'compactPlanCardStyle')).toContain('padding: 8')
    expect(styleBlock(pricingSource, 'compactPlanTopStyle')).toContain("gridTemplateColumns: '34px minmax(0, 1fr)'")
    expect(styleBlock(pricingSource, 'compactPriceStyle')).toContain('fontSize: 16')
    expect(styleBlock(pricingSource, 'compactPrimaryPlanButtonStyle')).toContain("width: '100%'")
    expect(styleBlock(pricingSource, 'compactPrimaryPlanButtonStyle')).toContain('minHeight: 30')
    expect(styleBlock(pricingSource, 'detailsSectionStyle')).toContain('overflowWrap: \'anywhere\'')
    expect(styleBlock(pricingSource, 'billingDetailsBodyStyle')).toContain('paddingTop: 14')
    expect(pricingSource).toContain('<details id="job-chooser"')
    expect(pricingSource).toContain('<details id="workspace"')
    expect(pricingSource).toContain('<details id="compare"')
    expect(pricingSource).toContain('<details id="billing"')
    expect(pricingSource).toContain('Show billing')
  })

  it('keeps paid tool entry pages action-first on phones', () => {
    expect(myLabSource).toContain('More tools')
    expect(myLabSource).toContain('Progress, calendar, coach.')
    expect(myLabSource).toContain('Start here')
    expect(myLabSource).toContain('Find yourself and choose a focus.')
    expect(myLabSource).toContain('const showLockedMobileMyLabPreview = isMobile && !accessPending && !access.canUseAdvancedPlayerInsights')
    expect(myLabSource).toContain('open={!isMobile}')
    expect(myLabSource).toContain('desktopPassthroughDetailsStyle')
    expect(myLabSource).toContain('desktopHiddenSummaryStyle')
    expect(myLabSource).toContain('className="myLabDetailsSection"')
    expect(myLabSource).toContain('className="myLabDetailsBody"')
    expect(appGlobalsSource).toContain('.myLabDetailsSection:not([open]) > .myLabDetailsBody')
    expect(myLabSource).toContain('{isMobile ? (')
    expect(myLabSource).toContain('const visiblePersonalLabPathCards = isMobile ? personalLabPathCards.slice(0, 2) : personalLabPathCards')
    expect(myLabSource).toContain('const extraPersonalLabPathCards = isMobile ? personalLabPathCards.slice(2) : []')
    expect(myLabSource).toContain('More lab moves')
    expect(myLabSource).toContain('Matchup, drills, video.')
    expect(myLabSource).toContain('summaryOnly={isMobile}')
    expect(myLabSource).toContain('setupCompactPanelStyle')
    expect(myLabSource).toContain('setupCompactHeroStyle')
    expect(myLabSource).toContain('setupCompactTitleStyle')
    expect(myLabSource).toContain('Setup steps')
    expect(myLabSource).toContain('Profile, context, lab.')
    expect(styleBlock(myLabSource, 'setupCompactPanelStyle')).toContain('padding: 14')
    expect(myLabSource).toContain('Follows and updates.')
    expect(myLabSource).not.toContain('Follows and updates when you want the wider picture.')
    expect(styleBlock(myLabSource, 'mobileLabMoveDetailsStyle')).toContain('overflow: \'hidden\'')
    const startHereIndex = myLabSource.indexOf('<strong>Start here</strong>')
    const moreToolsIndex = myLabSource.indexOf('<strong>More tools</strong>')
    const watchlistIndex = myLabSource.indexOf('<strong>Watchlist</strong>')
    expect(myLabSource.lastIndexOf('{!showLockedMobileMyLabPreview ? (', startHereIndex)).toBeGreaterThan(-1)
    expect(myLabSource.lastIndexOf('!showLockedMobileMyLabPreview ? (', moreToolsIndex)).toBeGreaterThan(-1)
    expect(myLabSource.lastIndexOf('{!showLockedMobileMyLabPreview ? (', watchlistIndex)).toBeGreaterThan(moreToolsIndex)
    expect(myLabSource.indexOf('More tools')).toBeLessThan(
      myLabSource.indexOf('<PlayerDevelopmentPathPanel'),
    )
    expect(styleBlock(myLabSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(myLabSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(myLabSource, 'watermarkStyle')).not.toContain("right: 'clamp(-92px")

    expect(leagueCoordinatorSource).toContain('open={setupOpen || !!editingId}')
    expect(leagueCoordinatorSource).not.toContain('open={setupOpen || !!editingId || records.length === 0}')
    expect(leagueCoordinatorSource).toContain('const { isMobile, isTablet } = useViewportBreakpoints()')
    expect(leagueCoordinatorSource).toContain('const isCompactViewport = isMobile || isTablet')
    expect(leagueCoordinatorSource).toContain('const responsiveRegistryPanel = isCompactViewport')
    expect(leagueCoordinatorSource).toContain('const responsiveCommandCard = isCompactViewport ? { ...commandCard, ...compactCommandCardStyle } : commandCard')
    expect(leagueCoordinatorSource).toContain('const responsiveResultBookPanel = isCompactViewport')
    expect(leagueCoordinatorSource).toContain('style={responsiveRegistryPanel}')
    expect(leagueCoordinatorSource).toContain('style={responsiveResultBookPanel}')
    expect(styleBlock(leagueCoordinatorSource, 'mobileScrollablePanelStyle')).toContain("maxHeight: 'min(680px, 82vh)'")
    expect(styleBlock(leagueCoordinatorSource, 'mobileScrollablePanelStyle')).toContain("overflowY: 'auto'")
    expect(leagueCoordinatorSource).toContain('const responsiveOptionalSummary = isCompactViewport ? responsiveDetailsSummary : desktopHiddenSummaryStyle')
    expect(leagueCoordinatorSource).toContain('<details className="leagueCoordinatorDetailsSection" style={startChecklistDetailsStyle}>')
    expect(leagueCoordinatorSource).toContain('Readiness checklist')
    expect(leagueCoordinatorSource).toContain('Open setup, participants, results, and visibility checks.')
    expect(leagueCoordinatorSource).toContain('const primaryLeagueDeskItem = leagueDeskItems.find((item) => !item.complete) ?? leagueDeskItems[0]')
    expect(leagueCoordinatorSource).toContain('Show other season jobs.')
    expect(leagueCoordinatorSource).toContain('style={leagueDeskMoreDetailsStyle}')
    expect(leagueCoordinatorSource).toContain('<details className="leagueCoordinatorDetailsSection" id="shared-calendar" style={responsiveCommandCard} open={!isCompactViewport}>')
    expect(leagueCoordinatorSource).toContain('<details className="leagueCoordinatorDetailsSection" style={responsiveResultBookPanel} open={!isCompactViewport}>')
    expect(leagueCoordinatorSource).toContain('<details className="leagueCoordinatorDetailsSection" style={responsiveLeagueAwardPanel} open={!isCompactViewport}>')
    expect(appGlobalsSource).toContain('.leagueCoordinatorDetailsSection:not([open]) > :not(summary)')
    expect(leagueCoordinatorSource).toContain('Show season home')
    expect(leagueCoordinatorSource).toContain('Show books')
    expect(leagueCoordinatorSource).toContain('Show awards')
    expect(leagueCoordinatorSource).toContain('<LeagueSecondaryToolsGroup isMobile={isMobile}>')
    expect(leagueCoordinatorSource).toContain('Open public pages, result books, awards, and readiness.')
    expect(styleBlock(leagueCoordinatorSource, 'startChecklistDetailsStyle')).toContain('overflow: \'hidden\'')
    expect(styleBlock(leagueCoordinatorSource, 'leagueDeskMoreDetailsStyle')).toContain("gridColumn: '1 / -1'")
    expect(styleBlock(leagueCoordinatorSource, 'leagueDeskMoreDetailsStyle')).toContain('overflow: \'hidden\'')
    expect(styleBlock(leagueCoordinatorSource, 'leagueSecondaryToolsDetailsStyle')).toContain('overflow: \'hidden\'')
    expect(styleBlock(leagueCoordinatorSource, 'leagueSecondaryToolsBodyStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueCoordinatorSource, 'desktopHiddenSummaryStyle')).toContain("display: 'none'")
    expect(styleBlock(leagueCoordinatorSource, 'portalWatermarkStyle')).toContain('right: 0')
    expect(styleBlock(leagueCoordinatorSource, 'portalWatermarkStyle')).toContain("width: 'min(220px, 52vw)'")
    expect(styleBlock(leagueCoordinatorSource, 'portalWatermarkStyle')).not.toContain("right: '-72px'")

    expect(styleBlock(captainSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(captainSource, 'watermarkStyle')).toContain("width: 'min(280px, 58vw)'")
    expect(styleBlock(captainSource, 'watermarkStyle')).not.toContain("right: 'clamp(-92px")

    expect(playerDevelopmentSource).toContain('playerQuestionStripInline')
    expect(playerDevelopmentSource).toContain('playerQuestionStripDrawer')
    expect(playerDevelopmentSource).toContain('Open tennis moves for today')
    expect(playerDevelopmentSource).toContain('improveHubMoreActions')
    expect(playerDevelopmentSource).toContain('Open My Lab or build a tactic plan.')
    expect(playerDevelopmentSource).toContain('playerIdActionPlanMore')
    expect(playerDevelopmentSource).toContain('Show prove and use cues.')
    expect(playerDevelopmentSource).toContain('overviewDetailsDesktopStack')
    expect(playerDevelopmentSource).toContain('overviewDetailsMobileGroup')
    expect(playerDevelopmentSource).toContain('Open guide, dashboard, and saved work.')
    expect(playerDevelopmentSource).toContain('Build a tactic plan')
    expect(playerDevelopmentSource).not.toContain('Build a tactic board')
    expect(playerDevelopmentSource).toContain('run one rep, score one proof')
    expect(playerDevelopmentStyles).toContain('.playerQuestionStripDrawer')
    expect(playerDevelopmentStyles).toContain('.playerQuestionStripInline')
    expect(playerDevelopmentStyles).toContain('.overviewDetailsDesktopStack')
    expect(playerDevelopmentStyles).toContain('.overviewDetailsMobileGroup')
    expect(playerDevelopmentStyles).toContain('.overviewDetailsMobileGroupBody')
    expect(playerDevelopmentStyles).toContain('.improveHubSecondaryActions')
    expect(playerDevelopmentStyles).toContain('.improveHubMoreActions')
    expect(playerDevelopmentStyles).toContain('@media (max-width: 860px)')
    expect(playerDevelopmentStyles).toContain('.improveHubSecondaryActions {\n    display: none;\n  }')
    expect(playerDevelopmentStyles).toContain('.overviewDetailsDesktopStack {\n    display: none;\n  }')
    expect(playerDevelopmentStyles).toContain('.playerIdActionPlanGrid article:nth-child(n+2)')
    expect(playerDevelopmentStyles).toContain('.playerIdActionPlanMore')
    expect(playerDevelopmentStyles).toContain('.playerIdActionPlanActions :global(.button-secondary)')
    expect(playerDevelopmentStyles).toContain('width: calc(100% - 20px)')
    expect(playerDevelopmentStyles).toContain('display: none')
    expect(playerDevelopmentStyles).toContain('padding: 0 14px 14px')

    expect(matchupSource).toContain('const demoMatchupPreview = isMobile ? (')
    expect(matchupSource).toContain('null')
    expect(matchupSource).toContain('const matchupSupportDetails = isMobile ? (')
    expect(matchupSource).toContain('Prep path and player context.')
    expect(matchupSource).toContain('{matchupDataTrust}')
    expect(matchupSource).toContain('<DemoMatchupCard />')
    expect(matchupSource).toContain('Show help')
    expect(matchupSource).toContain("{!isMobile ? <div style={toolHeaderTextStyle}>{MATCHUP_STORY.proof.join(' - ')}</div> : null}")
    expect(matchupSource).toContain("{!isMobile ? <PlayerSuitePanel active=\"matchup\" playerLabel={profileLink?.linked_player_name || 'Player prep'} /> : null}")
    expect(matchupSource).toContain('{!isMobile ? <div style={selectionProgressTextStyle}>{selectionGuidance}</div> : null}')
    expect(matchupSource).toContain('dynamicControlsCard')
    expect(styleBlock(matchupSource, 'matchupMobileSupportStackStyle')).toContain('overflow: \'hidden\'')
    expect(matchupSource).toContain('const matchupDataTrust = (')
    expect(matchupSource).toContain('Check what powers this read.')
    expect(matchupSource).toContain('summaryOnly={isMobile}')
    expect(matchupSource).toContain("headline={isMobile ? 'Unlock Matchup.' : MATCHUP_STORY.upgradeHeadline}")
    expect(matchupSource).toContain("footnote={isMobile ? undefined : MATCHUP_STORY.upgradeFootnote}")
    expect(matchupSource).toContain("Choose two different players.")
    expect(matchupSource).toContain('Free preview: gap, form, and one watch item. Player unlocks the full read.')
    const buildFirstIndex = matchupSource.indexOf('<div style={emptyStateTitle}>Build the matchup first</div>')
    expect(buildFirstIndex).toBeGreaterThanOrEqual(0)
    expect(buildFirstIndex).toBeLessThan(matchupSource.indexOf('{demoMatchupPreview}', buildFirstIndex))
  })

  it('keeps TIQ league standings, schedules, and result books mobile-safe', () => {
    expect(tiqLeagueDetailSource).toContain('const teamStandingsScrollStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain('Start with the first match.')
    expect(tiqLeagueDetailSource).toContain('Shared calendar</GhostLink>')
    expect(tiqLeagueDetailSource).toContain('scheduleSubscribeHref')
    expect(tiqLeagueDetailSource).toContain('/api/calendar/tiq-league/${encodeURIComponent(league.id)}/calendar.ics')
    expect(tiqLeagueDetailSource).toContain('Subscribe calendar</GhostLink>')
    expect(tiqLeagueDetailSource).toContain('const emptyActionCardStyle: CSSProperties')
    expect(styleBlock(tiqLeagueDetailSource, 'teamStandingsScrollStyle')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(tiqLeagueDetailSource, 'teamStandingsTableStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'leagueHubPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'leagueHubHeaderCopyStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(tiqLeagueDetailSource, 'hubNavStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleCalendarGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleHeaderActionRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleHeaderActionRowStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'scheduleRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(tiqLeagueDetailSource, 'watermarkStyle')).toContain('right: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'watermarkStyle')).toContain("width: 'min(100%, 310px)'")
    expect(styleBlock(tiqLeagueDetailSource, 'watermarkStyle')).not.toContain("right: '-110px'")
    expect(styleBlock(tiqLeagueDetailSource, 'resultCueItemStyle')).toContain("'minmax(0, auto) minmax(0, 1fr)'")
    expect(styleBlock(tiqLeagueDetailSource, 'teamLineGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'leagueStatusPillStyle')).toContain("whiteSpace: 'normal'")
    expect(tiqLeagueDetailSource).not.toContain("'auto minmax(0, 1fr)'")
    expect(tiqLeagueDetailSource).not.toContain("'minmax(0, 1fr) auto'")
    expect(tiqLeagueDetailSource).not.toContain('No team match events have been logged for this league yet.')
  })
})
