import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const exploreSource = readFileSync(join(process.cwd(), 'app/explore/page.tsx'), 'utf8')
const exploreSearchSource = readFileSync(join(process.cwd(), 'app/explore/search/page.tsx'), 'utf8')
const rankingsSource = readFileSync(join(process.cwd(), 'app/rankings/page.tsx'), 'utf8')
const playersSource = readFileSync(join(process.cwd(), 'app/players/page.tsx'), 'utf8')
const playerDetailSource = readFileSync(join(process.cwd(), 'app/players/[id]/page.tsx'), 'utf8')
const teamsSource = readFileSync(join(process.cwd(), 'app/teams/page.tsx'), 'utf8')
const teamDetailSource = readFileSync(join(process.cwd(), 'app/teams/[team]/page.tsx'), 'utf8')
const leaguesSource = readFileSync(join(process.cwd(), 'app/leagues/page.tsx'), 'utf8')
const leagueDetailSource = readFileSync(join(process.cwd(), 'app/leagues/[league]/page.tsx'), 'utf8')
const exploreLeaguesSource = readFileSync(join(process.cwd(), 'app/explore/leagues/page.tsx'), 'utf8')
const ustaExploreLeagueDetailSource = readFileSync(join(process.cwd(), 'app/explore/leagues/usta/[league]/page.tsx'), 'utf8')
const tiqLeagueDetailSource = readFileSync(join(process.cwd(), 'app/explore/leagues/tiq/[league]/page.tsx'), 'utf8')

function styleBlock(source: string, styleName: string) {
  const start = source.indexOf(`const ${styleName}:`)
  expect(start).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

function functionBlock(source: string, functionName: string) {
  const start = source.indexOf(`const ${functionName} =`)
  expect(start).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

describe('Explore responsive surfaces', () => {
  it('keeps Explore action cards protected from narrow mobile overflow', () => {
    expect(exploreSource).toContain('const actionBody: CSSProperties')
    expect(exploreSource).toContain('const actionFooterRow: CSSProperties')
    expect(exploreSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(exploreSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(exploreSource).toContain("overflowWrap: 'anywhere'")
    expect(exploreSource).toContain("flexWrap: 'wrap'")
    expect(exploreSource).toContain('minWidth: 0')
  })

  it('keeps Explore Search grids and filter controls mobile-safe', () => {
    expect(exploreSearchSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(exploreSearchSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(exploreSearchSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(exploreSearchSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(exploreSearchSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(exploreSearchSource).toContain('function FilterSelect')
    expect(exploreSearchSource).toContain("style={{ display: 'grid', gap: 6, minWidth: 0 }}")
    expect(exploreSearchSource).toContain("style={{ ...buttonGhost, maxWidth: '100%', textAlign: 'center', overflowWrap: 'anywhere' }}")
    expect(styleBlock(exploreSearchSource, 'emptyStateStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'emptyTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'exampleSearchButtonStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(exploreSearchSource, 'resultBadgeWrapStyle')).toContain('minWidth: 0')
    expect(styleBlock(exploreSearchSource, 'filterJumpStyle')).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps Explore start-step markers shell-aware across themes', () => {
    expect(exploreSource).toContain('const startStepNumber: CSSProperties')
    expect(exploreSource).toContain("background: 'color-mix(in srgb, var(--brand-green) 22%, var(--shell-chip-bg) 78%)'")
    expect(exploreSource).toContain("color: 'var(--foreground-strong)'")
    expect(exploreSource).not.toContain("color: 'var(--text-dark)',\n  background: 'linear-gradient(135deg, var(--brand-green) 0%, #4ade80 100%)'")
  })

  it('keeps rankings compact cards single-column friendly on mobile', () => {
    expect(rankingsSource).toContain('dynamicLeaderboardActionGrid')
    expect(rankingsSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(rankingsSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(rankingsSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(rankingsSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(rankingsSource).toContain('const compactRankingCardStyle: CSSProperties')
    expect(rankingsSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 112px), 1fr))'")
    expect(rankingsSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 132px), 1fr))'")
    expect(rankingsSource).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(rankingsSource, 'heroContent')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'controlsGrid')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'podiumGrid')).toContain('minWidth: 0')
  })

  it('keeps rankings insight panels and table actions mobile-safe', () => {
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain("overscrollBehaviorX: 'contain'")
    expect(styleBlock(rankingsSource, 'tableWrap')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'dataTable')).toContain("minWidth: 'min(100%, 760px)'")
    expect(styleBlock(rankingsSource, 'rowActionStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(rankingsSource, 'rowActionPrimaryStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(rankingsSource, 'insightSummary')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(rankingsSource, 'signalListItem')).toContain("flexWrap: 'wrap'")
    expect(styleBlock(rankingsSource, 'distributionRow')).toContain("gridTemplateColumns: 'minmax(0, 72px) minmax(0, 1fr) minmax(0, 32px)'")
  })

  it('keeps public discovery empty states actionable and Data Assist aware', () => {
    expect(playersSource).toContain('Public discovery only shows reviewed player context')
    expect(playersSource).toContain('Reset filters')
    expect(playersSource).toContain('emptyStateActionRow')
    expect(playersSource).toContain('DATA_ASSIST_STORY.cta')

    expect(teamsSource).toContain('Public discovery only shows reviewed team context')
    expect(teamsSource).toContain('Reset team filters')
    expect(teamsSource).toContain('emptyActionRow')
    expect(teamsSource).toContain('DATA_ASSIST_STORY.cta')
  })

  it('keeps Players and Teams directory grids minmax-safe on mobile', () => {
    expect(playersSource).not.toContain("gridTemplateColumns: isTablet\n      ? '1fr'")
    expect(playersSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(playersSource).toMatch(/gridTemplateColumns: isTablet\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(playersSource).toContain("isSmallMobile ? 'minmax(0, 1fr)'")
    expect(styleBlock(playersSource, 'heroContent')).toContain('minWidth: 0')
    expect(styleBlock(playersSource, 'cardGrid')).toContain('minWidth: 0')

    expect(teamsSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(teamsSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(teamsSource).toContain('const filtersGrid = (isMobile: boolean): CSSProperties')
    expect(teamsSource).toContain('const cardsGrid = (isTablet: boolean, isMobile: boolean): CSSProperties')
    expect(teamsSource).toContain('minWidth: 0')
    expect(styleBlock(teamsSource, 'surfaceCard')).toContain("background: 'var(--shell-panel-bg)'")
  })

  it('keeps Teams directory readable in light mode with shell tokens', () => {
    expect(teamsSource).toContain('var(--background)')
    expect(teamsSource).toContain("color: 'var(--foreground)'")
    expect(teamsSource).toContain("background: 'var(--shell-panel-bg)'")
    expect(teamsSource).toContain("color: 'var(--foreground-strong)'")
    expect(teamsSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(teamsSource).toContain("colorScheme: 'normal'")
    expect(teamsSource).not.toContain("colorScheme: 'dark'")
  })

  it('keeps Leagues directory Data Assist centered and light-mode readable', () => {
    expect(leaguesSource).toContain('Browse uploaded league seasons.')
    expect(leaguesSource).toContain('reviewed Data Assist league groupings')
    expect(leaguesSource).toContain('DATA_ASSIST_STORY.cta')
    expect(leaguesSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(leaguesSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(leaguesSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(leaguesSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(leaguesSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(leaguesSource).toMatch(/gridTemplateColumns: isSmallMobile\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(styleBlock(leaguesSource, 'heroContent')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'summaryGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'filterGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'cardGrid')).toContain('minWidth: 0')
    expect(styleBlock(leaguesSource, 'leagueDetailGrid')).toContain('minWidth: 0')
    expect(leaguesSource).toContain("background: 'var(--shell-chip-bg)'")
    expect(leaguesSource).toContain("color: 'var(--foreground-strong)'")
    expect(leaguesSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(leaguesSource).toContain("colorScheme: 'normal'")
    expect(leaguesSource).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps league detail pages Data Assist aware and light-mode readable', () => {
    expect(leagueDetailSource).toContain('reviewed match rows')
    expect(leagueDetailSource).toContain('DATA_ASSIST_STORY.cta')
    expect(leagueDetailSource).toContain('Use reviewed Data Assist uploads')
    expect(leagueDetailSource).toContain('const standingsTableScrollStyle: CSSProperties')
    expect(leagueDetailSource).toContain("overscrollBehaviorX: 'contain'")
    expect(leagueDetailSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(leagueDetailSource).toContain("minWidth: 'min(100%, 620px)'")
    expect(leagueDetailSource).toContain("tableLayout: 'auto'")
    expect(styleBlock(leagueDetailSource, 'standingsTableHeaderCellStyle')).toContain("whiteSpace: 'normal'")
    expect(leagueDetailSource).toContain("background: 'var(--shell-panel-bg)'")
    expect(leagueDetailSource).toContain("background: 'var(--shell-chip-bg)'")
    expect(leagueDetailSource).toContain("color: 'var(--foreground-strong)'")
    expect(leagueDetailSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(leagueDetailSource).toContain("colorScheme: 'normal'")
    expect(leagueDetailSource).toContain("overflowWrap: 'anywhere'")
    expect(leagueDetailSource).toContain('const topPerformerGridStyle: CSSProperties')
    expect(leagueDetailSource).toContain('const standingsViewToggleRowStyle: CSSProperties')
    expect(styleBlock(leagueDetailSource, 'topPerformerGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(leagueDetailSource, 'standingsViewToggleRowStyle')).toContain("flexWrap: 'wrap'")
    expect(leagueDetailSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(leagueDetailSource).toContain("? 'minmax(0, 1fr)'")
    expect(leagueDetailSource).toContain("subtitle={subtitleParts.join(' | ')}")
    expect(leagueDetailSource).toContain("row.score ?? '-'")
    expect(leagueDetailSource).not.toContain("<Link href={teamHref} style={{ color: '#93c5fd'")
    expect(leagueDetailSource).not.toContain("row.score ?? '—'")
    expect(ustaExploreLeagueDetailSource).toContain("export { default } from '@/app/leagues/[league]/page'")
  })

  it('keeps team detail pages Data Assist aware and light-mode readable', () => {
    expect(teamDetailSource).toContain('reviewed scorecards')
    expect(teamDetailSource).toContain('No reviewed scorecards yet')
    expect(teamDetailSource).toContain('reviewed Data Assist scorecards')
    expect(teamDetailSource).toContain('DATA_ASSIST_STORY.cta')
    expect(teamDetailSource).not.toContain("gridTemplateColumns: isTablet ? '1fr'")
    expect(teamDetailSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(teamDetailSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(teamDetailSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(teamDetailSource).toMatch(/gridTemplateColumns: isSmallMobile\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(teamDetailSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(functionBlock(teamDetailSource, 'signalGridStyle')).toContain('minWidth: 0')
    expect(functionBlock(teamDetailSource, 'teamDiscoveryGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("overscrollBehaviorX: 'contain'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("scrollbarWidth: 'thin'")
    expect(styleBlock(teamDetailSource, 'tableWrap')).toContain("maxWidth: '100%'")
    expect(styleBlock(teamDetailSource, 'dataTable')).toContain("minWidth: 'min(100%, 620px)'")
    expect(styleBlock(teamDetailSource, 'tableCell')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(teamDetailSource, 'scoreCellStackStyle')).toContain('minWidth: 0')
    expect(styleBlock(teamDetailSource, 'scoreCellStackStyle')).toContain("maxWidth: '100%'")
    expect(teamDetailSource).not.toContain('minWidth: 112')
    expect(teamDetailSource).toContain("minWidth: 'min(100%, 420px)'")
    expect(teamDetailSource).toContain("background: 'var(--shell-panel-bg)'")
    expect(teamDetailSource).toContain("background: 'var(--shell-chip-bg)'")
    expect(teamDetailSource).toContain("color: 'var(--foreground-strong)'")
    expect(teamDetailSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(teamDetailSource).toContain("boxShadow: 'var(--shadow-soft)'")
  })

  it('keeps player detail analytics and match lists mobile-safe', () => {
    expect(playerDetailSource).not.toContain("gridTemplateColumns: isTablet\n      ? '1fr'")
    expect(playerDetailSource).not.toContain("gridTemplateColumns: isSmallMobile ? '1fr'")
    expect(playerDetailSource).not.toContain("gridTemplateColumns: isMobile ? '1fr'")
    expect(playerDetailSource).toMatch(/gridTemplateColumns: isTablet\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(playerDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(playerDetailSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(playerDetailSource).toContain('const comparisonMetricGridStyle: CSSProperties')
    expect(playerDetailSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 160px), 1fr))'")
    expect(playerDetailSource).toContain('const matchHistoryToolbarStyle: CSSProperties')
    expect(playerDetailSource).toContain("width: 'min(100%, 180px)'")
    expect(playerDetailSource).toContain('const rivalryRowStyle: CSSProperties')
    expect(playerDetailSource).toContain('const seasonTableWrapStyle: CSSProperties')
    expect(playerDetailSource).toContain('const ratingHistoryTableWrapStyle: CSSProperties')
    expect(playerDetailSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(styleBlock(playerDetailSource, 'tableWrap')).toContain('minWidth: 0')
    expect(styleBlock(playerDetailSource, 'dataTable')).toContain("minWidth: 'min(100%, 760px)'")
    expect(styleBlock(playerDetailSource, 'seasonTableStyle')).toContain("minWidth: 'min(100%, 560px)'")
    expect(styleBlock(playerDetailSource, 'scoreCellStackStyle')).toContain('minWidth: 0')
    expect(playerDetailSource).toContain("minWidth: 'min(100%, 162px)'")
    expect(playerDetailSource).not.toContain('minWidth: 560')
    expect(playerDetailSource).not.toContain('minWidth: 162')
    expect(playerDetailSource).not.toContain('minWidth: 112')
    expect(functionBlock(playerDetailSource, 'profileDiscoveryGridStyle')).toContain('minWidth: 0')
    expect(functionBlock(playerDetailSource, 'signalGridStyle')).toContain('minWidth: 0')
    expect(playerDetailSource).toContain('const nearbyPlayerRowStyle: CSSProperties')
    expect(playerDetailSource).toContain("overflowWrap: 'anywhere'")
  })

  it('keeps Explore Leagues empty lanes separated by source and workflow', () => {
    expect(exploreLeaguesSource).toContain("emptyKind=\"usta\"")
    expect(exploreLeaguesSource).toContain('USTA league lanes come from reviewed TennisLink exports')
    expect(exploreLeaguesSource).toContain('Search leagues')
    expect(exploreLeaguesSource).toContain("emptyKind=\"tiq-team\"")
    expect(exploreLeaguesSource).toContain('TIQ team leagues are coordinator-created seasons')
    expect(exploreLeaguesSource).toContain('Create team league')
    expect(exploreLeaguesSource).toContain("emptyKind=\"tiq-individual\"")
    expect(exploreLeaguesSource).toContain('TIQ individual leagues are coordinator-created player-vs-player seasons')
    expect(exploreLeaguesSource).toContain('Create individual league')
  })

  it('keeps TIQ league standings and team results theme-aware on mobile', () => {
    expect(tiqLeagueDetailSource).toContain('const teamStandingsScrollStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain("overscrollBehaviorX: 'contain'")
    expect(tiqLeagueDetailSource).toContain("WebkitOverflowScrolling: 'touch'")
    expect(tiqLeagueDetailSource).toContain("minWidth: 'min(100%, 560px)'")
    expect(tiqLeagueDetailSource).toContain("tableLayout: 'auto'")
    expect(styleBlock(tiqLeagueDetailSource, 'teamStandingsHeaderCellStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(tiqLeagueDetailSource, 'teamStandingsTeamNameCellStyle')).toContain('minWidth: 0')
    expect(tiqLeagueDetailSource).toContain("color: 'var(--foreground-strong)'")
    expect(tiqLeagueDetailSource).toContain("color: 'var(--shell-copy-muted)'")
    expect(tiqLeagueDetailSource).toContain("border: '1px solid var(--shell-panel-border)'")
    expect(tiqLeagueDetailSource).toContain("overflowWrap: 'anywhere'")
    expect(tiqLeagueDetailSource).toContain('const teamResultHeaderRowStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain('const teamLineGridStyle: CSSProperties')
    expect(tiqLeagueDetailSource).toContain('const teamLineHeaderStyle: CSSProperties')
    expect(styleBlock(tiqLeagueDetailSource, 'teamLineGridStyle')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'teamLineHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(tiqLeagueDetailSource).toContain("join(' | ')")
    expect(tiqLeagueDetailSource).not.toContain("color: '#94a3b8'")
    expect(tiqLeagueDetailSource).not.toContain("color: '#64748b'")
    expect(tiqLeagueDetailSource).not.toContain("color: '#cbd5e1'")
  })

  it('keeps TIQ league detail grids minmax-safe on mobile', () => {
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : '56px minmax(0, 1fr)'")
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : 'repeat(2, minmax(0, 1fr))'")
    expect(tiqLeagueDetailSource).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)' : isMobile ? 'repeat(2, minmax(0, 1fr))' : 'repeat(4, minmax(0, 1fr))'")
    expect(styleBlock(tiqLeagueDetailSource, 'pageWrap')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'heroGrid')).toContain('minWidth: 0')
    expect(styleBlock(tiqLeagueDetailSource, 'pillBase')).toContain("whiteSpace: 'normal'")
  })
})
