import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('homepage portal action alignment', () => {
  it('keeps Find, Team, League, and Full-Court homepage actions aligned with the persistent portal', () => {
    const homepage = readFileSync(join(process.cwd(), 'app/components/preview-homepage.tsx'), 'utf8')
    const portal = readFileSync(join(process.cwd(), 'app/components/portal-tool-bar.tsx'), 'utf8')

    for (const label of ['Find a player', 'Browse teams', 'Check standings', 'Check rankings']) {
      expect(homepage).toContain(label)
      expect(portal).toContain(label)
    }

    for (const label of ['Who can play', 'Plan practice', 'Build lineup', 'Send plan']) {
      expect(homepage).toContain(label)
      expect(portal).toContain(label)
    }

    for (const label of ['Shared calendar', 'Build tournament', 'Team book', 'Player book']) {
      expect(homepage).toContain(label)
      expect(portal).toContain(label)
    }

    expect(homepage).toContain("queue: ['Find a player', 'Browse teams', 'Check standings', 'Check rankings']")
    expect(homepage).toContain("{ href: '/explore/players', label: 'Find a player' }")
    expect(homepage).not.toContain("label: 'Player directory'")
    expect(homepage).not.toContain("queue: ['Find a player', 'Browse a team', 'Check standings', 'Upload a scorecard']")
    expect(homepage).not.toContain("title: 'Upload scorecard'")
    expect(homepage).toContain("href: '/captain/practice'")
    expect(homepage).toContain("queue: ['Who can play', 'Plan practice', 'Build lineup', 'Send plan']")
    expect(homepage).toContain('Captain includes Player features plus availability')
    expect(homepage).not.toContain('Captain includes Player plus availability')
    expect(homepage).toContain("href: '/league-coordinator/tournaments'")
    expect(homepage).toContain("queue: ['Shared calendar', 'Build tournament', 'Team book', 'Player book']")
    expect(homepage).toContain("queue: ['Build tournament', 'Open Team Hub', 'Track results', 'Open player book']")
    expect(homepage).toContain('Support every tennis role')
    expect(homepage).toContain('Support every tennis role.')
    expect(homepage).toContain('Every tennis role, supported.')
    expect(homepage).toContain('unlimited Tournament Desk runs open from one account')
    expect(homepage).toContain('unlimited Tournament Desk runs stay open from one account')
    expect(homepage).toContain('runs stay ready from one account')
    expect(homepage).toContain('See player context across connected tennis activity.')
    expect(homepage).toContain('Full-Court opens My Lab, Coach Hub, Team Hub, League Office, and unlimited Tournament Desk runs.')
    expect(homepage).toContain('Unlock Full-Court when one role no longer covers the tennis work.')
    expect(homepage).toContain('Full-Court plan')
    expect(homepage).not.toContain('Full-Court operation')
    expect(homepage).toContain('Compare Full-Court')
    expect(homepage).toContain('Compare paid plans')
    expect(homepage).not.toContain('full suite')
    expect(homepage).not.toContain('Open the full toolkit')
    expect(homepage).not.toContain('Use the complete TenAceIQ toolkit.')
    expect(homepage).not.toContain('complete TenAceIQ toolkit')
    expect(homepage).not.toContain('one connected tennis toolkit')
    expect(homepage).not.toContain('as one tennis operation')
    expect(homepage).not.toContain('one connected tennis operation')
    expect(homepage).not.toContain('one connected suite')
    expect(homepage).not.toContain('Championship suite')
    expect(homepage).not.toContain('Compare suite')
    expect(homepage).not.toContain('See paid workspaces')
    expect(homepage).not.toContain('Run the full court from one workspace.')
    expect(homepage).not.toContain('same workspace')
    expect(homepage).not.toContain('one workspace')
    expect(homepage).not.toContain('power your workspace')
    expect(homepage).toContain('Message the team from Team Hub.')
    expect(homepage).toContain('one coach toolkit')
    expect(homepage).toContain('power your tennis tools')
    expect(homepage).toContain("import { COACH_TACTICS_BOARD_HREF } from '@/lib/tactics-hrefs'")
    expect(homepage).toContain('href: COACH_TACTICS_BOARD_HREF')
    expect(homepage).not.toContain("href: '/tactics'")
    expect(homepage).not.toContain('The full tennis operation.')
    expect(homepage).not.toContain('Run the full tennis operation.')
    expect(homepage).not.toContain('Everything in the tiers above')
    expect(homepage).not.toContain('See player context across the full operation.')
    expect(homepage).not.toContain("title: 'Scout opponent'")
    expect(homepage).not.toContain("title: 'Check readiness'")
    expect(homepage).not.toContain("title: 'Send team brief'")
    expect(homepage).not.toContain("title: 'My leagues'")
    expect(homepage).not.toContain("title: 'Create tournament'")
    expect(homepage).toContain('Start with your tennis need')
    expect(homepage).toContain('Explore, improve, compete, or manage with less chaos.')
    expect(homepage).toContain('Start with the tennis map, then unlock the tools that save your week.')
    expect(homepage).toContain('when your tennis needs become personal, team-based, or league-wide.')
    expect(homepage).toContain('Search first, then choose whether the next need is personal prep, team decisions, or league operations.')
    expect(homepage).toContain('then open the right tool for the next problem in your week.')
    expect(homepage).toContain('when your game, team, players, league, or tournament needs more support.')
    expect(homepage).toContain('Unlock My Lab, Team Hub, or League Office')
    expect(homepage).not.toContain('when the job becomes personal, team-based, or league-wide.')
    expect(homepage).not.toContain('Search first, then choose whether the next job is personal prep, team decisions, or league operations.')
    expect(homepage).not.toContain('Start with the tennis map, then unlock the workspace that saves your week.')
    expect(homepage).not.toContain('Start with the tennis map, then unlock the home base that saves your week.')
    expect(homepage).not.toContain('then unlock the workspace that solves the next problem in your week.')
    expect(homepage).not.toContain('when the next tennis job needs one connected place.')
    expect(homepage).not.toContain('when the next tennis job needs a home base.')
    expect(homepage).not.toContain('when that workspace saves your week')
    expect(homepage).not.toContain('Paid tiers unlock private workflows')
    expect(homepage).toContain('title="Team Hub"')
    expect(homepage).toContain('title="League Office"')
    expect(homepage).toContain('League Office')
    expect(homepage).not.toContain('Four doors. One tennis day.')
    expect(homepage).not.toContain('Captain workspace')
    expect(homepage).not.toContain('League workspace')
    expect(homepage).not.toContain('Full-Court combines Player, Coach, Captain, League')
    expect(homepage).not.toContain('Open Coach\'')
    expect(homepage).not.toContain('Open Team\'')
    expect(portal).toContain('Message the team from Team Hub.')
    expect(portal).not.toContain('same workspace')
  })

  it('keeps legacy hero chips aligned when those components are reused', () => {
    const responsiveHero = readFileSync(join(process.cwd(), 'app/components/homepage-hero-responsive.tsx'), 'utf8')
    const animatedHero = readFileSync(join(process.cwd(), 'app/components/hero-animated.tsx'), 'utf8')

    for (const source of [responsiveHero, animatedHero]) {
      expect(source).toContain('Team Hub')
      expect(source).not.toContain('Captain workspace')
    }
  })
})
