import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const hubSource = readFileSync(join(process.cwd(), 'app/leagues-and-tournaments/page.tsx'), 'utf8')
const navigationSource = readFileSync(join(process.cwd(), 'lib/site-navigation.ts'), 'utf8')
const portalSource = readFileSync(join(process.cwd(), 'app/components/portal-tool-bar.tsx'), 'utf8')
const productStorySource = readFileSync(join(process.cwd(), 'lib/product-story.ts'), 'utf8')
const commandCenterSource = readFileSync(join(process.cwd(), 'app/components/public-command-center.tsx'), 'utf8')

describe('Leagues and tournaments hub', () => {
  it('gives the combined organizer nav item a real public hub', () => {
    expect(navigationSource).toContain("href: '/leagues-and-tournaments', label: 'Leagues & Tournaments'")
    expect(navigationSource).toContain('Organize seasons, events, players, teams, scores, and results.')
    expect(portalSource).toContain("route: '/leagues-and-tournaments'")
    expect(productStorySource).toContain("href: '/leagues-and-tournaments'")
    expect(commandCenterSource).toContain("href: '/leagues-and-tournaments'")
  })

  it('keeps organizer copy practical and role-specific', () => {
    expect(hubSource).toContain("import Link from 'next/link'")
    expect(hubSource).toContain("title: 'Leagues & Tournaments'")
    expect(hubSource).toContain('Run competition with less admin work.')
    expect(hubSource).toContain('Organizer quick path')
    expect(hubSource).toContain('What organizer need moves first?')
    expect(hubSource).toContain(
      'Pick the practical need, then open the organizer path that reduces schedule, player, score, or source chaos.',
    )
    expect(hubSource).not.toContain('What admin job needs to move first?')
    expect(hubSource).not.toContain('Pick the practical job, then open the organizer path')
    expect(hubSource).not.toContain('open the workspace that reduces schedule, player, score, or source chaos')
    expect(hubSource).toContain('organizerQuickPaths.map((path)')
    expect(hubSource).toContain('How do I organize schedules?')
    expect(hubSource).toContain('How do I manage players or teams?')
    expect(hubSource).toContain('How do I track scores?')
    expect(hubSource).toContain('How do I run the event desk?')
    expect(hubSource).toContain('What needs source review?')
    expect(hubSource).toContain('Open Schedule Setup')
    expect(hubSource).toContain('Open Results')
    expect(hubSource).toContain('Open Tournament Desk')
    expect(hubSource).toContain('Open Data Assist')
    expect(hubSource).toContain('data-organizer-path-job={path.job}')
    expect(hubSource).toContain('aria-label={`${path.cta}: ${path.question}`}')
    expect(hubSource).toContain("job: 'organize_schedules'")
    expect(hubSource).toContain("job: 'manage_players_teams'")
    expect(hubSource).toContain("job: 'track_scores'")
    expect(hubSource).toContain("job: 'run_event_desk'")
    expect(hubSource).toContain("job: 'review_source_data'")
    expect(hubSource).toContain("href: '/data-assist?intent=upload-source&context=Leagues%20and%20Tournaments%20quick%20path'")
    expect(hubSource).toContain('Organizer work path')
    expect(hubSource).toContain('Set up, schedule, score, publish.')
    expect(hubSource).toContain('organize schedules, manage players or teams, track scores, publish updates, and reduce admin work')
    expect(hubSource).toContain('Set up a league')
    expect(hubSource).toContain('How do I organize the season before players start asking where everything lives?')
    expect(hubSource).toContain('Set Up League')
    expect(hubSource).toContain('Set up a tournament')
    expect(hubSource).toContain('How do I manage entries, draws, courts, and event-day movement?')
    expect(hubSource).toContain('Set Up Tournament')
    expect(hubSource).toContain('Track scores')
    expect(hubSource).toContain('Where do scores go, and what needs review before standings move?')
    expect(hubSource).toContain('Track Scores')
    expect(hubSource).toContain('Publish updates')
    expect(hubSource).toContain('How do I give everyone one place to check schedules, results, and corrections?')
    expect(hubSource).toContain('Publish Updates')
    expect(hubSource).toContain("href: '/league-coordinator/results'")
    expect(hubSource).toContain('League Office')
    expect(hubSource).toContain('Tournament Desk')
    expect(hubSource).toContain('Data Assist')
  })

  it('keeps organizer quick paths tappable on mobile', () => {
    expect(hubSource).toContain('const organizerQuickPathStyle')
    expect(hubSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 340px), 1fr))'")
    expect(hubSource).toContain('const organizerQuickPathGridStyle')
    expect(hubSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 175px), 1fr))'")
    expect(hubSource).toContain('const organizerQuickPathCardStyle')
    expect(hubSource).toContain('minHeight: 104')
    expect(hubSource).toContain('const organizerQuickPathQuestionStyle')
    expect(hubSource).toContain("overflowWrap: 'anywhere'")
  })
})
