import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const hubSource = readFileSync(join(process.cwd(), 'app/leagues-and-tournaments/page.tsx'), 'utf8')
const navigationSource = readFileSync(join(process.cwd(), 'lib/site-navigation.ts'), 'utf8')
const portalSource = readFileSync(join(process.cwd(), 'app/components/portal-tool-bar.tsx'), 'utf8')
const productStorySource = readFileSync(join(process.cwd(), 'lib/product-story.ts'), 'utf8')
const commandCenterSource = readFileSync(join(process.cwd(), 'app/components/public-command-center.tsx'), 'utf8')
const globalsSource = readFileSync(join(process.cwd(), 'app/globals.css'), 'utf8')

describe('Leagues and tournaments hub', () => {
  it('gives the combined organizer nav item a real public hub', () => {
    expect(navigationSource).toContain("href: '/leagues-and-tournaments', label: 'Leagues & Tournaments'")
    expect(navigationSource).toContain('Organize seasons, events, players, teams, scores, and results.')
    expect(portalSource).toContain("route: '/leagues-and-tournaments'")
    expect(productStorySource).toContain("href: '/leagues-and-tournaments'")
    expect(commandCenterSource).toContain("href: '/leagues-and-tournaments'")
  })

  it('keeps organizer copy practical and role-specific', () => {
    expect(hubSource).toContain("import Link from 'next/link'")
    expect(hubSource).toContain("title: 'Leagues & Tournaments'")
    expect(hubSource).toContain('Run competition with less admin work.')
    expect(hubSource).toContain('Keep schedules, entries, scores, standings, draws, and updates in one competition home.')
    expect(hubSource).toContain('Search tools')
    expect(hubSource).toContain('searchCompact')
    expect(hubSource).toContain('showSearchResults={false}')
    expect(hubSource).toContain('showBoard={false}')
    expect(hubSource).toContain('Organizer quick path')
    expect(hubSource).toContain('What needs organizing first?')
    expect(hubSource).toContain('Open the tool for the job in front of you.')
    expect(hubSource).not.toContain(
      'Pick the tennis need in front of you, then open the path for schedules, players, scores, events, or source review.',
    )
    expect(hubSource).not.toContain('What admin job needs to move first?')
    expect(hubSource).not.toContain('What organizer need moves first?')
    expect(hubSource).not.toContain('Pick the practical job, then open the organizer path')
    expect(hubSource).not.toContain('open the workspace that reduces schedule, player, score, or source chaos')
    expect(hubSource).toContain('organizerQuickPaths.map((path)')
    expect(hubSource).toContain('className="organizerQuickPath"')
    expect(hubSource).toContain('className="organizerQuickPathGrid"')
    expect(hubSource).toContain('className="organizerQuickPathCard"')
    expect(hubSource).toContain('Schedule season')
    expect(hubSource).toContain('Manage teams')
    expect(hubSource).toContain('Track scores')
    expect(hubSource).toContain('Event desk')
    expect(hubSource).toContain('Review source data')
    expect(hubSource).not.toContain('Schedule the season')
    expect(hubSource).not.toContain('Manage players or teams')
    expect(hubSource).not.toContain('Run the event desk')
    expect(hubSource).toContain('Open setup')
    expect(hubSource).toContain('Open Results')
    expect(hubSource).toContain('Open Tournament Desk')
    expect(hubSource).toContain('Open Data Assist')
    expect(hubSource).toContain('data-organizer-path-job={path.job}')
    expect(hubSource).toContain('aria-label={`${path.cta}: ${path.question}`}')
    expect(hubSource).toContain("job: 'organize_schedules'")
    expect(hubSource).toContain("job: 'manage_players_teams'")
    expect(hubSource).toContain("job: 'track_scores'")
    expect(hubSource).toContain("job: 'run_event_desk'")
    expect(hubSource).toContain("job: 'review_source_data'")
    expect(hubSource).toContain("href: '/data-assist?intent=upload-source&context=Leagues%20and%20Tournaments%20quick%20path'")
    expect(hubSource).toContain('Organizer tools')
    expect(hubSource).toContain('className="organizerToolsSection"')
    expect(hubSource).toContain('className="organizerCommandBoard"')
    expect(hubSource).toContain('className="organizerCommandDeskText"')
    expect(hubSource).toContain('Open the desk, then move the season.')
    expect(hubSource).toContain('Use League Office, Tournament Desk, or Data Assist for setup, event day, scores, or updates.')
    expect(hubSource).toContain('Run the work behind play.')
    expect(hubSource).toContain('Set up competition, review scores, publish updates, and keep players pointed to one place.')
    expect(hubSource).toContain('OrganizerCommandStep')
    expect(hubSource).toContain('MetricTile')
    expect(hubSource).not.toContain('Organizer work path')
    expect(hubSource).not.toContain('What gets simpler')
    expect(hubSource).not.toContain('TiqActionCard')
    expect(hubSource).not.toContain('TiqWorkspacePreview')
    expect(hubSource).toContain('Set up a league')
    expect(hubSource).toContain('How do I organize the season before players start asking where everything lives?')
    expect(hubSource).toContain('Set Up League')
    expect(hubSource).toContain('Set up a tournament')
    expect(hubSource).toContain('How do I manage entries, draws, courts, and event-day movement?')
    expect(hubSource).toContain('Set Up Tournament')
    expect(hubSource).toContain('Track scores')
    expect(hubSource).toContain('Where do scores go, and what needs review before standings move?')
    expect(hubSource).toContain('Track Scores')
    expect(hubSource).toContain('Publish updates')
    expect(hubSource).toContain('How do I give everyone one place to check schedules, results, and corrections?')
    expect(hubSource).toContain('Publish Updates')
    expect(hubSource).toContain("href: '/league-coordinator/results'")
    expect(hubSource).toContain('League Office')
    expect(hubSource).toContain('Tournament Desk')
    expect(hubSource).toContain('Data Assist')
    expect(hubSource).toContain("location: 'leagues_tournaments_command'")
  })

  it('keeps organizer quick paths tappable on mobile', () => {
    expect(hubSource).toContain('const organizerQuickPathStyle')
    expect(hubSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 340px), 1fr))'")
    expect(hubSource).toContain('const organizerQuickPathGridStyle')
    expect(hubSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 128px), 1fr))'")
    expect(hubSource).toContain('const organizerQuickPathCardStyle')
    expect(hubSource).toContain('minHeight: 70')
    expect(globalsSource).toContain('.organizerQuickPathHeader > p')
    expect(globalsSource).toContain('display: none !important')
    expect(globalsSource).toContain('font-size: 19px !important')
    expect(globalsSource).toContain('min-height: 50px !important')
    expect(hubSource).toContain('const organizerDetailsSectionStyle')
    expect(hubSource).toContain("display: 'block'")
    expect(hubSource).toContain('className="organizerDetailsSection"')
    expect(hubSource).toContain('className="organizerDetailsBody"')
    expect(hubSource).toContain('const organizerQuickPathQuestionStyle')
    expect(hubSource).toContain("overflowWrap: 'anywhere'")
    expect(hubSource).toContain('className="organizerQuickPathQuestion"')
    expect(hubSource).toContain('className="organizerQuickPathCta"')
  })
})
