import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pageSource = readFileSync(join(process.cwd(), 'app/level-up/page.tsx'), 'utf8')
const contentSource = readFileSync(join(process.cwd(), 'app/level-up/level-up-page-content.tsx'), 'utf8')
const identityPageSource = readFileSync(join(process.cwd(), 'app/level-up/[identity]/page.tsx'), 'utf8')
const myLabSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const navSource = readFileSync(join(process.cwd(), 'lib/site-navigation.ts'), 'utf8')
const sitemapSource = readFileSync(join(process.cwd(), 'app/sitemap.ts'), 'utf8')
const trainingMenusSource = readFileSync(join(process.cwd(), 'lib/player-training-menus.ts'), 'utf8')
const developmentSystemSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development-system.tsx'), 'utf8')
const liveWorkbenchSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-live-workbench.tsx'), 'utf8')
const developmentStylesSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development.module.css'), 'utf8')

describe('Level Up page', () => {
  it('creates a direct phone-first Level Up destination from the shared drill engine', () => {
    expect(existsSync(join(process.cwd(), 'app/level-up/page.tsx'))).toBe(true)
    expect(pageSource).toContain('LevelUpPageContent')
    expect(contentSource).toContain('PlayerLiveWorkbench')
    expect(contentSource).toContain('getPlayerTrainingMenus')
    expect(contentSource).toContain('Start now')
    expect(contentSource).toContain('/mylab#coach-assignments')
    expect(contentSource).toContain('Choose development identity')
  })

  it('surfaces Level Up from My Lab, navigation, and the sitemap', () => {
    expect(myLabSource).toContain('Level Up now')
    expect(myLabSource).toContain('href="/level-up"')
    expect(navSource).toContain("{ href: '/level-up', label: 'Level Up' }")
    expect(sitemapSource).toContain("{ path: '/level-up'")
  })

  it('keeps workbook and route drill menus in one shared source', () => {
    expect(trainingMenusSource).toContain('Serve target reps')
    expect(trainingMenusSource).toContain('First-strike conditioning')
    expect(developmentSystemSource).toContain("from '@/lib/player-training-menus'")
    expect(developmentSystemSource).not.toContain('function getPlayerTrainingMenus')
  })

  it('gives every development identity a direct Level Up URL', () => {
    expect(existsSync(join(process.cwd(), 'app/level-up/[identity]/page.tsx'))).toBe(true)
    expect(identityPageSource).toContain('generateStaticParams')
    expect(identityPageSource).toContain('PLAYER_DEVELOPMENT_IDENTITIES')
    expect(identityPageSource).toContain('LevelUpPageContent')
    expect(contentSource).toContain('href={`/level-up/${item.slug}`}')
    expect(sitemapSource).toContain('`/level-up/${identity.slug}`')
  })

  it('hands coach assignments straight into the on-court Level Up flow', () => {
    expect(myLabSource).toContain('buildAssignmentLevelUpHref')
    expect(myLabSource).toContain("coach: '1'")
    expect(myLabSource).toContain('inferAssignmentLevelUpWorkType')
    expect(myLabSource).toContain('workType: inferAssignmentLevelUpWorkType')
    expect(myLabSource).toContain('Start Level Up')
    expect(myLabSource).toContain('/level-up/${encodeURIComponent(identitySlug)}')
    expect(liveWorkbenchSource).toContain('useSearchParams')
    expect(liveWorkbenchSource).toContain('Coach challenge loaded')
    expect(liveWorkbenchSource).toContain('normalizeAssignmentWorkType')
    expect(liveWorkbenchSource).toContain('useState(hasCoachAssignment ? `${initialFocusId}-coach-${initialWorkType}` :')
    expect(liveWorkbenchSource).toContain('setActiveDrillId(`${nextFocusId}-coach-${nextWorkType}`)')
    expect(liveWorkbenchSource).toContain('assignmentId: assignmentId || undefined')
    expect(liveWorkbenchSource).toContain('Synced. Coach assignment marked complete for review.')
  })

  it('keeps the phone Level Up flow compact for on-court use', () => {
    expect(liveWorkbenchSource).toContain('liveCompactSummary')
    expect(liveWorkbenchSource).toContain('type EditingStep')
    expect(liveWorkbenchSource).toContain('setEditingStep')
    expect(liveWorkbenchSource).toContain('data-collapsed={editingStep !==')
    expect(liveWorkbenchSource).toContain('data-flow-state={editingStep ??')
    expect(liveWorkbenchSource).toContain('liveDrillSteps')
    expect(liveWorkbenchSource).toContain('getDrillActionSteps')
    expect(liveWorkbenchSource).toContain('shortenDrillStep')
    expect(liveWorkbenchSource).toContain('scrollIntoView')
    expect(liveWorkbenchSource).toContain('data-assignment={hasCoachAssignment')
    expect(liveWorkbenchSource).toContain('id="level-up-activity"')
    expect(liveWorkbenchSource).toContain('data-timer-state={timerState}')
    expect(liveWorkbenchSource).toContain('function goToScore')
    expect(liveWorkbenchSource).toContain('onDone={goToScore}')
    expect(liveWorkbenchSource).toContain('data-scoring={scoringDrillId === activeDrill.id')
    expect(liveWorkbenchSource).toContain('Score now')
    expect(liveWorkbenchSource).toContain('data-action="done"')
    expect(liveWorkbenchSource).toContain('savedRef.current?.scrollIntoView')
    expect(liveWorkbenchSource).toContain('function repeatActivity')
    expect(liveWorkbenchSource).toContain('function pickNewFocus')
    expect(liveWorkbenchSource).toContain('Save ${draft.rating}/5')
    expect(liveWorkbenchSource).toContain('New focus')
    expect(liveWorkbenchSource).toContain('Score and save.')
    expect(developmentStylesSource).toContain('.liveCompactSummary')
    expect(developmentStylesSource).toContain('.liveCompactEdits')
    expect(developmentStylesSource).toContain('.liveDrillSteps')
    expect(developmentStylesSource).toContain(".levelUpShell:has(.liveWorkbench[data-assignment='true']) .levelUpRouteHeader")
    expect(developmentStylesSource).toContain(".liveWorkbench[data-assignment='true'] .liveCompactSummary")
    expect(developmentStylesSource).toContain('scroll-margin-top: 12px')
    expect(developmentStylesSource).toContain(".liveTimerPanel[data-timer-state='running']")
    expect(developmentStylesSource).toContain(".liveActionCard:has(.liveTimerPanel[data-timer-state='running']) .liveDrillSteps")
    expect(developmentStylesSource).toContain(".liveTimerActions button[data-action='done']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-scoring='true'] .liveActionCard")
    expect(developmentStylesSource).toContain(".liveWorkbench:has(.liveWorkbenchBody[data-scoring='true']) .liveCompactSummary")
    expect(developmentStylesSource).toContain('.liveScoreGuide')
    expect(developmentStylesSource).toContain('.liveSavedActions')
    expect(developmentStylesSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(developmentStylesSource).toContain(".liveStepPanel[data-collapsed='true']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='focus']")
    expect(developmentStylesSource).toContain('.liveCoachLoop,')
    expect(developmentStylesSource).toContain('.liveAccessPanel,')
    expect(developmentStylesSource).toContain('.levelUpRouteActions,')
    expect(developmentStylesSource).toContain('.liveAssignmentBanner,')
    expect(developmentStylesSource).toContain('.liveProgressPanel,')
    expect(developmentStylesSource).toContain('display: none;')
    expect(developmentStylesSource).toContain('overflow-x: auto')
    expect(developmentStylesSource).toContain('min-height: 78px')
  })
})
