import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const migrationPath = join(process.cwd(), 'supabase/migrations/20260612000400_create_level_up_custom_quests.sql')
const migrationSource = readFileSync(migrationPath, 'utf8')
const completionsMigrationPath = join(process.cwd(), 'supabase/migrations/20260613000100_create_level_up_custom_quest_completions.sql')
const completionsMigrationSource = readFileSync(completionsMigrationPath, 'utf8')
const clientSource = readFileSync(join(process.cwd(), 'app/level-up/quest-builder-client.tsx'), 'utf8')
const workbenchSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-live-workbench.tsx'), 'utf8')
const typeSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-types.ts'), 'utf8')

describe('Level Up custom quest persistence', () => {
  it('stores custom quests in a private user-owned Supabase table', () => {
    expect(existsSync(migrationPath)).toBe(true)
    expect(migrationSource).toContain('create table if not exists public.level_up_custom_quests')
    expect(migrationSource).toContain('user_id uuid not null references auth.users(id) on delete cascade')
    expect(migrationSource).toContain('alter table public.level_up_custom_quests enable row level security')
    expect(migrationSource).toContain('using (auth.uid() = user_id)')
    expect(migrationSource).toContain('with check (auth.uid() = user_id)')
    expect(migrationSource).toContain('level_up_custom_quests_user_active_idx')
    expect(migrationSource).toContain('on public.level_up_custom_quests (user_id, active, updated_at desc)')
    expect(migrationSource).toContain('level_up_custom_quests_user_category_idx')
    expect(migrationSource).toContain("category in ('tennis-skill', 'fitness', 'nutrition-hydration', 'mindset', 'recovery', 'match-prep')")
    expect(migrationSource).toContain("cadence in ('daily', 'weekly', 'practice-day', 'match-day')")
  })

  it('loads and writes saved quests through the authenticated client path', () => {
    expect(clientSource).toContain("import { useAuth } from '@/app/components/auth-provider'")
    expect(clientSource).toContain("from('level_up_custom_quests')")
    expect(clientSource).toContain("const { authResolved, userId, role, entitlements } = useAuth()")
    expect(clientSource).toContain(".eq('user_id', userId)")
    expect(clientSource).toContain('linked_card_id')
    expect(clientSource).toContain('Sign in to save')
    expect(clientSource).toContain('Open linked drill')
    expect(clientSource).toContain('Private to your account')
    expect(typeSource).toContain('export type LevelUpCustomQuest')
    expect(typeSource).toContain('linkedCardId: string | null')
  })

  it('records private custom quest completions with same-owner RLS checks', () => {
    expect(existsSync(completionsMigrationPath)).toBe(true)
    expect(completionsMigrationSource).toContain('create table if not exists public.level_up_custom_quest_completions')
    expect(completionsMigrationSource).toContain('custom_quest_id uuid not null references public.level_up_custom_quests(id) on delete cascade')
    expect(completionsMigrationSource).toContain('constraint level_up_custom_quest_completions_unique_day unique (custom_quest_id, completed_on)')
    expect(completionsMigrationSource).toContain('alter table public.level_up_custom_quest_completions enable row level security')
    expect(completionsMigrationSource).toContain('auth.uid() = user_id')
    expect(completionsMigrationSource).toContain('quest.id = custom_quest_id')
    expect(completionsMigrationSource).toContain('quest.user_id = auth.uid()')
    expect(completionsMigrationSource).toContain('level_up_custom_quest_completions_user_completed_idx')
    expect(completionsMigrationSource).toContain('level_up_custom_quest_completions_quest_completed_idx')
  })

  it('links saved quests into drill completion and refreshable XP progress', () => {
    expect(clientSource).toContain('LevelUpCustomQuestCompletion')
    expect(clientSource).toContain("from('level_up_custom_quest_completions')")
    expect(clientSource).toContain('buildCustomQuestProgress')
    expect(clientSource).toContain('buildTodayQuestStack')
    expect(clientSource).toContain('buildQuestCoachInsights')
    expect(clientSource).toContain('QUEST_PACKS')
    expect(clientSource).toContain('QUEST_GOAL_OPTIONS')
    expect(clientSource).toContain('applyGoalOption')
    expect(clientSource).toContain('buildGoalWeekPlan')
    expect(clientSource).toContain('buildDraftFromPackItem')
    expect(clientSource).toContain('createQuestPack')
    expect(clientSource).toContain('buildWeeklyQuestReview')
    expect(clientSource).toContain('buildProductAccessState')
    expect(clientSource).toContain('canUseSavedQuestFeatures')
    expect(clientSource).toContain('Goal wizard')
    expect(clientSource).toContain('Recommended path')
    expect(clientSource).toContain('7-day starter plan')
    expect(clientSource).toContain('Pressure rep')
    expect(clientSource).toContain('Load starter quest')
    expect(clientSource).toContain('Goal packs')
    expect(clientSource).toContain('Quest history')
    expect(clientSource).toContain('Weekly review')
    expect(clientSource).toContain('Coach assignable')
    expect(clientSource).toContain('Team pack')
    expect(clientSource).toContain('Today&apos;s stack')
    expect(clientSource).toContain('Best next quests')
    expect(clientSource).toContain('Quest Coach')
    expect(clientSource).toContain('This week&apos;s read')
    expect(clientSource).toContain('getIdentityQuestCategories')
    expect(clientSource).toContain('levelUpQuestProgressStrip')
    expect(clientSource).toContain('levelUpQuestTodayStack')
    expect(clientSource).toContain('levelUpQuestCoachPanel')
    expect(clientSource).toContain('&quest=${quest.id}#level-up-flow')
    expect(workbenchSource).toContain("searchParams.get('quest')")
    expect(workbenchSource).toContain('syncCustomQuestCompletion')
    expect(workbenchSource).toContain("from('level_up_custom_quest_completions')")
    expect(workbenchSource).toContain("onConflict: 'custom_quest_id,completed_on'")
    expect(typeSource).toContain('export type LevelUpCustomQuestCompletion')
  })
})
