import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const coachSource = readFileSync(join(process.cwd(), 'app/coach/page.tsx'), 'utf8')
const captainSource = readFileSync(join(process.cwd(), 'app/captain/page.tsx'), 'utf8')
const captainChallengeSource = readFileSync(join(process.cwd(), 'lib/captain-level-up-challenge.ts'), 'utf8')
const captainPracticeSource = readFileSync(join(process.cwd(), 'app/captain/practice/page.tsx'), 'utf8')
const captainWeeklyBriefSource = readFileSync(join(process.cwd(), 'app/captain/weekly-brief/page.tsx'), 'utf8')
const captainMessagingSource = readFileSync(join(process.cwd(), 'app/captain/messaging/page.tsx'), 'utf8')
const playerLevelUpSessionsApiSource = readFileSync(join(process.cwd(), 'app/api/player/level-up-sessions/route.ts'), 'utf8')
const coachAssignmentsApiSource = readFileSync(join(process.cwd(), 'app/api/coach/assignments/route.ts'), 'utf8')

describe('Level Up handoff surfaces', () => {
  it('turns Level Up pack links into Coach Hub assignment context', () => {
    expect(coachSource).toContain('useSearchParams')
    expect(coachSource).toContain('COACH_LEVEL_UP_HANDOFF_PACKS')
    expect(coachSource).toContain("searchParams.get('levelUpPack')")
    expect(coachSource).toContain('Level Up handoff')
    expect(coachSource).toContain('Coach assignment bridge')
    expect(coachSource).toContain('Load into assignment form')
    expect(coachSource).toContain('Save draft assignment')
    expect(coachSource).toContain('buildCoachLevelUpHandoffPack')
    expect(coachSource).toContain('buildCoachLevelUpAssignmentPack')
    expect(coachSource).toContain('setAssignmentTitle(pack.assignmentTitle)')
    expect(coachSource).toContain('setAssignmentLevelUpPackId(pack.id)')
    expect(coachSource).toContain('setAssignmentLevelUpCardId')
    expect(coachSource).toContain("consumeCoachHandoffParams(['levelUpPack', 'card'], '#coach-lesson-frame')")
    expect(coachSource).toContain("consumeCoachHandoffParams(['levelUpPack', 'card'])")
    expect(coachSource).toContain('levelUpPack')
    expect(coachSource).toContain("'level-up-pack-handoff'")
    expect(coachSource).toContain("saveCoachAssignment('draft', pack)")
    expect(coachSource).toContain('Draft assignments')
    expect(coachSource).toContain('loadDraftAssignment')
    expect(coachSource).toContain("updateAssignmentStatus(assignment, 'assigned')")
    expect(coachSource).toContain("updateAssignmentStatus(assignment, 'archived')")
    expect(coachSource).toContain('Pack progress')
    expect(coachSource).toContain('rhythm-builder')
    expect(coachSource).toContain('consistency-builder')
    expect(coachSource).toContain('point-start-routine')
    expect(coachSource).toContain('doubles-readiness')
    expect(coachSource).toContain('match-day-routine')
  })

  it('updates assigned Level Up packs card-by-card before closing the assignment', () => {
    expect(playerLevelUpSessionsApiSource).toContain('buildPlayerAssignmentPackCardCompletion')
    expect(playerLevelUpSessionsApiSource).toContain('cardId: payload.focus_id')
    expect(playerLevelUpSessionsApiSource).toContain("status: packCompletion.complete ? 'completed' : 'assigned'")
    expect(coachAssignmentsApiSource).toContain("status === 'draft' || status === 'assigned' || status === 'completed' || status === 'archived'")
  })

  it('turns Level Up challenge links into Captain team challenge context', () => {
    expect(captainSource).toContain('useSearchParams')
    expect(captainChallengeSource).toContain('CAPTAIN_LEVEL_UP_CHALLENGES')
    expect(captainSource).toContain("searchParams.get('levelUpChallenge')")
    expect(captainSource).toContain('Level Up team challenge')
    expect(captainSource).toContain('Team challenge mode')
    expect(captainChallengeSource).toContain('Aggregate completion only')
    expect(captainChallengeSource).toContain('Private player proof and notes stay with each player.')
    expect(captainChallengeSource).toContain('rhythm-builder')
    expect(captainChallengeSource).toContain('consistency-builder')
    expect(captainChallengeSource).toContain('point-start-routine')
    expect(captainSource).toContain('appendLevelUpChallengeHref')
    expect(captainSource).toContain("incomingLevelUpTeamChallenge && canConsumeLevelUpHandoff ? ['levelUpChallenge', 'card'] : []")
    expect(captainSource).toContain('const canConsumeLevelUpHandoff = authResolved && premiumEnabled')
    expect(captainSource).toContain('returnToHref={captainEntryHref}')
    expect(captainSource).toContain("getPlanUnlockHref('captain', returnToHref)")
    expect(captainSource).toContain('ctaHref={captainUnlockHref}')
    expect(captainSource).toContain('Plan practice')
    expect(captainSource).toContain('Add to weekly brief')
    expect(captainPracticeSource).toContain("['levelUpChallenge', 'card']")
    expect(captainPracticeSource).toContain('Practice focus is filled in.')
    expect(captainWeeklyBriefSource).toContain("['levelUpChallenge', 'card']")
    expect(captainWeeklyBriefSource).toContain('Level Up challenge loaded into weekly brief')
  })

  it('carries the selected match-week challenge into the brief and team message', () => {
    expect(captainWeeklyBriefSource).toContain('buildCaptainWeekChallengeHistoryHref')
    expect(captainWeeklyBriefSource).toContain("This week's team challenge")
    expect(captainWeeklyBriefSource).toContain('Open Team Room')
    expect(captainWeeklyBriefSource).toContain('buildCaptainLevelUpCardHref')
    expect(captainMessagingSource).toContain('buildCaptainWeekChallengeHistoryHref')
    expect(captainMessagingSource).toContain('appendCaptainWeekChallengeToMessage')
    expect(captainMessagingSource).toContain('Included in message')
    expect(captainMessagingSource).toContain('Open Team Room')
  })
})
