import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pageSource = readFileSync(join(process.cwd(), 'app/level-up/page.tsx'), 'utf8')
const contentSource = readFileSync(join(process.cwd(), 'app/level-up/level-up-page-content.tsx'), 'utf8')
const identityPageSource = readFileSync(join(process.cwd(), 'app/level-up/[identity]/page.tsx'), 'utf8')
const myLabSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const navSource = readFileSync(join(process.cwd(), 'lib/site-navigation.ts'), 'utf8')
const sitemapSource = readFileSync(join(process.cwd(), 'app/sitemap.ts'), 'utf8')
const trainingMenusSource = readFileSync(join(process.cwd(), 'lib/player-training-menus.ts'), 'utf8')
const levelUpTypesSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-types.ts'), 'utf8')
const levelUpCardsSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-cards.ts'), 'utf8')
const levelUpModulesSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-modules.ts'), 'utf8')
const levelUpProfilesSource = readFileSync(join(process.cwd(), 'lib/level-up/identity-recommendations.ts'), 'utf8')
const levelUpRecommendationsSource = readFileSync(join(process.cwd(), 'lib/level-up/recommendations.ts'), 'utf8')
const playerDevelopmentPortalSource = readFileSync(join(process.cwd(), 'app/player-development/_components/level-up-portal.tsx'), 'utf8')
const developmentSystemSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development-system.tsx'), 'utf8')
const liveWorkbenchSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-live-workbench.tsx'), 'utf8')
const developmentStylesSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development.module.css'), 'utf8')

describe('Level Up page', () => {
  it('creates a direct phone-first Level Up destination from the shared drill engine', () => {
    expect(existsSync(join(process.cwd(), 'app/level-up/page.tsx'))).toBe(true)
    expect(pageSource).toContain('LevelUpPageContent')
    expect(contentSource).toContain('PlayerLiveWorkbench')
    expect(contentSource).toContain('getPlayerTrainingMenus')
    expect(contentSource).toContain('Start now')
    expect(contentSource).toContain('/mylab#coach-assignments')
    expect(contentSource).toContain('Choose development identity')
  })

  it('adds a Level Up portal library model for coach assignments, favorites, and recommendations', () => {
    expect(existsSync(join(process.cwd(), 'lib/level-up/level-up-types.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/level-up-cards.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/level-up-modules.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/identity-recommendations.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/recommendations.ts'))).toBe(true)
    expect(levelUpTypesSource).toContain('export type LevelUpCard')
    expect(levelUpTypesSource).toContain('export type LevelUpAssignment')
    expect(levelUpTypesSource).toContain('export type LevelUpFavorite')
    expect(levelUpTypesSource).toContain('export type LevelUpCompletion')
    expect(levelUpCardsSource).toContain('export const LEVEL_UP_CARDS')
    expect(levelUpCardsSource).toContain('export const LEVEL_UP_MODULES')
    expect(levelUpCardsSource).toContain('assignable: true')
    expect(levelUpCardsSource).toContain('favoriteable: true')
    expect(levelUpCardsSource).toContain('Movement Engine')
    expect(levelUpCardsSource).toContain('Serve Pressure Reset')
    expect(levelUpCardsSource).toContain('getRecommendedLevelUpCards')
    expect(levelUpCardsSource).toContain('cardContentEnhancements')
    expect(levelUpCardsSource).toContain('Recovered before watching 0-5')
    expect(levelUpCardsSource).toContain('Serve target clarity 0-5')
    expect(levelUpCardsSource).toContain('Partner first-move clarity 0-5')
    expect(levelUpCardsSource).toContain('Wall rep quality and recovery 0-5')
    expect(levelUpCardsSource).toContain('Arrived balanced and recovered 0-5')
    expect(levelUpCardsSource).toContain('Decision quality under fatigue 0-5')
    expect(levelUpCardsSource).toContain('Balanced attack decision 0-5')
    expect(levelUpCardsSource).toContain('Finish, recover, then read the next ball.')
    expect(levelUpCardsSource).toContain('Set the cone, line, or shadow lane.')
    expect(levelUpCardsSource).toContain('You finish with movement that connects contact, recovery, and the next ready position.')
    expect(levelUpCardsSource).toContain('Walk the pattern first')
    expect(levelUpCardsSource).toContain('buildTennisGoal')
    expect(levelUpCardsSource).toContain('buildSafetyNote')
    expect(levelUpModulesSource).toContain('recovery-after-contact')
    expect(levelUpModulesSource).toContain('conditioning-under-fatigue')
    expect(levelUpProfilesSource).toContain('IDENTITY_LEVEL_UP_PROFILES')
    expect(levelUpProfilesSource).toContain('relentless-competitor-4-0')
    expect(levelUpRecommendationsSource).toContain('scoreLevelUpCard')
    expect(levelUpRecommendationsSource).toContain('recommendLevelUpCards')
    expect(contentSource).toContain('LEVEL_UP_CARDS')
    expect(contentSource).toContain('LEVEL_UP_MODULES')
    expect(contentSource).toContain('getRecommendedLevelUpCards')
    expect(contentSource).toContain('levelUpPortal')
    expect(contentSource).toContain('Coach Assigned')
    expect(contentSource).toContain('Favorites')
    expect(contentSource).toContain('Recommended for Your Player Identity')
    expect(contentSource).toContain('Your tennis training hub.')
    expect(contentSource).toContain('LevelUpTrainingCard')
    expect(contentSource).toContain('quickStartCards')
    expect(contentSource).toContain('Proof: {card.proof}')
    expect(contentSource).toContain('formatCardList')
    expect(developmentStylesSource).toContain('.levelUpPortal')
    expect(developmentStylesSource).toContain('.levelUpCardRail')
    expect(developmentStylesSource).toContain('.levelUpLibraryGrid')
  })

  it('creates the preferred player-development Level Up portal route with mock v1 tooling', () => {
    expect(existsSync(join(process.cwd(), 'app/player-development/[identity]/level-up/page.tsx'))).toBe(true)
    expect(playerDevelopmentPortalSource).toContain('LevelUpPortal')
    expect(playerDevelopmentPortalSource).toContain('Today&apos;s Mission')
    expect(playerDevelopmentPortalSource).toContain('Coach Assigned')
    expect(playerDevelopmentPortalSource).toContain('Recommended for Your Player Identity')
    expect(playerDevelopmentPortalSource).toContain('Quick Wins Under 10 Minutes')
    expect(playerDevelopmentPortalSource).toContain('Performance Upgrade')
    expect(playerDevelopmentPortalSource).toContain('Favorites')
    expect(playerDevelopmentPortalSource).toContain('tiq-level-up-favorites')
    expect(playerDevelopmentPortalSource).toContain('tiq-level-up-completions')
    expect(playerDevelopmentPortalSource).not.toContain('Coach Assignment Mode')
    expect(playerDevelopmentPortalSource).toContain('LevelUpStartList')
    expect(playerDevelopmentPortalSource).toContain('Start here')
    expect(playerDevelopmentPortalSource).toContain('Log proof')
    expect(playerDevelopmentPortalSource).toContain('Advanced filters')
    expect(playerDevelopmentPortalSource).toContain('levelUpFilterControls')
    expect(playerDevelopmentPortalSource).toContain('startListRef')
    expect(playerDevelopmentPortalSource).toContain('scrollToStartList')
    expect(playerDevelopmentPortalSource).toContain('level-up-start-here')
    expect(playerDevelopmentPortalSource).toContain('buildCardStartHref')
    expect(playerDevelopmentPortalSource).toContain('getCardWorkType')
    expect(playerDevelopmentPortalSource).toContain('card: card.id')
    expect(playerDevelopmentPortalSource).toContain('levelUpRailSummary')
    expect(playerDevelopmentPortalSource).toContain('defaultOpen')
    expect(playerDevelopmentPortalSource.indexOf('LevelUpStartList')).toBeLessThan(playerDevelopmentPortalSource.indexOf('LevelUpFilters'))
    expect(playerDevelopmentPortalSource).toContain('Move well before adding speed.')
    expect(playerDevelopmentPortalSource).toContain('showAllCards')
    expect(playerDevelopmentPortalSource).toContain('visibleAllCards')
    expect(playerDevelopmentPortalSource).toContain('Show all {filteredCards.length} cards')
    expect(playerDevelopmentPortalSource).toContain('countActiveFilters')
    expect(playerDevelopmentPortalSource).toContain('intentPresets')
    expect(playerDevelopmentPortalSource).toContain('LevelUpIntentPresets')
    expect(playerDevelopmentPortalSource).toContain('LevelUpSessionDock')
    expect(playerDevelopmentPortalSource).toContain('Level Up session shortcuts')
    expect(playerDevelopmentPortalSource).toContain('level-up-filters')
    expect(playerDevelopmentPortalSource).toContain('visibleStartCount')
    expect(playerDevelopmentPortalSource).toContain('What can you do right now?')
    expect(playerDevelopmentPortalSource).toContain('10 min quick win')
    expect(playerDevelopmentPortalSource).toContain('levelUpCardPlan')
    expect(playerDevelopmentPortalSource).toContain('levelUpDoNow')
    expect(playerDevelopmentPortalSource).toContain('Do now')
    expect(playerDevelopmentPortalSource).toContain('card.routine[0]')
    expect(playerDevelopmentPortalSource).toContain('levelUpPlanGoal')
    expect(playerDevelopmentPortalSource).toContain('Why it matters')
    expect(playerDevelopmentPortalSource).toContain('card.tennisGoal')
    expect(playerDevelopmentPortalSource).toContain('View plan')
    expect(playerDevelopmentPortalSource).toContain('card.routine.slice(0, 3)')
    expect(playerDevelopmentPortalSource).toContain('Level up:')
    expect(playerDevelopmentPortalSource).toContain('Scale down:')
    expect(playerDevelopmentPortalSource).toContain('levelUpModuleCards')
    expect(playerDevelopmentPortalSource).toContain('levelUpModuleProgress')
    expect(playerDevelopmentPortalSource).toContain('completedCount')
    expect(playerDevelopmentPortalSource).toContain('Next up:')
    expect(playerDevelopmentPortalSource).toContain('Continue module')
    expect(playerDevelopmentPortalSource).toContain("data-complete")
    expect(playerDevelopmentPortalSource).toContain('Start module')
    expect(playerDevelopmentPortalSource).toContain('module.cardIds')
    expect(playerDevelopmentPortalSource).toContain('buildCardStartHref(identitySlug, nextCard)')
    expect(playerDevelopmentPortalSource).toContain('savedRating')
    expect(playerDevelopmentPortalSource).toContain('shownSavedRating')
    expect(playerDevelopmentPortalSource).toContain('loggerOpen')
    expect(playerDevelopmentPortalSource).toContain('openLogger')
    expect(playerDevelopmentPortalSource).toContain('Score</button>')
    expect(playerDevelopmentPortalSource).toContain("block: 'center'")
    expect(playerDevelopmentPortalSource).toContain('Saved ${shownSavedRating}/5')
    expect(playerDevelopmentPortalSource).toContain('Tap the number first.')
    expect(playerDevelopmentPortalSource).toContain('levelUpProofScale')
    expect(playerDevelopmentPortalSource).toContain('0: not yet')
    expect(playerDevelopmentPortalSource).toContain('3: showed up sometimes')
    expect(playerDevelopmentPortalSource).toContain('5: automatic today')
    expect(playerDevelopmentPortalSource).toContain('setNote(\'\')')
    expect(playerDevelopmentPortalSource).toContain('CompletionSummaryPill')
    expect(playerDevelopmentPortalSource).toContain('buildCompletionSummaryByCardId')
    expect(playerDevelopmentPortalSource).toContain('completionSummaryByCardId')
    expect(playerDevelopmentPortalSource).toContain('Last proof')
    expect(developmentStylesSource).toContain('.levelUpHero')
    expect(developmentStylesSource).toContain('.levelUpCardTile')
    expect(developmentStylesSource).toContain('.levelUpDoNow')
    expect(developmentStylesSource).toContain('.levelUpCardPlan')
    expect(developmentStylesSource).toContain('.levelUpPlanCue')
    expect(developmentStylesSource).toContain('.levelUpPlanGoal')
    expect(developmentStylesSource).toContain('.levelUpPlanScale')
    expect(developmentStylesSource).toContain('.levelUpModuleCards')
    expect(developmentStylesSource).toContain('.levelUpModuleProgress')
    expect(developmentStylesSource).toContain("[data-complete='true']")
    expect(developmentStylesSource).toContain('.completionSummaryPill')
    expect(developmentStylesSource).toContain('.completionSavedMessage')
    expect(developmentStylesSource).toContain('.levelUpProofScale')
    expect(developmentStylesSource).toContain('.scoreButton')
    expect(developmentStylesSource).toContain('.levelUpFilterSummary')
    expect(developmentStylesSource).toContain('.levelUpFilterControls')
    expect(developmentStylesSource).toContain('.levelUpIntentPresets')
    expect(developmentStylesSource).toContain('.levelUpSessionDock')
    expect(developmentStylesSource).toContain('.levelUpSessionActions')
    expect(developmentStylesSource).toContain('.levelUpStartList')
    expect(developmentStylesSource).toContain('.levelUpRailSummary')
    expect(developmentStylesSource).toContain('.levelUpShowMoreButton')
    expect(sitemapSource).toContain('`/player-development/${identity.slug}/level-up`')
  })

  it('surfaces Level Up from My Lab, navigation, and the sitemap', () => {
    expect(myLabSource).toContain('Level Up now')
    expect(myLabSource).toContain('href="/level-up"')
    expect(navSource).toContain("{ href: '/level-up', label: 'Level Up' }")
    expect(sitemapSource).toContain("{ path: '/level-up'")
  })

  it('keeps workbook and route drill menus in one shared source', () => {
    expect(trainingMenusSource).toContain('Serve target reps')
    expect(trainingMenusSource).toContain('First-strike conditioning')
    expect(developmentSystemSource).toContain("from '@/lib/player-training-menus'")
    expect(developmentSystemSource).not.toContain('function getPlayerTrainingMenus')
  })

  it('gives every development identity a direct Level Up URL', () => {
    expect(existsSync(join(process.cwd(), 'app/level-up/[identity]/page.tsx'))).toBe(true)
    expect(identityPageSource).toContain('generateStaticParams')
    expect(identityPageSource).toContain('PLAYER_DEVELOPMENT_IDENTITIES')
    expect(identityPageSource).toContain('LevelUpPageContent')
    expect(contentSource).toContain('href={`/level-up/${item.slug}`}')
    expect(sitemapSource).toContain('`/level-up/${identity.slug}`')
  })

  it('hands coach assignments straight into the on-court Level Up flow', () => {
    expect(myLabSource).toContain('buildAssignmentLevelUpHref')
    expect(myLabSource).toContain("coach: '1'")
    expect(myLabSource).toContain('inferAssignmentLevelUpWorkType')
    expect(myLabSource).toContain('workType: inferAssignmentLevelUpWorkType')
    expect(myLabSource).toContain('Start Level Up')
    expect(myLabSource).toContain('/level-up/${encodeURIComponent(identitySlug)}')
    expect(liveWorkbenchSource).toContain('useSearchParams')
    expect(liveWorkbenchSource).toContain('hasQuickStart')
    expect(liveWorkbenchSource).toContain('normalizeTrainingContext')
    expect(liveWorkbenchSource).toContain("?? [fallback, 'Do one focused block")
    expect(liveWorkbenchSource).toContain('Coach challenge loaded')
    expect(liveWorkbenchSource).toContain('normalizeAssignmentWorkType')
    expect(liveWorkbenchSource).toContain('useState(hasCoachAssignment ? `${initialFocusId}-coach-${initialWorkType}` :')
    expect(liveWorkbenchSource).toContain('setActiveDrillId(`${nextFocusId}-coach-${nextWorkType}`)')
    expect(liveWorkbenchSource).toContain('assignmentId: assignmentId || undefined')
    expect(liveWorkbenchSource).toContain('Synced. Coach assignment marked complete for review.')
  })

  it('keeps the phone Level Up flow compact for on-court use', () => {
    expect(liveWorkbenchSource).toContain('liveCompactSummary')
    expect(liveWorkbenchSource).toContain('type EditingStep')
    expect(liveWorkbenchSource).toContain('setEditingStep')
    expect(liveWorkbenchSource).toContain('contextOptionsByWorkType')
    expect(liveWorkbenchSource).toContain("setEditingStep('work')")
    expect(liveWorkbenchSource).toContain("setEditingStep(hasCoachAssignment ? null : 'setup')")
    expect(liveWorkbenchSource).toContain('contextOptions.map')
    expect(liveWorkbenchSource).toContain("court: ['alone', 'partner', 'singles', 'doubles']")
    expect(liveWorkbenchSource).toContain('liveCoachChallengeEntry')
    expect(liveWorkbenchSource).toContain('On court')
    expect(liveWorkbenchSource).toContain('Off court: body')
    expect(liveWorkbenchSource).toContain('function showActivity')
    expect(liveWorkbenchSource).toContain('Start activity')
    expect(liveWorkbenchSource).toContain('data-collapsed={editingStep !==')
    expect(liveWorkbenchSource).toContain('data-flow-state={editingStep ??')
    expect(liveWorkbenchSource).toContain('liveDrillSteps')
    expect(liveWorkbenchSource).toContain('getDrillActionSteps')
    expect(liveWorkbenchSource).toContain('getActionStepLabel')
    expect(liveWorkbenchSource).toContain('shortenDrillStep')
    expect(liveWorkbenchSource).toContain('scrollIntoView')
    expect(liveWorkbenchSource).toContain('data-assignment={hasCoachAssignment')
    expect(liveWorkbenchSource).toContain('id="level-up-activity"')
    expect(liveWorkbenchSource).toContain('data-timer-state={timerState}')
    expect(liveWorkbenchSource).toContain('function goToScore')
    expect(liveWorkbenchSource).toContain('onDone={goToScore}')
    expect(liveWorkbenchSource).toContain('data-scoring={scoringDrillId === activeDrill.id')
    expect(liveWorkbenchSource).toContain('Score now')
    expect(liveWorkbenchSource).toContain('sourceCard?: LevelUpCard')
    expect(liveWorkbenchSource).toContain('buildCardDrillOption')
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard?.routine')
    expect(liveWorkbenchSource).toContain("activeDrill.sourceCard ? 'Cue' : 'Watch'")
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard.reward')
    expect(liveWorkbenchSource).toContain('liveAdjustmentPanel')
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard.progression')
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard.regression')
    expect(liveWorkbenchSource).toContain('appendPortalCompletion')
    expect(liveWorkbenchSource).toContain('tiq-level-up-completions')
    expect(liveWorkbenchSource).toContain('cardId: card.id')
    expect(liveWorkbenchSource).toContain('<span>{drill.duration}</span>')
    expect(liveWorkbenchSource).toContain('<small>{shortenDrillStep(drill.proof)}</small>')
    expect(liveWorkbenchSource).toContain('data-action="done"')
    expect(liveWorkbenchSource).toContain('savedRef.current?.scrollIntoView')
    expect(liveWorkbenchSource).toContain('function repeatActivity')
    expect(liveWorkbenchSource).toContain('function pickNewFocus')
    expect(liveWorkbenchSource).toContain('Save ${draft.rating}/5')
    expect(liveWorkbenchSource).toContain('New focus')
    expect(liveWorkbenchSource).toContain('Score and save.')
    expect(developmentStylesSource).toContain('.liveCompactSummary')
    expect(developmentStylesSource).toContain('.liveCompactEdits')
    expect(developmentStylesSource).toContain('.liveDrillSteps')
    expect(developmentStylesSource).toContain('.liveAdjustmentPanel')
    expect(developmentStylesSource).toContain('text-transform: uppercase')
    expect(developmentStylesSource).toContain(".levelUpShell:has(.liveWorkbench[data-assignment='true']) .levelUpRouteHeader")
    expect(developmentStylesSource).toContain(".liveWorkbench[data-assignment='true'] .liveCompactSummary")
    expect(developmentStylesSource).toContain('scroll-margin-top: 12px')
    expect(developmentStylesSource).toContain(".liveTimerPanel[data-timer-state='running']")
    expect(developmentStylesSource).toContain(".liveActionCard:has(.liveTimerPanel[data-timer-state='running']) .liveDrillSteps")
    expect(developmentStylesSource).toContain(".liveTimerActions button[data-action='done']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-scoring='true'] .liveActionCard")
    expect(developmentStylesSource).toContain(".liveWorkbench:has(.liveWorkbenchBody[data-scoring='true']) .liveCompactSummary")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='work'] .liveActionCard")
    expect(developmentStylesSource).toContain('min-height: 0')
    expect(developmentStylesSource).toContain('.liveCoachChallengeEntry')
    expect(developmentStylesSource).toContain('.liveScoreGuide')
    expect(developmentStylesSource).toContain('.liveDrillChoices button small')
    expect(developmentStylesSource).toContain('.liveSetupActions')
    expect(developmentStylesSource).toContain('.liveSavedActions')
    expect(developmentStylesSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(developmentStylesSource).toContain(".liveStepPanel[data-collapsed='true']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='focus']")
    expect(developmentStylesSource).toContain('.liveCoachLoop,')
    expect(developmentStylesSource).toContain('.liveAccessPanel,')
    expect(developmentStylesSource).toContain('.levelUpRouteActions,')
    expect(developmentStylesSource).toContain('.liveAssignmentBanner,')
    expect(developmentStylesSource).toContain('.liveProgressPanel,')
    expect(developmentStylesSource).toContain('display: none;')
    expect(developmentStylesSource).toContain('overflow-x: auto')
    expect(developmentStylesSource).toContain('min-height: 78px')
  })
})
