import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pageSource = readFileSync(join(process.cwd(), 'app/level-up/page.tsx'), 'utf8')
const contentSource = readFileSync(join(process.cwd(), 'app/level-up/level-up-page-content.tsx'), 'utf8')
const identityPageSource = readFileSync(join(process.cwd(), 'app/level-up/[identity]/page.tsx'), 'utf8')
const myLabSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const navSource = readFileSync(join(process.cwd(), 'lib/site-navigation.ts'), 'utf8')
const sitemapSource = readFileSync(join(process.cwd(), 'app/sitemap.ts'), 'utf8')
const trainingMenusSource = readFileSync(join(process.cwd(), 'lib/player-training-menus.ts'), 'utf8')
const levelUpTypesSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-types.ts'), 'utf8')
const levelUpCardsSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-cards.ts'), 'utf8')
const levelUpModulesSource = readFileSync(join(process.cwd(), 'lib/level-up/level-up-modules.ts'), 'utf8')
const levelUpProfilesSource = readFileSync(join(process.cwd(), 'lib/level-up/identity-recommendations.ts'), 'utf8')
const levelUpRecommendationsSource = readFileSync(join(process.cwd(), 'lib/level-up/recommendations.ts'), 'utf8')
const playerDevelopmentPortalSource = readFileSync(join(process.cwd(), 'app/player-development/_components/level-up-portal.tsx'), 'utf8')
const developmentSystemSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development-system.tsx'), 'utf8')
const liveWorkbenchSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-live-workbench.tsx'), 'utf8')
const developmentStylesSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development.module.css'), 'utf8')

describe('Level Up page', () => {
  it('creates a direct phone-first Level Up destination from the shared drill engine', () => {
    expect(existsSync(join(process.cwd(), 'app/level-up/page.tsx'))).toBe(true)
    expect(pageSource).toContain('LevelUpPageContent')
    expect(contentSource).toContain('PlayerLiveWorkbench')
    expect(contentSource).toContain('getPlayerTrainingMenus')
    expect(contentSource).toContain('Start now')
    expect(contentSource).toContain('/mylab#coach-assignments')
    expect(contentSource).toContain('Choose development identity')
  })

  it('adds a Level Up portal library model for coach assignments, favorites, and recommendations', () => {
    expect(existsSync(join(process.cwd(), 'lib/level-up/level-up-types.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/level-up-cards.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/level-up-modules.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/identity-recommendations.ts'))).toBe(true)
    expect(existsSync(join(process.cwd(), 'lib/level-up/recommendations.ts'))).toBe(true)
    expect(levelUpTypesSource).toContain('export type LevelUpCard')
    expect(levelUpTypesSource).toContain('export type LevelUpAssignment')
    expect(levelUpTypesSource).toContain('export type LevelUpFavorite')
    expect(levelUpTypesSource).toContain('export type LevelUpCompletion')
    expect(levelUpTypesSource).toContain('useWhen?: string')
    expect(levelUpTypesSource).toContain('sessionPlan?: string[]')
    expect(levelUpTypesSource).toContain('successCriteria?: string')
    expect(levelUpCardsSource).toContain('export const LEVEL_UP_CARDS')
    expect(levelUpCardsSource).toContain('export const LEVEL_UP_MODULES')
    expect(levelUpCardsSource).toContain('assignable: true')
    expect(levelUpCardsSource).toContain('favoriteable: true')
    expect(levelUpCardsSource).toContain('Movement Engine')
    expect(levelUpCardsSource).toContain('Serve Pressure Reset')
    expect(levelUpCardsSource).toContain('getRecommendedLevelUpCards')
    expect(levelUpCardsSource).toContain('cardContentEnhancements')
    expect(levelUpCardsSource).toContain('Recovered before watching 0-5')
    expect(levelUpCardsSource).toContain('Serve target clarity 0-5')
    expect(levelUpCardsSource).toContain('Partner first-move clarity 0-5')
    expect(levelUpCardsSource).toContain('Wall rep quality and recovery 0-5')
    expect(levelUpCardsSource).toContain('Arrived balanced and recovered 0-5')
    expect(levelUpCardsSource).toContain('Decision quality under fatigue 0-5')
    expect(levelUpCardsSource).toContain('Balanced attack decision 0-5')
    expect(levelUpCardsSource).toContain('Finish, recover, then read the next ball.')
    expect(levelUpCardsSource).toContain('Set the cone, line, or shadow lane.')
    expect(levelUpCardsSource).toContain('You finish with movement that connects contact, recovery, and the next ready position.')
    expect(levelUpCardsSource).toContain('Walk the pattern first')
    expect(levelUpCardsSource).toContain('Split as the opponent would contact')
    expect(levelUpCardsSource).toContain('Wall recovery rule completed 0-5')
    expect(levelUpCardsSource).toContain('Crosscourt build quality 0-5')
    expect(levelUpCardsSource).toContain('This is not max testing.')
    expect(levelUpCardsSource).toContain('Second-serve routine commitment 0-5')
    expect(levelUpCardsSource).toContain('Defense-neutral-attack decision quality 0-5')
    expect(levelUpCardsSource).toContain('Routine discipline at 30-30 0-5')
    expect(levelUpCardsSource).toContain('Core control for serve rhythm 0-5')
    expect(levelUpCardsSource).toContain('Use light resistance. The goal is control, not max loading.')
    expect(levelUpCardsSource).toContain('Split squat control for tennis posture 0-5')
    expect(levelUpCardsSource).toContain('Wall rhythm with foot reset 0-5')
    expect(levelUpCardsSource).toContain('Serve location and partner readiness 0-5')
    expect(levelUpCardsSource).toContain('Switch call timing 0-5')
    expect(levelUpCardsSource).toContain('Doubles clarity at 30-30 0-5')
    expect(levelUpCardsSource).toContain('One proof, one leak, one next rep.')
    expect(levelUpCardsSource).toContain('buildTennisGoal')
    expect(levelUpCardsSource).toContain('buildSafetyNote')
    expect(levelUpModulesSource).toContain('recovery-after-contact')
    expect(levelUpModulesSource).toContain('conditioning-under-fatigue')
    expect(levelUpModulesSource).toContain('Use this when the player hits, watches, and gets late to the next ball.')
    expect(levelUpModulesSource).toContain('The player can call the target, run the same routine, and reset after a miss.')
    expect(levelUpModulesSource).toContain('Wall reps include contact quality, a foot reset, and honest recovery after contact.')
    expect(levelUpProfilesSource).toContain('IDENTITY_LEVEL_UP_PROFILES')
    expect(levelUpProfilesSource).toContain('relentless-competitor-4-0')
    expect(levelUpRecommendationsSource).toContain('scoreLevelUpCard')
    expect(levelUpRecommendationsSource).toContain('recommendLevelUpCards')
    expect(contentSource).toContain('LEVEL_UP_CARDS')
    expect(contentSource).toContain('LEVEL_UP_MODULES')
    expect(contentSource).toContain('getRecommendedLevelUpCards')
    expect(contentSource).toContain('levelUpPortal')
    expect(contentSource).toContain('Coach Assigned')
    expect(contentSource).toContain('Favorites')
    expect(contentSource).toContain('Recommended for Your Player Identity')
    expect(contentSource).toContain('Your tennis training hub.')
    expect(contentSource).toContain('LevelUpTrainingCard')
    expect(contentSource).toContain('quickStartCards')
    expect(contentSource).toContain('Proof: {card.proof}')
    expect(contentSource).toContain('formatCardList')
    expect(developmentStylesSource).toContain('.levelUpPortal')
    expect(developmentStylesSource).toContain('.levelUpCardRail')
    expect(developmentStylesSource).toContain('.levelUpLibraryGrid')
  })

  it('creates the preferred player-development Level Up portal route with mock v1 tooling', () => {
    expect(existsSync(join(process.cwd(), 'app/player-development/[identity]/level-up/page.tsx'))).toBe(true)
    expect(playerDevelopmentPortalSource).toContain('LevelUpPortal')
    expect(playerDevelopmentPortalSource).toContain('LevelUpTodayDashboard')
    expect(playerDevelopmentPortalSource).toContain('LevelUpNextBestRepPanel')
    expect(playerDevelopmentPortalSource).toContain('buildNextBestRep')
    expect(playerDevelopmentPortalSource).toContain('LevelUpTrainingPulsePanel')
    expect(playerDevelopmentPortalSource).toContain('buildTrainingPulse')
    expect(playerDevelopmentPortalSource).toContain('LevelUpCoachUpdatePanel')
    expect(playerDevelopmentPortalSource).toContain('buildCoachUpdateDigest')
    expect(playerDevelopmentPortalSource).toContain('Shareable recap')
    expect(playerDevelopmentPortalSource).toContain('Copy update')
    expect(playerDevelopmentPortalSource).toContain('No proof sent yet.')
    expect(playerDevelopmentPortalSource).toContain('getTrainingAreaLabel')
    expect(playerDevelopmentPortalSource).toContain('Training pulse')
    expect(playerDevelopmentPortalSource).toContain('Keep the work aligned.')
    expect(playerDevelopmentPortalSource).toContain('Under-trained next')
    expect(playerDevelopmentPortalSource).toContain('Next best rep')
    expect(playerDevelopmentPortalSource).toContain('Start next rep')
    expect(playerDevelopmentPortalSource).toContain('Same card, cleaner proof.')
    expect(playerDevelopmentPortalSource).toContain('Log one honest proof score.')
    expect(playerDevelopmentPortalSource).toContain('LevelUpCoachAssignmentBanner')
    expect(playerDevelopmentPortalSource).toContain('buildMockCoachAssignment')
    expect(playerDevelopmentPortalSource).toContain('formatAssignmentDueDate')
    expect(playerDevelopmentPortalSource).toContain('Open, choose, start.')
    expect(playerDevelopmentPortalSource).toContain('Coach challenge')
    expect(playerDevelopmentPortalSource).toContain('Start coach challenge')
    expect(playerDevelopmentPortalSource).toContain('Ready to send')
    expect(playerDevelopmentPortalSource).toContain('Review coach update')
    expect(playerDevelopmentPortalSource).toContain("data-status={readyToSend ? 'ready' : 'assigned'}")
    expect(playerDevelopmentPortalSource).toContain('Proof required')
    expect(playerDevelopmentPortalSource).toContain('Proof trend')
    expect(playerDevelopmentPortalSource).toContain('getRecentProofRead')
    expect(playerDevelopmentPortalSource).toContain('Today&apos;s Mission')
    expect(playerDevelopmentPortalSource).toContain('Coach Assigned')
    expect(playerDevelopmentPortalSource).toContain('Recommended for Your Player Identity')
    expect(playerDevelopmentPortalSource).toContain('Quick Wins Under 10 Minutes')
    expect(playerDevelopmentPortalSource).toContain('Performance Upgrade')
    expect(playerDevelopmentPortalSource).toContain('Favorites')
    expect(playerDevelopmentPortalSource).toContain('tiq-level-up-favorites')
    expect(playerDevelopmentPortalSource).toContain('tiq-level-up-completions')
    expect(playerDevelopmentPortalSource).toContain('setFavorites(readStringList')
    expect(playerDevelopmentPortalSource).toContain('setCompletions(readCompletions')
    expect(playerDevelopmentPortalSource).not.toContain('Coach Assignment Mode')
    expect(playerDevelopmentPortalSource).toContain('LevelUpStartList')
    expect(playerDevelopmentPortalSource).toContain('Start here')
    expect(playerDevelopmentPortalSource).toContain('Log proof')
    expect(playerDevelopmentPortalSource).toContain('Advanced filters')
    expect(playerDevelopmentPortalSource).toContain('levelUpFilterControls')
    expect(playerDevelopmentPortalSource).toContain('startListRef')
    expect(playerDevelopmentPortalSource).toContain('scrollToStartList')
    expect(playerDevelopmentPortalSource).toContain('level-up-start-here')
    expect(playerDevelopmentPortalSource).toContain('buildCardStartHref')
    expect(playerDevelopmentPortalSource).toContain('getCardWorkType')
    expect(playerDevelopmentPortalSource).toContain('card: card.id')
    expect(playerDevelopmentPortalSource).toContain('levelUpRailSummary')
    expect(playerDevelopmentPortalSource).toContain('defaultOpen')
    expect(playerDevelopmentPortalSource.indexOf('LevelUpStartList')).toBeLessThan(playerDevelopmentPortalSource.indexOf('LevelUpFilters'))
    expect(playerDevelopmentPortalSource).toContain('Move well before adding speed.')
    expect(playerDevelopmentPortalSource).toContain('showAllCards')
    expect(playerDevelopmentPortalSource).toContain('visibleAllCards')
    expect(playerDevelopmentPortalSource).toContain('Show all {filteredCards.length} cards')
    expect(playerDevelopmentPortalSource).toContain('countActiveFilters')
    expect(playerDevelopmentPortalSource).toContain('intentPresets')
    expect(playerDevelopmentPortalSource).toContain('LevelUpIntentPresets')
    expect(playerDevelopmentPortalSource).toContain('LevelUpSessionDock')
    expect(playerDevelopmentPortalSource).toContain('Level Up session shortcuts')
    expect(playerDevelopmentPortalSource).toContain('level-up-filters')
    expect(playerDevelopmentPortalSource).toContain('visibleStartCount')
    expect(playerDevelopmentPortalSource).toContain('sessionRead')
    expect(playerDevelopmentPortalSource).toContain('getSessionReadLabel')
    expect(playerDevelopmentPortalSource).toContain('No proof yet')
    expect(playerDevelopmentPortalSource).toContain('Build proof')
    expect(playerDevelopmentPortalSource).toContain('What can you do right now?')
    expect(playerDevelopmentPortalSource).toContain('10 min quick win')
    expect(playerDevelopmentPortalSource).toContain('levelUpCardPlan')
    expect(playerDevelopmentPortalSource).toContain('levelUpDoNow')
    expect(playerDevelopmentPortalSource).toContain('Do now')
    expect(playerDevelopmentPortalSource).toContain('card.routine[0]')
    expect(playerDevelopmentPortalSource).toContain('levelUpRunStrip')
    expect(playerDevelopmentPortalSource).toContain('How to run')
    expect(playerDevelopmentPortalSource).toContain('getCardSetupLabel')
    expect(playerDevelopmentPortalSource).toContain('No gear needed')
    expect(playerDevelopmentPortalSource).toContain('Partner and one clear rule')
    expect(playerDevelopmentPortalSource).toContain('controlled block')
    expect(playerDevelopmentPortalSource).toContain('levelUpPurposeStrip')
    expect(playerDevelopmentPortalSource).toContain('Training purpose for')
    expect(playerDevelopmentPortalSource).toContain('getCardPurposeLabel')
    expect(playerDevelopmentPortalSource).toContain('getCardSettingLabel')
    expect(playerDevelopmentPortalSource).toContain('getCardCoachSignal')
    expect(playerDevelopmentPortalSource).toContain('Recovery before watching')
    expect(playerDevelopmentPortalSource).toContain('Proof score plus one cue')
    expect(playerDevelopmentPortalSource).toContain('levelUpTrainingStandards')
    expect(playerDevelopmentPortalSource).toContain('Training standards for')
    expect(playerDevelopmentPortalSource).toContain('Train clean')
    expect(playerDevelopmentPortalSource).toContain('Counts when')
    expect(playerDevelopmentPortalSource).toContain('getCardProofStandard')
    expect(playerDevelopmentPortalSource).toContain('You move back to ready before judging the shot.')
    expect(playerDevelopmentPortalSource).toContain('You can repeat the cue without needing a coach reminder.')
    expect(playerDevelopmentPortalSource).toContain('getCardAvoidCue')
    expect(playerDevelopmentPortalSource).toContain('Do not hit and watch. Recover first, then read.')
    expect(playerDevelopmentPortalSource).toContain('Do not add volume until the cue is clear.')
    expect(playerDevelopmentPortalSource).toContain('Coach handoff')
    expect(playerDevelopmentPortalSource).toContain('getCardCoachHandoff')
    expect(playerDevelopmentPortalSource).toContain('Tell your coach when recovery happened before watching and when it disappeared.')
    expect(playerDevelopmentPortalSource).toContain('Bring one proof score, one cue that helped, and one question for the next lesson.')
    expect(playerDevelopmentPortalSource).toContain('levelUpPlanGoal')
    expect(playerDevelopmentPortalSource).toContain('Why it matters')
    expect(playerDevelopmentPortalSource).toContain('card.tennisGoal')
    expect(playerDevelopmentPortalSource).toContain('View plan')
    expect(playerDevelopmentPortalSource).toContain('card.routine.slice(0, 3)')
    expect(playerDevelopmentPortalSource).toContain('levelUpQualityChecks')
    expect(playerDevelopmentPortalSource).toContain('Quality checks')
    expect(playerDevelopmentPortalSource).toContain('getCardQualityChecks')
    expect(playerDevelopmentPortalSource).toContain('Finish balanced before you look for the result.')
    expect(playerDevelopmentPortalSource).toContain('Score routine clarity separately from serve makes.')
    expect(playerDevelopmentPortalSource).toContain('Count only reps that match the tennis habit.')
    expect(playerDevelopmentPortalSource).toContain('levelUpReadinessCheck')
    expect(playerDevelopmentPortalSource).toContain('Before you start')
    expect(playerDevelopmentPortalSource).toContain('getCardReadinessCheck')
    expect(playerDevelopmentPortalSource).toContain('Ready means:')
    expect(playerDevelopmentPortalSource).toContain('Pick the exact ready spot before the first rep.')
    expect(playerDevelopmentPortalSource).toContain('Name the one tennis habit you want to see.')
    expect(playerDevelopmentPortalSource).toContain('levelUpTrainingOptions')
    expect(playerDevelopmentPortalSource).toContain('Run it today')
    expect(playerDevelopmentPortalSource).toContain('getCardTrainingOptions')
    expect(playerDevelopmentPortalSource).toContain('With someone')
    expect(playerDevelopmentPortalSource).toContain('Shadow the contact, recover to the ready spot, then score whether you moved before watching.')
    expect(playerDevelopmentPortalSource).toContain('Ask a partner to watch for the proof behavior, not just the drill result.')
    expect(playerDevelopmentPortalSource).toContain('levelUpCommonMiss')
    expect(playerDevelopmentPortalSource).toContain('Common miss')
    expect(playerDevelopmentPortalSource).toContain('getCardCommonMiss')
    expect(playerDevelopmentPortalSource).toContain('Fast fix:')
    expect(playerDevelopmentPortalSource).toContain('You hit, watch, and arrive late to the next ready spot.')
    expect(playerDevelopmentPortalSource).toContain('The rep gets completed, but the tennis habit is not obvious.')
    expect(playerDevelopmentPortalSource).toContain('levelUpDoseGuide')
    expect(playerDevelopmentPortalSource).toContain('Enough for today')
    expect(playerDevelopmentPortalSource).toContain('getCardDoseGuide')
    expect(playerDevelopmentPortalSource).toContain('Stop when:')
    expect(playerDevelopmentPortalSource).toContain('2-3 short rounds where recovery happens before watching.')
    expect(playerDevelopmentPortalSource).toContain('5-8 quiet minutes with a before-and-after readiness score.')
    expect(playerDevelopmentPortalSource).toContain('levelUpTransferGuide')
    expect(playerDevelopmentPortalSource).toContain('Use it in points')
    expect(playerDevelopmentPortalSource).toContain('getCardTransferGuide')
    expect(playerDevelopmentPortalSource).toContain('Try next:')
    expect(playerDevelopmentPortalSource).toContain('After any ball you like, miss, or feel proud of.')
    expect(playerDevelopmentPortalSource).toContain('In the first live point where this habit naturally appears.')
    expect(playerDevelopmentPortalSource).toContain('levelUpCoachLens')
    expect(playerDevelopmentPortalSource).toContain('Coach lens')
    expect(playerDevelopmentPortalSource).toContain('getCardCoachLens')
    expect(playerDevelopmentPortalSource).toContain('Ask:')
    expect(playerDevelopmentPortalSource).toContain('Does the player recover before reacting to the shot result?')
    expect(playerDevelopmentPortalSource).toContain('What would make this habit easier to repeat next practice?')
    expect(playerDevelopmentPortalSource).toContain('Level up:')
    expect(playerDevelopmentPortalSource).toContain('Scale down:')
    expect(playerDevelopmentPortalSource).toContain('levelUpModuleCards')
    expect(playerDevelopmentPortalSource).toContain('levelUpModuleProgress')
    expect(playerDevelopmentPortalSource).toContain('levelUpModulePath')
    expect(playerDevelopmentPortalSource).toContain('buildModuleProgressStages')
    expect(playerDevelopmentPortalSource).toContain('Learn')
    expect(playerDevelopmentPortalSource).toContain('Pressure')
    expect(playerDevelopmentPortalSource).toContain('Show it in points.')
    expect(playerDevelopmentPortalSource).toContain('levelUpModuleGuide')
    expect(playerDevelopmentPortalSource).toContain('How to use this module')
    expect(playerDevelopmentPortalSource).toContain('module.sessionPlan')
    expect(playerDevelopmentPortalSource).toContain('Done when')
    expect(playerDevelopmentPortalSource).toContain('completedCount')
    expect(playerDevelopmentPortalSource).toContain('Next up:')
    expect(playerDevelopmentPortalSource).toContain('Continue module')
    expect(playerDevelopmentPortalSource).toContain("data-complete")
    expect(playerDevelopmentPortalSource).toContain('Start module')
    expect(playerDevelopmentPortalSource).toContain('module.cardIds')
    expect(playerDevelopmentPortalSource).toContain('buildCardStartHref(identitySlug, nextCard)')
    expect(playerDevelopmentPortalSource).toContain('savedRating')
    expect(playerDevelopmentPortalSource).toContain('shownSavedRating')
    expect(playerDevelopmentPortalSource).toContain("savedRating === null ? 'Save proof'")
    expect(playerDevelopmentPortalSource).toContain('loggerOpen')
    expect(playerDevelopmentPortalSource).toContain('activityOpen')
    expect(playerDevelopmentPortalSource).toContain('startActivity')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityMode')
    expect(playerDevelopmentPortalSource).toContain('Active drill')
    expect(playerDevelopmentPortalSource).toContain('Do this now. Log one honest score.')
    expect(playerDevelopmentPortalSource).toContain('timerRunning')
    expect(playerDevelopmentPortalSource).toContain('elapsedSeconds')
    expect(playerDevelopmentPortalSource).toContain('cleanRepCount')
    expect(playerDevelopmentPortalSource).toContain('getCleanRepTarget')
    expect(playerDevelopmentPortalSource).toContain('roundComplete')
    expect(playerDevelopmentPortalSource).toContain('levelUpRoundComplete')
    expect(playerDevelopmentPortalSource).toContain('getRoundCompletePrompt')
    expect(playerDevelopmentPortalSource).toContain('getRoundResetCue')
    expect(playerDevelopmentPortalSource).toContain('Round complete')
    expect(playerDevelopmentPortalSource).toContain('Reset first')
    expect(playerDevelopmentPortalSource).toContain('Score this round')
    expect(playerDevelopmentPortalSource).toContain('Repeat round')
    expect(playerDevelopmentPortalSource).toContain('Decide before doing more.')
    expect(playerDevelopmentPortalSource).toContain('Walk back to ready, say recover first, then decide score or repeat.')
    expect(playerDevelopmentPortalSource).toContain('Take one breath, name the cue, then score or repeat.')
    expect(playerDevelopmentPortalSource).toContain('getActivitySuggestedRating')
    expect(playerDevelopmentPortalSource).toContain('getActivityProofNote')
    expect(playerDevelopmentPortalSource).toContain('formatTimer')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityTimer')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityRepCounter')
    expect(playerDevelopmentPortalSource).toContain('activeFocusState')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityFocusBar')
    expect(playerDevelopmentPortalSource).toContain('getActiveFocusLabel')
    expect(playerDevelopmentPortalSource).toContain('Timer running')
    expect(playerDevelopmentPortalSource).toContain('Work in progress')
    expect(playerDevelopmentPortalSource).toContain('Start timer')
    expect(playerDevelopmentPortalSource).toContain('+1 clean')
    expect(playerDevelopmentPortalSource).toContain('Tap +1 only when the proof behavior showed up.')
    expect(playerDevelopmentPortalSource).toContain('Stop early if quality drops.')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityStandard')
    expect(playerDevelopmentPortalSource).toContain('getCardSessionStandard')
    expect(playerDevelopmentPortalSource).toContain('Counts')
    expect(playerDevelopmentPortalSource).toContain('levelUpRoundTarget')
    expect(playerDevelopmentPortalSource).toContain('getCardRoundTarget')
    expect(playerDevelopmentPortalSource).toContain('Win this round')
    expect(playerDevelopmentPortalSource).toContain('If missed')
    expect(playerDevelopmentPortalSource).toContain('recoveries before watching')
    expect(playerDevelopmentPortalSource).toContain('Make the next call earlier and shorter.')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityFixNow')
    expect(playerDevelopmentPortalSource).toContain('Fix now')
    expect(playerDevelopmentPortalSource).toContain('If this shows up')
    expect(playerDevelopmentPortalSource).toContain('Do this next rep')
    expect(playerDevelopmentPortalSource).toContain('commonMiss.miss')
    expect(playerDevelopmentPortalSource).toContain('commonMiss.fix')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityRepLadder')
    expect(playerDevelopmentPortalSource).toContain('getCardRepLadder')
    expect(playerDevelopmentPortalSource).toContain('Rep ladder')
    expect(playerDevelopmentPortalSource).toContain('Find it')
    expect(playerDevelopmentPortalSource).toContain('Repeat it')
    expect(playerDevelopmentPortalSource).toContain('Pressure it')
    expect(playerDevelopmentPortalSource).toContain('Play 30-30 or second-serve score with the same target call.')
    expect(playerDevelopmentPortalSource).toContain('!activityOpen')
    expect(playerDevelopmentPortalSource).toContain('levelUpActivityScoreGuide')
    expect(playerDevelopmentPortalSource).toContain('getCardProofAnchors')
    expect(playerDevelopmentPortalSource).toContain('Score honestly')
    expect(playerDevelopmentPortalSource).toContain('The rep counts when the proof behavior is obvious.')
    expect(playerDevelopmentPortalSource).toContain('Activity recap')
    expect(playerDevelopmentPortalSource).toContain('Suggested proof:')
    expect(playerDevelopmentPortalSource).toContain('Edit the score if the habit felt different.')
    expect(playerDevelopmentPortalSource).toContain('Open guided flow')
    expect(playerDevelopmentPortalSource).toContain("data-activity={activityOpen ? 'true' : 'false'}")
    expect(playerDevelopmentPortalSource).toContain('openLogger')
    expect(playerDevelopmentPortalSource).toContain('Score</button>')
    expect(playerDevelopmentPortalSource).toContain("block: 'start'")
    expect(playerDevelopmentPortalSource).toContain('Saved ${savedRating}/5')
    expect(playerDevelopmentPortalSource).toContain('Tap the number first.')
    expect(playerDevelopmentPortalSource).toContain('levelUpProofScale')
    expect(playerDevelopmentPortalSource).toContain('0: not yet')
    expect(playerDevelopmentPortalSource).toContain('3: showed up sometimes')
    expect(playerDevelopmentPortalSource).toContain('5: automatic today')
    expect(playerDevelopmentPortalSource).toContain('getProofRatingGuidance')
    expect(playerDevelopmentPortalSource).toContain('Next rep')
    expect(playerDevelopmentPortalSource).toContain('levelUpRepFeedback')
    expect(playerDevelopmentPortalSource).toContain('getCardRepFeedback')
    expect(playerDevelopmentPortalSource).toContain('getCardFeedbackFocus')
    expect(playerDevelopmentPortalSource).toContain('Fix first')
    expect(playerDevelopmentPortalSource).toContain('Repeat cue')
    expect(playerDevelopmentPortalSource).toContain('Protect it')
    expect(playerDevelopmentPortalSource).toContain('Slow the finish and recover first.')
    expect(playerDevelopmentPortalSource).toContain('Quality beats the clock.')
    expect(playerDevelopmentPortalSource).toContain('Raise one variable at a time.')
    expect(playerDevelopmentPortalSource).toContain('levelUpCoachableNote')
    expect(playerDevelopmentPortalSource).toContain('Worth noting')
    expect(playerDevelopmentPortalSource).toContain('getCoachableNotePrompt')
    expect(playerDevelopmentPortalSource).toContain('getCardNoteFocus')
    expect(playerDevelopmentPortalSource).toContain('Name the blocker.')
    expect(playerDevelopmentPortalSource).toContain('Name the repeat cue.')
    expect(playerDevelopmentPortalSource).toContain('Name what transferred.')
    expect(playerDevelopmentPortalSource).toContain('Write where recovery disappeared: finish, first step, or ready spot.')
    expect(playerDevelopmentPortalSource).toContain('Write the cue you should repeat next session.')
    expect(playerDevelopmentPortalSource).toContain('Scale it down.')
    expect(playerDevelopmentPortalSource).toContain('Repeat before moving on.')
    expect(playerDevelopmentPortalSource).toContain('Progress the challenge.')
    expect(playerDevelopmentPortalSource).toContain('Save proof')
    expect(playerDevelopmentPortalSource).toContain('getProofNotePrompt')
    expect(playerDevelopmentPortalSource).toContain('What got in the way?')
    expect(playerDevelopmentPortalSource).toContain('What cue should you repeat?')
    expect(playerDevelopmentPortalSource).toContain('What made it work?')
    expect(playerDevelopmentPortalSource).toContain('Proof saved')
    expect(playerDevelopmentPortalSource).toContain('levelUpProofSnapshot')
    expect(playerDevelopmentPortalSource).toContain('buildProofSnapshot')
    expect(playerDevelopmentPortalSource).toContain('savedProofSnapshot')
    expect(playerDevelopmentPortalSource).toContain('Proof snapshot')
    expect(playerDevelopmentPortalSource).toContain('Rep signal')
    expect(playerDevelopmentPortalSource).toContain('Coach ask')
    expect(playerDevelopmentPortalSource).toContain('getProofSnapshotCoachAsk')
    expect(playerDevelopmentPortalSource).toContain('Score saved without timed reps')
    expect(playerDevelopmentPortalSource).toContain('Watch whether')
    expect(playerDevelopmentPortalSource).toContain('levelUpAfterScoreNext')
    expect(playerDevelopmentPortalSource).toContain('Next move')
    expect(playerDevelopmentPortalSource).toContain('levelUpScoreDecision')
    expect(playerDevelopmentPortalSource).toContain('getScoreDecision')
    expect(playerDevelopmentPortalSource).toContain('savedScoreDecision')
    expect(playerDevelopmentPortalSource).toContain('Decision')
    expect(playerDevelopmentPortalSource).toContain('Shrink it before you repeat.')
    expect(playerDevelopmentPortalSource).toContain('Repeat before you progress.')
    expect(playerDevelopmentPortalSource).toContain('Progress one variable only.')
    expect(playerDevelopmentPortalSource).toContain('getAfterScorePrimaryAction')
    expect(playerDevelopmentPortalSource).toContain('getAfterScoreDetail')
    expect(playerDevelopmentPortalSource).toContain('Scale down and repeat one clean cue.')
    expect(playerDevelopmentPortalSource).toContain('getSavedProofAction')
    expect(playerDevelopmentPortalSource).toContain('buildCoachUpdate')
    expect(playerDevelopmentPortalSource).toContain('copyCoachUpdate')
    expect(playerDevelopmentPortalSource).toContain('coachUpdateCopied')
    expect(playerDevelopmentPortalSource).toContain('savedProofNote')
    expect(playerDevelopmentPortalSource).toContain('savedCoachUpdate')
    expect(playerDevelopmentPortalSource).toContain('Coach update')
    expect(playerDevelopmentPortalSource).toContain('Copy coach update')
    expect(playerDevelopmentPortalSource).toContain('Coach update copied')
    expect(playerDevelopmentPortalSource).toContain('STORED_STATE_HYDRATION_DELAY_MS')
    expect(playerDevelopmentPortalSource).toContain('repeatActivity')
    expect(playerDevelopmentPortalSource).toContain('finishActivity')
    expect(playerDevelopmentPortalSource).toContain('Repeat card')
    expect(playerDevelopmentPortalSource).toContain('Done for now')
    expect(playerDevelopmentPortalSource).toContain('Scale down next.')
    expect(playerDevelopmentPortalSource).toContain('Repeat this card.')
    expect(playerDevelopmentPortalSource).toContain('Level up one variable.')
    expect(playerDevelopmentPortalSource).not.toContain('completedCardIds =')
    expect(playerDevelopmentPortalSource).toContain('setNote(\'\')')
    expect(playerDevelopmentPortalSource).toContain('CompletionSummaryPill')
    expect(playerDevelopmentPortalSource).toContain('levelUpNextPractice')
    expect(playerDevelopmentPortalSource).toContain('getCardNextPractice')
    expect(playerDevelopmentPortalSource).toContain('Shrink the drill.')
    expect(playerDevelopmentPortalSource).toContain('Repeat the same standard.')
    expect(playerDevelopmentPortalSource).toContain('Raise the challenge.')
    expect(playerDevelopmentPortalSource).toContain('previousRating')
    expect(playerDevelopmentPortalSource).toContain('getProofTrendLabel')
    expect(playerDevelopmentPortalSource).toContain('first look')
    expect(playerDevelopmentPortalSource).toContain('improving')
    expect(playerDevelopmentPortalSource).toContain('holding')
    expect(playerDevelopmentPortalSource).toContain('rebuild')
    expect(playerDevelopmentPortalSource).toContain('getProofTrendAction')
    expect(playerDevelopmentPortalSource).toContain('raise the challenge')
    expect(playerDevelopmentPortalSource).toContain('repeat clean')
    expect(playerDevelopmentPortalSource).toContain('scale down')
    expect(playerDevelopmentPortalSource).toContain('log again')
    expect(playerDevelopmentPortalSource).toContain('getProofProgressPrescription')
    expect(playerDevelopmentPortalSource).toContain('Next session: shrink the setup and chase one clean cue.')
    expect(playerDevelopmentPortalSource).toContain('Next session: repeat the same card before adding difficulty.')
    expect(playerDevelopmentPortalSource).toContain('Next session: raise only one variable and keep proof honest.')
    expect(playerDevelopmentPortalSource).toContain('Next session: protect the habit, then add one small challenge.')
    expect(playerDevelopmentPortalSource).toContain('buildCompletionSummaryByCardId')
    expect(playerDevelopmentPortalSource).toContain('completionSummaryByCardId')
    expect(playerDevelopmentPortalSource).toContain('Last proof')
    expect(developmentStylesSource).toContain('.levelUpHero')
    expect(developmentStylesSource).toContain('.levelUpTodayDashboard')
    expect(developmentStylesSource).toContain('.levelUpNextBestRep')
    expect(developmentStylesSource).toContain('.levelUpNextBestRepCard')
    expect(developmentStylesSource).toContain('.levelUpTrainingPulse')
    expect(developmentStylesSource).toContain('.levelUpPulseGrid')
    expect(developmentStylesSource).toContain('.levelUpCoachUpdate')
    expect(developmentStylesSource).toContain('.levelUpCoachUpdatePreview')
    expect(developmentStylesSource).toContain('.levelUpCoachAssignmentBanner')
    expect(developmentStylesSource).toContain(".levelUpCoachAssignmentBanner[data-status='ready']")
    expect(developmentStylesSource).toContain('.levelUpCoachAssignmentMeta')
    expect(developmentStylesSource).toContain('.levelUpCoachAssignmentProof')
    expect(developmentStylesSource).toContain('.levelUpTodayDashboardGrid')
    expect(developmentStylesSource).toContain('.levelUpTodayDashboardGrid a')
    expect(developmentStylesSource).toContain('.levelUpCardTile')
    expect(developmentStylesSource).toContain('.levelUpCardTileActive')
    expect(developmentStylesSource).toContain('.levelUpActivityMode')
    expect(developmentStylesSource).toContain("[data-focus-state='running']")
    expect(developmentStylesSource).toContain('.levelUpActivityFocusBar')
    expect(developmentStylesSource).toContain('.levelUpActivitySteps')
    expect(developmentStylesSource).toContain('.levelUpRoundTarget')
    expect(developmentStylesSource).toContain('.levelUpActivityFixNow')
    expect(developmentStylesSource).toContain('.levelUpActivityStandard')
    expect(developmentStylesSource).toContain('.levelUpActivityRepLadder')
    expect(developmentStylesSource).toContain('.levelUpScoreDecision')
    expect(developmentStylesSource).toContain('.levelUpActivityScoreGuide')
    expect(developmentStylesSource).toContain('.levelUpActivityTimer')
    expect(developmentStylesSource).toContain(".levelUpActivityTimer[data-timer-state='running']")
    expect(developmentStylesSource).toContain('.levelUpActivityTimerTrack')
    expect(developmentStylesSource).toContain('.levelUpActivityRepCounter')
    expect(developmentStylesSource).toContain(".levelUpActivityRepCounter[data-rep-state='complete']")
    expect(developmentStylesSource).toContain('.levelUpRoundComplete')
    expect(developmentStylesSource).toContain('.levelUpRoundReset')
    expect(developmentStylesSource).toContain('.levelUpActivityRepActions')
    expect(developmentStylesSource).toContain('.levelUpActivityRecap')
    expect(developmentStylesSource).toContain("[data-activity='true']")
    expect(developmentStylesSource).toContain('.levelUpDoNow')
    expect(developmentStylesSource).toContain('.levelUpRunStrip')
    expect(developmentStylesSource).toContain('.levelUpPurposeStrip')
    expect(developmentStylesSource).toContain('.levelUpTrainingStandards')
    expect(developmentStylesSource).toContain('.levelUpCardPlan')
    expect(developmentStylesSource).toContain('.levelUpPlanCue')
    expect(developmentStylesSource).toContain('.levelUpPlanGoal')
    expect(developmentStylesSource).toContain('.levelUpQualityChecks')
    expect(developmentStylesSource).toContain('.levelUpReadinessCheck')
    expect(developmentStylesSource).toContain('.levelUpTrainingOptions')
    expect(developmentStylesSource).toContain('.levelUpCommonMiss')
    expect(developmentStylesSource).toContain('.levelUpDoseGuide')
    expect(developmentStylesSource).toContain('.levelUpTransferGuide')
    expect(developmentStylesSource).toContain('.levelUpCoachLens')
    expect(developmentStylesSource).toContain('.levelUpPlanScale')
    expect(developmentStylesSource).toContain('.levelUpModuleCards')
    expect(developmentStylesSource).toContain('.levelUpModuleProgress')
    expect(developmentStylesSource).toContain('.levelUpModulePath')
    expect(developmentStylesSource).toContain("[data-active='true']")
    expect(developmentStylesSource).toContain("[data-complete='true']")
    expect(developmentStylesSource).toContain('.levelUpModuleGuide')
    expect(developmentStylesSource).toContain("[data-complete='true']")
    expect(developmentStylesSource).toContain('.completionSummaryPill')
    expect(developmentStylesSource).toContain('.completionSummaryPill strong')
    expect(developmentStylesSource).toContain('.levelUpNextPractice')
    expect(developmentStylesSource).toContain('.completionSavedMessage')
    expect(developmentStylesSource).toContain('.completionSavedMessage strong')
    expect(developmentStylesSource).toContain('.levelUpProofSnapshot')
    expect(developmentStylesSource).toContain('.levelUpAfterScoreNext')
    expect(developmentStylesSource).toContain('.coachUpdatePreview')
    expect(developmentStylesSource).toContain('.coachUpdatePreview p')
    expect(developmentStylesSource).toContain('.completionSavedActions')
    expect(developmentStylesSource).toContain('.levelUpProofScale')
    expect(developmentStylesSource).toContain('.levelUpProofNextStep')
    expect(developmentStylesSource).toContain('.levelUpRepFeedback')
    expect(developmentStylesSource).toContain('.levelUpCoachableNote')
    expect(developmentStylesSource).toContain('.scoreButton')
    expect(developmentStylesSource).toContain('.levelUpFilterSummary')
    expect(developmentStylesSource).toContain('.levelUpFilterControls')
    expect(developmentStylesSource).toContain('.levelUpIntentPresets')
    expect(developmentStylesSource).toContain('.levelUpSessionDock')
    expect(developmentStylesSource).toContain('.levelUpSessionActions')
    expect(developmentStylesSource).toContain('.levelUpStartList')
    expect(developmentStylesSource).toContain('.levelUpRailSummary')
    expect(developmentStylesSource).toContain('.levelUpShowMoreButton')
    expect(sitemapSource).toContain('`/player-development/${identity.slug}/level-up`')
  })

  it('surfaces Level Up from My Lab, navigation, and the sitemap', () => {
    expect(myLabSource).toContain('Level Up now')
    expect(myLabSource).toContain('href="/level-up"')
    expect(navSource).toContain("{ href: '/level-up', label: 'Level Up' }")
    expect(sitemapSource).toContain("{ path: '/level-up'")
  })

  it('keeps workbook and route drill menus in one shared source', () => {
    expect(trainingMenusSource).toContain('Serve target reps')
    expect(trainingMenusSource).toContain('First-strike conditioning')
    expect(developmentSystemSource).toContain("from '@/lib/player-training-menus'")
    expect(developmentSystemSource).not.toContain('function getPlayerTrainingMenus')
  })

  it('gives every development identity a direct Level Up URL', () => {
    expect(existsSync(join(process.cwd(), 'app/level-up/[identity]/page.tsx'))).toBe(true)
    expect(identityPageSource).toContain('generateStaticParams')
    expect(identityPageSource).toContain('PLAYER_DEVELOPMENT_IDENTITIES')
    expect(identityPageSource).toContain('LevelUpPageContent')
    expect(contentSource).toContain('href={`/level-up/${item.slug}`}')
    expect(sitemapSource).toContain('`/level-up/${identity.slug}`')
  })

  it('hands coach assignments straight into the on-court Level Up flow', () => {
    expect(myLabSource).toContain('buildAssignmentLevelUpHref')
    expect(myLabSource).toContain("coach: '1'")
    expect(myLabSource).toContain('inferAssignmentLevelUpWorkType')
    expect(myLabSource).toContain('workType: inferAssignmentLevelUpWorkType')
    expect(myLabSource).toContain('Start Level Up')
    expect(myLabSource).toContain('/level-up/${encodeURIComponent(identitySlug)}')
    expect(liveWorkbenchSource).toContain('useSearchParams')
    expect(liveWorkbenchSource).toContain('hasQuickStart')
    expect(liveWorkbenchSource).toContain('normalizeTrainingContext')
    expect(liveWorkbenchSource).toContain("?? [fallback, 'Do one focused block")
    expect(liveWorkbenchSource).toContain('Coach challenge loaded')
    expect(liveWorkbenchSource).toContain('normalizeAssignmentWorkType')
    expect(liveWorkbenchSource).toContain('useState(hasCoachAssignment ? `${initialFocusId}-coach-${initialWorkType}` :')
    expect(liveWorkbenchSource).toContain('setActiveDrillId(`${nextFocusId}-coach-${nextWorkType}`)')
    expect(liveWorkbenchSource).toContain('assignmentId: assignmentId || undefined')
    expect(liveWorkbenchSource).toContain('Synced. Coach assignment marked complete for review.')
  })

  it('keeps the phone Level Up flow compact for on-court use', () => {
    expect(liveWorkbenchSource).toContain('liveCompactSummary')
    expect(liveWorkbenchSource).toContain('type EditingStep')
    expect(liveWorkbenchSource).toContain('setEditingStep')
    expect(liveWorkbenchSource).toContain('contextOptionsByWorkType')
    expect(liveWorkbenchSource).toContain("setEditingStep('work')")
    expect(liveWorkbenchSource).toContain("setEditingStep(hasCoachAssignment ? null : 'setup')")
    expect(liveWorkbenchSource).toContain('contextOptions.map')
    expect(liveWorkbenchSource).toContain("court: ['alone', 'partner', 'singles', 'doubles']")
    expect(liveWorkbenchSource).toContain('liveCoachChallengeEntry')
    expect(liveWorkbenchSource).toContain('On court')
    expect(liveWorkbenchSource).toContain('Off court: body')
    expect(liveWorkbenchSource).toContain('function showActivity')
    expect(liveWorkbenchSource).toContain('Start activity')
    expect(liveWorkbenchSource).toContain('data-collapsed={editingStep !==')
    expect(liveWorkbenchSource).toContain('data-flow-state={editingStep ??')
    expect(liveWorkbenchSource).toContain('liveDrillSteps')
    expect(liveWorkbenchSource).toContain('getDrillActionSteps')
    expect(liveWorkbenchSource).toContain('getActionStepLabel')
    expect(liveWorkbenchSource).toContain('shortenDrillStep')
    expect(liveWorkbenchSource).toContain('scrollIntoView')
    expect(liveWorkbenchSource).toContain('data-assignment={hasCoachAssignment')
    expect(liveWorkbenchSource).toContain('id="level-up-activity"')
    expect(liveWorkbenchSource).toContain('data-timer-state={timerState}')
    expect(liveWorkbenchSource).toContain('function goToScore')
    expect(liveWorkbenchSource).toContain('onDone={goToScore}')
    expect(liveWorkbenchSource).toContain('data-scoring={scoringDrillId === activeDrill.id')
    expect(liveWorkbenchSource).toContain('Score now')
    expect(liveWorkbenchSource).toContain('sourceCard?: LevelUpCard')
    expect(liveWorkbenchSource).toContain('buildCardDrillOption')
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard?.routine')
    expect(liveWorkbenchSource).toContain("activeDrill.sourceCard ? 'Cue' : 'Watch'")
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard.reward')
    expect(liveWorkbenchSource).toContain('liveAdjustmentPanel')
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard.progression')
    expect(liveWorkbenchSource).toContain('activeDrill.sourceCard.regression')
    expect(liveWorkbenchSource).toContain('liveQualityGrid')
    expect(liveWorkbenchSource).toContain('Quality standards for this activity')
    expect(liveWorkbenchSource).toContain('getCardWorkBlock')
    expect(liveWorkbenchSource).toContain('getCardQualityStandard')
    expect(liveWorkbenchSource).toContain('getCardCommonMiss')
    expect(liveWorkbenchSource).toContain('Fix first')
    expect(liveWorkbenchSource).toContain('You recover before judging whether the shot was good.')
    expect(liveWorkbenchSource).toContain('liveProofRubric')
    expect(liveWorkbenchSource).toContain('Proof rating guide')
    expect(liveWorkbenchSource).toContain('getLiveProofRubric')
    expect(liveWorkbenchSource).toContain('Target and routine stayed clear')
    expect(liveWorkbenchSource).toContain('Partner could act on it')
    expect(liveWorkbenchSource).toContain('appendPortalCompletion')
    expect(liveWorkbenchSource).toContain('tiq-level-up-completions')
    expect(liveWorkbenchSource).toContain('cardId: card.id')
    expect(liveWorkbenchSource).toContain('<span>{drill.duration}</span>')
    expect(liveWorkbenchSource).toContain('<small>{shortenDrillStep(drill.proof)}</small>')
    expect(liveWorkbenchSource).toContain('data-action="done"')
    expect(liveWorkbenchSource).toContain('savedRef.current?.scrollIntoView')
    expect(liveWorkbenchSource).toContain('function repeatActivity')
    expect(liveWorkbenchSource).toContain('function pickNewFocus')
    expect(liveWorkbenchSource).toContain('Save ${draft.rating}/5')
    expect(liveWorkbenchSource).toContain('New focus')
    expect(liveWorkbenchSource).toContain('Score and save.')
    expect(developmentStylesSource).toContain('.liveCompactSummary')
    expect(developmentStylesSource).toContain('.liveCompactEdits')
    expect(developmentStylesSource).toContain('.liveDrillSteps')
    expect(developmentStylesSource).toContain('.liveAdjustmentPanel')
    expect(developmentStylesSource).toContain('.liveQualityGrid')
    expect(developmentStylesSource).toContain('.liveProofRubric')
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='drill']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='drill'] .liveLaneColumn[data-collapsed='true']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='drill'][data-scoring='false'] .liveTracker")
    expect(developmentStylesSource).toContain('align-content: start')
    expect(developmentStylesSource).toContain('text-transform: uppercase')
    expect(developmentStylesSource).toContain(".levelUpShell:has(.liveWorkbench[data-assignment='true']) .levelUpRouteHeader")
    expect(developmentStylesSource).toContain(".liveWorkbench[data-assignment='true'] .liveCompactSummary")
    expect(developmentStylesSource).toContain('scroll-margin-top: 12px')
    expect(developmentStylesSource).toContain(".liveTimerPanel[data-timer-state='running']")
    expect(developmentStylesSource).toContain(".liveActionCard:has(.liveTimerPanel[data-timer-state='running']) .liveDrillSteps")
    expect(developmentStylesSource).toContain(".liveTimerActions button[data-action='done']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-scoring='true'] .liveActionCard")
    expect(developmentStylesSource).toContain(".liveWorkbench:has(.liveWorkbenchBody[data-scoring='true']) .liveCompactSummary")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='work'] .liveActionCard")
    expect(developmentStylesSource).toContain('min-height: 0')
    expect(developmentStylesSource).toContain('.liveCoachChallengeEntry')
    expect(developmentStylesSource).toContain('.liveScoreGuide')
    expect(developmentStylesSource).toContain('.liveDrillChoices button small')
    expect(developmentStylesSource).toContain('.liveSetupActions')
    expect(developmentStylesSource).toContain('.liveSavedActions')
    expect(developmentStylesSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(developmentStylesSource).toContain(".liveStepPanel[data-collapsed='true']")
    expect(developmentStylesSource).toContain(".liveWorkbenchBody[data-flow-state='focus']")
    expect(developmentStylesSource).toContain('.liveCoachLoop,')
    expect(developmentStylesSource).toContain('.liveAccessPanel,')
    expect(developmentStylesSource).toContain('.levelUpRouteActions,')
    expect(developmentStylesSource).toContain('.liveAssignmentBanner,')
    expect(developmentStylesSource).toContain('.liveProgressPanel,')
    expect(developmentStylesSource).toContain('display: none;')
    expect(developmentStylesSource).toContain('overflow-x: auto')
    expect(developmentStylesSource).toContain('min-height: 78px')
  })
})
