import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const playerApiSource = readFileSync(join(process.cwd(), 'app/api/player/level-up-sessions/route.ts'), 'utf8')
const playerAssignmentsApiSource = readFileSync(join(process.cwd(), 'app/api/player/coach-assignments/route.ts'), 'utf8')
const coachApiSource = readFileSync(join(process.cwd(), 'app/api/coach/level-up-sessions/route.ts'), 'utf8')
const coachPageSource = readFileSync(join(process.cwd(), 'app/coach/page.tsx'), 'utf8')
const workbenchSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-live-workbench.tsx'), 'utf8')
const portalSource = readFileSync(join(process.cwd(), 'app/player-development/_components/level-up-portal.tsx'), 'utf8')
const authSource = readFileSync(join(process.cwd(), 'lib/player-api-auth.ts'), 'utf8')

describe('Level Up session sync', () => {
  it('keeps coach-invited access separate from Player self-guided access', () => {
    expect(authSource).toContain('getSignedInPlayerApiAuth')
    expect(authSource).toContain('PLAYER_TIER_NAME = MEMBERSHIP_TIERS.player_plus.name')
    expect(authSource).toContain('${PLAYER_TIER_NAME} access is required for this tool.')
    expect(authSource).not.toContain('Player+ access is required for this tool.')
    expect(playerApiSource).toContain("accessMode === 'coach_invited'")
    expect(playerApiSource).toContain("accessMode === 'player_plus'")
    expect(playerApiSource).toContain('assignmentSync')
    expect(playerApiSource).toContain('AssignmentSyncResult')
    expect(playerApiSource).toContain('getCoachAssignmentPackProgress')
    expect(playerApiSource).toContain('progressLabel')
    expect(playerApiSource).toContain('loadPlayerAccess')
    expect(playerApiSource).toContain('PLAYER_TIER_NAME = MEMBERSHIP_TIERS.player_plus.name')
    expect(playerApiSource).toContain('Connect with a coach invite before syncing coach-visible Level Up work.')
    expect(playerApiSource).toContain('${PLAYER_TIER_NAME} is required to sync self-guided Level Up history across devices.')
    expect(playerApiSource).not.toContain('Player+ is required to sync self-guided Level Up history across devices.')
  })

  it('persists Level Up work for players and exposes shared logs to coaches', () => {
    expect(existsSync(join(process.cwd(), 'supabase/migrations/20260530000100_create_level_up_sessions.sql'))).toBe(true)
    expect(playerApiSource).toContain(".from('level_up_sessions')")
    expect(playerApiSource).toContain('shared_with_coach,session_json,completed_at')
    expect(playerApiSource).toContain('buildLevelUpAssignmentRecap(payload)')
    expect(playerApiSource).toContain('function buildLevelUpAssignmentRecap')
    expect(playerApiSource).toContain('function getPayloadStarterRead')
    expect(playerApiSource).toContain('Trained: ${starterRead.starterRep}')
    expect(playerApiSource).toContain('Counted: ${starterRead.starterProofCue}')
    expect(playerApiSource).toContain('Leaked: ${starterRead.starterLeakWatch}')
    expect(playerApiSource).toContain('Next: ${starterRead.starterSmartNext}')
    expect(playerAssignmentsApiSource).toContain('buildPlayerAssignmentCompletion')
    expect(playerAssignmentsApiSource).toContain('assignmentId')
    expect(workbenchSource).toContain('assignmentId')
    expect(workbenchSource).toContain('studentLinkId')
    expect(coachApiSource).toContain(".from('level_up_sessions')")
    expect(coachApiSource).toContain('shared_with_coach,session_json,completed_at')
    expect(coachApiSource).toContain(".eq('shared_with_coach', true)")
    expect(workbenchSource).toContain('/api/player/level-up-sessions')
    expect(workbenchSource).toContain('starterRead: session.starterRead ?? undefined')
    expect(workbenchSource).toContain('Synced. Your linked coach can use this for the next lesson.')
    expect(workbenchSource).toContain('Free preview saved locally.')
  })

  it('syncs portal proof logs through coach invite, Player, or local fallback', () => {
    expect(portalSource).toContain('function useLevelUpCompletions(')
    expect(portalSource).toContain('assignmentByCardId: Map<string, LevelUpAssignment>')
    expect(portalSource).toContain('PLAYER_TIER_NAME = MEMBERSHIP_TIERS.player_plus.name')
    expect(portalSource).toContain('supabase.auth.getSession')
    expect(portalSource).toContain('/api/player/level-up-sessions')
    expect(portalSource).toContain('/api/player/coach-assignments')
    expect(portalSource).toContain("accessMode: 'coach_invited'")
    expect(portalSource).toContain("accessMode: 'player_plus'")
    expect(portalSource).toContain('assignmentId: assignmentByCardId.get(cardId)?.id')
    expect(portalSource).toContain('Saved locally. Sign in from a coach invite or ${PLAYER_TIER_NAME} to sync proof history.')
    expect(portalSource).not.toContain('Saved locally. Sign in from a coach invite or Player+ to sync proof history.')
    expect(portalSource).toContain('Synced. Your linked coach can use this for the next lesson.')
    expect(portalSource).toContain('PortalAssignmentSyncResult')
    expect(portalSource).toContain('coachResult.assignmentSync?.updated')
    expect(portalSource).toContain('Synced. Coach assignment progress updated for review')
    expect(portalSource).toContain('Synced to your Level Up history.')
    expect(portalSource).toContain('remoteSessionToCompletion')
    expect(portalSource).toContain('mergeCompletions')
  })

  it('surfaces Level Up proof on coach assignment review cards', () => {
    expect(coachPageSource).toContain('buildAssignmentProofMap(levelUpSessions)')
    expect(coachPageSource).toContain('assignmentProofById.get(assignment.id)')
    expect(coachPageSource).toContain('Level Up proof received')
    expect(coachPageSource).toContain('buildLevelUpProofReviewDraft')
    expect(coachPageSource).toContain('buildCoachProofReviewStandard')
    expect(coachPageSource).toContain('buildCoachProofStarterRead')
    expect(coachPageSource).toContain('CoachProofStarterReadItem')
    expect(coachPageSource).toContain('const proofStarterRead = levelUpProof ? buildCoachProofStarterRead(levelUpProof) : null')
    expect(coachPageSource).toContain('Coach starter read for ${assignment.title}')
    expect(coachPageSource).toContain('What the player trained, counted, leaked, and should run next.')
    expect(coachPageSource).toContain("label: 'Trained'")
    expect(coachPageSource).toContain('value: session.starterRead.starterRep')
    expect(coachPageSource).toContain("label: 'Counted'")
    expect(coachPageSource).toContain('value: session.starterRead.starterProofCue')
    expect(coachPageSource).toContain("label: 'Leak'")
    expect(coachPageSource).toContain('value: session.starterRead.starterLeakWatch')
    expect(coachPageSource).toContain("label: 'Next'")
    expect(coachPageSource).toContain('value: session.starterRead.starterSmartNext')
    expect(coachPageSource).toContain('proofReviewStandard')
    expect(coachPageSource).toContain('Coach review standard for')
    expect(coachPageSource).toContain('Review standard')
    expect(coachPageSource).toContain('Player counted')
    expect(coachPageSource).toContain('Coach checks')
    expect(coachPageSource).toContain('Next rep')
    expect(coachPageSource).toContain('card.qualityChecks?.[0] ?? card.proof')
    expect(coachPageSource).toContain('card.proofAnchors?.high ?? card.proof')
    expect(coachPageSource).toContain('card.commonMiss?.fix ?? card.regression ?? card.cue')
    expect(coachPageSource).toContain('setReviewNote(proofReviewDraft?.note')
    expect(coachPageSource).toContain('setReviewNextFocus(proofReviewDraft?.nextFocus')
    expect(coachPageSource).toContain('proofReplyPlan')
    expect(coachPageSource).toContain('Coach proof reply plan')
    expect(coachPageSource).toContain('Turn the saved proof into one clear player message.')
    expect(coachPageSource).toContain('Acknowledge')
    expect(coachPageSource).toContain('Next focus')
    expect(coachPageSource).toContain('Assign next')
    expect(coachPageSource).toContain('proofReplyPlanStyle')
    expect(coachPageSource).toContain('proofReplyPlanGridStyle')
    expect(coachPageSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(coachPageSource).toContain('proofReplyPlanItemStyle')
    expect(coachPageSource).toContain('firstProofReviewCommand')
    expect(coachPageSource).toContain('Coach proof review command')
    expect(coachPageSource).toContain('Proof to review first')
    expect(coachPageSource).toContain('Use the proof note, choose the response, then assign the next clean rep.')
    expect(coachPageSource).toContain('proofReviewCommandStyle')
    expect(coachPageSource).toContain('proofReviewCommandGridStyle')
    expect(coachPageSource).toContain('proofReviewCommandItemStyle')
    expect(coachPageSource).toContain('Review proof')
    expect(coachPageSource).toContain('buildCoachProofResponseMessageHref')
    expect(coachPageSource).toContain('buildCoachProofResponseBody')
    expect(coachPageSource).toContain('Message proof response')
    expect(coachPageSource).toContain('const starterRead = proof.starterRead')
    expect(coachPageSource).toContain('Player ID read: ${proof.focusTitle}')
    expect(coachPageSource).toContain('Trained: ${starterRead.starterRep}')
    expect(coachPageSource).toContain('Counted: ${starterRead.starterProofCue}')
    expect(coachPageSource).toContain('Leaked: ${starterRead.starterLeakWatch}')
    expect(coachPageSource).toContain('Next: ${starterRead.starterSmartNext}')
    expect(coachPageSource).toContain('Coach response: ${draft.note}')
    expect(coachPageSource).toContain('Train first: ${draft.nextMove.title}')
    expect(coachPageSource).toContain('Proof target: ${draft.nextFocus}')
    expect(coachPageSource).toContain('Coach question: ${draft.note}')
    expect(coachPageSource).toContain('const proofHistoryRead = playerCheckIn?.recap ? buildCoachProofHistoryRead(playerCheckIn.recap) : null')
    expect(coachPageSource).toContain('Proof history read for ${assignment.title}')
    expect(coachPageSource).toContain('function buildCoachProofHistoryRead')
    expect(coachPageSource).toContain("getProofHistoryRecapMarker(recap, 'Trained')")
    expect(coachPageSource).toContain("getProofHistoryRecapMarker(recap, 'Counted')")
    expect(coachPageSource).toContain("getProofHistoryRecapMarker(recap, 'Leaked')")
    expect(coachPageSource).toContain("getProofHistoryRecapMarker(recap, 'Next')")
    expect(coachPageSource).toContain('proofHistoryReadStyle')
    expect(coachPageSource).toContain('proofHistoryReadGridStyle')
    expect(coachPageSource).toContain('proofHistoryReadItemStyle')
  })

  it('recommends and preloads the next coach assignment from Level Up proof', () => {
    expect(coachPageSource).toContain('loadNextAssignmentFromProof')
    expect(coachPageSource).toContain('buildLevelUpProofReviewDecisions')
    expect(coachPageSource).toContain('loadReviewDecisionFromProof')
    expect(coachPageSource).toContain('Coach proof decision panel')
    expect(coachPageSource).toContain('Review decision')
    expect(coachPageSource).toContain('proofReviewDraft.nextMove')
    expect(coachPageSource).toContain('Load next assignment')
    expect(coachPageSource).toContain('Choose the next coach move before assigning.')
    expect(coachPageSource).toContain('setAssignmentLevelUpCardId(nextCardId)')
    expect(coachPageSource).toContain('Repeat clean:')
    expect(coachPageSource).toContain('Scale down:')
    expect(coachPageSource).toContain("'add-pressure'")
  })

  it('lets Coach Hub assign exact Level Up cards into the player portal', () => {
    expect(coachPageSource).toContain('assignmentLevelUpCardId')
    expect(coachPageSource).toContain('Assign exact Level Up card')
    expect(coachPageSource).toContain('buildCoachLevelUpAssignmentCards')
    expect(coachPageSource).toContain('cardId: levelUpCard.id')
    expect(coachPageSource).toContain('moduleId: levelUpModule?.id')
    expect(coachPageSource).toContain('portalHref: `/player-development/${')
    expect(coachPageSource).toContain('buildCoachAssignmentCourtHref')
    expect(coachPageSource).toContain('appendCoachAssignmentCourtParams')
    expect(coachPageSource).toContain("url.searchParams.set('coach', '1')")
    expect(coachPageSource).toContain("url.searchParams.set('assignmentId', assignment.id)")
    expect(coachPageSource).toContain('copyCoachAssignmentCourtLink')
    expect(coachPageSource).toContain('navigator.clipboard.writeText(text)')
    expect(coachPageSource).toContain('Copy court link')
    expect(coachPageSource).toContain('Open court link')
  })

  it('opens direct coach assignment card links inside the player portal', () => {
    expect(portalSource).toContain("searchParams.get('card') || searchParams.get('startCard')")
    expect(portalSource).toContain('requestedStartCardId')
    expect(portalSource).toContain('directStartHandledRef')
    expect(portalSource).toContain('setActiveLaneCardId(requestedCard.id)')
    expect(portalSource).toContain("setSelectedIntent('Coach link')")
  })

  it('labels active direct-start cards with coach assignment context', () => {
    expect(portalSource).toContain('activeLaneCoachAssignment')
    expect(portalSource).toContain('buildDirectStartAssignment')
    expect(portalSource).toContain('coachAssignment={activeLaneCoachAssignment}')
    expect(portalSource).toContain('coachAssignedCardPill')
    expect(portalSource).toContain('Coach assigned')
  })
})
