import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const myLabSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const playerCoachAssignmentsApiSource = readFileSync(join(process.cwd(), 'app/api/player/coach-assignments/route.ts'), 'utf8')

describe('My Lab coach check-in guide', () => {
  it('keeps Player+ assignment recaps tied to the coach evidence target', () => {
    expect(myLabSource).toContain('Player+ recap guide')
    expect(myLabSource).toContain('buildPlayerAssignmentCheckInDraft')
    expect(myLabSource).toContain('id="coach-assignments"')
    expect(myLabSource).toContain('Assigned to me pack')
    expect(myLabSource).toContain('Assigned to me')
    expect(myLabSource).toContain('assignedQueue')
    expect(myLabSource).toContain('Start assigned card')
    expect(myLabSource).toContain('Coach assigned pack')
    expect(myLabSource).toContain('buildLevelUpHabitPaths')
    expect(myLabSource).toContain('Active habit path')
    expect(myLabSource).toContain('activeHabitPath')
    expect(myLabSource).toContain('Start drill')
    expect(myLabSource).toContain('Build quest')
    expect(myLabSource).toContain('Coach pack')
    expect(myLabSource).toContain('Team challenge')
    expect(myLabSource).toContain('getCoachAssignmentPackProgress')
    expect(myLabSource).toContain('coachAssignmentPackBarFillStyle')
    expect(myLabSource).toContain("pack.items.find((item) => item.status !== 'completed'")
    expect(myLabSource).toContain('Use guided draft')
    expect(myLabSource).toContain('summary?.expectedEvidence')
    expect(myLabSource).toContain('Question for coach')
    expect(myLabSource).toContain('/api/player/calendar-links')
    expect(myLabSource).toContain('Coach lesson calendar')
    expect(myLabSource).toContain('Subscribe link')
    expect(myLabSource).toContain('activeCoachCalendarSubscribed')
    expect(myLabSource).toContain('coachCalendarFeedStatusByStudentId')
    expect(myLabSource).toContain('activeCoachCalendarStatusLabel')
    expect(myLabSource).toContain('Revoke feed')
    expect(myLabSource).toContain('revokePlayerCoachCalendarLink')
    expect(myLabSource).toContain('buildPlayerCoachLessonEvents')
    expect(myLabSource).toContain('MyLabCalendarPanel')
    expect(myLabSource).toContain('LOCAL_PERSONAL_CALENDAR_KEY')
    expect(myLabSource).toContain('/api/player/calendar-items')
    expect(myLabSource).toContain('Account calendar')
    expect(myLabSource).toContain('Browser calendar')
    expect(myLabSource).toContain('/api/player/personal-calendar-link')
    expect(myLabSource).toContain('Subscribe calendar')
    expect(myLabSource).toContain('Add to calendar')
    expect(myLabSource).toContain('Calendar help')
    expect(myLabSource).toContain('toWebcalUrl')
    expect(myLabSource).toContain('location')
    expect(myLabSource).toContain('Replace link')
    expect(myLabSource).toContain('calendarFeedActive')
    expect(myLabSource).toContain('calendarFeedLastUsedAt')
    expect(myLabSource).toContain('personalCalendarFeedUrl')
    expect(myLabSource).toContain('revokePersonalCalendarFeedLink')
    expect(myLabSource).toContain('Your tennis week, plus shared coach dates.')
    expect(myLabSource).toContain('Add personal reminders here while coach lessons and assignment due dates flow in from Coach Hub.')
  })

  it('only syncs player assignment status for assignments linked to that player', () => {
    expect(playerCoachAssignmentsApiSource).toContain(".from('coach_player_links')")
    expect(playerCoachAssignmentsApiSource).toContain(".eq('id', existing.studentLinkId)")
    expect(playerCoachAssignmentsApiSource).toContain(".eq('player_user_id', auth.userId)")
    expect(playerCoachAssignmentsApiSource).toContain(".eq('student_link_id', existing.studentLinkId)")
  })
})
