import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const myLabSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const playerCoachAssignmentsApiSource = readFileSync(join(process.cwd(), 'app/api/player/coach-assignments/route.ts'), 'utf8')

describe('My Lab coach check-in guide', () => {
  it('keeps Player assignment recaps tied to the coach evidence target', () => {
    expect(myLabSource).toContain('Player recap guide')
    expect(myLabSource).toContain('Player adds the full library, favorites, history, and trends.')
    expect(myLabSource).not.toContain('Player+ recap guide')
    expect(myLabSource).toContain('buildPlayerAssignmentCheckInDraft')
    expect(myLabSource).toContain('getPlayerAssignmentCheckIn')
    expect(myLabSource).toContain('buildPlayerAssignmentStatusPath')
    expect(myLabSource).toContain('coachAssignmentStatusPathStyle')
    expect(myLabSource).toContain('coachAssignmentStatusStepStyle')
    expect(myLabSource).toContain('Coach assignment status path')
    expect(myLabSource).toContain('Status path for')
    expect(myLabSource).toContain('buildPlayerAssignmentProofStandard')
    expect(myLabSource).toContain('buildLevelUpCardProofStandard')
    expect(myLabSource).toContain('getAssignmentLevelUpCard')
    expect(myLabSource).toContain('Coach assignment proof standard')
    expect(myLabSource).toContain('Proof standard for')
    expect(myLabSource).toContain('Count only')
    expect(myLabSource).toContain('Common leak')
    expect(myLabSource).toContain('Next clean rep')
    expect(myLabSource).toContain('card.qualityChecks?.[0] ?? card.proof')
    expect(myLabSource).toContain('card.commonMiss?.fix ?? card.regression ?? card.cue')
    expect(myLabSource).toContain('Open on court')
    expect(myLabSource).toContain('Save proof')
    expect(myLabSource).toContain('Recap sent')
    expect(myLabSource).toContain('Coach replied')
    expect(myLabSource).toContain('buildPlayerCoachReviewNextPlan')
    expect(myLabSource).toContain('coachReviewNextPlan')
    expect(myLabSource).toContain('Coach review next rep')
    expect(myLabSource).toContain('Coach said')
    expect(myLabSource).toContain('Run next')
    expect(myLabSource).toContain('Run response on court')
    expect(myLabSource).toContain('latestCoachFeedback')
    expect(myLabSource).toContain('Latest coach feedback')
    expect(myLabSource).toContain('aria-label="Latest coach feedback cue"')
    expect(myLabSource).toContain('latestCoachFeedbackFollowThrough')
    expect(myLabSource).toContain('Latest coach feedback follow-through')
    expect(myLabSource).toContain('Follow-through')
    expect(myLabSource).toContain('Turn the review into one court rep.')
    expect(myLabSource).toContain("label: 'Coach said'")
    expect(myLabSource).toContain("label: 'Run now'")
    expect(myLabSource).toContain("label: 'Send back'")
    expect(myLabSource).toContain('Player ID plan from coach')
    expect(myLabSource).toContain('aria-label="My Lab Player ID coach plan"')
    expect(myLabSource).toContain('latestCoachFeedbackPlayerIdHref')
    expect(myLabSource).toContain('latestCoachFeedbackPlayerIdPlan')
    expect(myLabSource).toContain('Player ID follow-up:')
    expect(myLabSource).toContain('Player ID read:')
    expect(myLabSource).toContain('Train first:')
    expect(myLabSource).toContain('Proof target:')
    expect(myLabSource).toContain('Coach question:')
    expect(myLabSource).toContain('Message Player ID plan')
    expect(myLabSource).toContain('playerIdCoachPlanStyle')
    expect(myLabSource).toContain('playerIdCoachPlanGridStyle')
    expect(myLabSource).toContain('playerIdCoachPlanItemStyle')
    expect(myLabSource).toContain('Run coach response')
    expect(myLabSource).toContain('latestCoachFeedbackCueStyle')
    expect(myLabSource).toContain('latestCoachFeedbackGridStyle')
    expect(myLabSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 160px), 1fr))'")
    expect(myLabSource).toContain('latestCoachFeedbackItemStyle')
    expect(myLabSource).toContain('latestCoachFollowThroughStyle')
    expect(myLabSource).toContain('latestCoachFollowThroughGridStyle')
    expect(myLabSource).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'")
    expect(myLabSource).toContain('latestCoachFollowThroughItemStyle')
    expect(myLabSource).toContain('Ask coach')
    expect(myLabSource).toContain('I saw your review on')
    expect(myLabSource).toContain('proofStandard?.nextCleanRep')
    expect(myLabSource).toContain('proofStandard?.countOnly')
    expect(myLabSource).toContain('id="coach-assignments"')
    expect(myLabSource).toContain('Assigned to me pack')
    expect(myLabSource).toContain('Assigned to me')
    expect(myLabSource).toContain('assignedQueue')
    expect(myLabSource).toContain('Start assigned card')
    expect(myLabSource).toContain('Coach assigned pack')
    expect(myLabSource).toContain('buildLevelUpHabitPaths')
    expect(myLabSource).toContain('Active habit path')
    expect(myLabSource).toContain('activeHabitPath')
    expect(myLabSource).toContain('Start drill')
    expect(myLabSource).toContain('Build quest')
    expect(myLabSource).toContain('Coach pack')
    expect(myLabSource).toContain('Team challenge')
    expect(myLabSource).toContain('getCoachAssignmentPackProgress')
    expect(myLabSource).toContain('coachAssignmentPackBarFillStyle')
    expect(myLabSource).toContain("pack.items.find((item) => item.status !== 'completed'")
    expect(myLabSource).toContain('Use guided draft')
    expect(myLabSource).toContain('summary?.expectedEvidence')
    expect(myLabSource).toContain('Question for coach')
    expect(myLabSource).toContain('/api/player/calendar-links')
    expect(myLabSource).toContain('Coach lesson calendar')
    expect(myLabSource).toContain('My Lab coach invite landing cue')
    expect(myLabSource).toContain('Coach connection is ready.')
    expect(myLabSource).toContain('Ask for one measurable assignment')
    expect(myLabSource).toContain('coachInviteLandingSteps')
    expect(myLabSource).toContain('Coach invite accepted next steps')
    expect(myLabSource).toContain('Coach connected empty assignment steps')
    expect(myLabSource).toContain('Waiting on coach')
    expect(myLabSource).toContain('Request one measurable assignment or keep training in Level Up.')
    expect(myLabSource).toContain('coachInviteLandingStepGridStyle')
    expect(myLabSource).toContain('coachInviteLandingStepStyle')
    expect(myLabSource).toContain('firstAssignmentRequestHref')
    expect(myLabSource).toContain('buildFirstAssignmentRequestBody(activeCoachLink)')
    expect(myLabSource).toContain('function buildFirstAssignmentRequestBody')
    expect(myLabSource).toContain('is connected in My Lab now.')
    expect(myLabSource).toContain('one measurable first assignment from Coach Hub')
    expect(myLabSource).toContain('the proof you want back')
    expect(myLabSource).toContain('Current player context:')
    expect(myLabSource).toContain('coachInviteLandingCueStyle')
    expect(myLabSource).toContain('Subscribe link')
    expect(myLabSource).toContain('activeCoachCalendarSubscribed')
    expect(myLabSource).toContain('coachCalendarFeedStatusByStudentId')
    expect(myLabSource).toContain('activeCoachCalendarStatusLabel')
    expect(myLabSource).toContain('Revoke feed')
    expect(myLabSource).toContain('revokePlayerCoachCalendarLink')
    expect(myLabSource).toContain('buildPlayerCoachLessonEvents')
    expect(myLabSource).toContain('MyLabCalendarPanel')
    expect(myLabSource).toContain('LOCAL_PERSONAL_CALENDAR_KEY')
    expect(myLabSource).toContain('/api/player/calendar-items')
    expect(myLabSource).toContain('Account calendar')
    expect(myLabSource).toContain('Browser calendar')
    expect(myLabSource).toContain('/api/player/personal-calendar-link')
    expect(myLabSource).toContain('Subscribe calendar')
    expect(myLabSource).toContain('Add to calendar')
    expect(myLabSource).toContain('Calendar help')
    expect(myLabSource).toContain('toWebcalUrl')
    expect(myLabSource).toContain('location')
    expect(myLabSource).toContain('Replace link')
    expect(myLabSource).toContain('calendarFeedActive')
    expect(myLabSource).toContain('calendarFeedLastUsedAt')
    expect(myLabSource).toContain('personalCalendarFeedUrl')
    expect(myLabSource).toContain('revokePersonalCalendarFeedLink')
    expect(myLabSource).toContain('Your tennis week, plus shared coach dates.')
    expect(myLabSource).toContain('Add personal reminders here while coach lessons and assignment due dates flow in from Coach Hub.')
  })

  it('only syncs player assignment status for assignments linked to that player', () => {
    expect(playerCoachAssignmentsApiSource).toContain(".from('coach_player_links')")
    expect(playerCoachAssignmentsApiSource).toContain(".eq('id', existing.studentLinkId)")
    expect(playerCoachAssignmentsApiSource).toContain(".eq('player_user_id', auth.userId)")
    expect(playerCoachAssignmentsApiSource).toContain(".eq('student_link_id', existing.studentLinkId)")
  })
})
