import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pageSource = readFileSync(join(process.cwd(), 'app/mylab/page.tsx'), 'utf8')
const componentSource = readFileSync(join(process.cwd(), 'app/mylab/my-lab-command-center.tsx'), 'utf8')
const styleSource = readFileSync(join(process.cwd(), 'app/mylab/my-lab-command-center.module.css'), 'utf8').replace(/\r\n/g, '\n')
const iconSource = readFileSync(join(process.cwd(), 'components/brand/TiqFeatureIcon.tsx'), 'utf8')
const portalSource = readFileSync(join(process.cwd(), 'app/components/portal-tool-bar.tsx'), 'utf8')
const pricingSource = readFileSync(join(process.cwd(), 'app/pricing/page.tsx'), 'utf8')
const upgradeSource = readFileSync(join(process.cwd(), 'app/upgrade/page.tsx'), 'utf8')

describe('My Lab command center', () => {
  it('puts one data-backed court action ahead of the legacy lab workspace', () => {
    const commandCenterIndex = pageSource.indexOf('<MyLabCommandCenter')
    const legacyWorkspaceIndex = pageSource.indexOf('<PlayerWorkshopShell')

    expect(commandCenterIndex).toBeGreaterThanOrEqual(0)
    expect(legacyWorkspaceIndex).toBeGreaterThan(commandCenterIndex)
    expect(pageSource).toContain('latestLevelUpProofCard?.title')
    expect(pageSource).toContain('isProfileConfirmed && hasMyLabFocus ? latestLevelUpProofCard?.durationMinutes || 10 : null')
    expect(pageSource).toContain("? 'Repeat this rep'")
    expect(pageSource).toContain('completedSessions={commandCenterCompletedSessions}')
    expect(pageSource).toContain('firstServeSteps={firstServeSteps}')
    expect(pageSource).toContain('postRepReturn={postRepReturn}')
    expect(pageSource).toContain('nextCourtEvent={nextCourtEvent}')
  })

  it('returns completed players to proof and one score-adjusted weekly plan', () => {
    expect(pageSource).toContain('const postRepReturn = latestLevelUpProof')
    expect(pageSource).toContain('buildMyLabWeeklyImprovementPlan(levelUpProofRecords)')
    expect(pageSource).toContain('weeklyImprovementPlan.nextAction')
    expect(pageSource).toContain("? 'Connect your player record so this proof stays with your tennis.'")
    expect(pageSource).toContain("? 'Tie this proof to one focus for your next match or practice.'")
    expect(componentSource).toContain('Rep saved · {postRepReturn.timeLabel}')
    expect(componentSource).toContain('{postRepReturn.syncLabel}')
    expect(componentSource).toContain('This week')
    expect(componentSource).toContain('Weekly plan · {postRepReturn.planLabel}')
    expect(componentSource).toContain('{postRepReturn.planWhy}')
    expect(componentSource).toContain('{postRepReturn.proofTarget}')
    expect(componentSource).toContain('{postRepReturn.trendLabel}')
    expect(componentSource).toContain('href={postRepReturn.nextHref}')
    expect(styleSource).toContain('.postRepReturn')
    expect(styleSource).toContain('.postRepSync')
    expect(pageSource).toContain("'Account proof is current across devices.'")
    expect(pageSource).toContain('weeklyImprovementPlan.nextCta')
    expect(styleSource).toContain('.postRepPlanMeta')
  })

  it('guides first use with real setup progress and retires the path after the first rep', () => {
    expect(pageSource).toContain('const hasMyLabFocus = Boolean(activeGoal.goal.trim())')
    expect(pageSource).toContain('!isProfileConfirmed || (hasMyLabFocus && latestLevelUpProof)')
    expect(pageSource).toContain("title: 'Connect your player'")
    expect(pageSource).toContain("title: 'Choose one focus'")
    expect(pageSource).toContain("title: 'Finish your first rep'")
    expect(pageSource).toContain("href: !isProfileConfirmed ? '/profile' : hasMyLabFocus ? '/mylab#player-tools' : MY_LAB_GOAL_PROGRESS_HREF")
    expect(pageSource).toContain("action: isProfileConfirmed ? 'Set my focus' : 'Connect player first'")
    expect(pageSource).toContain('open={!hasMyLabFocus}')
    expect(pageSource).toContain("? 'Find your player record'")
    expect(pageSource).toContain("? 'Choose one tennis focus'")
    expect(componentSource).toContain('Build your player loop.')
    expect(componentSource).toContain("aria-current={isCurrent ? 'step' : undefined}")
    expect(componentSource).toContain("data-has-current={nextFirstServeStep >= 0 ? 'true' : 'false'}")
    expect(componentSource).toContain('styles.firstServeStepSecondary')
    expect(componentSource).toContain('href={step.href}')
    expect(pageSource).not.toContain('First My Lab read')
  })

  it('keeps player and opponent details navigable', () => {
    expect(componentSource).toContain('href={`/players/${encodeURIComponent(playerId)}`}')
    expect(componentSource).toContain('href={`/players/${encodeURIComponent(matchup.opponentId)}`}')
    expect(componentSource).toContain("const matchupActionHref = matchup?.href || (playerId ? '/matchup' : '/profile')")
    expect(componentSource).toContain("const matchupActionLabel = matchup ? 'View matchup' : playerId ? 'Build matchup' : 'Connect player record'")
    expect(componentSource).toContain('href={matchupActionHref}')
    expect(componentSource).toContain('See progress')
  })

  it('gives unlinked players one clear path before matchup building', () => {
    expect(componentSource).toContain("{playerId ? 'Build your first read' : 'Connect your player record'}")
    expect(componentSource).toContain("? 'Choose two players to surface a useful next test.'")
    expect(componentSource).toContain(": 'Keep matchup insight tied to your tennis and surface a useful next test.'")
    expect(componentSource).toContain('!matchup && !playerId ? styles.matchActionPrimary :')
    expect(styleSource).toContain('.matchActionPrimary {')
  })

  it('uses real TenAceIQ court assets and a mobile-safe hierarchy', () => {
    expect(componentSource).toContain('src="/tiq/courts/tiq-court-master.png"')
    expect(componentSource).toContain('src="/tiq/tokens/tennis-ball-reference.png"')
    expect(componentSource).toContain('sizes="(max-width: 760px) 100vw, 760px"')
    expect(styleSource).toContain('@media (max-width: 680px)')
    expect(styleSource).toContain('grid-template-columns: 1fr;')
    expect(styleSource).toContain('min-height: 58px;')
    expect(styleSource).toContain('overflow-wrap: anywhere;')
    expect(styleSource).toContain('.firstServeGrid')
    expect(styleSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(styleSource).toContain(".firstServeGrid[data-has-current='true'] .firstServeStepSecondary")
    expect(componentSource).toContain("${postRepReturn ? styles.primaryGridAfterRep : ''}")
    expect(componentSource).toContain('className={styles.repCard}')
    expect(componentSource).toContain('{!postRepReturn ? <article className={styles.momentumCard}>')
    expect(styleSource).toContain('.supportStackAfterRep .matchCard')
    expect(styleSource).toContain('.ballImage {\n    right: 0;')
    expect(styleSource).toContain('width: clamp(128px, 23vw, 178px);')
    expect(styleSource).toContain('width: 108px;')
    expect(styleSource).not.toContain('right: -42px;')
    expect(styleSource).not.toContain('right: -44px;')
  })

  it('keeps the active-player context compact on a phone', () => {
    expect(componentSource).toContain("data-player-linked={playerId && playerName ? 'true' : 'false'}")
    expect(styleSource).toContain('.playerLink {\n    display: flex;\n    grid-column: 2;')
    expect(styleSource).toContain('grid-row: 1;\n    width: fit-content;')
    expect(styleSource).toContain('max-width: min(220px, 58vw);')
    expect(styleSource).toContain('font-size: clamp(2rem, 9.6vw, 2.8rem);')
    expect(styleSource).toContain('grid-template-columns: minmax(0, 1fr) auto;')
    expect(styleSource).toContain('.intro > div {\n    display: contents;')
    expect(styleSource).toContain('grid-column: 1 / -1;')
    expect(styleSource).toContain('.labSignature small,\n  .playerLink span {\n    display: none;')
    expect(styleSource).toContain('white-space: nowrap;')
    expect(styleSource).toContain(".intro[data-player-linked='false'] h1 {\n    font-size: clamp(1.65rem, 7.2vw, 2rem);")
  })

  it('keeps the current first-serve action compact and above the mobile fold', () => {
    expect(componentSource).toContain('aria-label="First serve setup"')
    expect(styleSource).toContain('.firstServeHeading > div > p:last-child {\n    display: none;')
    expect(styleSource).toContain('.firstServeHeading h2 {\n    display: none;')
    expect(styleSource).toContain('.firstServeHeading .cardEyebrow {\n    margin: 0;')
    expect(styleSource).toContain('min-height: 56px;')
    expect(styleSource).toContain('grid-template-columns: 26px minmax(0, 1fr) auto;')
    expect(styleSource).toContain('.firstServeCopy small {\n    display: none;')
    expect(styleSource).toContain('margin-bottom: 8px;')
  })

  it('keeps the unlinked phone rep focused on its account action', () => {
    expect(componentSource).toContain("data-player-linked={playerId && playerName ? 'true' : 'false'}")
    expect(styleSource).toContain(".repCard[data-player-linked='false'],\n  .repCard[data-player-linked='false'] .repContent {\n    min-height: 330px;")
    expect(styleSource).toContain(".repCard[data-player-linked='false'] .repContent h2 {\n    padding-right: 24px;\n    font-size: clamp(2.15rem, 9.6vw, 2.8rem);")
  })

  it('puts the weekly plan ahead of supporting progress and proof detail on phones', () => {
    const weeklyPlanIndex = componentSource.indexOf('<div className={styles.postRepNext}>')
    const weeklyProgressIndex = componentSource.indexOf('<div className={styles.postRepProgress}>')
    const weeklyActionIndex = componentSource.indexOf('<Link href={postRepReturn.nextHref}>')
    const weeklyWhyIndex = componentSource.indexOf('<p className={styles.postRepWhy}>')
    const weeklyMetaIndex = componentSource.indexOf('<div className={styles.postRepPlanMeta}>')

    expect(weeklyPlanIndex).toBeGreaterThanOrEqual(0)
    expect(weeklyProgressIndex).toBeGreaterThan(weeklyPlanIndex)
    expect(weeklyActionIndex).toBeGreaterThanOrEqual(0)
    expect(weeklyWhyIndex).toBeGreaterThan(weeklyActionIndex)
    expect(weeklyMetaIndex).toBeGreaterThan(weeklyWhyIndex)
    expect(styleSource).toContain('.postRepReturn {\n    grid-template-columns: 1fr;\n    gap: 0;')
    expect(styleSource).toContain('.postRepNext {\n    gap: 7px;\n    padding-top: 6px;')
    expect(styleSource).toContain('.postRepProgress {\n    grid-template-columns: minmax(0, 1fr) auto;')
    expect(styleSource).toContain('.postRepProgress > a {\n    grid-column: 2;\n    grid-row: 1;')
    expect(styleSource).toContain('.postRepTrack {\n    grid-column: 1 / -1;\n    grid-row: 2;')
    expect(styleSource).toContain('.postRepPlanMeta {\n    grid-template-columns: repeat(2, minmax(0, 1fr));')
  })

  it('uses a compact daily pulse instead of a second large weekly card on phones', () => {
    expect(componentSource).toContain('const dailyPulseItems = [')
    expect(componentSource).toContain("label: 'Court time'")
    expect(componentSource).toContain("label: 'This week'")
    expect(componentSource).toContain("label: 'Matchup'")
    expect(componentSource).toContain('aria-label="My Lab daily pulse"')
    expect(componentSource).toContain('{!postRepReturn ? (')
    expect(styleSource).toContain('.dailyPulse')
    expect(styleSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(styleSource).toContain('.momentumCard {\n    display: none;')
  })

  it('puts an actual upcoming scheduled match ahead of generic match prep', () => {
    expect(pageSource).toContain('const nextCourtEvent = [')
    expect(pageSource).toContain("item.eventType === 'match' && item.date >= todayDateKey")
    expect(pageSource).toContain("item.kind === 'match' && item.date >= todayDateKey")
    expect(pageSource).toContain('getLocalDateKey(new Date())')
    expect(componentSource).toContain('Next on court')
    expect(componentSource).toContain('className={styles.nextCourtEvent}')
    expect(componentSource).toContain('{nextCourtEvent.cta}')
    expect(componentSource).toContain('{nextCourtEvent.readiness}')
    expect(styleSource).toContain('.nextCourtEvent {\n    grid-template-columns: minmax(0, 1fr);')
    expect(styleSource).toContain('.nextCourtEventMeta {\n    grid-template-columns: minmax(0, 1fr) auto;')
    expect(styleSource).toContain('grid-row: 1 / 3;\n    min-height: 44px;')
    expect(pageSource).toContain("'Availability needs a reply'")
    expect(pageSource).toContain("'Availability confirmed'")
  })

  it('keeps the deeper legacy workspace behind one mobile disclosure', () => {
    expect(pageSource).toContain('const collapseLegacyWorkspace = isMobile && isProfileConfirmed')
    expect(pageSource).toContain("const PlayerWorkshopShell: 'details' | 'section'")
    expect(pageSource).toContain('<strong>More in My Lab</strong>')
    expect(pageSource).toContain('aria-label="Open more My Lab tools"')
    expect(pageSource).toContain('Go deeper on goals, coach work, and team tools.')
    expect(pageSource).toContain('style={mobileMyLabExtrasActionStyle}>See all tools')
    expect(pageSource).toContain('const mobileMyLabExtrasActionStyle: CSSProperties = {')
    expect(pageSource).toContain('mobileMyLabExtrasDetailsStyle')
  })

  it('turns the Watchlist summary into a clear mobile action', () => {
    expect(pageSource).toContain("aria-label={follows.length ? 'Open Watchlist to review updates' : 'Open Watchlist to follow tennis context'}")
    expect(pageSource).toContain("? `${follows.length} ${follows.length === 1 ? 'follow' : 'follows'} · Player, team, and league updates.`")
    expect(pageSource).toContain("{follows.length ? 'Review updates' : 'Build watchlist'} <span>→</span>")
    expect(pageSource).toContain('style={watchlistSummaryActionStyle}')
    expect(pageSource).toContain('const watchlistSummaryActionStyle: CSSProperties = {')
    expect(pageSource).toContain('minWidth: 140')
  })

  it('keeps Watchlist updates visible while management stays one level deeper on phones', () => {
    expect(pageSource).toContain("const WatchlistManageShell: 'details' | 'div' = isMobile ? 'details' : 'div'")
    expect(pageSource).toContain('aria-label="Open Watchlist management"')
    expect(pageSource).toContain('<strong>Manage watchlist</strong>')
    expect(pageSource).toContain('Find or unfollow tennis context.')
    expect(pageSource).toContain('<FollowList items={follows} onRemove={removeFollow} />')
    expect(pageSource).toContain('{!isMobile ? <div style={rightColumnStyle}>')
    expect(pageSource).toContain('const watchlistManageActionStyle: CSSProperties = {')
  })

  it('condenses Watchlist update filters into a phone-friendly selector', () => {
    expect(pageSource).toContain('{isMobile ? (')
    expect(pageSource).toContain('aria-label="Filter Watchlist updates"')
    expect(pageSource).toContain('<option value="all">All updates</option>')
    expect(pageSource).toContain('<option value="achievement">Achievements</option>')
    expect(pageSource).toContain('style={watchlistRefreshButtonStyle}')
    expect(pageSource).toContain("{loading ? 'Refreshing...' : 'Refresh'}")
    expect(pageSource).toContain('const watchlistFeedActionsMobileStyle: CSSProperties = {')
    expect(pageSource).toContain('const watchlistFeedFilterSelectStyle: CSSProperties = {')
    expect(pageSource).toContain("(['all', 'match', 'rating', 'achievement', 'team', 'league', 'community'] as const).map(")
  })

  it('turns upcoming Watchlist matches into compact phone briefs', () => {
    expect(pageSource).toContain("mobileContext: upcoming ? `${leagueName || 'League match'}${flight ? ` · ${flight}` : ''}` : undefined")
    expect(pageSource).toContain('mobileBody: upcoming ? upcomingLineupRead : undefined')
    expect(pageSource).toContain('isMobile && item.upcoming && item.matchId ? (')
    expect(pageSource).toContain('style={mobileUpcomingFeedLinkStyle}')
    expect(pageSource).toContain('const mobileUpcomingFeedCardStyle =')
    expect(pageSource).toContain('const mobileUpcomingFeedLinkStyle: CSSProperties = {')
  })

  it('turns recent league results into compact phone scorecards', () => {
    expect(pageSource).toContain("const [mobileResultTitle, ...mobileResultDetailParts] = rowBody.split(' • ')")
    expect(pageSource).toContain('mobileTitle: isLeagueResult ? mobileResultTitle : undefined')
    expect(pageSource).toContain("const mobileLatestResult = isMobile && !item.upcoming && item.badge === 'League result'")
    expect(pageSource).toContain("{item.mobileBody || 'Result posted.'}")
    expect(pageSource).toContain('style={mobileLatestResultLinkStyle}')
    expect(pageSource).toContain('View league')
  })

  it('uses one consistent My Lab mark without a nested signature frame', () => {
    expect(iconSource).toContain('myLab: FlaskIcon')
    expect(iconSource).not.toContain("signature = name === 'myLab'")
    expect(iconSource).not.toContain('tiq-feature-icon--signature')
    expect(iconSource).not.toContain('data-icon-treatment')
    expect(componentSource).toContain('<TiqFeatureIcon name="myLab" size="md" variant="surface" />')
    expect(componentSource).toContain('Player tools')
    expect(portalSource).toContain("icon: 'myLab'")
    expect(pricingSource).toContain("player_plus: 'myLab'")
    expect(upgradeSource).toContain("player_plus: 'myLab'")
  })
})
