import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/players/page.tsx'), 'utf8')

function styleBlock(styleName: string) {
  const match = source.match(new RegExp(`const ${styleName}: CSSProperties = \\{[\\s\\S]*?\\n\\}`))
  expect(match, `${styleName} style block`).not.toBeNull()
  return match![0]
}

describe('Players Player ID launchpad', () => {
  it('connects player discovery to the Player ID flow', () => {
    expect(source).toContain('playerIdLaunchpadSignals')
    expect(source).toContain('Player ID launchpad')
    expect(source).toContain('Use a player record for the next move.')
    expect(source).toContain('Pick your next player move.')
    expect(source).toContain('Search or browse players')
    expect(source).toContain('Next player move')
    expect(source).toContain("isMobile ? 'Next move' : 'Next player move'")
    expect(source).toContain('aria-label="Player directory starter actions"')
    expect(source).toContain('Find the ID')
    expect(source).toContain('Your anchor')
    expect(source).toContain('Next move')
    expect(source).toContain('Starter read')
    expect(source).toContain('Profile, Matchup, My Lab')
    expect(source).toContain('DIRECTORY_PLAYER_IDENTITY_READ.label')
    expect(source).toContain('DIRECTORY_PLAYER_IDENTITY_READ.levelUpNudge')
    expect(source).toContain('Set your profile for Matchup and My Lab handoffs.')
    expect(source).toContain('Open, compare, follow, or send missing context.')
    expect(source).toContain('No match history yet? Start with Level Up.')
    expect(source).toContain('<TiqFeatureIcon name="playerRatings" size="sm" variant="ghost" />')
    expect(source).toContain('const shouldShowPlayerResults = hasActiveFilters || browseAll')
    expect(source).not.toContain('const shouldShowPlayerResults = hasActiveFilters || browseAll || players.length > 0')
    expect(source).toContain(') : !shouldShowPlayerResults ? null : visiblePlayers.length === 0')
    expect(source).toContain('open={open} onToggle={(event) => setOpen(event.currentTarget.open)}')
    expect(source).toContain('playerDirectoryDetailsBodyClosedStyle')
    expect(source).toContain("gridTemplateColumns: isSmallMobile")
    expect(source).toContain("gridColumn: isMobile ? '1 / -1' : undefined")
    expect(source).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
  })

  it('keeps Level Up support after the usable directory', () => {
    expect(source).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(source).toContain("const DIRECTORY_PLAYER_IDENTITY = getPlayerDevelopmentIdentity('relentless-competitor-4-0')")
    expect(source).toContain('const DIRECTORY_LEVEL_UP_HREF = `/level-up/${DIRECTORY_PLAYER_IDENTITY.slug}#level-up-flow`')
    expect(source).toContain('const DIRECTORY_PLAYER_DEVELOPMENT_HREF = `/player-development/${DIRECTORY_PLAYER_IDENTITY.slug}`')
    expect(source).toContain('Player ID starter path')
    expect(source).toContain("title={isMobile ? 'Player ID details' : DIRECTORY_PLAYER_IDENTITY_READ.title}")
    expect(source).toContain("summary={isMobile ? 'Open' : 'Show player record cues'}")
    expect(source).toContain('aria-label="Player ID starter read"')
    expect(source).toContain('Train first')
    expect(source).toContain('Proof target')
    expect(source).toContain('Match test')
    expect(source).toContain('Start Level Up')
    expect(source).toContain('Read Player ID')
    expect(source.indexOf('Player ID starter path')).toBeGreaterThan(source.indexOf('{visiblePlayers.map((player) => {'))
    expect(source.indexOf('Player ID starter path')).toBeGreaterThan(source.indexOf('Show full directory'))
  })

  it('keeps the launchpad compact and mobile-safe', () => {
    expect(styleBlock('playerIdLaunchpadStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerIdLaunchpadStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerIdLaunchpadStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 250px), 1fr))'")
    expect(styleBlock('playerIdLaunchpadHeaderStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('playerIdLaunchpadGridStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerIdLaunchpadCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerIdLaunchpadCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerIdLaunchpadTextStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerIdStarterReadStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerIdStarterReadGridStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 96px), 1fr))'")
    expect(styleBlock('playerIdStarterReadItemStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerIdStarterReadItemStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerIdStarterActionRowStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('playerIdLaunchpadActionPanelStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerIdLaunchpadActionPanelStyle')).toContain("gridColumn: '1 / -1'")
    expect(styleBlock('playerIdLaunchpadActionListStyle')).toContain("gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 118px), 1fr))'")
    expect(styleBlock('findStartActionStyle')).toContain('minWidth: 0')
    expect(source).toContain('const dynamicPlayerIdLaunchpadStyle')
    expect(source).toContain("gridTemplateColumns: 'minmax(0, 1fr)'")
    expect(source).toContain('const dynamicPlayerIdLaunchpadActionListStyle')
    expect(source).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(source).toContain('const dynamicFindStartActionStyle')
    expect(source).toContain('minHeight: 44')
  })

  it('keeps repeated player-card trust details on request', () => {
    expect(source).toContain('<details style={playerCardTrustDetailsStyle}>')
    expect(source).toContain('<summary style={playerCardTrustSummaryStyle}>')
    expect(source).toContain('Data check')
    expect(source).toContain("player.matches > 0 ? 'Match context' : 'Profile context'")
    expect(source).toContain('<div style={playerCardTrustBodyStyle}>')
    expect(styleBlock('playerCardTrustDetailsStyle')).toContain('minWidth: 0')
    expect(styleBlock('playerCardTrustSummaryStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('playerCardTrustSummaryStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('playerCardTrustBodyStyle')).toContain('minWidth: 0')
  })

  it('keeps the mobile player directory controls compact', () => {
    expect(source).toContain("padding: isMobile ? '10px' : '18px'")
    expect(source).toContain("borderRadius: isMobile ? '16px' : controlsShell.borderRadius")
    expect(source).toContain("height: isMobile ? '40px' : selectStyle.height")
    expect(source).toContain("fontSize: isMobile ? '12px' : selectStyle.fontSize")
    expect(source).toContain('const dynamicControlsHelperText: CSSProperties = isMobile')
    expect(source).toContain('const dynamicQuickFilterButtonStyle: CSSProperties')
    expect(source).toContain('const dynamicClearFilterButton: CSSProperties')
    expect(source).toContain('compact={isMobile}')
    expect(styleBlock('compactSearchInput')).toContain("padding: '11px 12px 11px 40px'")
    expect(styleBlock('compactControlsHelperText')).toContain('...srOnlyStyle')
    expect(styleBlock('compactQuickFilterButton')).toContain("minHeight: '40px'")
    expect(styleBlock('compactClearFilterButton')).toContain("minHeight: '32px'")
    expect(styleBlock('compactStatChip')).toContain("padding: '8px 9px'")
    expect(styleBlock('compactStatChipValue')).toContain("fontSize: '16px'")
  })
})
