import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const systemSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development-system.tsx'), 'utf8')
const stylesSource = readFileSync(join(process.cwd(), 'app/player-development/_components/player-development.module.css'), 'utf8')

describe('player development question strip', () => {
  it('frames the public player-development page around player questions', () => {
    expect(systemSource).toContain("import { DATA_ASSIST_STORY, PRODUCT_MOTTO, getMembershipTier } from '@/lib/product-story'")
    expect(systemSource).toContain('{PRODUCT_MOTTO} Choose today&apos;s court habit, run the rep from your phone, score one proof, and keep the next step visible')
    expect(systemSource).toContain('PlayerIdActionPlan')
    expect(systemSource).toContain('aria-label="Player ID action plan"')
    expect(systemSource).toContain('aria-label="Player ID train prove use loop"')
    expect(systemSource).toContain('Player ID action plan')
    expect(systemSource).toContain('Train the identity before the next score moment.')
    expect(systemSource).toContain("['Train', actionRead.trainingPriority]")
    expect(systemSource).toContain("['Prove', firstCard?.proof ?? actionRead.proofTarget]")
    expect(systemSource).toContain("['Use it', actionRead.nextCue]")
    expect(systemSource).toContain('Open drill mode')
    expect(systemSource).toContain('PlayerQuestionStrip')
    expect(systemSource).toContain('Find the next useful tennis move.')
    expect(systemSource).toContain('Start with the tennis need you have today')
    expect(systemSource).toContain('What should I work on?')
    expect(systemSource).toContain('How am I improving?')
    expect(systemSource).toContain('What matchups matter?')
    expect(systemSource).toContain('What drills or resources can help me level up faster?')
    expect(systemSource).toContain('PlayerIdentitySnapshot')
    expect(systemSource).toContain('Player ID snapshot')
    expect(systemSource).toContain('Know the player profile before choosing the work.')
    expect(systemSource).toContain('Primary weapon')
    expect(systemSource).toContain('Training priority')
    expect(systemSource).toContain('Proof target')
    expect(systemSource).toContain('Style leak')
    expect(systemSource).toContain('Match trigger')
    expect(systemSource).toContain('First Level Up move')
    expect(systemSource).toContain('Player ID action read')
    expect(systemSource).toContain('Coach read')
    expect(systemSource).toContain('Next cue')
    expect(systemSource).toContain('Match test')
    expect(systemSource).toContain('Player ID handoff board')
    expect(systemSource).toContain('Profile ID handoff')
    expect(systemSource).toContain('Make the next touchpoint easier.')
    expect(systemSource).toContain('Log this proof')
    expect(systemSource).toContain('Open coach work')
    expect(systemSource.indexOf('<PlayerIdActionPlan identity={identity} />')).toBeGreaterThan(systemSource.indexOf('className={styles.hero}'))
    expect(systemSource.indexOf('<PlayerIdActionPlan identity={identity} />')).toBeLessThan(systemSource.indexOf('<PlayerSuitePanel'))
  })

  it('links each player question to a practical action path', () => {
    expect(systemSource).toContain("href: `/player-development/${identity.slug}#weekly-action-plan`")
    expect(systemSource).toContain("href: `/player-development/${identity.slug}#toolbelt`")
    expect(systemSource).toContain("href: `/player-development/${identity.slug}#match-card`")
    expect(systemSource).toContain("href: `/player-development/${identity.slug}/level-up`")
    expect(systemSource).toContain('const playerDevelopmentLevelUpHref =')
    expect(systemSource).toContain('const drillModeHref =')
    expect(systemSource).toContain("href={playerDevelopmentLevelUpHref}")
    expect(systemSource).toContain("href={drillModeHref}")
    expect(systemSource).toContain('#level-up-flow')
    expect(systemSource).toContain("href={`/player-development/${identity.slug}/level-up?card=${card.id}`}")
    expect(systemSource).toContain("cta: 'Choose a focus'")
    expect(systemSource).toContain("cta: 'Check progress'")
    expect(systemSource).toContain("cta: 'Prep the match'")
    expect(systemSource).toContain("cta: 'Start Level Up'")
  })

  it('keeps the question cards mobile-safe and tappable', () => {
    expect(stylesSource).toContain('.playerQuestionStrip')
    expect(stylesSource).toContain('.playerIdActionPlan')
    expect(stylesSource).toContain('.playerIdActionPlanGrid')
    expect(stylesSource).toContain('.playerIdActionPlanActions')
    expect(stylesSource).toContain('.playerQuestionGrid')
    expect(stylesSource).toContain('.playerIdSnapshot')
    expect(stylesSource).toContain('.playerIdSnapshotGrid')
    expect(stylesSource).toContain('.playerIdLevelUpBridge')
    expect(stylesSource).toContain('.playerIdProofTrail')
    expect(stylesSource).toContain('.playerIdHandoffBoard')
    expect(stylesSource).toContain('.playerIdHandoffGrid')
    expect(stylesSource).toContain('.playerIdHandoffActions')
    expect(stylesSource).toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(stylesSource).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 150px), 1fr))')
    expect(stylesSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(stylesSource).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(stylesSource).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 190px), 1fr))')
    expect(stylesSource).toContain('grid-template-columns: minmax(0, 1.05fr) minmax(260px, 0.95fr) minmax(210px, 0.7fr) auto')
    expect(stylesSource).toContain('.playerQuestionGrid,')
    expect(stylesSource).toContain('.playerIdActionPlanGrid,')
    expect(stylesSource).toContain('.playerIdActionPlanActions,')
    expect(stylesSource).toContain('.auditGrid,')
    expect(stylesSource).toContain('overflow-wrap: anywhere')
    expect(stylesSource).toContain('min-width: 0')
  })
})
