import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pricingSource = readFileSync(join(process.cwd(), 'app/pricing/page.tsx'), 'utf8')
const pricingLayoutSource = readFileSync(join(process.cwd(), 'app/pricing/layout.tsx'), 'utf8')
const joinSource = readFileSync(join(process.cwd(), 'app/join/page.tsx'), 'utf8')

describe('pricing simplification', () => {
  it('keeps pricing organized around the five decision sections', () => {
    expect(pricingSource).toContain('Choose by tennis need')
    expect(pricingSource).toContain('Start from what you are trying to do.')
    expect(pricingSource).toContain('JOB_CHOOSER')
    expect(pricingSource).toContain('Find tennis context')
    expect(pricingSource).toContain('Improve my game')
    expect(pricingSource).toContain('Captain match week')
    expect(pricingSource).toContain('Run a season or event')
    expect(pricingSource).toContain('Choose your role')
    expect(pricingSource).toContain('See plans')
    expect(pricingSource).toContain('See the tools')
    expect(pricingSource).toContain('Not sure which plan fits?')
    expect(pricingSource).toContain('Show plan helper')
    expect(pricingSource).toContain('Compare what unlocks')
    expect(pricingSource).toContain('<th style={tableHeadStyle}>Need</th>')
    expect(pricingSource).toContain('<td style={tableNeedStyle}>{row.need}</td>')
    expect(pricingSource).toContain('Billing clarity')
    expect(pricingSource).toContain('Start free / upgrade')
    expect(pricingSource).not.toContain('<th style={tableHeadStyle}>Job</th>')
    expect(pricingSource).not.toContain('<td style={tableJobStyle}>{row.job}</td>')
  })

  it('puts paid plan selection before the optional plan helper', () => {
    const chooseIndex = pricingSource.indexOf('id="choose"')
    const helperIndex = pricingSource.indexOf('id="job-chooser"')

    expect(chooseIndex).toBeGreaterThanOrEqual(0)
    expect(helperIndex).toBeGreaterThanOrEqual(0)
    expect(chooseIndex).toBeLessThan(helperIndex)
    expect(pricingSource).toContain('<details id="job-chooser"')
  })

  it('uses public workspace naming and consistent League billing', () => {
    expect(pricingSource).toContain('Player - My Lab for your game')
    expect(pricingSource).toContain('Coach - Coach Hub for player development')
    expect(pricingSource).toContain('Captain - Team Hub for match week')
    expect(pricingSource).toContain('League - League Office for a season')
    expect(pricingSource).toContain('Full-Court - Every tennis role, including Tournament Desk')
    expect(pricingSource).toContain('Use My Lab, Coach Hub, Team Hub, League Office')
    expect(pricingSource).toContain('const PLAN_JOB_FIT')
    expect(pricingSource).toContain('You need Team Hub to collect availability, compare lineups, scout, and send the match-week plan.')
    expect(pricingSource).toContain('You support more than one tennis role and need My Lab, Coach Hub, Team Hub, League Office, and Tournament Desk connected.')
    expect(pricingSource).toContain('paid plans unlock the right tools when the work gets specific.')
    expect(pricingSource).toContain('Full-Court access pass')
    expect(pricingSource).toContain('Start free, then unlock the right TenAceIQ tools: My Lab, Coach Hub, Team Hub, League Office, or Full-Court.')
    expect(pricingSource).toContain('Search players, teams, leagues, rankings, tournaments, coaches, and tennis resources before choosing paid tools.')
    expect(pricingSource).toContain('All paid tools are active.')
    expect(pricingSource).toContain('Use this pass to open My Lab, Coach Hub, Team Hub, and League Office from one account.')
    expect(pricingSource).toContain('Full-Court role guide')
    expect(pricingSource).toContain('Pick the right tool for the tennis need.')
    expect(pricingSource).toContain('Full-Court role switching')
    expect(pricingSource).toContain('Move between paid tools from one account.')
    expect(pricingSource).toContain('FULL_COURT_ROLE_SWITCHING_PROOF')
    expect(pricingSource).toContain('Start with Full-Court active and every paid tool available from Pricing.')
    expect(pricingSource).toContain('Visit My Lab, Coach Hub, Team Hub, and League Office')
    expect(pricingSource).toContain('Open each tool for the player, coach, captain, or league task in front of you.')
    expect(pricingSource).toContain('Come back to Pricing when you need the next role path.')
    expect(pricingSource).toContain('Player need')
    expect(pricingSource).toContain('Coach need')
    expect(pricingSource).toContain('Captain need')
    expect(pricingSource).toContain('League or event need')
    expect(pricingSource).toContain('FULL_COURT_WORKSPACE_PASS')
    expect(pricingSource).toContain('FULL_COURT_WORKSPACE_FIT_PROOF')
    expect(pricingSource).toContain("href: '/mylab'")
    expect(pricingSource).toContain("href: '/coach'")
    expect(pricingSource).toContain("href: '/captain'")
    expect(pricingSource).toContain("href: '/league-coordinator'")
    expect(pricingSource).toContain('League is $14.99 per season for one bounded league, ladder, or tournament.')
    expect(pricingSource).toContain('then choose the right tools when your game, team, players, league, or tournament needs more support.')
    expect(pricingLayoutSource).toContain('Free, My Lab, Coach Hub, Team Hub, League Office, and Full-Court')
    expect(joinSource).toContain('Search players, teams, leagues, rankings, and tennis context first. Upgrade only when a specific tennis need calls for more support.')
    expect(joinSource).toContain('Search the tennis map first. Upgrade only when a specific tennis need calls for more support.')
    expect(joinSource).toContain('Full-Court starts with a free account, then opens My Lab, Coach Hub, Team Hub, League Office')
    expect(joinSource).toContain('Start free. Pick the tennis tools later.')
    expect(joinSource).toContain('Coach starts from Free, then opens Coach Hub for lessons, assignments, player proof, and follow-through.')
    expect(joinSource).toContain('Captain starts from Free, then opens Team Hub for availability, lineups, scouting, and team messages.')
    expect(joinSource).toContain('League starts from Free, then opens League Office for one season of schedules, scores, and standings.')
    expect(joinSource).toContain('one season or event tool')
    expect(joinSource).toContain('Support every tennis role.')
    expect(joinSource).toContain('Create your account. Support every tennis role.')
    expect(joinSource).toContain('Activate Full-Court next, then support players, teams, leagues, and events from one account.')
    expect(joinSource).toContain('activate Full-Court to support every tennis role.')
    expect(pricingSource).not.toContain('You, Coach, Team, or League')
    expect(pricingSource).not.toContain('League is $14.99/month')
    expect(pricingSource).not.toContain('Full-Court - Everything connected, including Tournament Desk')
    expect(pricingSource).not.toContain('Full-Court - Complete toolkit, including Tournament Desk')
    expect(pricingSource).not.toContain('Use the full toolkit')
    expect(pricingSource).not.toContain('Connect My Lab, Coach Hub, Team Hub, League Office')
    expect(pricingSource).not.toContain('Full-Court tool fit proof cue')
    expect(pricingSource).not.toContain('Full-Court role switching proof cue')
    expect(pricingSource).not.toContain('Prove every paid tool opens without stale locks.')
    expect(pricingSource).not.toContain('without stale locks or repeated upgrade prompts')
    expect(pricingSource).not.toContain('Confirm each tool opens')
    expect(pricingSource).not.toContain('role-switching confusion')
    expect(pricingSource).not.toContain('open the role workspace that saves your week')
    expect(pricingSource).not.toContain('season workspace')
    expect(pricingSource).not.toContain('All paid workspaces are active.')
    expect(pricingSource).not.toContain('Prove every paid workspace opens without stale locks.')
    expect(pricingSource).not.toContain('Search players, teams, leagues, rankings, tournaments, coaches, and tennis resources before choosing a paid workspace.')
    expect(pricingSource).not.toContain('then unlock the workspace that matches your tennis job')
    expect(pricingSource).not.toContain('then unlock the home base that matches your tennis job')
    expect(pricingSource).not.toContain('next tennis job')
    expect(pricingSource).not.toContain('home base')
    expect(pricingSource).not.toContain('then choose the next tennis job that needs a workspace.')
    expect(pricingSource).not.toContain('paid plans unlock the workspace behind the work')
    expect(joinSource).not.toContain('the full suite')
    expect(joinSource).not.toContain('the full toolkit')
    expect(joinSource).not.toContain('full toolkit')
    expect(joinSource).not.toContain('complete toolkit')
    expect(joinSource).not.toContain('open one connected tennis operation')
    expect(joinSource).not.toContain('Create your account. Run the full court.')
    expect(joinSource).not.toContain('Start free. Add workspaces when you need them.')
    expect(joinSource).not.toContain('Upgrade only when a specific job needs a workspace.')
    expect(joinSource).not.toContain('Upgrade only when a specific tennis job needs a workspace.')
    expect(joinSource).not.toContain('Upgrade only when a specific tennis job needs a home base.')
    expect(joinSource).not.toContain('tennis job')
    expect(joinSource).not.toContain('TenAceIQ will point you to the right next step after signup.')
    expect(joinSource).not.toContain('Explore the tennis map first. Upgrade only when a workspace saves you time.')
    expect(joinSource).not.toContain('open the full tennis operations workspace')
    expect(`${pricingSource}\n${pricingLayoutSource}\n${joinSource}`).not.toContain('Player, Coach, Captain, League, and unlimited tournaments')
  })
})
