import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const pricingSource = readFileSync(join(process.cwd(), 'app/pricing/page.tsx'), 'utf8')
const pricingLayoutSource = readFileSync(join(process.cwd(), 'app/pricing/layout.tsx'), 'utf8')
const joinSource = readFileSync(join(process.cwd(), 'app/join/page.tsx'), 'utf8')

describe('pricing simplification', () => {
  it('keeps pricing organized around the five decision sections', () => {
    expect(pricingSource).toContain('Choose by tennis need')
    expect(pricingSource).toContain('Start from what you are trying to do.')
    expect(pricingSource).toContain('JOB_CHOOSER')
    expect(pricingSource).toContain('Find tennis context')
    expect(pricingSource).toContain('Improve my game')
    expect(pricingSource).toContain('Captain match week')
    expect(pricingSource).toContain('Run a season or event')
    expect(pricingSource).toContain('Choose your role')
    expect(pricingSource).toContain('See the workspace')
    expect(pricingSource).toContain('Compare what unlocks')
    expect(pricingSource).toContain('Billing clarity')
    expect(pricingSource).toContain('Start free / upgrade')
  })

  it('uses public workspace naming and consistent League billing', () => {
    expect(pricingSource).toContain('Player - My Lab for your game')
    expect(pricingSource).toContain('Coach - Coach Hub for player development')
    expect(pricingSource).toContain('Captain - Team Hub for match week')
    expect(pricingSource).toContain('League - League Office for a season')
    expect(pricingSource).toContain('Full-Court - Complete toolkit, including Tournament Desk')
    expect(pricingSource).toContain('Connect My Lab, Coach Hub, Team Hub, League Office')
    expect(pricingSource).toContain('const PLAN_JOB_FIT')
    expect(pricingSource).toContain('You need Team Hub to collect availability, compare lineups, scout, and send the match-week plan.')
    expect(pricingSource).toContain('You support more than one tennis role and need My Lab, Coach Hub, Team Hub, League Office, and Tournament Desk connected.')
    expect(pricingSource).toContain('paid plans unlock the right tools when the work gets specific.')
    expect(pricingSource).toContain('Full-Court access pass')
    expect(pricingSource).toContain('Start free, then unlock the right TenAceIQ tools: My Lab, Coach Hub, Team Hub, League Office, or Full-Court.')
    expect(pricingSource).toContain('Search players, teams, leagues, rankings, tournaments, coaches, and tennis resources before choosing paid tools.')
    expect(pricingSource).toContain('All paid workspaces are active.')
    expect(pricingSource).toContain('without stale locks or repeated upgrade prompts')
    expect(pricingSource).toContain('Full-Court workspace fit proof cue')
    expect(pricingSource).toContain('Pick the right tool for the tennis need.')
    expect(pricingSource).toContain('Full-Court role switching proof cue')
    expect(pricingSource).toContain('Prove every paid workspace opens without stale locks.')
    expect(pricingSource).toContain('FULL_COURT_ROLE_SWITCHING_PROOF')
    expect(pricingSource).toContain('Begin on Pricing with the Full-Court plan marked active')
    expect(pricingSource).toContain('Visit My Lab, Coach Hub, Team Hub, and League Office')
    expect(pricingSource).toContain('Come back to Pricing and choose the next workspace')
    expect(pricingSource).toContain('Player need')
    expect(pricingSource).toContain('Coach need')
    expect(pricingSource).toContain('Captain need')
    expect(pricingSource).toContain('League or event need')
    expect(pricingSource).toContain('FULL_COURT_WORKSPACE_PASS')
    expect(pricingSource).toContain('FULL_COURT_WORKSPACE_FIT_PROOF')
    expect(pricingSource).toContain("href: '/mylab'")
    expect(pricingSource).toContain("href: '/coach'")
    expect(pricingSource).toContain("href: '/captain'")
    expect(pricingSource).toContain("href: '/league-coordinator'")
    expect(pricingSource).toContain('League is $14.99 per season workspace')
    expect(pricingSource).toContain('then choose the right tools when your game, team, players, league, or tournament needs more support.')
    expect(pricingLayoutSource).toContain('Free, My Lab, Coach Hub, Team Hub, League Office, and Full-Court')
    expect(joinSource).toContain('Search players, teams, leagues, rankings, and tennis context first. Upgrade only when a specific tennis need calls for more support.')
    expect(joinSource).toContain('Search the tennis map first. Upgrade only when a specific tennis need calls for more support.')
    expect(joinSource).toContain('Full-Court starts with a free account, then unlocks My Lab, Coach Hub, Team Hub, League Office')
    expect(joinSource).toContain('Start free. Pick the tennis tools later.')
    expect(joinSource).toContain('Coach starts from Free, then opens Coach Hub for lessons, assignments, player proof, and follow-through.')
    expect(joinSource).toContain('Captain starts from Free, then opens Team Hub for availability, lineups, scouting, and team messages.')
    expect(joinSource).toContain('League starts from Free, then opens League Office for one season of schedules, scores, and standings.')
    expect(joinSource).toContain('Set up the full toolkit.')
    expect(joinSource).toContain('Create your account. Unlock the full toolkit.')
    expect(joinSource).toContain('Activate Full-Court next, then open one connected tennis operation.')
    expect(joinSource).toContain('activate Full-Court to unlock the full toolkit.')
    expect(pricingSource).not.toContain('You, Coach, Team, or League')
    expect(pricingSource).not.toContain('League is $14.99/month')
    expect(pricingSource).not.toContain('Full-Court - Everything connected, including Tournament Desk')
    expect(pricingSource).not.toContain('open the role workspace that saves your week')
    expect(pricingSource).not.toContain('Search players, teams, leagues, rankings, tournaments, coaches, and tennis resources before choosing a paid workspace.')
    expect(pricingSource).not.toContain('then unlock the workspace that matches your tennis job')
    expect(pricingSource).not.toContain('then unlock the home base that matches your tennis job')
    expect(pricingSource).not.toContain('next tennis job')
    expect(pricingSource).not.toContain('home base')
    expect(pricingSource).not.toContain('then choose the next tennis job that needs a workspace.')
    expect(pricingSource).not.toContain('paid plans unlock the workspace behind the work')
    expect(joinSource).not.toContain('the full suite')
    expect(joinSource).not.toContain('Create your account. Run the full court.')
    expect(joinSource).not.toContain('Start free. Add workspaces when you need them.')
    expect(joinSource).not.toContain('Upgrade only when a specific job needs a workspace.')
    expect(joinSource).not.toContain('Upgrade only when a specific tennis job needs a workspace.')
    expect(joinSource).not.toContain('Upgrade only when a specific tennis job needs a home base.')
    expect(joinSource).not.toContain('tennis job')
    expect(joinSource).not.toContain('TenAceIQ will point you to the right next step after signup.')
    expect(joinSource).not.toContain('Explore the tennis map first. Upgrade only when a workspace saves you time.')
    expect(joinSource).not.toContain('open the full tennis operations workspace')
    expect(`${pricingSource}\n${pricingLayoutSource}\n${joinSource}`).not.toContain('Player, Coach, Captain, League, and unlimited tournaments')
  })
})
