import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const previewSource = readFileSync(join(process.cwd(), 'app/components/preview-homepage.tsx'), 'utf8')
const heroSource = readFileSync(join(process.cwd(), 'app/components/homepage-hero-responsive.tsx'), 'utf8')
const commandCenterSource = readFileSync(join(process.cwd(), 'app/components/public-command-center.tsx'), 'utf8')
const portalToolbarSource = readFileSync(join(process.cwd(), 'app/components/portal-tool-bar.tsx'), 'utf8')
const universalSearchSource = readFileSync(join(process.cwd(), 'app/components/universal-search.tsx'), 'utf8')

function styleBlock(source: string, name: string) {
  const pattern = new RegExp(`const ${name}: CSSProperties = \\{([\\s\\S]*?)\\n\\}`)
  return source.match(pattern)?.[1] ?? ''
}

describe('Public home mobile layout guards', () => {
  it('keeps active homepage grids minmax-safe on mobile and tablet', () => {
    expect(previewSource).not.toContain("? '1fr'")
    expect(previewSource).not.toContain("whiteSpace: 'nowrap'")
    expect(previewSource).not.toMatch(/minmax\([0-9]+px/)
    expect(previewSource).toContain("isTablet ? 'minmax(0, 1fr)'")
    expect(previewSource).toMatch(/isMobile\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(previewSource).toContain("isSmallMobile ? 'minmax(0, 1fr)'")
    expect(previewSource).toContain('minmax(min(100%, 360px), 0.96fr)')
    expect(previewSource).toContain('minmax(min(100%, 320px), 1.08fr)')
    expect(previewSource).toContain('overflowWrap: \'anywhere\'')
  })

  it('keeps preview homepage compact rows shrink-safe', () => {
    expect(previewSource).not.toContain("'auto minmax(min(100%, 132px), 160px) minmax(0, 1fr) auto'")
    expect(previewSource).not.toContain("'minmax(0, 1fr) auto'")
    expect(previewSource).not.toContain("'52px minmax(0, 1fr) auto auto'")
    expect(previewSource).not.toContain("'28px minmax(0, 1fr) auto auto'")
    expect(previewSource).not.toContain("'12px 1fr'")

    expect(previewSource).toContain("'minmax(0, auto) minmax(min(100%, 132px), 160px) minmax(0, 1fr) minmax(0, auto)'")
    expect(previewSource).toContain("'minmax(0, 52px) minmax(0, 1fr) minmax(0, auto) minmax(0, auto)'")
    expect(previewSource).toContain("'minmax(0, 28px) minmax(0, 1fr) minmax(0, auto) minmax(0, auto)'")
    expect(styleBlock(previewSource, 'captainSignalRowStyle')).toContain(
      "gridTemplateColumns: 'minmax(0, 1fr) minmax(0, auto)'",
    )
    expect(styleBlock(previewSource, 'bulletRowStyle')).toContain(
      "gridTemplateColumns: 'minmax(0, 12px) minmax(0, 1fr)'",
    )
  })

  it('keeps alternate hero component aligned with public home guards', () => {
    expect(heroSource).not.toContain("? '1fr'")
    expect(heroSource).toContain('Team Hub')
    expect(heroSource).not.toContain('Captain workspace')
    expect(heroSource).toContain('one team-ready view')
    expect(heroSource).not.toContain('one premium workflow')
    expect(heroSource).toContain('Explore Tennis')
    expect(heroSource).not.toContain('Explore the platform')
    expect(heroSource).toContain("const heroGrid = isTablet ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain("const statGrid = isMobile ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain("const featureGrid = isMobile ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain('minWidth: 0')
  })

  it('keeps the active public command-center homepage mobile-safe', () => {
    expect(styleBlock(commandCenterSource, 'heroStyle')).toContain(
      "gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))'",
    )
    expect(commandCenterSource).not.toContain('10vw')
    expect(styleBlock(commandCenterSource, 'heroCopyStyle')).toContain("containerType: 'inline-size'")
    expect(styleBlock(commandCenterSource, 'heroTitleStyle')).toContain("fontSize: 'clamp(2.45rem, 10cqw, 4rem)'")
    expect(styleBlock(commandCenterSource, 'heroBodyStyle')).toContain("fontSize: 'clamp(0.98rem, 2.4cqw, 1.12rem)'")
    expect(styleBlock(commandCenterSource, 'heroCopyStyle')).toContain("boxSizing: 'border-box'")
    expect(styleBlock(commandCenterSource, 'heroPanelStyle')).toContain("boxSizing: 'border-box'")
    expect(styleBlock(commandCenterSource, 'heroTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(commandCenterSource, 'primaryButtonStyle')).toContain("whiteSpace: 'normal'")
    expect(styleBlock(commandCenterSource, 'homePrimaryCtaStyle')).toContain("width: '100%'")
    expect(styleBlock(commandCenterSource, 'homePrimaryCtaStyle')).toContain("boxSizing: 'border-box'")
    expect(styleBlock(commandCenterSource, 'homeSecondaryCtaStyle')).toContain("alignItems: 'flex-start'")
    expect(styleBlock(commandCenterSource, 'homeCtaHeadingStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(commandCenterSource, 'homeCtaTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(commandCenterSource, 'homeCtaHelperStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(commandCenterSource, 'homeCtaAudienceStyle')).toContain("textTransform: 'uppercase'")
    expect(commandCenterSource).toContain('Choose your path')
    expect(commandCenterSource).toContain('Start with the tennis need you have today.')
    expect(commandCenterSource).toContain("audience: 'Players'")
    expect(commandCenterSource).toContain("audience: 'Coaches'")
    expect(commandCenterSource).toContain("helper: 'Search players, teams, leagues, and rankings.'")
    expect(commandCenterSource).toContain("helper: 'Find drills, skills, and training paths.'")
  })

  it('keeps the persistent public portal toolbar from becoming a clipped mobile rail', () => {
    expect(portalToolbarSource).not.toContain("display: publicVisitor && isMobile ? 'flex' : 'grid'")
    expect(portalToolbarSource).not.toContain("overflowX: publicVisitor && isMobile ? 'auto' : undefined")
    expect(portalToolbarSource).not.toContain("flex: '0 0 154px'")
    expect(portalToolbarSource).toContain('screenWidth < 360')
    expect(portalToolbarSource).toContain("'repeat(2, minmax(0, 1fr))'")
    expect(portalToolbarSource).toContain("const compactMobileLaneCardStyle")
    expect(styleBlock(portalToolbarSource, 'compactMobileLaneCardStyle')).toContain("width: '100%'")
    expect(styleBlock(portalToolbarSource, 'compactMobileLaneCardStyle')).toContain("boxSizing: 'border-box'")
  })

  it('keeps the persistent mobile portal as a docked two-level icon palette', () => {
    expect(portalToolbarSource).toContain('const [mobilePortalLaneState, setMobilePortalLaneState] = useState<{ pathname: string; laneId: PortalLaneId | null }>')
    expect(portalToolbarSource).toContain('const mobilePortalLaneId = mobilePortalLaneState.pathname === pathname ? mobilePortalLaneState.laneId : null')
    expect(portalToolbarSource).toContain("const showPortalBrandRunway = publicVisitor && pathname === '/' && !isMobile")
    expect(portalToolbarSource).toContain('const collapseMobilePortal = isMobile')
    expect(portalToolbarSource).toContain('const mobilePortalLane = mobilePortalLaneId ? portalLanes.find')
    expect(portalToolbarSource).toContain('const [currentHash, setCurrentHash] = useState')
    expect(portalToolbarSource).toContain('const currentPortalPath = `${pathname}${currentHash}`')
    expect(portalToolbarSource).toContain('const mobilePortalHasActiveTask = mobilePortalLane')
    expect(portalToolbarSource).toContain('active={!mobilePortalHasActiveTask && pathname === mobilePortalLane.route && !currentHash}')
    expect(portalToolbarSource).toContain('active={isPortalTaskActive(currentPortalPath, task.href)}')
    expect(portalToolbarSource).toContain("const mobilePortalStickyTop = 'var(--header-height)'")
    expect(portalToolbarSource).toContain('const showExpandedPortalIntro = !collapseMobilePortal')
    expect(portalToolbarSource).toContain("const portalMenuId = 'tenaceiq-mobile-portal-menu'")
    expect(portalToolbarSource).toContain("aria-label={mobilePortalLane ? `${mobilePortalLane.label} actions` : 'Main TenAceIQ menu'}")
    expect(portalToolbarSource).toContain('aria-live="polite"')
    expect(portalToolbarSource).toContain('MobilePortalHubTile')
    expect(portalToolbarSource).toContain('getMobileHubLabel')
    expect(portalToolbarSource).toContain("aria-label={`${getMobileLaneLabel(lane.id)} hub${target.locked ? ' locked' : ''}: ${lane.cue}`}")
    expect(portalToolbarSource).toContain('MobilePortalTaskTile')
    expect(portalToolbarSource).toContain('getMobileLaneLabel')
    expect(portalToolbarSource).toContain('getMobileTaskLabel')
    expect(portalToolbarSource).toContain("aria-label={`${target.title}${target.locked ? ' locked' : ''}: ${task.detail}`}")
    expect(portalToolbarSource).toContain("position: collapseMobilePortal ? 'sticky' : 'relative'")
    expect(portalToolbarSource).toContain('top: collapseMobilePortal ? mobilePortalStickyTop : undefined')
    expect(portalToolbarSource).toContain("zIndex: collapseMobilePortal ? 32 : 25")
    expect(portalToolbarSource).toContain('background: collapseMobilePortal ? mobilePortalDockBackground : undefined')
    expect(portalToolbarSource).not.toContain('overflowY: mobilePortalOpen')
    expect(portalToolbarSource).not.toContain('maxHeight: mobilePortalOpen')
    expect(portalToolbarSource).not.toContain('mobilePortalFlowHeight')
    expect(portalToolbarSource).toContain('showExpandedPortalIntro ? (')
    expect(portalToolbarSource).toContain('style={mobilePortalLane ? mobilePortalActionPaletteStyle : mobilePortalPaletteStyle}')
    expect(portalToolbarSource).toContain('onClick={handleMobilePortalMainSelect}')
    expect(portalToolbarSource).toContain('onClick={(event) => handleMobilePortalLaneSelect(event, lane.id)}')
    expect(portalToolbarSource).toContain('onClick={(event) => onActivate(event, target.href)}')
    expect(portalToolbarSource).toContain('event.currentTarget.blur()')
    expect(portalToolbarSource).toContain('setCurrentHash(target.hash || \'\')')
    expect(styleBlock(portalToolbarSource, 'mobilePortalPaletteStyle')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalActionPaletteStyle')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
    expect(portalToolbarSource).toContain('mobilePortalLane.tasks.slice(0, 4)')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain('gridTemplateRows')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain('minHeight: 48')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain("touchAction: 'manipulation'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain("WebkitTapHighlightColor: 'transparent'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalBackTileStyle')).toContain("background: 'rgba(255,255,255,0.03)'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileIconStyle')).toContain('width: 24')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileLabelStyle')).toContain('fontSize: 9.75')
    expect(portalToolbarSource).toContain("if (laneId === 'you') return 'Improve Hub'")
    expect(portalToolbarSource).toContain("if (title === 'Player bench') return 'Bench'")
    expect(portalToolbarSource).toContain("if (title === 'Open My Lab') return 'My Lab'")
    expect(portalToolbarSource).toContain("if (title === 'Fix tennis context') return 'Fix context'")
  })

  it('keeps public hub routes mapped to the right mobile portal lane', () => {
    expect(portalToolbarSource).toContain("paths: ['/coach', '/coaches', '/player-development', '/tactics']")
    expect(portalToolbarSource).toContain("paths: ['/captain', '/manage', '/compete/teams']")
    expect(portalToolbarSource).toContain("'/player-development', '/resources', '/tactics'")
    expect(portalToolbarSource).toContain("from '@/lib/tactics-hrefs'")
    expect(portalToolbarSource).toContain('href: PLAYER_TACTICS_BOARD_HREF')
    expect(portalToolbarSource).toContain('href: COACH_TACTICS_BOARD_HREF')
    expect(portalToolbarSource).toContain('href: CAPTAIN_TACTICS_BOARD_HREF')
    expect(portalToolbarSource).not.toContain("href: '/tactics'")
    expect(portalToolbarSource).toContain("paths: ['/leagues-and-tournaments', '/league-coordinator', '/tournaments'")
  })

  it('keeps mobile universal search actionable in one compact row', () => {
    expect(universalSearchSource).toContain("'minmax(0, 1fr) minmax(84px, auto)'")
    expect(universalSearchSource).toContain('gap: isMobile ? 8 : 10')
    expect(universalSearchSource).toContain('aria-label="Search TenAceIQ"')
    expect(universalSearchSource).toContain("{isMobile ? 'Search' : 'Search Tennis'}")
  })
})
