import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const previewSource = readFileSync(join(process.cwd(), 'app/components/preview-homepage.tsx'), 'utf8')
const heroSource = readFileSync(join(process.cwd(), 'app/components/homepage-hero-responsive.tsx'), 'utf8')
const homePageSource = readFileSync(join(process.cwd(), 'app/page.tsx'), 'utf8')
const commandCenterSource = readFileSync(join(process.cwd(), 'app/components/public-command-center.tsx'), 'utf8')
const portalToolbarSource = readFileSync(join(process.cwd(), 'app/components/portal-tool-bar.tsx'), 'utf8')
const siteShellSource = readFileSync(join(process.cwd(), 'app/components/site-shell.tsx'), 'utf8')
const siteFooterSource = readFileSync(join(process.cwd(), 'app/components/site-footer.tsx'), 'utf8')
const universalSearchSource = readFileSync(join(process.cwd(), 'app/components/universal-search.tsx'), 'utf8')
const shellSmokeSource = readFileSync(join(process.cwd(), 'scripts/site-shell-layout-smoke.mjs'), 'utf8')

function styleBlock(source: string, name: string) {
  const pattern = new RegExp(`const ${name}: CSSProperties = \\{([\\s\\S]*?)\\n\\}`)
  return source.match(pattern)?.[1] ?? ''
}

describe('Public home mobile layout guards', () => {
  it('keeps active homepage grids minmax-safe on mobile and tablet', () => {
    expect(previewSource).not.toContain("? '1fr'")
    expect(previewSource).not.toContain("whiteSpace: 'nowrap'")
    expect(previewSource).not.toMatch(/minmax\([0-9]+px/)
    expect(previewSource).toContain("isTablet ? 'minmax(0, 1fr)'")
    expect(previewSource).toMatch(/isMobile\s*\?\s*'minmax\(0, 1fr\)'/)
    expect(previewSource).toContain("isSmallMobile ? 'minmax(0, 1fr)'")
    expect(previewSource).toContain('minmax(min(100%, 360px), 0.96fr)')
    expect(previewSource).toContain('minmax(min(100%, 320px), 1.08fr)')
    expect(previewSource).toContain('overflowWrap: \'anywhere\'')
  })

  it('keeps preview homepage compact rows shrink-safe', () => {
    expect(previewSource).not.toContain("'auto minmax(min(100%, 132px), 160px) minmax(0, 1fr) auto'")
    expect(previewSource).not.toContain("'minmax(0, 1fr) auto'")
    expect(previewSource).not.toContain("'52px minmax(0, 1fr) auto auto'")
    expect(previewSource).not.toContain("'28px minmax(0, 1fr) auto auto'")
    expect(previewSource).not.toContain("'12px 1fr'")

    expect(previewSource).toContain("'minmax(0, auto) minmax(min(100%, 132px), 160px) minmax(0, 1fr) minmax(0, auto)'")
    expect(previewSource).toContain("'minmax(0, 52px) minmax(0, 1fr) minmax(0, auto) minmax(0, auto)'")
    expect(previewSource).toContain("'minmax(0, 28px) minmax(0, 1fr) minmax(0, auto) minmax(0, auto)'")
    expect(styleBlock(previewSource, 'captainSignalRowStyle')).toContain(
      "gridTemplateColumns: 'minmax(0, 1fr) minmax(0, auto)'",
    )
    expect(styleBlock(previewSource, 'bulletRowStyle')).toContain(
      "gridTemplateColumns: 'minmax(0, 12px) minmax(0, 1fr)'",
    )
  })

  it('keeps alternate hero component aligned with public home guards', () => {
    expect(heroSource).not.toContain("? '1fr'")
    expect(heroSource).toContain('Team Hub')
    expect(heroSource).not.toContain('Captain workspace')
    expect(heroSource).toContain('one team-ready view')
    expect(heroSource).not.toContain('one premium workflow')
    expect(heroSource).toContain('Explore Tennis')
    expect(heroSource).not.toContain('Explore the platform')
    expect(heroSource).toContain("const heroGrid = isTablet ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain("const statGrid = isMobile ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain("const featureGrid = isMobile ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain("gridTemplateColumns: isMobile ? 'minmax(0, 1fr)'")
    expect(heroSource).toContain('minWidth: 0')
  })

  it('keeps the active public command-center homepage mobile-safe', () => {
    expect(styleBlock(commandCenterSource, 'heroStyle')).toContain(
      "gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))'",
    )
    expect(commandCenterSource).not.toContain('10vw')
    expect(styleBlock(commandCenterSource, 'heroCopyStyle')).toContain("containerType: 'inline-size'")
    expect(styleBlock(commandCenterSource, 'heroCopyStyle')).toContain("padding: 'clamp(14px, 4cqw, 22px)'")
    expect(styleBlock(commandCenterSource, 'heroTitleStyle')).toContain("fontSize: 'clamp(2.05rem, 9cqw, 3.7rem)'")
    expect(styleBlock(commandCenterSource, 'heroBodyStyle')).toContain("fontSize: 'clamp(0.9rem, 2.2cqw, 1.08rem)'")
    expect(styleBlock(universalSearchSource, 'mobileInputStyle')).toContain('minHeight: 48')
    expect(styleBlock(universalSearchSource, 'mobileButtonStyle')).toContain('minHeight: 48')
    expect(styleBlock(commandCenterSource, 'heroCopyStyle')).toContain("boxSizing: 'border-box'")
    expect(styleBlock(commandCenterSource, 'heroPanelStyle')).toContain("boxSizing: 'border-box'")
    expect(commandCenterSource).not.toContain('miniCourtStyle')
    expect(commandCenterSource).toContain('Quick actions')
    expect(commandCenterSource).toContain('Pick the job, then move.')
    expect(commandCenterSource).toContain('Search when you know the name.')
    expect(styleBlock(commandCenterSource, 'heroBoardGridStyle')).toContain(
      "gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 150px), 1fr))'",
    )
    expect(styleBlock(commandCenterSource, 'heroBoardActionStyle')).toContain('minHeight: 50')
    expect(shellSmokeSource).toContain("type: 'home-hero-too-tall'")
    expect(shellSmokeSource).toContain('homeHeroHeightLimit')
    expect(shellSmokeSource).toContain("viewport.name === 'mobile' ? 850")
    expect(styleBlock(commandCenterSource, 'heroTitleStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock(commandCenterSource, 'primaryButtonStyle')).toContain("whiteSpace: 'normal'")
    expect(commandCenterSource).toContain('Next best step')
    expect(commandCenterSource).toContain('Pick the job in front of you.')
    expect(commandCenterSource).toContain('A lighter board for the common tennis needs')
    expect(commandCenterSource).toContain('Decision board')
    expect(commandCenterSource).toContain('Choose once, then move into the lane or tool that matches the work.')
    expect(styleBlock(commandCenterSource, 'actionListStyle')).toContain(
      "gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 390px), 1fr))'",
    )
    expect(styleBlock(commandCenterSource, 'actionRowCardStyle')).toContain('minWidth: 0')
    expect(commandCenterSource).toContain('aria-label={`${card.title}: ${card.body}`}')
    expect(commandCenterSource).not.toContain('actionRowBodyStyle')
    expect(commandCenterSource).toContain("title: 'Find Player Insights'")
    expect(commandCenterSource).toContain("title: 'Run a League or Tournament'")
    expect(commandCenterSource).not.toContain('HomeCtaGrid')
    expect(commandCenterSource).not.toContain('AudiencePathGrid')
    expect(commandCenterSource).not.toContain('Choose your path')
    expect(commandCenterSource).not.toContain('Who it helps')
    expect(commandCenterSource).not.toContain('Every path explains who it helps')
    expect(homePageSource).toContain('<ActionGrid />')
    expect(homePageSource).not.toContain('homeTierPromiseStyle')
    expect(homePageSource).not.toContain('Start free, then unlock My Lab, Coach Hub, Team Hub')
    expect(homePageSource).not.toContain('<HomeCtaGrid />')
    expect(homePageSource).not.toContain('<AudiencePathGrid />')
  })

  it('keeps desktop and tablet portal navigation frozen while the content lane scrolls', () => {
    expect(siteShellSource).toContain('data-portal-content-scroll="true"')
    expect(styleBlock(siteShellSource, 'portalRailLayoutStyle')).toContain("height: 'calc(100dvh - var(--header-height))'")
    expect(styleBlock(siteShellSource, 'portalRailLayoutStyle')).toContain("overflow: 'hidden'")
    expect(styleBlock(siteShellSource, 'portalRailScrollStyle')).toContain("overflowY: 'auto'")
    expect(styleBlock(siteShellSource, 'portalRailScrollStyle')).toContain("overscrollBehavior: 'contain'")
    expect(siteShellSource).toContain('<SiteFooter railLayout railWidth={0} />')
    expect(siteFooterSource).toContain("document.querySelector('[data-portal-content-scroll=\"true\"]')")
    expect(siteFooterSource).toContain('portalScroller.scrollTo({ top: 0, behavior: \'smooth\' })')
    expect(shellSmokeSource).toContain("type: 'portal-content-scroll-missing'")
    expect(shellSmokeSource).toContain("type: 'portal-window-scrolled-with-content'")
    expect(shellSmokeSource).toContain("type: 'portal-header-moved-during-content-scroll'")
    expect(shellSmokeSource).toContain("type: 'portal-rail-moved-during-content-scroll'")
  })

  it('keeps the persistent public portal toolbar from becoming a clipped mobile rail', () => {
    expect(portalToolbarSource).not.toContain("import { SITE_HEADER_COMPACT_BREAKPOINT } from '@/lib/site-header-responsive'")
    expect(portalToolbarSource).toContain('const showPortalLanePicker = !collapseMobilePortal')
    expect(portalToolbarSource).toContain('{showPortalLanePicker ? (')
    expect(portalToolbarSource).not.toContain("display: publicVisitor && isMobile ? 'flex' : 'grid'")
    expect(portalToolbarSource).not.toContain("overflowX: publicVisitor && isMobile ? 'auto' : undefined")
    expect(portalToolbarSource).not.toContain("flex: '0 0 154px'")
    expect(portalToolbarSource).toContain('const desktopPortalCommandGridStyle')
    expect(portalToolbarSource).toContain('const desktopPortalMemberCommandGridStyle')
    expect(portalToolbarSource).toContain('const desktopPortalRailStyle')
    expect(portalToolbarSource).toContain('const desktopPortalMainStyle')
    expect(portalToolbarSource).toContain('const desktopPortalSummaryStyle')
    expect(portalToolbarSource).toContain('Active path')
    expect(portalToolbarSource).toContain('const desktopPortalLaneGridStyle')
    expect(portalToolbarSource).toContain('const desktopPortalMemberLaneGridStyle')
    expect(portalToolbarSource).toContain('const signedInPortalTitleStyle')
    expect(portalToolbarSource).toContain('const denseDesktopLaneCardStyle')
    expect(portalToolbarSource).toContain('const denseDesktopLaneCueStyle')
    expect(portalToolbarSource).toContain('const useDenseDesktopPortalRail = authenticated && !isMobile')
    expect(portalToolbarSource).toContain('const useCompactPortalControls = publicVisitor || !isMobile')
    expect(portalToolbarSource).toContain('showPortalBrandRunway && !useCompactPortalControls')
    expect(portalToolbarSource).toContain('...(useDenseDesktopPortalRail ? desktopPortalMemberCommandGridStyle : null)')
    expect(portalToolbarSource).toContain('...(useDenseDesktopPortalRail ? desktopPortalMemberLaneGridStyle : null)')
    expect(portalToolbarSource).toContain('dense={useDenseDesktopPortalRail}')
    expect(styleBlock(portalToolbarSource, 'desktopPortalCommandGridStyle')).toContain(
      "gridTemplateColumns: 'minmax(min(100%, 240px), 0.52fr) minmax(0, 1.48fr)'",
    )
    expect(styleBlock(portalToolbarSource, 'desktopPortalMemberCommandGridStyle')).toContain(
      "gridTemplateColumns: 'minmax(min(100%, 360px), 0.72fr) minmax(0, 1.28fr)'",
    )
    expect(styleBlock(portalToolbarSource, 'desktopPortalLaneGridStyle')).toContain("gridTemplateColumns: 'minmax(0, 1fr)'")
    expect(styleBlock(portalToolbarSource, 'desktopPortalMemberLaneGridStyle')).toContain("gridTemplateColumns: 'repeat(2, minmax(0, 1fr))'")
    expect(styleBlock(portalToolbarSource, 'signedInPortalTitleStyle')).toContain("fontSize: 'clamp(1.35rem, 2.4vw, 2.05rem)'")
    expect(styleBlock(portalToolbarSource, 'denseDesktopLaneCardStyle')).toContain('minHeight: 42')
    expect(styleBlock(portalToolbarSource, 'denseDesktopLaneCueStyle')).toContain("display: 'none'")
    expect(portalToolbarSource).toContain("const compactMobileLaneCardStyle")
    expect(styleBlock(portalToolbarSource, 'compactMobileLaneCardStyle')).toContain("width: '100%'")
    expect(styleBlock(portalToolbarSource, 'compactMobileLaneCardStyle')).toContain("boxSizing: 'border-box'")
  })

  it('keeps the persistent mobile portal as a docked two-level icon palette', () => {
    expect(portalToolbarSource).toContain('const [mobilePortalLaneState, setMobilePortalLaneState] = useState<{ pathname: string; laneId: PortalLaneId | null }>')
    expect(portalToolbarSource).toContain('const mobilePortalLaneId = mobilePortalLaneState.pathname === pathname ? mobilePortalLaneState.laneId : null')
    expect(portalToolbarSource).toContain("const showPortalBrandRunway = publicVisitor && pathname === '/' && !isMobile")
    expect(portalToolbarSource).toContain('const collapseMobilePortal = isMobile')
    expect(portalToolbarSource).toContain('const mobilePortalLane = mobilePortalLaneId ? portalLanes.find')
    expect(portalToolbarSource).toContain('const [currentHash, setCurrentHash] = useState')
    expect(portalToolbarSource).toContain('const currentPortalPath = `${pathname}${currentHash}`')
    expect(portalToolbarSource).toContain('const mobilePortalHasActiveTask = mobilePortalLane')
    expect(portalToolbarSource).toContain('active={!mobilePortalHasActiveTask && pathname === mobilePortalLane.route && !currentHash}')
    expect(portalToolbarSource).toContain('active={isPortalTaskActive(currentPortalPath, task.href)}')
    expect(portalToolbarSource).toContain("const mobilePortalStickyTop = 'var(--header-height)'")
    expect(portalToolbarSource).toContain('const showExpandedPortalIntro = !collapseMobilePortal')
    expect(portalToolbarSource).toContain("const portalMenuId = 'tenaceiq-mobile-portal-menu'")
    expect(portalToolbarSource).toContain("const portalActionMenuId = 'tenaceiq-mobile-portal-actions'")
    expect(portalToolbarSource).toContain('id={mobilePortalLane ? portalActionMenuId : portalMenuId}')
    expect(portalToolbarSource).toContain("data-mobile-portal-palette={mobilePortalLane ? 'actions' : 'lanes'}")
    expect(portalToolbarSource).toContain("aria-label={mobilePortalLane ? `${mobilePortalLane.label} actions` : 'Main TenAceIQ menu'}")
    expect(portalToolbarSource).toContain('aria-live="polite"')
    expect(portalToolbarSource).toContain('MobilePortalHubTile')
    expect(portalToolbarSource).toContain('MobilePortalLaneButton')
    expect(portalToolbarSource).toContain('const label = getMobileLaneLabel(lane.id)')
    expect(portalToolbarSource).toContain('aria-label={`${label}: ${lane.cue}`}')
    expect(portalToolbarSource).toContain('getMobileHubLabel')
    expect(portalToolbarSource).toContain('data-mobile-portal-action={`${lane.id}-hub`}')
    expect(portalToolbarSource).toContain("aria-label={`${getMobileLaneLabel(lane.id)} hub${target.locked ? ' locked' : ''}: ${lane.cue}`}")
    expect(portalToolbarSource).toContain('MobilePortalTaskTile')
    expect(portalToolbarSource).toContain('getMobileLaneLabel')
    expect(portalToolbarSource).toContain('getMobileTaskLabel')
    expect(portalToolbarSource).toContain('getMobileActionKey')
    expect(portalToolbarSource).toContain('data-mobile-portal-action={getMobileActionKey(target.title)}')
    expect(portalToolbarSource).toContain("aria-label={`${target.title}${target.locked ? ' locked' : ''}: ${task.detail}`}")
    expect(portalToolbarSource).toContain("position: collapseMobilePortal ? 'sticky' : 'relative'")
    expect(portalToolbarSource).toContain('top: collapseMobilePortal ? mobilePortalStickyTop : undefined')
    expect(portalToolbarSource).toContain("zIndex: collapseMobilePortal ? 32 : 25")
    expect(portalToolbarSource).toContain('background: collapseMobilePortal ? mobilePortalDockBackground : undefined')
    expect(portalToolbarSource).not.toContain('overflowY: mobilePortalOpen')
    expect(portalToolbarSource).not.toContain('maxHeight: mobilePortalOpen')
    expect(portalToolbarSource).not.toContain('mobilePortalFlowHeight')
    expect(portalToolbarSource).toContain('showExpandedPortalIntro ? (')
    expect(portalToolbarSource).toContain('style={mobilePortalLane ? mobilePortalActionPaletteStyle : mobilePortalPaletteStyle}')
    expect(portalToolbarSource).toContain('onClick={handleMobilePortalMainSelect}')
    expect(portalToolbarSource).toContain('data-mobile-portal-action="main"')
    expect(portalToolbarSource).toContain('onSelect={handleMobilePortalLaneSelect}')
    expect(portalToolbarSource).toContain('onClick={(event) => onSelect(event, lane.id)}')
    expect(portalToolbarSource).toContain('data-mobile-portal-lane={lane.id}')
    expect(portalToolbarSource).toContain('controlsId={portalActionMenuId}')
    expect(portalToolbarSource).toContain('expanded={mobilePortalLaneId === lane.id}')
    expect(portalToolbarSource).toContain('aria-controls={controlsId}')
    expect(portalToolbarSource).toContain('aria-expanded={expanded}')
    expect(portalToolbarSource).toContain('aria-controls={portalMenuId}')
    expect(portalToolbarSource).toContain('onClick={(event) => onActivate(event, target.href)}')
    expect(portalToolbarSource).toContain('event.currentTarget.blur()')
    expect(portalToolbarSource).toContain('setCurrentHash(target.hash || \'\')')
    expect(styleBlock(portalToolbarSource, 'mobilePortalPaletteStyle')).toContain("gridAutoFlow: 'column'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalPaletteStyle')).toContain("gridAutoColumns: 'minmax(70px, 1fr)'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalPaletteStyle')).toContain("overflowX: 'auto'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalPaletteStyle')).toContain("scrollSnapType: 'x proximity'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalActionPaletteStyle')).not.toContain('gridTemplateColumns')
    expect(portalToolbarSource).toContain('mobilePortalLane.tasks.slice(0, 4)')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain('gridTemplateRows')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain('minHeight: 44')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain("touchAction: 'manipulation'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain("WebkitTapHighlightColor: 'transparent'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileStyle')).toContain("scrollSnapAlign: 'start'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalBackTileStyle')).toContain("background: 'rgba(255,255,255,0.03)'")
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileIconStyle')).toContain('width: 20')
    expect(styleBlock(portalToolbarSource, 'mobilePortalTileLabelStyle')).toContain('fontSize: 9.25')
    expect(portalToolbarSource).toContain("if (laneId === 'you') return 'Improve Hub'")
    expect(portalToolbarSource).toContain("return getMobileTaskLabel(title).toLowerCase().replace(/\\s+/g, '-')")
    expect(portalToolbarSource).toContain("if (title === 'Player bench') return 'Bench'")
    expect(portalToolbarSource).toContain("if (title === 'Open My Lab') return 'My Lab'")
    expect(portalToolbarSource).toContain("if (title === 'Fix tennis context') return 'Fix context'")
    expect(shellSmokeSource).toContain("type: 'mobile-portal-visible-under-header-menu'")
    expect(shellSmokeSource).toContain("type: 'mobile-portal-too-tall'")
    expect(shellSmokeSource).toContain("type: 'mobile-portal-lane-palette-missing'")
    expect(shellSmokeSource).toContain("type: 'mobile-portal-main-did-not-restore-lanes'")
    expect(shellSmokeSource).toContain('[data-mobile-portal-lane="compete"]')
    expect(shellSmokeSource).toContain('[data-mobile-portal-action="match-prep"]')
  })

  it('keeps public hub routes mapped to the right mobile portal lane', () => {
    expect(portalToolbarSource).toContain("paths: ['/coach', '/coaches', '/player-development', '/tactics']")
    expect(portalToolbarSource).toContain("paths: ['/captain', '/manage', '/compete/teams']")
    expect(portalToolbarSource).toContain("'/player-development', '/resources', '/tactics'")
    expect(portalToolbarSource).toContain("from '@/lib/tactics-hrefs'")
    expect(portalToolbarSource).toContain('href: PLAYER_TACTICS_BOARD_HREF')
    expect(portalToolbarSource).toContain('href: COACH_TACTICS_BOARD_HREF')
    expect(portalToolbarSource).toContain('href: CAPTAIN_TACTICS_BOARD_HREF')
    expect(portalToolbarSource).not.toContain("href: '/tactics'")
    expect(portalToolbarSource).toContain("paths: ['/leagues-and-tournaments', '/league-coordinator', '/tournaments'")
  })

  it('keeps mobile universal search actionable in one compact row', () => {
    expect(universalSearchSource).toContain("'minmax(0, 1fr) minmax(78px, auto)'")
    expect(universalSearchSource).toContain('gap: isMobile ? 7 : 10')
    expect(styleBlock(universalSearchSource, 'mobileInputStyle')).toContain('minHeight: 48')
    expect(styleBlock(universalSearchSource, 'mobileButtonStyle')).toContain('minHeight: 48')
    expect(universalSearchSource).toContain('aria-label="Search TenAceIQ"')
    expect(universalSearchSource).toContain('suppressHydrationWarning')
    expect(universalSearchSource).toContain("{isMobile ? 'Search' : 'Search Tennis'}")
  })
})
