import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const coachesSource = readFileSync(join(process.cwd(), 'app/coaches/page.tsx'), 'utf8')
const tournamentsSource = readFileSync(join(process.cwd(), 'app/tournaments/page.tsx'), 'utf8')
const commandCenterSource = readFileSync(join(process.cwd(), 'app/components/public-command-center.tsx'), 'utf8')

describe('public landing preview cards', () => {
  it('uses named coach preview cards with tracked product actions', () => {
    expect(coachesSource).toContain('TiqActionCard')
    expect(coachesSource).toContain('Coach development loop')
    expect(coachesSource).toContain('Assess, assign, track, and follow up without losing the thread.')
    expect(coachesSource).toContain('Know what the player needs')
    expect(coachesSource).toContain('Assign the next drill')
    expect(coachesSource).toContain('Track player development')
    expect(coachesSource).toContain('Support between sessions')
    expect(coachesSource).toContain('Assign Drills')
    expect(coachesSource).toContain('Track Development')
    expect(coachesSource).toContain('Recommend Resources')
    expect(coachesSource).toContain('Support Between Sessions')
    expect(coachesSource).toContain("location: 'coach_development_loop'")
    expect(coachesSource).toContain('Lesson loop')
    expect(coachesSource).toContain('Give every lesson a before, during, and after.')
    expect(coachesSource).toContain('Bring the right context')
    expect(coachesSource).toContain('Plan the court work')
    expect(coachesSource).toContain('Assign the next proof')
    expect(coachesSource).toContain('aria-labelledby="coach-lesson-loop-title"')
    expect(coachesSource).toContain('titleId="coach-lesson-loop-title"')
    expect(coachesSource).toContain('Coach path')
    expect(coachesSource).toContain('Assign, track, recommend, follow up.')
    expect(coachesSource).toContain('How can I assign drills?')
    expect(coachesSource).toContain('How can I track player development?')
    expect(coachesSource).toContain('How can I recommend resources?')
    expect(coachesSource).toContain('How can I support players between sessions?')
    expect(coachesSource).toContain('Assign Drills')
    expect(coachesSource).toContain('Track Development')
    expect(coachesSource).toContain('Recommend Resources')
    expect(coachesSource).toContain('Support Between Sessions')
    expect(coachesSource).toContain("eventName: 'coach_page_viewed'")
    expect(coachesSource).toContain("location: 'coaches_next_actions'")
    expect(coachesSource).not.toContain('Refresh player evidence')
    expect(coachesSource).toContain('TiqWorkspacePreview')
    expect(coachesSource).toContain('TiqCoachAssignmentCard')
    expect(coachesSource).toContain("eventName: 'coach_hub_clicked'")
    expect(coachesSource).toContain("eventName: 'coach_assignment_preview_clicked'")
    expect(coachesSource).toContain('context="Coaches trust strip"')
    expect(coachesSource).not.toContain('ProductPreviewGrid')
  })

  it('uses named tournament preview cards with Tournament Desk tracking', () => {
    expect(tournamentsSource).toContain('TiqTournamentDrawCard')
    expect(tournamentsSource).toContain('TiqWorkspacePreview')
    expect(tournamentsSource).toContain('TiqActionCard')
    expect(tournamentsSource).toContain("const tournamentDeskHref = '/join?plan=full_court&next=%2Fleague-coordinator%2Ftournaments'")
    expect(tournamentsSource).toContain('href={tournamentDeskHref}')
    expect(tournamentsSource).toContain('href: tournamentDeskHref')
    expect(tournamentsSource).toContain('Tournament next actions')
    expect(tournamentsSource).toContain('Pick the event job, then open the right tournament path.')
    expect(tournamentsSource).toContain('Find an event to play')
    expect(tournamentsSource).toContain('Follow a draw or court')
    expect(tournamentsSource).toContain('Run the event desk')
    expect(tournamentsSource).toContain('Plan the full competition')
    expect(tournamentsSource).toContain('Use the Leagues & Tournaments hub')
    expect(tournamentsSource).toContain("href: '/leagues-and-tournaments'")
    expect(tournamentsSource).toContain("cta: 'Open Organizer Hub'")
    expect(tournamentsSource).toContain('Report a draw or result issue')
    expect(tournamentsSource).toContain("location: 'tournament_next_actions'")
    expect(tournamentsSource).toContain("job: 'organize_competition'")
    expect(tournamentsSource).toContain('Find tournaments')
    expect(tournamentsSource).toContain('Search Events')
    expect(tournamentsSource).toContain('Preview Draws')
    expect(tournamentsSource).toContain('Open Desk')
    expect(tournamentsSource).toContain("location: 'tournaments_find_events'")
    expect(tournamentsSource).toContain("location: 'tournaments_follow_draw'")
    expect(tournamentsSource).toContain("location: 'tournaments_run_event'")
    expect(tournamentsSource).toContain('Tournament flow')
    expect(tournamentsSource).toContain('aria-labelledby="tournament-flow-title"')
    expect(tournamentsSource).toContain('titleId="tournament-flow-title"')
    expect(tournamentsSource).toContain('Event setup')
    expect(tournamentsSource).toContain('Player notifications')
    expect(tournamentsSource).toContain("{ label: 'Pending', value: 'Clear' }")
    expect(tournamentsSource).not.toContain("{ label: 'Pending', value: '0' }")
    expect(tournamentsSource).toContain("eventName: 'draw_preview_clicked'")
    expect(tournamentsSource).toContain("location: 'tournaments_draw_preview'")
    expect(tournamentsSource).toContain('Open Tournament Desk')
    expect(tournamentsSource).not.toContain('cta="Preview Draw"')
    expect(tournamentsSource).not.toContain('cta="Publish Results"')
    expect(tournamentsSource).toContain("eventName: 'tournament_desk_clicked'")
    expect(tournamentsSource).toContain('Draws reviewable')
    expect(tournamentsSource).toContain('context="Tournaments trust strip"')
    expect(tournamentsSource).not.toContain('ProductPreviewGrid')
  })

  it('lets public section headers provide accessible labels', () => {
    expect(commandCenterSource).toContain('titleId?: string')
    expect(commandCenterSource).toContain('<h2 id={titleId}')
    expect(commandCenterSource).toContain('context?: string')
    expect(commandCenterSource).toContain('const trustContext = encodeURIComponent(context)')
    expect(commandCenterSource).toContain("{ label: 'Results', value: 'Clear' }")
    expect(commandCenterSource).not.toContain("{ label: 'Results', value: '0 pending' }")
  })
})
