import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

import { createTacticalTemplate } from '../tactical/templates'

const gateSource = readFileSync(join(process.cwd(), 'components/tactical/TiqTacticalStudioGate.tsx'), 'utf8')
const tacticsPageSource = readFileSync(join(process.cwd(), 'app/tactics/page.tsx'), 'utf8')
const studioSource = readFileSync(join(process.cwd(), 'components/tactical/TiqTacticalStudio.tsx'), 'utf8')
const studioStyles = readFileSync(join(process.cwd(), 'components/tactical/TiqTacticalStudio.module.css'), 'utf8')
const markerIconsSource = readFileSync(join(process.cwd(), 'components/tactical/icons/TiqIcons.tsx'), 'utf8')
const courtOverlaySource = readFileSync(join(process.cwd(), 'components/tactical/TiqCourtOverlay.tsx'), 'utf8')
const tokenSource = readFileSync(join(process.cwd(), 'components/tactical/TiqTokens.tsx'), 'utf8')
const toolbarSource = readFileSync(join(process.cwd(), 'components/tactical/TiqToolbar.tsx'), 'utf8')
const boardSource = readFileSync(join(process.cwd(), 'components/tactical/TiqCourtBoard.tsx'), 'utf8')
const tacticalTypesSource = readFileSync(join(process.cwd(), 'lib/tactical/types.ts'), 'utf8')
const tacticalTemplatesSource = readFileSync(join(process.cwd(), 'lib/tactical/templates.ts'), 'utf8')

const TENNIS_BALL_ASSET = '/tiq/tokens/tennis-ball-reference.png'
const upgradePromptSource = readFileSync(join(process.cwd(), 'app/components/upgrade-prompt.tsx'), 'utf8')

describe('Tactical Studio player access', () => {
  it('lets Player users open Tactics Tools without requiring Coach', () => {
    expect(tacticsPageSource).toContain('<SiteShell active="you">')
    expect(tacticsPageSource).not.toContain('<SiteShell active="captain">')
    expect(gateSource).toContain('access.canUseAdvancedPlayerInsights')
    expect(gateSource).toContain('Loading your tactical board.')
    expect(gateSource).not.toContain('Loading your tactical workspace.')
    expect(gateSource).toContain('TIQ Tactical Studio is part of Player, Coach, Captain, and Full-Court access.')
    expect(gateSource).toContain('const gatePlanId = getTacticsGatePlanId(gateSource)')
    expect(gateSource).toContain('planId={gatePlanId}')
    expect(gateSource).toContain('headline={`Unlock TIQ Tactical Studio with ${gatePlanName}.`}')
    expect(gateSource).toContain('Player includes My Lab, Level Up, Tactics Tools')
  })

  it('keeps the opened studio chrome on the current Player tier name', () => {
    expect(studioSource).toContain('Player ready')
    expect(studioSource).not.toContain('Player+ ready')
  })

  it('opens player-ready starter boards from Improve links', () => {
    expect(studioSource).toContain('readTacticalEntryIntent')
    expect(studioSource).toContain("params.get('source')")
    expect(studioSource).toContain("params.get('template')")
    expect(studioSource).toContain("params.get('role')")
    expect(studioSource).toContain("params.get('identity')")
    expect(studioSource).toContain("params.get('identityLabel')")
    expect(studioSource).toContain("params.get('card')")
    expect(studioSource).toContain("params.get('cardTitle')")
    expect(studioSource).toContain('setTemplateKey(nextEntryIntent.templateKey)')
    expect(studioSource).toContain('setRole(nextEntryIntent.role)')
    expect(studioSource).toContain('setBriefingRole(nextEntryIntent.role)')
    expect(studioSource).toContain('const hasLevelUpCardIntent = Boolean(nextEntryIntent.cardId || nextEntryIntent.cardTitle)')
    expect(studioSource).toContain('getEntryReadyToast(nextEntryIntent, hasLevelUpCardIntent)')
    expect(studioSource).toContain('function getEntryReadyToast')
    expect(studioSource).toContain("if (hasLevelUpCardIntent) return 'My Lab proof board ready'")
    expect(studioSource).toContain("entryIntent.source === 'improve'")
    expect(studioSource).toContain('Improve board ready')
    expect(studioSource).toContain('My Lab proof board ready')
    expect(studioSource).toContain('styles.entryCallout')
    expect(studioSource).toContain('Improve starter')
    expect(studioSource).toContain("const hasEntryLevelUpCard = Boolean(entryIntent?.cardId || entryIntent?.cardTitle)")
    expect(studioSource).toContain("const entryIntentLabel = hasEntryLevelUpCard ? 'My Lab proof board' : 'Improve starter'")
    expect(studioSource).toContain('const entryProofReturnCopy = hasEntryLevelUpCard')
    expect(studioSource).toContain('Return ${entryCardTitle} proof to My Lab after saving this board.')
    expect(studioSource).toContain('href="/player-development"')
    expect(studioSource).toContain('href="/mylab#level-up-proof"')
    expect(studioSource).toContain('entryIdentityLabel')
    expect(studioSource).toContain('entryCardTitle')
    expect(studioSource).toContain('sent {entryCardTitle} into {scenario.name}. {entryProofReturnCopy}')
    expect(studioSource).toContain('Improve board handoff context')
    expect(studioSource).toContain('Player ID')
    expect(studioSource).toContain('Level Up card')
    expect(studioSource).toContain('cleanEntryIntentValue')
    expect(studioSource).toContain('Improve starter board steps')
    expect(studioSource).toContain('Read the pattern')
    expect(studioSource).toContain('Heavy cross, recover through middle, attack the short ball.')
    expect(studioSource).toContain('Adjust the court')
    expect(studioSource).toContain('Drag the attacker, defender, target window, or path handles to match your next rep.')
    expect(studioSource).toContain('Capture proof')
    expect(studioSource).toContain('<p>{entryProofReturnCopy}</p>')
    expect(studioSource).toContain('Court mode')
    expect(studioSource).toContain('Copy brief')
    expect(studioSource).toContain('Save board')
    expect(studioSource).toContain('href="/mylab#level-up-proof"')
    expect(studioStyles).toContain('.entryCallout')
    expect(studioStyles).toContain('.entryCalloutActions')
    expect(studioStyles).toContain('.entryCalloutLink')
    expect(studioStyles).toContain('.entryStarterStrip')
    expect(studioStyles).toContain('.entryStarterContext')
    expect(studioStyles).toContain('.entryStarterActions')
    expect(studioStyles).toContain('.entryStarterButton')
  })

  it('opens coach lesson boards from Coach Hub links', () => {
    expect(studioSource).toContain("entryIntent.source === 'coach'")
    expect(studioSource).toContain('Coach lesson board ready')
    expect(studioSource).toContain('getEntryReadyToast(nextEntryIntent, hasLevelUpCardIntent)')
    expect(studioSource).toContain('function getEntryReadyToast')
    expect(studioSource).toContain("entryIntent?.source === 'coach'")
    expect(studioSource).toContain('Coach lesson board')
    expect(studioSource).toContain('Coach Hub opened {scenario.name} with teaching cues ready.')
    expect(studioSource).toContain('Map the drill, copy the brief, then assign the next step.')
    expect(studioSource).toContain('href="/coach"')
    expect(studioSource).toContain('Development paths')
    expect(studioSource).toContain('Coach lesson board steps')
    expect(studioSource).toContain('Coach board handoff context')
    expect(studioSource).toContain('Teach the constraint')
    expect(studioSource).toContain('Use the board to show feed, recovery, attack lane, and finish before the first live rep.')
    expect(studioSource).toContain('Score the rep')
    expect(studioSource).toContain('Assign the next step')
    expect(studioSource).toContain('Copy coach brief')
    expect(studioSource).toContain('Save lesson board')
  })

  it('opens captain match-week boards from Team Hub links', () => {
    expect(studioSource).toContain("entryIntent.source === 'captain'")
    expect(studioSource).toContain('Captain match-week board ready')
    expect(studioSource).toContain("entryIntent?.source === 'captain'")
    expect(studioSource).toContain('Captain match-week board')
    expect(studioSource).toContain('Team Hub opened {scenario.name} for a clean doubles picture.')
    expect(studioSource).toContain('Set the pattern, name the assignments, then send the team plan.')
    expect(studioSource).toContain('href="/captain"')
    expect(studioSource).toContain('Lineup builder')
    expect(studioSource).toContain('Captain match-week board steps')
    expect(studioSource).toContain('Captain board handoff context')
    expect(studioSource).toContain('Name the pattern')
    expect(studioSource).toContain('Show the serve, first move, recovery lane, and target so the doubles pair has one picture.')
    expect(studioSource).toContain('Confirm assignments')
    expect(studioSource).toContain('Send the plan')
    expect(studioSource).toContain('Copy team brief')
    expect(studioSource).toContain('Save match board')
    expect(studioSource).toContain('href="/captain/messaging"')
  })

  it('connects Tactical Studio to a Player ID starter path before the unlock prompt', () => {
    expect(gateSource).toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
    expect(gateSource).toContain("import { useSearchParams } from 'next/navigation'")
    expect(gateSource).toContain("const TACTICS_PLAYER_IDENTITY = getPlayerDevelopmentIdentity('smart-attacker-4-0-to-4-5')")
    expect(gateSource).toContain('const TACTICS_LEVEL_UP_HREF = `/level-up/${TACTICS_PLAYER_IDENTITY.slug}#level-up-flow`')
    expect(gateSource).toContain('const TACTICS_PLAYER_DEVELOPMENT_HREF = `/player-development/${TACTICS_PLAYER_IDENTITY.slug}`')
    expect(gateSource).toContain("const TACTICS_MY_LAB_HREF = '/mylab#level-up-proof'")
    expect(gateSource).toContain("const TACTICS_IMPROVE_HREF = '/tactics?source=improve&template=crosscourt&role=player'")
    expect(gateSource).toContain('const searchParams = useSearchParams()')
    expect(gateSource).toContain('const tacticsGateHref = buildTacticsGateHref(searchParams)')
    expect(gateSource).toContain("cleanGateIntentValue(searchParams.get('identityLabel'))")
    expect(gateSource).toContain("const gateCardId = cleanGateIntentValue(searchParams.get('card'))")
    expect(gateSource).toContain("const requestedGateCardTitle = cleanGateIntentValue(searchParams.get('cardTitle'))")
    expect(gateSource).toContain('const hasGateLevelUpCard = Boolean(gateCardId || requestedGateCardTitle)')
    expect(gateSource).toContain('const gateIntentLabel = getGateIntentLabel(gateSource, hasGateLevelUpCard)')
    expect(gateSource).toContain('const gateProofReturnCue = getGateProofReturnCue(gateSource, gateCardTitle, hasGateLevelUpCard)')
    expect(gateSource).toContain('const tacticsGateStarterRead = getTacticsGateStarterRead')
    expect(gateSource).toContain("value: boardTitle")
    expect(gateSource).toContain("label: 'My Lab handoff'")
    expect(gateSource).toContain('value: handoffCue')
    expect(gateSource).toContain('href={getPlanUnlockHref(gatePlanId, tacticsGateHref)}>See {gatePlanName}')
    expect(gateSource).toContain("href={getPlanUnlockHref('full_court', tacticsGateHref)}>See Full-Court")
    expect(gateSource).toContain('ctaHref={getPlanUnlockHref(gatePlanId, tacticsGateHref)}')
    expect(gateSource).toContain("secondaryHref={getPlanUnlockHref('full_court', tacticsGateHref)}")
    expect(gateSource).toContain('secondaryLabel="Unlock Full-Court"')
    expect(gateSource).toContain('function buildTacticsGateHref')
    expect(gateSource).toContain("const intentKeys = ['identity', 'identityLabel', 'card', 'cardTitle'] as const")
    expect(gateSource).toContain("if (!hasCustomIntent && source === 'improve') return TACTICS_IMPROVE_HREF")
    expect(gateSource).toContain('return `/tactics?${nextParams.toString()}`')
    expect(gateSource).toContain('function cleanGateIntentValue')
    expect(gateSource).toContain('Tactics Player ID starter path')
    expect(gateSource).toContain('Tactics Player ID starter read')
    expect(gateSource).toContain('Improve starter board requested')
    expect(gateSource).toContain('My Lab proof board requested')
    expect(gateSource).toContain('aria-label={gateIntentLabel}')
    expect(gateSource).toContain('{gateCardTitle} opens after {gatePlanName} unlock.')
    expect(gateSource).toContain('${identityLabel}: read the Player ID cue, adjust the court, then save the proof back to My Lab.')
    expect(gateSource.indexOf('Improve starter board requested')).toBeLessThan(gateSource.indexOf('Tactics Player ID starter path'))
    expect(gateSource).toContain('Start with the player read, then build the board.')
    expect(gateSource).toContain("label: 'Board starter'")
    expect(gateSource).toContain('assignment, and My Lab proof the next session needs.')
    expect(gateSource).toContain('Build the drill board, then return the proof.')
    expect(gateSource).toContain('Return ${boardTitle} proof to My Lab after the board is saved.')
    expect(gateSource).toContain('Save the board back to My Lab before the next court block.')
    expect(gateSource).toContain('Start Level Up')
    expect(gateSource).toContain('Build starter board')
    expect(gateSource).toContain("href: getPlanUnlockHref('player_plus', tacticsGateHref)")
    expect(gateSource).toContain('Read Player ID')
    expect(gateSource).toContain("href: TACTICS_MY_LAB_HREF")
    expect(gateSource).toContain('const tacticsUnlockSteps = getTacticsUnlockSteps(gateSource)')
    expect(gateSource).toContain('Open the starter board')
    expect(gateSource).toContain('Player unlock keeps the crosscourt board attached after checkout.')
    expect(gateSource).toContain('Adjust the court')
    expect(gateSource).toContain('Send proof back')
    expect(gateSource).toContain('unlockSteps={tacticsUnlockSteps}')
    expect(gateSource).not.toContain('Compare Captain')
    expect(upgradePromptSource).toContain('unlockSteps?: ReadonlyArray<UpgradePromptUnlockStep>')
    expect(upgradePromptSource).toContain('const resolvedUnlockSteps = unlockSteps ?? getUnlockSteps(planId)')
    expect(gateSource.indexOf('styles.tacticsPlayerIdTrail')).toBeLessThan(gateSource.indexOf('<UpgradePrompt'))
  })

  it('preserves Coach and Captain board intent through the locked gate', () => {
    expect(gateSource).toContain("type TacticsGateSource = 'improve' | 'coach' | 'captain'")
    expect(gateSource).toContain("const gateSource = getTacticsGateSource(searchParams.get('source'), searchParams.get('role'))")
    expect(gateSource).toContain("if (source === 'coach' || role === 'coach') return 'coach'")
    expect(gateSource).toContain("if (source === 'captain' || role === 'captain') return 'captain'")
    expect(gateSource).toContain("if (source === 'coach') return 'coachProgression'")
    expect(gateSource).toContain("if (source === 'captain') return 'basicDoubles'")
    expect(gateSource).toContain("if (source === 'coach') return 'coach'")
    expect(gateSource).toContain("if (source === 'captain') return 'captain'")
    expect(gateSource).toContain('Coach lesson board requested')
    expect(gateSource).toContain('Captain match-week board requested')
    expect(gateSource).toContain('Coach Hub to tactics')
    expect(gateSource).toContain('Team Hub to tactics')
    expect(gateSource).toContain('Tactics Coach lesson starter path')
    expect(gateSource).toContain('Tactics Captain match-week starter path')
    expect(gateSource).toContain('Coach unlock keeps the progression board attached after checkout.')
    expect(gateSource).toContain('Captain unlock keeps the doubles board attached after checkout.')
    expect(gateSource).toContain('Build lesson board')
    expect(gateSource).toContain('Build match board')
    expect(gateSource).toContain('Coach includes Player features plus Coach Hub')
    expect(gateSource).toContain('Captain includes Player features plus Team Hub')
  })

  it('keeps the Tactics Player ID bridge compact for phone layouts', () => {
    expect(gateSource).toContain('styles.tacticsPlayerIdTrail')
    expect(gateSource).toContain('styles.tacticsPlayerIdGrid')
    expect(gateSource).toContain('styles.tacticsPlayerIdActions')
    expect(gateSource).toContain('styles.gateStarterCue')
    expect(studioStyles).toContain('.gateStarterCue')
    expect(studioStyles).toContain('.gateStats .stat p')
    expect(studioStyles).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 180px), 1fr));')
    expect(gateSource).not.toContain('gateStats gateStats')
  })

  it('keeps the phone tactical board shrink-safe inside the viewport', () => {
    expect(studioStyles).toContain('.workspace > section')
    expect(studioStyles).toContain('max-width: 100svw;')
    expect(studioStyles).toContain('max-width: 100%;')
    expect(studioStyles).toContain('overflow-x: hidden;')
    expect(studioStyles).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(studioStyles).toContain('max-height: none;')
    expect(studioStyles).toContain('width: 100%;')
  })

  it('uses the uploaded tennis ball image asset for tactical ball markers', () => {
    expect(tokenSource).toContain(TENNIS_BALL_ASSET)
    expect(markerIconsSource).toContain(TENNIS_BALL_ASSET)
    expect(courtOverlaySource).toContain('<symbol id="tiq-ball-marker"')
    expect(courtOverlaySource).toContain(TENNIS_BALL_ASSET)
    expect(studioStyles).toContain('.ballToken')
    expect(studioStyles).toContain('.ballTokenImage')
    expect(studioStyles).toContain('.ballPaletteButton')
  })

  it('keeps the Basic Board ball token separated from the server token', () => {
    const basicBoard = createTacticalTemplate('basicDoubles')
    const server = basicBoard.tokens.find((token) => token.type === 'player' && token.role === 'Server')
    const ball = basicBoard.tokens.find((token) => token.type === 'ball')

    expect(server).toBeDefined()
    expect(ball).toBeDefined()
    expect(ball!.x).toBeLessThan(server!.x - 4)
    expect(ball!.y).toBeLessThan(server!.y - 4)
  })

  it('keeps the upgraded tactical board workflow controls available', () => {
    expect(studioSource).toContain('boardFocusMode')
    expect(studioSource).toContain('presentationMode')
    expect(studioSource).toContain('downloadBoardPng')
    expect(studioSource).toContain('ScenarioThumbnail')
    expect(studioSource).toContain('applySnapPreset')
    expect(studioSource).toContain('addPathPreset')
    expect(studioSource).toContain('undoLastPath')
    expect(studioSource).toContain('BoardToolDock')
    expect(studioSource).toContain('clearBoardMarks')
    expect(toolbarSource).toContain('Token size')
    expect(toolbarSource).toContain('Snap spots')
    expect(toolbarSource).toContain('Export PNG')
    expect(toolbarSource).toContain('Present')
    expect(boardSource).toContain('roleView')
    expect(boardSource).toContain('readOnly')
    expect(boardSource).toContain('tokenScaleClass')
    expect(studioStyles).toContain('.boardFocusActive')
    expect(studioStyles).toContain('.presentationStage')
    expect(studioStyles).toContain('.scenarioThumbnail')
    expect(studioStyles).toContain('.tokenScaleLarge')
    expect(studioStyles).toContain('.boardToolDock')
    expect(studioStyles).toContain('position: sticky;')
    expect(tacticalTypesSource).toContain("export type TacticalTokenScale = 'small' | 'medium' | 'large'")
    expect(tacticalTemplatesSource).toContain('tacticalSnapPresets')
    expect(tacticalTemplatesSource).toContain('tacticalPathPresets')
  })
})
