import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

function readSource(path: string) {
  return readFileSync(join(process.cwd(), path), 'utf8').replaceAll('\r\n', '\n')
}

describe('Team Room live availability card', () => {
  it('uses the private availability request as the projected-lineup response source', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const availabilityApi = readSource('app/api/captain/availability-requests/route.ts')

    expect(roomApi).toContain('loadAvailabilityRequestSummaries')
    expect(roomApi).toContain(".from('captain_availability_request_invites')")
    expect(roomApi).toContain(".from('captain_availability_request_responses')")
    expect(roomApi).toContain('summarizeTeamRoomAvailability({')
    expect(availabilityApi).toContain("url.searchParams.get('requestId')")
    expect(availabilityApi).toContain('canManageSharedAvailabilityRequest')
  })

  it('keeps both captain follow-up actions on the live card', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const messagingPage = readSource('app/captain/messaging/page.tsx')
    const lineupPage = readSource('app/captain/lineup-builder/page.tsx')

    expect(roomPage).toContain('Nudge {waiting} waiting')
    expect(roomPage).toContain('Update lineup')
    expect(roomPage).toContain("{message.responseSummary.total ? 'Build from replies' : 'Build lineup'}")
    expect(roomPage).toContain("new URLSearchParams({ source: 'team_room', availability: 'replies' })")
    expect(roomPage).toContain('#captain-lineup-courts')
    expect(roomPage).toContain('availabilityRequest')
    expect(roomPage).toContain("focus: 'waiting'")
    expect(roomPage).toContain('aria-label="Availability response summary"')
    expect(roomPage).toContain('Match replies')
    expect(roomPage).toContain('See player statuses')
    expect(roomPage).toContain('Find replacement')
    expect(roomPage).toContain('buildCaptainReplyReviewHref({')
    expect(messagingPage).toContain("params.get('availabilityRequest')")
    expect(messagingPage).toContain("params.set('requestId', requestedAvailabilityRequestId)")
    expect(messagingPage).toContain("params.get('focus') === 'waiting'")
    expect(messagingPage).toContain("getElementById('potential-lineup-confirm-title')")
    expect(lineupPage).toContain("params.get('source') === 'team_room' && params.get('availability') === 'replies'")
    expect(lineupPage).toContain('Team replies applied: ${teamRoomReplyCounts.yes} In')
    expect(lineupPage).toContain("status === 'maybe' || status === 'limited'")
  })

  it('opens the exact reply as an actionable Captain replacement review', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const captainPage = readSource('app/captain/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomPage).toContain("notice: CAPTAIN_AVAILABILITY_REPLY_NOTICE")
    expect(roomPage).toContain("source: 'team_room'")
    expect(roomPage).toContain("status: group.status === 'no' ? 'unavailable' : 'maybe'")
    expect(roomPage).toContain('needs the first decision.')
    expect(captainPage).toContain("searchParams.get('notice') !== CAPTAIN_AVAILABILITY_REPLY_NOTICE")
    expect(captainPage).toContain("id: 'team-room-reply-focus'")
    expect(captainPage).toContain("document.getElementById('captain-reply-alert')")
    expect(captainPage).toContain("target.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' })")
    expect(roomStyles).toContain('.replyDigest')
    expect(roomStyles).toContain('.replyPriority')
  })

  it('keeps a saved replacement silent until the captain notifies affected players', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain("if (action === 'notify_lineup_change')")
    expect(roomApi).toContain('const silent = body.silent === true')
    expect(roomApi).toContain('if (!silent) {')
    expect(roomApi).toContain('buildLineupChangeNotice(previousCard.lineup, effectiveCard.lineup, changeContext)')
    expect(roomApi).toContain('notifyAffectedLineupPlayers')
    expect(roomApi).toContain('directShareNames')
    expect(roomPage).toContain('Ready to notify affected players')
    expect(roomPage).toContain('Notify ${lineupChangeNotice.affectedNames.length} affected')
    expect(roomPage).toContain("action: 'notify_lineup_change'")
    expect(roomStyles).toContain('.lineupChangePending')
    expect(roomStyles).toContain('.lineupChangeSent')
  })

  it('lets the linked replacement answer and reopens the exact court after a decline', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain("if (action === 'respond_lineup_change')")
    expect(roomApi).toContain('Only the replacement player can answer this lineup change.')
    expect(roomApi).toContain("response === 'accepted' ? 'yes' : 'no'")
    expect(roomApi).toContain('notifyManagersOfLineupChangeResponse')
    expect(roomPage).toContain("action: 'respond_lineup_change'")
    expect(roomPage).toContain('Can you play this court?')
    expect(roomPage).toContain('Choose another backup')
    expect(roomPage).toContain("lineupChangeNotice?.response === 'declined'")
    expect(roomStyles).toContain('.lineupChangeDecision')
    expect(roomStyles).toContain('.lineupChangeDeclined')
  })

  it('schedules one free replacement reminder and flags an unanswered court', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const reminderRunner = readSource('app/api/team-rooms/reminders/route.ts')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain("if (action === 'schedule_lineup_change_deadline')")
    expect(roomApi).toContain('needsLineupChangeResponse: true')
    expect(roomApi).toContain("status: 'cancelled'")
    expect(roomPage).toContain('Reply by')
    expect(roomPage).toContain('TIQ will check that morning.')
    expect(roomPage).toContain('Response overdue')
    expect(roomPage).toContain('Review this court')
    expect(reminderRunner).toContain('target.needsLineupChangeResponse && !lineupChangeAnswered')
    expect(reminderRunner).toContain("deadlineStatus: 'reminded'")
    expect(reminderRunner).toContain('Accept or choose Can’t play')
    expect(roomStyles).toContain('.lineupChangeDeadline')
    expect(roomStyles).toContain('.lineupChangeOverdue')
  })

  it('opens reply alerts on the exact card and highlights the affected court', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')
    const roomApi = readSource('app/api/team-rooms/route.ts')

    expect(roomPage).toContain("searchParams.get('message')")
    expect(roomPage).toContain('match-card-${message.id}')
    expect(roomPage).toContain('replied {focusedStatusLabel}')
    expect(roomPage).toContain('styles.lineupRowFocused')
    expect(roomStyles).toContain('.matchCardFocused')
    expect(roomStyles).toContain('@media (prefers-reduced-motion: reduce)')
    expect(roomApi).toContain('teamRoomMessageId: input.messageId')
    expect(roomApi).toContain('findCaptainReplyCourt(input.metadata.lineup')
  })

  it('summarizes every court before showing detailed player replies', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomPage).toContain('buildTeamRoomCourtReadiness({')
    expect(roomPage).toContain('Lineup readiness')
    expect(roomPage).toContain('Needs captain')
    expect(roomPage).toContain('Player reply details')
    expect(roomPage).toContain('courtReadinessAnchor(message.id, index)')
    expect(roomStyles).toContain('.courtReadinessGrid')
    expect(roomStyles).toContain('.courtReadinessCaptain')
    expect(roomStyles).toContain('.readinessReplyDetails')
    expect(roomStyles).toContain('.lineupRow:target')
  })

  it('shares unresolved court readiness with Captain Home without another request', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')

    expect(roomApi).toContain('buildTeamRoomCourtReadiness({')
    expect(roomApi).toContain('courtReadiness: {')
    expect(roomApi).toContain("court.status === 'confirmed'")
    expect(roomApi).toContain("status: court.status")
    expect(roomApi).toContain('lineup: activeLineup')
    expect(roomApi).toContain('lineupChange: activeLineupChange ? {')
    expect(roomApi).toContain('afterPlayers: activeLineupChange.afterPlayers')
    expect(roomApi).toContain('respondedAt: activeLineupChange.respondedAt')
  })

  it('stores one shared final-lineup send for every captain', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')

    expect(roomApi).toContain("if (action === 'send_final_lineup')")
    expect(roomApi).toContain('readiness.finalLineup?.lineupId === serverLineupId')
    expect(roomApi).toContain('buildCaptainLockedLineupAnnouncement({')
    expect(roomApi).toContain(".filter('metadata', 'eq', JSON.stringify(cardResult.metadata))")
    expect(roomApi).toContain('finalLineupAnnouncement: true')
    expect(roomApi).toContain('alreadySent: true')
    expect(roomApi).toContain('finalLineup: finalLineup ? {')
    expect(roomApi).toContain('readTeamRoomFinalLineupReceipt(latestCard?.metadata?.finalLineup)')
    expect(roomPage).toContain("action: 'send_final_lineup'")
    expect(roomPage).toContain("{sendingFinalLineup ? 'Sending…' : 'Send lineup to team'}")
    expect(roomPage).toContain("<span className={styles.captainActionComplete}>Lineup sent</span>")
  })

  it('publishes one affected-court update when a final lineup changes', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')

    expect(roomApi).toContain("previousFinalLineup?.lineupId || previousLineupChange?.previousFinalLineupId || ''")
    expect(roomApi).toContain('const changesPublishedLineup = Boolean(previousPublishedLineupId && lineupChangeNotice && lineupChanges.length)')
    expect(roomApi).toContain('buildPublishedLineupChangeAnnouncement({')
    expect(roomApi).toContain('finalLineupChangeAnnouncement: true')
    expect(roomApi).toContain(".filter('metadata', 'eq', JSON.stringify(cardResult.metadata))")
    expect(roomApi).toContain('const nextFinalLineup = changeNotice.publishedLineupChange')
    expect(roomApi).toContain('finalLineup: nextFinalLineup')
    expect(roomApi).toContain('finalLineupPublished: Boolean(republishedFinalLineup)')
    expect(roomPage).toContain('Final lineup change ready')
    expect(roomPage).toContain('Send lineup change')
    expect(roomPage).toContain('Published update sent')
    expect(roomPage).toContain('The revised lineup is published.')
  })

  it('pins the current final lineup and labels older lineup history', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain('lineupAnnouncement: !row.deleted_at ? readTeamRoomLineupAnnouncement(row.metadata) : null')
    expect(roomApi).toContain('Published lineup updates stay in team history.')
    expect(roomPage).toContain('<PublishedLineupPin')
    expect(roomPage).toContain('review={room.finalLineupReview}')
    expect(roomPage).toContain('pinnedMessage?.card && !pinnedMessage.card.finalLineup ? (')
    expect(roomPage).toContain('open={defaultOpen ?? Boolean(result || receipt)}')
    expect(roomPage).toContain("isMatchDay ? 'Match day' : 'Match plan'")
    expect(roomPage).toContain("isMatchDay ? 'Today' : 'Sent'")
    expect(roomPage).toContain("{' · Sent to team'}")
    expect(roomPage).toContain('lineupHref={finalLineupEditHref}')
    expect(roomPage).toContain('>Update lineup</Link>')
    expect(roomPage).toContain("lineupStatus === 'pending' ? 'Awaiting confirmation'")
    expect(roomPage).toContain("lineupStatus === 'superseded' ? 'Superseded' : 'Past lineup'")
    expect(roomPage).toContain('message.isMine && !message.lineupAnnouncement')
    expect(roomStyles).toContain('.publishedLineupPin')
    expect(roomStyles).toContain(".lineupStatusBadge[data-status='superseded']")
  })

  it('tracks final-lineup reviews and sends one reminder only to unseen players', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain("if (action === 'ack_final_lineup')")
    expect(roomApi).toContain("if (action === 'remind_final_lineup_unseen')")
    expect(roomApi).toContain('buildTeamRoomFinalLineupReview({')
    expect(roomApi).toContain('finalLineupReviewReminderSentAt')
    expect(roomApi).toContain(".filter('metadata', 'eq', JSON.stringify(lineupResult.announcement.metadata))")
    expect(roomApi).toContain('sendFinalLineupReviewReminder(auth.service, {')
    expect(roomPage).toContain("'Mark seen'")
    expect(roomPage).toContain('Reminder sent')
    expect(roomPage).toContain('Everyone has seen it.')
    expect(roomStyles).toContain('.publishedLineupReview')
  })

  it('hands a final lineup from match-day logistics to scorecard entry', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain("if (action === 'complete_match_day')")
    expect(roomApi).toContain('matchCompletedAt')
    expect(roomApi).toContain("message: 'Only a captain or co-captain can close the match.'")
    expect(roomPage).toContain("'Match complete'")
    expect(roomPage).toContain('Add scorecard')
    expect(roomPage).toContain('Open maps')
    expect(roomPage).toContain("isPostMatch ? 'After match' : isMatchDay ? 'Match day' : 'Match plan'")
    expect(roomStyles).toContain('.matchDayLogistics')
    expect(roomStyles).toContain('.matchDayActions')
  })

  it('lets assigned players check in while elevating late arrivals to captains', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')

    expect(roomApi).toContain("if (action === 'set_arrival_status')")
    expect(roomApi).toContain('findTeamRoomAssignedCourt(normalizeLineupRows(cardResult.metadata.lineup)')
    expect(roomApi).toContain("if (body.arrivalStatus === 'running_late')")
    expect(roomApi).toContain('notifyManagersOfArrivalStatus(auth.service')
    expect(roomApi).toContain(".filter('metadata', 'eq', JSON.stringify(cardResult.metadata))")
    expect(roomApi).toContain('arrivalCheckIns: readTeamRoomArrivalCheckIns(row.metadata.arrivalCheckIns)')
    expect(roomPage).toContain("action: 'set_arrival_status'")
    expect(roomPage).toContain("['on_my_way', 'On my way']")
    expect(roomPage).toContain("['here', 'Here']")
    expect(roomPage).toContain("['running_late', 'Running late']")
    expect(roomPage).toContain(': `match-plan-${activeMatchMessage.id}`}')
    expect(roomPage).toContain('aria-label="Team arrival status"')
    expect(roomStyles).toContain('.arrivalCheckIn')
    expect(roomStyles).toContain('.arrivalCourtGrid')
    expect(roomStyles).toContain("[data-status='running_late']")
  })

  it('opens a late-arrival alert on the exact court with three captain actions', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')
    const lineupBuilder = readSource('app/captain/lineup-builder/page.tsx')

    expect(roomApi).toContain('hrefUrl.hash = `match-plan-${encodeURIComponent(input.messageId)}`')
    expect(roomPage).toContain('findTeamRoomLateArrival(arrivalCourts, focusedCourtLabel)')
    expect(roomPage).toContain('buildTeamRoomLateArrivalBuilderHref(lineupHref, lateArrival)')
    expect(roomPage).toContain('Message player')
    expect(roomPage).toContain('Prepare backup')
    expect(roomPage).toContain('Update lineup')
    expect(roomPage).toContain('Please share your ETA.')
    expect(roomStyles).toContain('.lateArrivalActions')
    expect(roomStyles).toContain('.arrivalCourtFocused')
    expect(lineupBuilder).toContain("initialContext.mode === 'backup'")
    expect(lineupBuilder).toContain('Available players are already filtered.')
    expect(lineupBuilder).toContain('document.getElementById(`captain-lineup-slot-${backupFocusSlot.id}`)?.scrollIntoView')
    expect(lineupBuilder).toContain('focused={backupFocusSlot?.id === slot.id}')
  })

  it('returns a saved match-day backup to the affected Team Room court', () => {
    const roomPage = readSource('app/team-room/page.tsx')
    const lineupBuilder = readSource('app/captain/lineup-builder/page.tsx')

    expect(lineupBuilder).toContain('const sourceSlots = backupSelectionDraft?.previousSlots ?? teamSlots')
    expect(lineupBuilder).toContain('outgoingPlayerName: backupHandoff.playerName')
    expect(lineupBuilder).toContain('Backup selected: ${result.replacementPlayerName}')
    expect(lineupBuilder).toContain('Save backup & return')
    expect(lineupBuilder).toContain('if (syncedChange && backupHandoff)')
    expect(lineupBuilder).toContain('router.push(syncedChange.href)')
    expect(lineupBuilder).toContain('The backup was saved, but Team Room could not be updated.')
    expect(roomPage).toContain('Final lineup change ready')
    expect(roomPage).toContain('Send lineup change')
  })

  it('preserves team arrivals and closes the backup response loop', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')

    expect(roomApi).toContain('keepTeamRoomArrivalCheckInsForLineup(')
    expect(roomApi).toContain("arrivalCheckIns: response === 'accepted'")
    expect(roomPage).toContain('document.getElementById(`team-room-arrival-${messageId}`)')
    expect(roomPage).toContain('arrival.focus({ preventScroll: true })')
    expect(roomPage).toContain('buildTeamRoomLateArrivalBuilderHref(lineupBaseHref, {')
    expect(roomPage).toContain('Choose another backup')
  })

  it('replaces scorecard entry with the linked final result', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')
    const lineupBuilder = readSource('app/captain/lineup-builder/page.tsx')

    expect(roomApi).toContain('loadTeamRoomFinalResult')
    expect(roomApi).toContain(".from('matches')")
    expect(roomApi).toContain('selectTeamRoomCompletedMatch')
    expect(roomApi).toContain('matchId: cleanText(metadata.matchId)')
    expect(lineupBuilder).toContain("matchId: selectedMatch?.id || ''")
    expect(roomPage).toContain('(currentFinalLineup || (room.finalResult && room.finalResultCardId === activeMatchMessage.id))')
    expect(roomPage).toContain("result ? 'Final result'")
    expect(roomPage).toContain('Scorecard linked')
    expect(roomPage).toContain('Court results')
    expect(roomPage).toContain('resultLines.map')
    expect(roomPage).toContain('finalResultCardId')
    expect(roomPage).toContain('Fix names')
    expect(roomApi).toContain('resolveTeamRoomMatchProgress')
    expect(roomStyles).toContain('.matchResultScore')
    expect(roomStyles).toContain('.matchResultLines')
    expect(roomStyles).toContain('.matchResultDataGap')
  })

  it('posts one final-result update and edits that update for corrections', () => {
    const announcementServer = readSource('lib/team-room-result-announcement-server.ts')
    const importRunner = readSource('lib/data-assist-import-runner.ts')
    const roomPage = readSource('app/team-room/page.tsx')

    expect(importRunner).toContain('announceTeamRoomScorecardResult({')
    expect(announcementServer).toContain('teamRoomResultAnnouncement: true')
    expect(announcementServer).toContain(".select('id,conversation_id,metadata')")
    expect(announcementServer).toContain('messageId: input.resultCardId || input.messageId')
    expect(announcementServer).toContain(".contains('metadata', { teamRoomResultAnnouncement: true, externalMatchId })")
    expect(announcementServer).toContain(".update({ body, metadata, edited_at: new Date().toISOString() })")
    expect(announcementServer).toContain('sendTeamRoomPush(service')
    expect(roomPage).toContain('focusedMessageId === room.finalResultCardId')
    expect(roomPage).toContain('`final-result-${focusedMessageId}`')
    expect(roomPage).toContain('defaultOpen={resultJustUpdated || focusedFinalResult}')
  })

  it('prefills the selected team next match before asking availability', () => {
    const roomApi = readSource('app/api/team-rooms/route.ts')
    const roomPage = readSource('app/team-room/page.tsx')
    const roomStyles = readSource('app/team-room/team-room.module.css')
    const nextMatch = readSource('lib/platform-resume-next-match.ts')

    expect(nextMatch).toContain('loadCaptainResumeNextMatchForScope')
    expect(nextMatch).toContain('match_source,facility')
    expect(nextMatch).toContain('scheduled_time,facility')
    expect(roomApi).toContain('planningCardId\n    ? null\n    : await loadCaptainResumeNextMatchForScope')
    expect(roomApi).toContain('nextScheduledMatch: nextScheduledMatch ? {')
    expect(roomPage).toContain("Match details came from your schedule.")
    expect(roomPage).toContain("hasActiveAvailability ? 'Review availability' : 'Ask availability'")
    expect(roomPage).toContain('const source = room.nextScheduledMatch || activeMatchMessage?.card')
    expect(roomPage).toContain("<summary>{room.nextScheduledMatch ? 'Edit match details' : 'Add match details'}</summary>")
    expect(roomStyles).toContain('.matchSummary')
  })
})
