import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(join(process.cwd(), 'app/teams/[team]/page.tsx'), 'utf8')

function styleBlock(styleName: string) {
  const start = source.indexOf(`const ${styleName}`)
  expect(start, styleName).toBeGreaterThanOrEqual(0)
  const nextStyle = source.indexOf('\nconst ', start + 1)
  return source.slice(start, nextStyle === -1 ? undefined : nextStyle)
}

describe('team detail week path', () => {
  it('answers the captain match-week questions on team detail pages', () => {
    expect(source).not.toContain('PRODUCT_MOTTO')
    expect(source).toContain('the team context that helps everyone stay ready')
    expect(source).toContain('canManageThisTeam ? (')
    expect(source).toContain('Team week path')
    expect(source).toContain('Answer match week from your phone.')
    expect(source).toContain('Who is available?')
    expect(source).toContain('What lineup gives us the best chance?')
    expect(source).toContain('Who should play together?')
    expect(source).toContain('What should I communicate?')
    expect(source).toContain('data-team-week-job={item.job}')
    expect(source).toContain('aria-label={`${item.cta}: ${item.question}`}')
    expect(source).toContain('const captainWeekFocus =')
    expect(source).toContain('data-team-week-focus={captainWeekFocus.key}')
    expect(source).toContain('Readiness check')
    expect(source).toContain('Build for ${nextScheduledMatch.opponent')
    expect(source).toContain('data-team-contact-readiness')
    expect(source).toContain('Text-ready')
  })

  it('leads the profile with an actionable next-match, roster, and court read', () => {
    expect(source).toContain('const nextScheduledMatch = useMemo')
    expect(source).toContain('const playedRosterCount = useMemo')
    expect(source).toContain('const teamCourtLead = useMemo')
    expect(source).toContain('aria-label="Team match pulse"')
    expect(source).toContain('Ready for the next opponent.')
    expect(source).toContain('players with a tracked start')
    expect(source).toContain('Top doubles read')
    expect(source).toContain('Top singles read')
    expect(source).toContain("{canManageThisTeam ? 'Open lineup' : 'Explore Captain'}")
    expect(source).toContain('Turn this team read into a clear lineup.')
    expect(source).toContain('teamPulseCaptainPreviewStyle')
  })

  it('keeps the team week path compact and mobile-safe', () => {
    expect(source).toContain('teamWeekPathStyle(isTablet)')
    expect(styleBlock('teamWeekPathStyle')).toContain("gridTemplateColumns: isTablet ? 'minmax(0, 1fr)'")
    expect(styleBlock('teamWeekPathGridStyle')).toContain("gridTemplateColumns: isSmallMobile ? 'minmax(0, 1fr)'")
    expect(styleBlock('teamWeekActionCardStyle')).toContain('minHeight: 146')
    expect(styleBlock('teamWeekActionCardStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('teamWeekActionTextStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('teamWeekFocusStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('teamWeekFocusStyle')).toContain("minWidth: 0")
  })

  it('keeps the core team jobs first and removes generic player-ID detours', () => {
    expect(source).toContain('aria-label="Team page sections"')
    expect(source).toContain('href="#team-overview"')
    expect(source).toContain('href="#team-schedule"')
    expect(source).toContain('href="#team-roster"')
    expect(source).toContain('id="team-schedule"')
    expect(source).toContain('id="team-roster"')
    expect(source).not.toContain('Roster Player ID trail')
    expect(source).not.toContain('ROSTER_PLAYER_IDENTITY')
    expect(source).not.toContain("import { getPlayerDevelopmentIdentity, getPlayerDevelopmentIdentityActionRead } from '@/lib/player-development'")
  })

  it('keeps public team exploration data-first while preserving private roster chat', () => {
    expect(source).toContain("{isLinkedTeamMember ? <a href=\"#team-chat\"")
    expect(source).toContain("{isLinkedTeamMember ? <section id=\"team-chat\"")
    expect(source).toContain('Team activity')
    expect(source).toContain('results ready to review')
    expect(source).toContain('>Activity</a>')
    expect(source).toContain('{!canManageThisTeam && !isMobile && !(nextScheduledMatch || roster.length || teamCourtLead) ? (')
  })

  it('renders responsive roster cards instead of compressing nine table columns', () => {
    const rosterStart = source.indexOf('style={dynamicRosterGrid}')
    const rosterEnd = source.indexOf('{filteredRoster.length > mobileRosterPreviewLimit ? (', rosterStart)
    const rosterBlock = source.slice(rosterStart, rosterEnd)

    expect(source).toContain('style={dynamicRosterGrid}')
    expect(source).toContain('style={mobileRosterCardStyle}')
    expect(source).toContain('style={mobileRosterCompactRowStyle}')
    expect(source).toContain('style={dynamicRosterMetricGrid}')
    expect(source).toContain('const showRosterFilters = !isMobile || hasRosterParticipationSplit')
    expect(source).toContain('{showRosterFilters && showRosterTools ? (')
    expect(source).toContain('{showRosterTools && selectedRosterPlayerIds.length > 0 ? <div style={rosterCompareTray}>')
    expect(source).toContain('selected — choose one more player')
    expect(styleBlock('mobileRosterMetricGridStyle')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
    expect(styleBlock('mobileRosterCardStyle')).toContain('minWidth: 0')
    expect(styleBlock('mobileRosterCardStyle')).toContain("padding: '13px 14px'")
    expect(styleBlock('mobileRosterIdentityStyle')).toContain("overflowWrap: 'anywhere'")
    expect(styleBlock('rosterFilterButton')).toContain("minHeight: '44px'")
    expect(styleBlock('rosterSelectButton')).toContain("minHeight: '44px'")
    expect(styleBlock('rosterActionLink')).toContain("minHeight: '44px'")
    expect(rosterBlock).toContain('>Profile</Link>')
    expect(rosterBlock).toContain('>Team chat</Link>')
    expect(rosterBlock).toContain('Text {contact.phone}')
  })

  it('keeps long team detail tables short by default with user-opened detail', () => {
    expect(source).toContain('const [showFullMatchHistory, setShowFullMatchHistory] = useState(false)')
    expect(source).toContain('const [showFullRoster, setShowFullRoster] = useState(false)')
    expect(source).toContain('const mobileRosterPreviewLimit = isMobile ? 4 : 12')
    expect(source).toContain('const visibleRoster = showFullRoster ? filteredRoster : filteredRoster.slice(0, mobileRosterPreviewLimit)')
    expect(source).toContain('{filteredRoster.length > mobileRosterPreviewLimit ? (')
    expect(source).toContain('const upcomingCards = filteredCards')
    expect(source).toContain('const completedCards = filteredCards')
    expect(source).toContain('...upcomingCards.slice(0, 2), ...completedCards.slice(0, 2)')
    expect(source).toContain('const visibleCards = showFullMatchHistory ? activityCards : previewCards')
    expect(source).toContain('Show how this team page is checked')
    expect(source).toContain('detailDrawerStyle')
    expect(source).toContain('tableControlRowStyle')
    expect(source).toContain('tableToggleButtonStyle')
    expect(source).toContain('Return to match preview')
    expect(source).toContain('Return to lineup snapshot')
    expect(styleBlock('detailDrawerSummaryStyle')).toContain("cursor: 'pointer'")
    expect(styleBlock('tableToggleButtonStyle')).toContain("whiteSpace: 'normal'")
    expect(source).toContain('{isMobile ? (')
    expect(source).toContain('style={mobileMatchListStyle}')
    expect(source).toContain("label: 'Upcoming'")
    expect(source).toContain("label: 'Recent results'")
    expect(source).toContain('style={mobileMatchGroupStyle}')
    expect(source).toContain('style={mobileMatchCardStyle}')
    expect(styleBlock('mobileMatchFactsStyle')).toContain("flexWrap: 'wrap'")
    expect(styleBlock('panelCountPill')).toContain("whiteSpace: 'nowrap'")
    expect(styleBlock('teamSectionNavLinkStyle')).toContain('minHeight: 44')
    expect(styleBlock('seasonFilterButtonStyle')).toContain('minHeight: 44')
  })

  it('does not render empty analysis sections before the team has usable data', () => {
    expect(source).toContain('{tiqParticipations.length || tiqParticipationWarning ? (')
    expect(source).toContain('{roster.length || (isDoublesOnlyTeam ? bestDoubles.length : bestSingles.length) || pairings.length ? (')
    expect(source).toContain('{matches.length ? (')
    expect(source).toContain('{roster.length ? (')
    expect(source).not.toContain('<span style={metricLabel}>Imported Scorecards</span>')
    expect(source).not.toContain('const teamSignals = [')
    expect(source).not.toContain('Next Best Actions')
  })

  it('keeps opponent records accurate and readable without a six-column phone table', () => {
    expect(source).toContain('const normalizedTeam = normalizeTeamName(teamName)')
    expect(source).toContain('normalizeTeamName(home) === normalizedTeam')
    expect(source).toContain('normalizeTeamName(away) === normalizedTeam')
    expect(source).toContain('style={opponentCardStyle(isSmallMobile)}')
    expect(source).toContain('style={opponentRecordStyle}')
    expect(source).toContain('<details style={opponentBreakdownDetailsStyle}>')
    expect(source).toContain('<span>Record vs. opponents</span>')
    expect(source).toContain("{opponentAnalysis.length} opponent{opponentAnalysis.length !== 1 ? 's' : ''}")
    expect(source).toContain('Last met {formatDate(opp.lastDate)}')
    expect(source).not.toContain("['Opponent', 'W', 'L', 'Win %', 'Matches', 'Last met']")
    expect(styleBlock('opponentCardStyle')).toContain("flexDirection: isSmallMobile ? 'column' : 'row'")
    expect(styleBlock('opponentRecordStyle')).toContain("gridTemplateColumns: 'repeat(3, minmax(0, 1fr))'")
  })
})
