import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const teamsSource = readFileSync(join(process.cwd(), 'app/teams/page.tsx'), 'utf8')
const leaguesSource = readFileSync(join(process.cwd(), 'app/leagues/page.tsx'), 'utf8')

function styleBlock(source: string, styleName: string) {
  const pattern = new RegExp(`const ${styleName}(?:: CSSProperties)? = ([\\s\\S]*?)(?=\\nconst |\\nfunction |\\nexport |$)`)
  const match = source.match(pattern)
  if (!match) throw new Error(`Missing style block: ${styleName}`)
  return match[0]
}

describe('Teams and Leagues public intros', () => {
  it('positions Teams publicly while keeping Captain as the paid leadership lane', () => {
    expect(teamsSource).toContain('Team discovery')
    expect(teamsSource).toContain('Find a team.')
    expect(teamsSource).toContain('Browse teams')
    expect(teamsSource).toContain('const shouldShowTeamResults = hasActiveFilters || browseAll')
    expect(teamsSource).not.toContain('const shouldShowTeamResults = hasActiveFilters || browseAll || rows.length > 0')
    expect(teamsSource).toContain('Team records are loading.')
    expect(teamsSource).toContain('Open Captain tools')
    expect(teamsSource).toContain('Captain Tools')
    expect(teamsSource).toContain('Team paths')
    expect(teamsSource).toContain('Team Hub preview')
    expect(teamsSource).toContain('Captain decision path')
    expect(teamsSource).toContain('Who can play, where they fit, and what gets sent?')
    expect(teamsSource).toContain('Who is available?')
    expect(teamsSource).toContain('What lineup gives us the best chance?')
    expect(teamsSource).toContain('Who should play together?')
    expect(teamsSource).toContain('What should I communicate?')
    expect(teamsSource).toContain('For players')
    expect(teamsSource).toContain('For captains')
    expect(teamsSource).toContain('For opponents')
    expect(teamsSource).toContain('For leagues')
    expect(teamsSource).toContain('TrackedProductLink')
    expect(teamsSource).toContain("eventName: 'captain_tools_clicked'")
    expect(teamsSource).toContain("eventName: 'availability_clicked'")
    expect(teamsSource).toContain("eventName: 'lineup_preview_clicked'")
    expect(teamsSource).toContain("eventName: 'matchup_started'")
    expect(teamsSource).not.toContain('Captain tennis without')
  })

  it('keeps Teams intro dense enough for phone-first discovery', () => {
    expect(teamsSource).toContain('const isTinyMobile = screenWidth < 360')
    expect(teamsSource).toContain('filterActionStyle')
    expect(teamsSource).toContain("display: isMobile ? 'none' : undefined")
    expect(teamsSource).toContain("padding: isMobile ? 12 : filtersCard.padding")
    expect(teamsSource).toContain('filtersGrid(isMobile)')
    expect(teamsSource).toContain('teamStartGridStyle')
    expect(teamsSource).toContain('publicIntroGridStyle(isTinyMobile)')
    expect(teamsSource).toContain("gridTemplateColumns: isTinyMobile ? 'minmax(0, 1fr)' : 'repeat(2, minmax(0, 1fr))'")
    expect(teamsSource).toContain('introMiniCardStyle(compact)')
    expect(teamsSource).toContain('minHeight: compact ? 84 : 132')
    expect(styleBlock(teamsSource, 'teamsDetailsSectionStyle')).toContain("display: 'block'")
    expect(styleBlock(teamsSource, 'teamsDetailsSectionStyle')).not.toContain("display: 'grid'")
    expect(styleBlock(teamsSource, 'teamsDetailsSummaryStyle')).toContain('borderRadius: 8')
    expect(styleBlock(teamsSource, 'summaryRow')).toContain("gap: isMobile ? '6px' : '8px'")
    expect(styleBlock(teamsSource, 'summaryRow')).toContain("marginTop: isMobile ? '10px' : '14px'")
    expect(styleBlock(teamsSource, 'statPill')).toContain('borderRadius: 8')
    expect(styleBlock(teamsSource, 'filtersCard')).toContain('borderRadius: 8')
    expect(styleBlock(teamsSource, 'filtersGrid')).toContain("gap: isMobile ? '8px' : '10px'")
    expect(styleBlock(teamsSource, 'filtersGrid')).toContain("marginTop: isMobile ? '10px' : '14px'")
    expect(styleBlock(teamsSource, 'compactDirectoryControlStyle')).toContain("height: '42px'")
    expect(styleBlock(teamsSource, 'compactFilterActionStyle')).toContain('minHeight: 36')
  })

  it('positions Leagues around League Office operations and Data Assist handoff', () => {
    expect(leaguesSource).toContain('Run the season without the spreadsheet chaos.')
    expect(leaguesSource).toContain('Find Leagues')
    expect(leaguesSource).toContain('Open League Office')
    expect(leaguesSource).toContain('Season control board')
    expect(leaguesSource).toContain('Find the season, then keep it moving.')
    expect(leaguesSource).toContain('One place for the season.')
    expect(leaguesSource).not.toContain('Pick the season job, then open the right path.')
    expect(leaguesSource).toContain('Find a league or flight')
    expect(leaguesSource).toContain('Publish the season schedule')
    expect(leaguesSource).toContain('Update standings cleanly')
    expect(leaguesSource).toContain('Plan league or tournament operations')
    expect(leaguesSource).toContain('Use the Leagues & Tournaments hub')
    expect(leaguesSource).toContain('Open Organizer Hub')
    expect(leaguesSource).toContain('Send corrections to review')
    expect(leaguesSource).toContain('League discovery')
    expect(leaguesSource).toContain('League setup')
    expect(leaguesSource).toContain('Corrections')
    expect(leaguesSource).toContain('Use Data Assist')
    expect(leaguesSource).toContain('TrackedProductLink')
    expect(leaguesSource).toContain("eventName: 'league_search_submitted'")
    expect(leaguesSource).toContain("eventName: 'league_office_clicked'")
    expect(leaguesSource).toContain("job: 'organize_competition'")
  })

  it('keeps Leagues intro dense enough for phone-first discovery', () => {
    expect(leaguesSource).toContain('const isTinyMobile = screenWidth < 360')
    expect(leaguesSource).toContain('publicIntroCardStyle(isMobile)')
    expect(leaguesSource).toContain('publicIntroGridStyle(isTinyMobile)')
    expect(leaguesSource).toContain("gridTemplateColumns: isTinyMobile ? 'minmax(0, 1fr)' : 'repeat(2, minmax(0, 1fr))'")
    expect(leaguesSource).toContain('introMiniCardStyle(compact)')
    expect(leaguesSource).toContain('minHeight: compact ? 104 : 132')
    expect(leaguesSource).toContain("display: isMobile ? 'none' : undefined")
    expect(leaguesSource).toContain('responsiveLeagueDetailsSummaryStyle')
    expect(leaguesSource).toContain('responsiveLeagueDetailsCueStyle')
    expect(styleBlock(leaguesSource, 'compactLeagueDetailsSummaryStyle')).toContain("padding: '10px 11px'")
    expect(styleBlock(leaguesSource, 'compactLeagueDetailsSummaryStyle')).toContain('borderRadius: 8')
    expect(styleBlock(leaguesSource, 'mobileFinderStackStyle')).toContain('gap: 8')
    expect(styleBlock(leaguesSource, 'mobileFinderStackStyle')).toContain('marginBottom: 10')
    expect(styleBlock(leaguesSource, 'compactLeagueSearchControlStyle')).toContain("padding: '0 10px 0 38px'")
    expect(styleBlock(leaguesSource, 'compactLeagueDirectoryControlStyle')).toContain("height: '42px'")
  })
})
