import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (file: string) => readFileSync(join(process.cwd(), file), 'utf8').replace(/\r\n/g, '\n')
const adminPage = read('app/admin/tennisrecord/page.tsx')
const adminRoute = read('app/api/admin/tennisrecord/route.ts')
const adminHome = read('app/admin/page.tsx')
const service = read('lib/tennisrecord/service.ts')
const globalStyles = read('app/globals.css')

describe('TennisRecord Admin import progress', () => {
  it('returns scoped campaign queue states for an active historical import', () => {
    expect(service).toContain('campaignProgress: {')
    expect(service).toContain('weeklyProgress: {')
    expect(service).toContain('Coverage aggregates are intentionally deferred from this heartbeat.')
    expect(service).not.toContain("service.from('tennisrecord_admin_coverage_summary')")
    expect(service).toContain("countCampaignPages('pending')")
    expect(service).toContain("countCampaignPages('done')")
    expect(service).toContain("countCampaignPages('review')")
    expect(service).toContain('seedTennisRecordCampaignFrontier')
    expect(service).toContain('campaignForecast: {')
    expect(service).toContain('weeklyForecast: {')
    expect(service).toContain('tennisRecordObservedCheckpointPace')
    expect(service).toContain('nextCampaign: nextCampaign ?')
    expect(service).toContain('attentionItems: attentionItems.data || []')
    expect(service).toContain("return emptySummary('awaiting_seed')")
  })

  it('shows separate live historical and weekly delivery-style trackers', () => {
    expect(adminPage).toContain('ariaLabel="Historical import progress"')
    expect(adminPage).toContain('ariaLabel="Weekly refresh progress"')
    expect(adminPage).toContain('progressPercent')
    expect(adminPage).toContain('weeklyPercent')
    expect(adminPage).toContain('window.setInterval')
    expect(adminPage).toContain('newly discovered public match pages can extend the queue.')
    expect(adminPage).toContain('aria-label="TennisRecord campaign path"')
    expect(adminPage).toContain('Automatic campaign path')
    expect(adminPage).toContain('Time remaining reflects the currently known queue')
    expect(adminPage).toContain('Evidence review pages were captured safely')
    expect(adminPage).toContain('Checkpoint pace')
    expect(adminPage).toContain('Safety throttle')
    expect(adminPage).toContain('campaignPaceDetail')
    expect(adminPage).toContain('recent completed checkpoint pace')
    expect(adminPage).toContain('Pause automatic collection')
    expect(adminPage).toContain('Next refresh: Wednesday')
    expect(adminPage).toContain('Missouri history starts automatically')
    expect(adminPage).toContain('aria-label="TennisRecord data coverage"')
    expect(adminPage).toContain('Filterable teams')
    expect(adminPage).toContain('Awaiting promotion')
    expect(adminPage).toContain('Transient retries')
    expect(adminPage).toContain('Source failures')
    expect(adminPage).toContain('Evidence review')
    expect(adminPage).toContain('aria-label="Import attention queue"')
    expect(adminPage).toContain('A problem on one source page never pauses the rest of the import.')
    expect(adminPage).toContain('Retry safely')
    expect(adminRoute).toContain("action === 'retry_queue_item'")
    expect(adminRoute).toContain(".in('status', ['review', 'error'])")
    expect(service).toContain('summary.transientRetries += 1')
    expect(service).toContain('summary.sourceFailures += 1')
    expect(service).toContain('Discovery refreshes provenance only.')
    expect(service).toContain("update({ last_seen_at: observedAt })")
    expect(service).toContain('buildTennisRecordQueueDiscoveryPlan')
    expect(service).toContain("onConflict: 'source_url', ignoreDuplicates: true")
    expect(service).toContain('await reclaimStaleTennisRecordRuns(service)')
    expect(service).toContain('tennisRecordCadenceSafetyStatus')
    expect(service).toContain('TENNISRECORD_AUTOMATION_INTERVAL_MINUTES')
    expect(service).toContain('Interrupted checkpoint reclaimed for retry.')
    expect(service).toContain('same_name_source_players_require_review')
    expect(service).toContain('[tennisrecord] captured-page replay quarantined')
    expect(service).toContain("status: 'review', failure_reason: `Captured-page replay needs review:")
    expect(service).not.toContain("select('id', { count: 'exact', head: true })")
  })

  it('does not label a delayed status request as a paused collector', () => {
    expect(adminPage).toContain("const statusLoading = status === null && !message")
    expect(adminPage).toContain('Checking live importer status')
    expect(adminPage).toContain('This is not a pause.')
    expect(adminPage).toContain('Safety cooldown:')
  })

  it('caches costly Admin status reads and keeps the importer available', () => {
    expect(adminRoute).toContain("namespace: 'tennisrecord-admin'")
    expect(adminRoute).toContain('ADMIN_STATUS_CACHE_TTL_SECONDS = 120')
    expect(adminRoute).toContain('cache hit')
    expect(adminRoute).toContain('expireTag(ADMIN_STATUS_CACHE_TAG)')
    expect(adminHome).toContain('const toolGroups = [')
    expect(adminHome).toContain("href: '/admin/tennisrecord'")
    expect(adminHome).toContain('Specialist tools')
  })

  it('keeps metric cards responsive instead of forcing phone screens into columns', () => {
    expect(globalStyles).toContain('repeat(auto-fit, minmax(min(100%, 210px), 1fr))')
    expect(globalStyles).toContain('@media (max-width: 767px)')
    expect(globalStyles).not.toContain('.metric-grid {\n    grid-template-columns: repeat(3, minmax(0, 1fr));')
  })
})
