import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('saved tournament room next move', () => {
  it('keeps saved event cards focused on one state-aware action', () => {
    const source = readFileSync(join(process.cwd(), 'app/components/tournament-builder-workspace.tsx'), 'utf8')

    expect(source).toContain('recordNextMove')
    expect(source).toContain('recordProfileReadyCount')
    expect(source).toContain('recordScheduledMatchCount')
    expect(source).toContain('recordFinishChecklist')
    expect(source).toContain('aria-label={`${record.name} readiness`}')
    expect(source).toContain('recordReadinessRailStyle')
    expect(source).toContain('recordReadinessItemStyle')
    expect(source).toContain('recordReadinessCopyStyle')
    expect(source).toContain('recordFinishChecklist.map((item)')
    expect(source).toContain("loadRecordSection(record, item.href.replace('#', ''))")
    expect(source).toContain('recordNextMoveStyle')
    expect(source).toContain("loadRecordSection(record, recordNextMove.href.replace('#', ''))")
    expect(source).toContain('Create the first tournament room.')
    expect(source).toContain('emptySavedRoomStyle')
    expect(source).toContain('Calendar fills from match slots.')
    expect(source).toContain('calendarEmptyStateStyle')
    expect(source).toContain('scheduledMonthEvents')
    expect(source).toContain('Court agenda')
    expect(source).toContain('Next scheduled matches')
    expect(source).toContain('Schedule from the scorebook')
    expect(source).toContain('calendarShellStyle')
    expect(source).toContain('calendarAgendaStyle')
    expect(source).toContain('formatCalendarAgendaDate')
    expect(source).toContain('Entry queue is clear.')
    expect(source).toContain('Private draw.')
    expect(source).toContain('Awards unlock from completed results.')
    expect(source).toContain('tournamentActionEmptyStyle')
    expect(source).toContain("selectedRecord ? '#tournament-scorebook' : '#tournament-setup'")
    expect(source).toContain('href="#tournament-setup"')
    expect(source).toContain('Open room')
    expect(source).toContain('Public view')
    expect(source).not.toContain('No tournaments saved yet. Build the first draw above.')
    expect(source).not.toContain('No pending entries. Share the public bracket link when registration opens.')
    expect(source).not.toContain('Turn on public registration in tournament setup to collect player entry requests.')
    expect(source).not.toContain('Complete the final, then create awards for 1st, 2nd, and 3rd place.')
    expect(source).not.toContain(">Awards</button>")
    expect(source).not.toContain(">Alerts</button>")
  })
})
