export type IdentityLevelUpProfile = {
  identitySlug: string
  featuredModuleIds: string[]
  starterCardIds: string[]
  focusTags: string[]
  lanePriority?: string[]
  avoidTags?: string[]
  recommendationCopy: string
}

export const IDENTITY_LEVEL_UP_PROFILES: Record<string, IdentityLevelUpProfile> = {
  'relentless-competitor-4-0': {
    identitySlug: 'relentless-competitor-4-0',
    featuredModuleIds: [
      'recovery-after-contact',
      'light-feet-starter',
      'late-match-legs',
      'serve-pressure-routine',
      'return-intent',
      'wide-ball-reset',
      'pressure-reset',
    ],
    starterCardIds: [
      'cone-recover-shadow-swing',
      'jump-rope-rhythm-builder',
      'wall-sit-leg-durability',
      'serve-target-call',
      'return-shadow-split-read',
      'three-step-reset',
      'wide-ball-neutralizer',
      'post-play-mobility-reset',
    ],
    focusTags: [
      'recovery-after-contact',
      'light-feet',
      'serve-routine',
      'return-intent',
      'return-recovery',
      'leg-durability',
      'pressure-reset',
      'defense-to-neutral',
      'decision-quality',
    ],
    lanePriority: ['movement', 'return', 'serve', 'singles', 'fitness', 'pressure', 'backhand', 'doubles'],
    recommendationCopy:
      'Recommended for Relentless Competitor because this path builds recovery, serve and return routine, late-game legs, and pressure response.',
  },
  'smart-attacker-4-0-to-4-5': {
    identitySlug: 'smart-attacker-4-0-to-4-5',
    featuredModuleIds: [
      'serve-plus-one-clarity',
      'forward-close',
      'attack-balance',
      'return-intent',
      'crosscourt-build-before-change',
      'shoulder-core-serve-support',
    ],
    starterCardIds: [
      'serve-1-shadow',
      'cone-close-recover',
      'short-ball-close-split',
      'single-leg-rdl',
      'return-step-in-game',
      'return-depth-lane',
      'towel-serve-flow',
    ],
    focusTags: [
      'serve-plus-one',
      'forward-close',
      'attack-balance',
      'return-intent',
      'return-recovery',
      'crosscourt-build',
      'decision-quality',
    ],
    lanePriority: ['serve', 'forehand', 'volley', 'return', 'singles', 'movement', 'fitness', 'doubles'],
    recommendationCopy:
      'Recommended for Smart Attacker because this path builds serve +1 clarity, forward closing, return intent, and balanced first-strike decisions.',
  },
  'consistent-builder-4-0': {
    identitySlug: 'consistent-builder-4-0',
    featuredModuleIds: [
      'crosscourt-build-before-change',
      'recovery-after-contact',
      'wide-ball-reset',
      'match-day-warm-up',
      'pressure-reset',
      'post-play-mobility-reset',
      'wall-work-starter',
    ],
    starterCardIds: [
      'crosscourt-consistency',
      'basket-forehand-crosscourt',
      'basket-backhand-crosscourt',
      'wide-ball-neutralizer',
      'wall-depth-builder',
      'three-step-reset',
      'dynamic-tennis-warm-up',
      'post-play-mobility-reset',
    ],
    focusTags: [
      'crosscourt-build',
      'recovery-after-contact',
      'wide-ball-reset',
      'defense-to-neutral',
      'pressure-reset',
      'match-day',
      'wall-work',
      'decision-quality',
    ],
    lanePriority: ['forehand', 'backhand', 'movement', 'singles', 'return', 'serve', 'fitness', 'doubles'],
    recommendationCopy:
      'Recommended for Consistent Builder because this path builds crosscourt tolerance, recovery, wide-ball reset, match-day readiness, and pressure control.',
  },
  'doubles-commander-4-0': {
    identitySlug: 'doubles-commander-4-0',
    featuredModuleIds: [
      'doubles-first-move',
      'return-intent',
      'serve-pressure-routine',
      'pressure-reset',
      'match-day-warm-up',
      'post-play-mobility-reset',
    ],
    starterCardIds: [
      'serve-location-call',
      'partner-first-move-call',
      'doubles-return-first-move',
      'poach-timing-shadow',
      'middle-ball-rule',
      'switch-call-drill',
      'doubles-30-30-game',
      'three-step-reset',
    ],
    focusTags: [
      'doubles-communication',
      'partner-first-move',
      'poach-timing',
      'return-intent',
      'serve-target',
      'decision-quality',
      'pressure-reset',
    ],
    lanePriority: ['doubles', 'volley', 'return', 'serve', 'movement', 'singles', 'fitness', 'forehand'],
    recommendationCopy:
      'Recommended for Doubles Commander because this path builds partner first move, poach timing, middle ownership, return intent, and pressure communication.',
  },
  'serve-forward-finisher-4-0': {
    identitySlug: 'serve-forward-finisher-4-0',
    featuredModuleIds: [
      'serve-plus-one-clarity',
      'serve-pressure-routine',
      'forward-close',
      'attack-balance',
      'shoulder-core-serve-support',
      'return-intent',
      'pressure-reset',
    ],
    starterCardIds: [
      'serve-target-call',
      'serve-target-ladder',
      'serve-1-shadow',
      'serve-1-partner',
      'short-ball-close-split',
      'approach-volley-close',
      'volley-ready-split',
      'volley-punch-target',
      'three-step-reset',
    ],
    focusTags: [
      'serve-target',
      'serve-routine',
      'serve-plus-one',
      'forward-close',
      'attack-balance',
      'volley',
      'decision-quality',
      'pressure-reset',
    ],
    lanePriority: ['serve', 'volley', 'forehand', 'return', 'singles', 'movement', 'fitness', 'doubles'],
    recommendationCopy:
      'Recommended for Serve-Forward Finisher because this path builds serve target clarity, plus-one decisions, earned forward closing, first-volley quality, and attack reset.',
  },
  'defensive-counterpuncher-4-0': {
    identitySlug: 'defensive-counterpuncher-4-0',
    featuredModuleIds: [
      'wide-ball-reset',
      'recovery-after-contact',
      'crosscourt-build-before-change',
      'late-match-legs',
      'pressure-reset',
      'wall-work-starter',
      'post-play-mobility-reset',
    ],
    starterCardIds: [
      'wide-ball-neutralizer',
      'cone-recover-shadow-swing',
      'three-cone-baseline-recover',
      'crosscourt-consistency',
      'basket-backhand-crosscourt',
      'wall-depth-builder',
      'wall-sit-leg-durability',
      'three-step-reset',
    ],
    focusTags: [
      'wide-ball-reset',
      'defense-to-neutral',
      'recovery-after-contact',
      'recover-before-watching',
      'crosscourt-build',
      'backhand',
      'leg-durability',
      'pressure-reset',
      'decision-quality',
    ],
    lanePriority: ['movement', 'backhand', 'singles', 'fitness', 'pressure', 'return', 'forehand', 'serve'],
    recommendationCopy:
      'Recommended for Defensive Counterpuncher because this path builds wide-ball reset, recovery discipline, rally tolerance, late-point legs, and earned counterattack choices.',
  },
  'pressure-closer-4-0': {
    identitySlug: 'pressure-closer-4-0',
    featuredModuleIds: [
      'pressure-reset',
      'match-day-warm-up',
      'serve-pressure-routine',
      'return-intent',
      'conditioning-under-fatigue',
      'post-play-mobility-reset',
    ],
    starterCardIds: [
      'three-step-reset',
      'tight-arm-reset',
      'closing-game-routine',
      'five-minute-match-primer',
      'serve-target-call',
      'double-fault-reset',
      'return-30-30-game',
      'post-match-five-minute-debrief',
    ],
    focusTags: [
      'pressure-reset',
      'between-points',
      'match-day',
      'serve-routine',
      'serve-target',
      'return-intent',
      'decision-quality',
      'posture-under-fatigue',
    ],
    lanePriority: ['pressure', 'serve', 'return', 'singles', 'fitness', 'movement', 'doubles', 'forehand'],
    recommendationCopy:
      'Recommended for Pressure Closer because this path builds reset routines, 30-30 clarity, serve recovery, closing-game behavior, and useful match recaps.',
  },
  'return-disruptor-4-0': {
    identitySlug: 'return-disruptor-4-0',
    featuredModuleIds: [
      'return-intent',
      'pressure-reset',
      'match-day-warm-up',
      'crosscourt-build-before-change',
      'wide-ball-reset',
      'post-play-mobility-reset',
    ],
    starterCardIds: [
      'return-shadow-split-read',
      'return-depth-lane',
      'second-serve-attack-or-build',
      'return-plus-one-recover',
      'return-30-30-game',
      'wall-return-recovery',
      'three-step-reset',
    ],
    focusTags: [
      'return-intent',
      'return-recovery',
      'split-step',
      'decision-quality',
      'pressure-reset',
      'crosscourt-build',
      'defense-to-neutral',
    ],
    lanePriority: ['return', 'movement', 'singles', 'backhand', 'pressure', 'serve', 'forehand', 'fitness'],
    recommendationCopy:
      'Recommended for Return Disruptor because this path builds split-read timing, return intent, depth lanes, second-serve decisions, recovery after return, and 30-30 return pressure.',
  },
  'forehand-pressure-builder-4-0': {
    identitySlug: 'forehand-pressure-builder-4-0',
    featuredModuleIds: [
      'crosscourt-build-before-change',
      'attack-balance',
      'forward-close',
      'serve-plus-one-clarity',
      'return-intent',
      'pressure-reset',
    ],
    starterCardIds: [
      'basket-forehand-crosscourt',
      'crosscourt-consistency',
      'defense-neutral-attack-rally',
      'short-ball-close-split',
      'cone-close-recover',
      'serve-1-shadow',
      'three-step-reset',
    ],
    focusTags: [
      'forehand',
      'crosscourt-build',
      'attack-balance',
      'decision-quality',
      'forward-close',
      'serve-plus-one',
      'pressure-reset',
    ],
    lanePriority: ['forehand', 'singles', 'serve', 'return', 'movement', 'volley', 'fitness', 'backhand'],
    recommendationCopy:
      'Recommended for Forehand Pressure Builder because this path builds forehand shape, crosscourt pressure, earned direction changes, attack balance, and short-ball conversion.',
  },
  'all-court-adapter-4-0': {
    identitySlug: 'all-court-adapter-4-0',
    featuredModuleIds: [
      'crosscourt-build-before-change',
      'return-intent',
      'serve-plus-one-clarity',
      'attack-balance',
      'forward-close',
      'wide-ball-reset',
      'pressure-reset',
    ],
    starterCardIds: [
      'defense-neutral-attack-rally',
      'crosscourt-consistency',
      'return-depth-lane',
      'serve-1-shadow',
      'short-ball-close-split',
      'approach-volley-close',
      'wide-ball-neutralizer',
      'three-step-reset',
    ],
    focusTags: [
      'decision-quality',
      'crosscourt-build',
      'return-intent',
      'serve-plus-one',
      'attack-balance',
      'forward-close',
      'wide-ball-reset',
      'pressure-reset',
    ],
    lanePriority: ['singles', 'return', 'serve', 'forehand', 'backhand', 'volley', 'movement', 'fitness'],
    recommendationCopy:
      'Recommended for All-Court Adapter because this path builds decision quality, point-start patterns, transition timing, reset discipline, and match adaptation.',
  },
  default: {
    identitySlug: 'default',
    featuredModuleIds: [
      'match-day-warm-up',
      'at-home-starter-pack',
      'pressure-reset',
      'post-play-mobility-reset',
    ],
    starterCardIds: [
      'dynamic-tennis-warm-up',
      'three-step-reset',
      'post-play-mobility-reset',
    ],
    focusTags: ['warm-up', 'pressure-reset', 'mobility', 'at-home'],
    lanePriority: ['match', 'movement', 'serve', 'return', 'singles', 'fitness'],
    recommendationCopy:
      'Recommended because these cards are safe starter tools for building a repeatable tennis habit.',
  },
}
