import type { LevelUpModule } from './level-up-types'

export const LEVEL_UP_MODULES: LevelUpModule[] = [
  {
    id: 'recovery-after-contact',
    title: 'Recovery After Contact',
    subtitle: 'Stop hitting and watching.',
    description: 'Train the habit of recovering before reacting to the result.',
    level: 'starter',
    durationLabel: '7-day mini block',
    cardIds: ['cone-recover-shadow-swing', 'three-cone-baseline-recover', 'wall-recovery-rule', 'recover-before-score'],
    tags: ['recovery-after-contact', 'movement-engine', 'shadow-swing'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Recovery after contact 0-5',
  },
  {
    id: 'light-feet-starter',
    title: 'Light Feet Starter',
    subtitle: 'Split, land, and move again.',
    description: 'Build quiet first-step rhythm before adding speed.',
    level: 'starter',
    durationLabel: '3 cards / 15 minutes',
    cardIds: ['split-step-rhythm', 'jump-rope-rhythm-builder', 'four-cone-tennis-star'],
    tags: ['light-feet', 'split-step', 'first-step', 'quick-win'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Light feet 0-5',
  },
  {
    id: 'late-match-legs',
    title: 'Late-Match Legs',
    subtitle: 'Keep posture under fatigue.',
    description: 'Connect leg durability and controlled conditioning to tennis decisions.',
    level: 'builder',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['wall-sit-leg-durability', 'late-set-legs-circuit', 'cone-shuffle-finisher', 'post-play-mobility-reset'],
    tags: ['leg-durability', 'posture-under-fatigue', 'conditioning'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Posture under fatigue 0-5',
  },
  {
    id: 'serve-pressure-routine',
    title: 'Serve Pressure Routine',
    subtitle: 'Make the serve routine visible.',
    description: 'Call the target, run the routine, and reset after pressure misses.',
    level: 'starter',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['serve-target-call', 'second-serve-routine-reps', 'double-fault-reset'],
    tags: ['serve-routine', 'serve-target', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Serve routine clarity 0-5',
  },
  {
    id: 'serve-plus-one-clarity',
    title: 'Serve +1 Clarity',
    subtitle: 'Serve to create the next ball.',
    description: 'Connect serve target to the first strike without rushing.',
    level: 'builder',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['serve-target-call', 'serve-1-shadow', 'serve-1-partner'],
    tags: ['serve-plus-one', 'serve-target', 'decision-quality'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Serve +1 clarity 0-5',
  },
  {
    id: 'return-intent',
    title: 'Return Intent',
    subtitle: 'Start return games on purpose.',
    description: 'Choose return shape, court position, and recovery before the point starts.',
    level: 'builder',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['return-step-in-game', 'jump-rope-return-prep', 'return-1-conditioning'],
    tags: ['return-intent', 'return-recovery', 'decision-quality'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Return intent 0-5',
  },
  {
    id: 'wide-ball-reset',
    title: 'Wide-Ball Reset',
    subtitle: 'Defend wide without panic.',
    description: 'Train the wide-ball response that gets you back to neutral.',
    level: 'starter',
    durationLabel: '3 cards / 18 minutes',
    cardIds: ['wide-ball-neutralizer', 'drop-step-recovery', 'three-step-reset'],
    tags: ['wide-ball-reset', 'defense-to-neutral', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Defense to neutral 0-5',
  },
  {
    id: 'attack-balance',
    title: 'Attack Balance',
    subtitle: 'Attack without donating points.',
    description: 'Separate earned attacks from rushed attacks and finish balanced.',
    level: 'builder',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['basket-forehand-crosscourt', 'defense-neutral-attack-rally', 'single-leg-rdl', 'tight-arm-reset'],
    tags: ['attack-balance', 'decision-quality', 'balance'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Attack balance 0-5',
  },
  {
    id: 'forward-close',
    title: 'Forward Close',
    subtitle: 'Move through the court.',
    description: 'Close forward, split before the pass, and recover after contact.',
    level: 'builder',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['short-ball-close-split', 'cone-close-recover', 'poach-timing-shadow'],
    tags: ['forward-close', 'first-step', 'balance'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Forward close 0-5',
  },
  {
    id: 'crosscourt-build-before-change',
    title: 'Crosscourt Build Before Change',
    subtitle: 'Earn the line change.',
    description: 'Use crosscourt depth and balance before changing direction.',
    level: 'starter',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['crosscourt-consistency', 'basket-forehand-crosscourt', 'basket-backhand-crosscourt'],
    tags: ['crosscourt-build', 'decision-quality', 'attack-balance'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Crosscourt build 0-5',
  },
  {
    id: 'pressure-reset',
    title: 'Pressure Reset',
    subtitle: 'Win the next-point routine.',
    description: 'Reset between points with breath, cue, and target.',
    level: 'starter',
    durationLabel: '3 cards / 10 minutes',
    cardIds: ['three-step-reset', 'tight-arm-reset', 'closing-game-routine'],
    tags: ['pressure-reset', 'between-points', 'quick-win'],
    identitySlugs: ['relentless-competitor-4-0', 'smart-attacker-4-0-to-4-5'],
    proof: 'Reset used 0-5',
  },
  {
    id: 'match-day-warm-up',
    title: 'Match-Day Warm-Up',
    subtitle: 'Prepare before play.',
    description: 'Use dynamic warm-up and match primer tools before the first point.',
    level: 'starter',
    durationLabel: '2 cards / 10 minutes',
    cardIds: ['dynamic-tennis-warm-up', 'five-minute-match-primer'],
    tags: ['match-day', 'warm-up', 'mobility'],
    proof: 'Match-day ready 0-5',
  },
  {
    id: 'post-play-mobility-reset',
    title: 'Post-Play Mobility Reset',
    subtitle: 'Reset after play.',
    description: 'Use slow mobility and range checks after training or matches.',
    level: 'starter',
    durationLabel: '2 cards / 10 minutes',
    cardIds: ['post-play-mobility-reset', 'thoracic-open-book'],
    tags: ['mobility', 'stretch', 'recovery'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Recovery reset 0-5',
  },
  {
    id: 'doubles-first-move',
    title: 'Doubles First Move',
    subtitle: 'Move with your partner.',
    description: 'Train serve location, partner call, and first move clarity.',
    level: 'starter',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['serve-location-call', 'partner-first-move-call', 'poach-timing-shadow', 'middle-ball-rule'],
    tags: ['doubles-communication', 'partner-first-move', 'poach-timing'],
    identitySlugs: ['relentless-competitor-4-0', 'smart-attacker-4-0-to-4-5'],
    proof: 'Partner first move 0-5',
  },
  {
    id: 'shoulder-core-serve-support',
    title: 'Shoulder + Core Serve Support',
    subtitle: 'Support the serve pattern.',
    description: 'Technique-first strength and mobility that supports serve rhythm.',
    level: 'starter',
    durationLabel: '4 cards / 18 minutes',
    cardIds: ['band-external-rotation', 'dead-bug-serve-shadow', 'towel-serve-flow', 'pallof-press'],
    tags: ['shoulder-support', 'core-control', 'serve-routine'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Serve support 0-5',
  },
  {
    id: 'at-home-starter-pack',
    title: 'At-Home Starter Pack',
    subtitle: 'No court needed.',
    description: 'Build tennis habits at home with simple space and controlled reps.',
    level: 'starter',
    durationLabel: '5 cards / 25 minutes',
    cardIds: ['jump-rope-starter', 'split-squat-control', 'front-plank-breathing', 'cue-phrase-shadow', 'post-play-mobility-reset'],
    tags: ['at-home', 'no-equipment', 'quick-win'],
    proof: 'At-home habit 0-5',
  },
  {
    id: 'no-equipment-quick-wins',
    title: 'No-Equipment Quick Wins',
    subtitle: 'Five useful minutes.',
    description: 'Quick tennis habits when you have no court and no gear.',
    level: 'starter',
    durationLabel: '4 cards / under 10 minutes',
    cardIds: ['split-step-rhythm', 'serve-shadow-slow-motion', 'cue-phrase-shadow', 'three-step-reset'],
    tags: ['no-equipment', 'quick-win', 'at-home'],
    proof: 'Quick win 0-5',
  },
  {
    id: 'wall-work-starter',
    title: 'Wall Work Starter',
    subtitle: 'Make the wall useful.',
    description: 'Use wall reps for rhythm, depth, and recovery after contact.',
    level: 'starter',
    durationLabel: '4 cards / 20 minutes',
    cardIds: ['wall-rally-rhythm', 'wall-depth-builder', 'wall-recovery-rule', 'wall-alternating-fh-bh'],
    tags: ['wall-work', 'recovery-after-contact', 'crosscourt-build'],
    proof: 'Wall work quality 0-5',
  },
  {
    id: 'conditioning-under-fatigue',
    title: 'Conditioning Under Fatigue',
    subtitle: 'Keep decisions clean late.',
    description: 'Condition in short controlled blocks without sacrificing posture or choices.',
    level: 'builder',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['jump-rope-intervals', '20-20-tennis-finisher', 'late-set-legs-circuit', 'three-step-reset'],
    tags: ['conditioning', 'posture-under-fatigue', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Decision quality under fatigue 0-5',
  },
]
