import type { LevelUpModule } from './level-up-types'

export const LEVEL_UP_MODULES: LevelUpModule[] = [
  {
    id: 'recovery-after-contact',
    title: 'Recovery After Contact',
    subtitle: 'Stop hitting and watching.',
    description: 'Train the habit of recovering before reacting to the result.',
    useWhen: 'Use this when the player hits, watches, and gets late to the next ball.',
    sessionPlan: [
      'Day 1-2: shadow recovery with cones before adding the wall or ball.',
      'Day 3-5: add wall or baseline reps where recovery counts before the result.',
      'Day 6-7: use a pressure score and log whether recovery happened automatically.',
    ],
    successCriteria: 'The player recovers before judging the shot on most reps and can name when the habit disappeared.',
    level: 'starter',
    durationLabel: '7-day mini block',
    cardIds: ['cone-recover-shadow-swing', 'three-cone-baseline-recover', 'wall-recovery-rule', 'recover-before-score'],
    tags: ['recovery-after-contact', 'movement-engine', 'shadow-swing'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Recovery after contact 0-5',
  },
  {
    id: 'light-feet-starter',
    title: 'Light Feet Starter',
    subtitle: 'Split, land, and move again.',
    description: 'Build quiet first-step rhythm before adding speed.',
    useWhen: 'Use this when the player looks planted, late, or heavy before contact.',
    sessionPlan: [
      'Start with quiet split-step landings and one first move.',
      'Add jump-rope rhythm only while landings stay soft.',
      'Finish with cone movement where the player returns to ready every rep.',
    ],
    successCriteria: 'Landings stay quiet, posture stays tall, and the first move happens without a reminder.',
    level: 'starter',
    durationLabel: '3 cards / 15 minutes',
    cardIds: ['split-step-rhythm', 'jump-rope-rhythm-builder', 'four-cone-tennis-star'],
    tags: ['light-feet', 'split-step', 'first-step', 'quick-win'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Light feet 0-5',
  },
  {
    id: 'late-match-legs',
    title: 'Late-Match Legs',
    subtitle: 'Keep posture under fatigue.',
    description: 'Connect leg durability and controlled conditioning to tennis decisions.',
    useWhen: 'Use this when the player stands up late in games or decision quality drops with tired legs.',
    sessionPlan: [
      'Start with wall-sit posture so the player knows the body standard.',
      'Add short conditioning only while posture and breathing stay clean.',
      'End with a reset or mobility card so fatigue does not become sloppy reps.',
    ],
    successCriteria: 'The player can stay low, breathe, and choose the next ball clearly while tired.',
    level: 'builder',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['wall-sit-leg-durability', 'late-set-legs-circuit', 'cone-shuffle-finisher', 'post-play-mobility-reset'],
    tags: ['leg-durability', 'posture-under-fatigue', 'conditioning'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Posture under fatigue 0-5',
  },
  {
    id: 'serve-pressure-routine',
    title: 'Serve Pressure Routine',
    subtitle: 'Make the serve routine visible.',
    description: 'Call the target, run the routine, and reset after pressure misses.',
    useWhen: 'Use this when serve practice has volume but not a repeatable pressure routine.',
    sessionPlan: [
      'Begin with target calls before every serve or shadow.',
      'Add second-serve reps where routine commitment is scored separately from makes.',
      'Finish with double-fault reset work so misses do not carry into the next point.',
    ],
    successCriteria: 'The player can call the target, run the same routine, and reset after a miss.',
    level: 'starter',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['serve-target-call', 'second-serve-routine-reps', 'double-fault-reset'],
    tags: ['serve-routine', 'serve-target', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Serve routine clarity 0-5',
  },
  {
    id: 'serve-plus-one-clarity',
    title: 'Serve +1 Clarity',
    subtitle: 'Serve to create the next ball.',
    description: 'Connect serve target to the first strike without rushing.',
    level: 'builder',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['serve-target-call', 'serve-1-shadow', 'serve-1-partner'],
    tags: ['serve-plus-one', 'serve-target', 'decision-quality'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Serve +1 clarity 0-5',
  },
  {
    id: 'return-intent',
    title: 'Return Intent',
    subtitle: 'Start return games on purpose.',
    description: 'Choose return shape, court position, and recovery before the point starts.',
    useWhen: 'Use this when the player blocks returns without a plan, attacks second serves randomly, or watches after the return.',
    sessionPlan: [
      'Start with shadow return split-read reps so the player chooses the job early.',
      'Add depth lane or second-serve decision work based on the serve they are seeing.',
      'Finish with return plus-one or 30-30 pressure so recovery and intent hold in points.',
    ],
    successCriteria: 'The player can call the return job before the toss, hit the chosen shape, and recover for the next ball.',
    level: 'builder',
    durationLabel: '6 cards / 30 minutes',
    cardIds: ['return-shadow-split-read', 'return-step-in-game', 'return-depth-lane', 'second-serve-attack-or-build', 'return-plus-one-recover', 'return-30-30-game'],
    tags: ['return-intent', 'return-recovery', 'decision-quality', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0', 'smart-attacker-4-0-to-4-5'],
    proof: 'Return intent 0-5',
  },
  {
    id: 'wide-ball-reset',
    title: 'Wide-Ball Reset',
    subtitle: 'Defend wide without panic.',
    description: 'Train the wide-ball response that gets you back to neutral.',
    useWhen: 'Use this when wide balls lead to rushed line changes, panic winners, or slow recovery.',
    sessionPlan: [
      'Teach the height-depth-recover shape without score pressure.',
      'Add drop-step or cone recovery so defense ends in a ready position.',
      'Finish with a reset cue after misses so defensive points stay composed.',
    ],
    successCriteria: 'The player uses height and recovery to get neutral instead of trying to win from defense.',
    level: 'starter',
    durationLabel: '3 cards / 18 minutes',
    cardIds: ['wide-ball-neutralizer', 'drop-step-recovery', 'three-step-reset'],
    tags: ['wide-ball-reset', 'defense-to-neutral', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Defense to neutral 0-5',
  },
  {
    id: 'attack-balance',
    title: 'Attack Balance',
    subtitle: 'Attack without donating points.',
    description: 'Separate earned attacks from rushed attacks and finish balanced.',
    level: 'builder',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['basket-forehand-crosscourt', 'defense-neutral-attack-rally', 'single-leg-rdl', 'tight-arm-reset'],
    tags: ['attack-balance', 'decision-quality', 'balance'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Attack balance 0-5',
  },
  {
    id: 'forward-close',
    title: 'Forward Close',
    subtitle: 'Move through the court.',
    description: 'Close forward, split before the pass, and recover after contact.',
    level: 'builder',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['short-ball-close-split', 'cone-close-recover', 'poach-timing-shadow'],
    tags: ['forward-close', 'first-step', 'balance'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Forward close 0-5',
  },
  {
    id: 'crosscourt-build-before-change',
    title: 'Crosscourt Build Before Change',
    subtitle: 'Earn the line change.',
    description: 'Use crosscourt depth and balance before changing direction.',
    level: 'starter',
    durationLabel: '3 cards / 20 minutes',
    cardIds: ['crosscourt-consistency', 'basket-forehand-crosscourt', 'basket-backhand-crosscourt'],
    tags: ['crosscourt-build', 'decision-quality', 'attack-balance'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Crosscourt build 0-5',
  },
  {
    id: 'pressure-reset',
    title: 'Pressure Reset',
    subtitle: 'Win the next-point routine.',
    description: 'Reset between points with breath, cue, and target.',
    useWhen: 'Use this when errors, score, or body tension change the next point.',
    sessionPlan: [
      'Practice the three-step reset without live pressure first.',
      'Add tight-arm or closing-game cues based on the player leak.',
      'Use pressure scoring and log whether the reset happened before the next point.',
    ],
    successCriteria: 'The player starts the next point with a cue and target instead of a replay of the last point.',
    level: 'starter',
    durationLabel: '3 cards / 10 minutes',
    cardIds: ['three-step-reset', 'tight-arm-reset', 'closing-game-routine'],
    tags: ['pressure-reset', 'between-points', 'quick-win'],
    identitySlugs: ['relentless-competitor-4-0', 'smart-attacker-4-0-to-4-5'],
    proof: 'Reset used 0-5',
  },
  {
    id: 'match-day-warm-up',
    title: 'Match-Day Warm-Up',
    subtitle: 'Prepare before play.',
    description: 'Use dynamic warm-up and match primer tools before the first point.',
    level: 'starter',
    durationLabel: '2 cards / 10 minutes',
    cardIds: ['dynamic-tennis-warm-up', 'five-minute-match-primer'],
    tags: ['match-day', 'warm-up', 'mobility'],
    proof: 'Match-day ready 0-5',
  },
  {
    id: 'post-play-mobility-reset',
    title: 'Post-Play Mobility Reset',
    subtitle: 'Reset after play.',
    description: 'Use slow mobility and range checks after training or matches.',
    level: 'starter',
    durationLabel: '2 cards / 10 minutes',
    cardIds: ['post-play-mobility-reset', 'thoracic-open-book'],
    tags: ['mobility', 'stretch', 'recovery'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Recovery reset 0-5',
  },
  {
    id: 'doubles-first-move',
    title: 'Doubles First Move',
    subtitle: 'Move with your partner.',
    description: 'Train serve location, partner call, and first move clarity.',
    useWhen: 'Use this when partners are guessing, poaching late, or unclear on middle balls.',
    sessionPlan: [
      'Start with serve location and partner first-move calls before every point.',
      'Add poach timing only after the trigger is clear.',
      'Finish with middle-ball rules so communication holds once the rally gets messy.',
    ],
    successCriteria: 'Both partners know the first move before the ball is live and can recover after confusion.',
    level: 'starter',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['serve-location-call', 'partner-first-move-call', 'poach-timing-shadow', 'middle-ball-rule'],
    tags: ['doubles-communication', 'partner-first-move', 'poach-timing'],
    identitySlugs: ['relentless-competitor-4-0', 'smart-attacker-4-0-to-4-5'],
    proof: 'Partner first move 0-5',
  },
  {
    id: 'shoulder-core-serve-support',
    title: 'Shoulder + Core Serve Support',
    subtitle: 'Support the serve pattern.',
    description: 'Technique-first strength and mobility that supports serve rhythm.',
    useWhen: 'Use this when the serve needs body support without adding heavy loading.',
    sessionPlan: [
      'Begin with light shoulder control and core posture checks.',
      'Add towel or shadow serve flow after the body work.',
      'Score whether serve posture and rhythm feel smoother, not whether the work was hard.',
    ],
    successCriteria: 'The player can connect controlled body work to a smoother, balanced serve pattern.',
    level: 'starter',
    durationLabel: '4 cards / 18 minutes',
    cardIds: ['band-external-rotation', 'dead-bug-serve-shadow', 'towel-serve-flow', 'pallof-press'],
    tags: ['shoulder-support', 'core-control', 'serve-routine'],
    identitySlugs: ['smart-attacker-4-0-to-4-5'],
    proof: 'Serve support 0-5',
  },
  {
    id: 'at-home-starter-pack',
    title: 'At-Home Starter Pack',
    subtitle: 'No court needed.',
    description: 'Build tennis habits at home with simple space and controlled reps.',
    level: 'starter',
    durationLabel: '5 cards / 25 minutes',
    cardIds: ['jump-rope-starter', 'split-squat-control', 'front-plank-breathing', 'cue-phrase-shadow', 'post-play-mobility-reset'],
    tags: ['at-home', 'no-equipment', 'quick-win'],
    proof: 'At-home habit 0-5',
  },
  {
    id: 'no-equipment-quick-wins',
    title: 'No-Equipment Quick Wins',
    subtitle: 'Five useful minutes.',
    description: 'Quick tennis habits when you have no court and no gear.',
    level: 'starter',
    durationLabel: '4 cards / under 10 minutes',
    cardIds: ['split-step-rhythm', 'serve-shadow-slow-motion', 'cue-phrase-shadow', 'three-step-reset'],
    tags: ['no-equipment', 'quick-win', 'at-home'],
    proof: 'Quick win 0-5',
  },
  {
    id: 'wall-work-starter',
    title: 'Wall Work Starter',
    subtitle: 'Make the wall useful.',
    description: 'Use wall reps for rhythm, depth, and recovery after contact.',
    useWhen: 'Use this when the player wants solo reps that actually transfer to rallies.',
    sessionPlan: [
      'Start with rhythm and a height window so contact is controlled.',
      'Add depth or alternating sides only after the feet reset between hits.',
      'Finish with the wall recovery rule and score recovery before watching.',
    ],
    successCriteria: 'Wall reps include contact quality, a foot reset, and honest recovery after contact.',
    level: 'starter',
    durationLabel: '4 cards / 20 minutes',
    cardIds: ['wall-rally-rhythm', 'wall-depth-builder', 'wall-recovery-rule', 'wall-alternating-fh-bh'],
    tags: ['wall-work', 'recovery-after-contact', 'crosscourt-build'],
    proof: 'Wall work quality 0-5',
  },
  {
    id: 'conditioning-under-fatigue',
    title: 'Conditioning Under Fatigue',
    subtitle: 'Keep decisions clean late.',
    description: 'Condition in short controlled blocks without sacrificing posture or choices.',
    level: 'builder',
    durationLabel: '4 cards / 25 minutes',
    cardIds: ['jump-rope-intervals', '20-20-tennis-finisher', 'late-set-legs-circuit', 'three-step-reset'],
    tags: ['conditioning', 'posture-under-fatigue', 'pressure-reset'],
    identitySlugs: ['relentless-competitor-4-0'],
    proof: 'Decision quality under fatigue 0-5',
  },
]
